### DISCUSSION TITLE
Custom and use plugin authen and author on kong_ingress k8s

### DISCUSSION THREAD

**Discussion by MinhDuc010194** [Kong/kubernetes-ingress-controller#1711] [Q&A] [answered]
hi everyone!
Is it possible to use a custom plugin like this link into kong_ingress?
`https://konghq.com/blog/custom-authentication-and-authorization-framework-with-kong/`
i want to try this one but I don't know how to add config like this link.
and after config is done how can I use this for kong_ingress.

**Comment by shaneutt** [comment, marked as answer]
Hi @MinhDuc010194,

You need to build a custom image that includes your plugin files and then deploy a `KongPlugin` to get it loaded.

If you're using the Helm chart there's a feature to load it via `ConfigMap` mounts:

https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L305-L324

### Notes

This gets more complicated if you need custom credentials and things like that.

For instance in DBLESS mode you have to write the YAML directly and embed it in a secret:

https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/configuring-custom-entities/

In DB mode you can't do this at all via the KIC _currently_: you have to do it directly via the Kong Admin API.

**Reply by MinhDuc010194** [reply]
Hi @shaneutt 
thank you for this. should I run helm file when kong_proxy run or delete all kong namespace then run helm file?
now I'm not using helm to import custom plugin. I'm following this guide to add custom-plugins
> https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/setting-up-custom-plugins/

but in the last steps require to change some config like this
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      containers:
      - name: proxy
        env:
        - name: KONG_PLUGINS
          value: bundled,myheader
        - name: KONG_LUA_PACKAGE_PATH
          value: "/opt/?.lua;;"
        volumeMounts:
        - name: kong-plugin-myheader
          mountPath: /opt/kong/plugins/myheader
      volumes:
      - name: kong-plugin-myheader
        configMap:
          name: kong-plugin-myheader
and I don't understand how to do this right. i had to clone config in 
> https://bit.ly/kong-ingress-dbless

and then modifi it to 
[kong_ingress.zip](https://github.com/Kong/kubernetes-ingress-controller/files/7005944/kong_ingress.zip)
but when I run this config file  I got err CrashLoopBackOff when creating pod/ingress-kong. what step did i do wrong?. Please help me. I spent too much time doing this.

**Reply by MinhDuc010194** [reply]
Update: I change some config and now pod/ingresss-kong was running. Then I exec into a pod and also saw myheader plugin had mounted to /opt/kong/plugins/myheader and contain 2 .lua files. then I created a plugin.yaml by follow guide and add annotation konghq.com/plugins: my-custom-plugin into  Ingress file point to /foo. in handle.lua I config all request to <ExternalIp>/foo must be return code 500. but when I test i still got code 200 from <ExternalIp>/foo. I don't know what happens in here. Please help me.
![image](https://user-images.githubusercontent.com/57885262/129929487-9f2df56d-e6b7-426a-bf2a-afa19855756f.png)

Ingress.yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: foo
>   namespace: default
>   annotations:
>     konghq.com/strip-path: "false"
>     #kubernetes.io/ingress.class: kong 
>     konghq.com/plugins: my-custom-plugin
> spec:
>   ingressClassName: kong
>   rules:
>   - http:
>       paths:
>       - path: /foo
>         pathType: Prefix
>         backend:
>           service:
>             name: foo-service
>             port:
>               number: 5000

Plugin.yaml

> apiVersion: configuration.konghq.com/v1
> kind: KongPlugin
> metadata:
>   name: my-custom-plugin
> config:
>   header_value: "my first plugin"
> plugin: myheader

**Reply by shaneutt** [reply]
It would appear that either:

1. your plugin isn't actually being applied
2. the code isn't valid for the result you're looking for

You can check for (1) by listing plugins in the Admin API directly.

For (2) it's possible that you can't use that function in that location:

https://github.com/Kong/kong/blob/master/kong/pdk/response.lua#L746

And you may need to move the code into the access phase.

The example plugin is designed to modify the headers of an existing response, not provide a complete response on its own, whereas the `access` phase can immediately issue a response:

https://github.com/Kong/kong/blob/master/kong/plugins/request-termination/handler.lua

See the following links for reference:

- https://github.com/openresty/lua-nginx-module#ngxstatus
- https://github.com/Kong/kong/blob/master/kong/pdk/response.lua#L819
- https://github.com/Kong/kong/blob/master/kong/pdk/response.lua#L541

And try a variation where you use `exit()` in the `access` phase.

Alternatively, if you just want to override the status of an existing response, use this instead:

- https://docs.konghq.com/gateway-oss/2.4.x/pdk/kong.response/#kongresponseset_statusstatus

**Reply by MinhDuc010194** [reply]
I use this api to get all plugins curl -i -X GET https://localhost:8444/plugins --insecure.
then I got back {"next":null,"data":[]}.
Is this because my plugin isn't actually being applied? How can I resolve this because all lua files had been mounted to pod/ingress-kong? And one more thing. Can kong in dbless mode using a custom plugin? I'm using kong ingress with dbless mode.

this is the config that I change.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ingress-kong
  name: ingress-kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-kong
  template:
    metadata:
      annotations:
        kuma.io/gateway: enabled
        prometheus.io/port: "8100"
        prometheus.io/scrape: "true"
        traffic.sidecar.istio.io/includeInboundPorts: ""
      labels:
        app: ingress-kong
    spec:
      containers:
      - env:
        - name: KONG_PROXY_LISTEN
          value: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
        - name: KONG_PORT_MAPS
          value: 80:8000, 443:8443
        - name: KONG_ADMIN_LISTEN
          value: 127.0.0.1:8444 ssl
        - name: KONG_STATUS_LISTEN
          value: 0.0.0.0:8100
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_NGINX_WORKER_PROCESSES
          value: "2"
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        image: kong:2.5
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - kong quit
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: proxy
#Mount volume plugins
        volumeMounts:
        - name: kong-plugin-myheader
          mountPath: /opt/kong/plugins/myheader
        ports:
        - containerPort: 8000
          name: proxy
          protocol: TCP
        - containerPort: 8443
          name: proxy-ssl
          protocol: TCP
        - containerPort: 8100
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      - env:
# Add plugin env
        - name: KONG_PLUGINS
          value: bundled,myheader
        - name: KONG_LUA_PACKAGE_PATH
          value: "/opt/?.lua;;"  
        - name: CONTROLLER_KONG_ADMIN_URL
          value: https://127.0.0.1:8444
        - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
          value: "true"
        - name: CONTROLLER_PUBLISH_SERVICE
          value: kong/kong-proxy
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: kong/kubernetes-ingress-controller:1.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1          
        name: ingress-controller
        ports:
        - containerPort: 8080
          name: webhook
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      serviceAccountName: kong-serviceaccount
#Create Volume
      volumes:
      - name: kong-plugin-myheader
        configMap:
          name: kong-plugin-myheader
```
