### DISCUSSION TITLE
can i use kong ingress controller on bare metal?

### DISCUSSION THREAD

**Discussion by ssam13** [Kong/kubernetes-ingress-controller#1819] [Q&A] [answered]
Hi everybody!
I've installed kong-ingress-controller using yaml file on a 3-nodes k8s cluster( bare metal ) and every thing is up and runnig.
the problem is with kong-proxy service: the EXTERNAL_IP field is pending.
i've asked about this problem in stackoverflow: https://stackoverflow.com/questions/69158477/kong-ingress-controllers-external-ip-is-pending
can anyone help me?

**Comment by shaneutt** [comment, marked as answer]
Hi @hesmoh :wave:,

When using a cloud provider the `LoadBalancer` type for `Services` will be managed and provisioned by the environment (see https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#external-load-balancer-providers) automatically, but when creating your own baremetal cluster you will need to add the service which will manage provisioning IPs for `LoadBalancer` type `Services`. One such service is [Metal-LB](https://metallb.org/) which is purpose built for this. Alternatively, you can use a `NodePort` type `Service` instead, and in fact our [Helm Chart](https://github.com/kong/charts) provides some options for deploying the ingress controller with `NodePort` instead of `LoadBalancer` type `Services`.

**Reply by ssam13** [reply]
Thanks for the complete explanation
I will try one of the methods you mentioned

**Comment by esatterwhite** [comment]
We're using metal lb in some environments (not aws), and this config worked out of the box.

```yaml   
   - apiVersion: v1
      kind: Service
      metadata:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
        name: kong-proxy
        namespace: kong
      spec:
        type: LoadBalancer
        externalTrafficPolicy: Local
        selector:
          app: ingress-kong
        ports:
        - name: proxy
          port: 80
          protocol: TCP
          targetPort: 8000
        - name: proxy-ssl
          port: 443
          protocol: TCP
          targetPort: 84
```
