### DISCUSSION TITLE
Centralized OAuth2 authentication with Kong Ingress Controller Not Working

### DISCUSSION THREAD

**Discussion by shahamit** [Kong/kubernetes-ingress-controller#1833] [Q&A] [answered]
I want to enable centralized authentication when deploying kong as a kubernetes ingress controller running with postgres database. Hence I deployed the plugin as decribed in this [yaml](https://pastebin.com/yLhEbJTt) file and added the plugin to the ingress component as shown in this [yaml](https://pastebin.com/qVgf8YG2). The yaml file contents are pasted below too for easy reference. I am running k3s on my laptop as the kubernetes cluster.

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oauth-mk8s-ingress
  namespace: kong
config:
  enable_authorization_code: true
  issuer: https://dev-13044354.okta.com/oauth2/default
plugin: oauth2
```

```
---
apiVersion: v1
kind: Service
metadata:
  name: mk8s-k8s-order-service
  namespace: mk8s
spec:
  ports:
  - port: 8981
    targetPort: 8981
    name: tcp
  selector:
    app: mk8s-k8s-order
---
apiVersion: v1
kind: Service
metadata:
  name: mk8s-k8s-customer-service
  namespace: mk8s
spec:
  ports:
  - port: 8980
    targetPort: 8980
    name: tcp
  selector:
    app: mk8s-k8s-customer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mk8s-k8s-ingress
  namespace: mk8s
  annotations:
    konghq.com/plugins: oauth-mk8s-ingress
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /api/order
        pathType: Prefix
        backend:
          service:
            name: mk8s-k8s-order-service
            port:
              number: 8981
      - path: /api/customer
        pathType: Prefix
        backend:
          service:
            name: mk8s-k8s-customer-service
            port:
              number: 8980
```
Even after applying the plugin I do not get an error if the Authorization header is not passed when making the api request through curl. I get a valid api response.
If I modify my application code to support OAuth2 authentication then it works (i.e. I get the 401 error) but that would defeat the purpose of having centralized authentication since each microservice would have to add support for OAuth2. I am hoping kong can do that centrally i.e. as an api gateway parse the http header and validate the access token either by communicating with the OAuth2 server or by itself if the access tokens are [self-encoded JWT access tokens](https://www.oauth.com/oauth2-servers/access-tokens/self-encoded-access-tokens/)

I suspect one reason for this could be the fact that the address field is not populated for the ingress controller as shown in this [screenshot](https://pasteboard.co/EAFlSgELv0Tc.png). It gets populated when traefik acts as an ingress controller. Due to this I cannot access the apis exposed by the microservices (pods) from outside.

Could you please guide me on what could be missing?
Thanks.
