### DISCUSSION TITLE
for ACME plugin, what's the best practice for updating domains

### DISCUSSION THREAD

**Discussion by MarkYQJ** [Kong/kubernetes-ingress-controller#2677] [General]
An ACME plugin (KongClusterPlugin) with below configuration is deployed.

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: acme-kongclusterplugin
  labels:
    global: "true"
config: 
  domains:
  - a.b.c.d
plugin: acme
```
When here comes another domain e.f.g.h, the **creation** of another ACME plugin will **failed** (reported by kong ingress)
```
level=error msg="multiple KongPlugin definitions found with 'global' label for 'acme', the plugin will not be applied"
```

Based on the error message, I think the only way to add "e.f.g.h" to hosts is to **update** current configuration.
Because both KongClusterPlugin CRs are applied without any complain from k8s, it's totally related to KIC design.
May I know what's the best practice for updating domains (including domain addition and deletion)

Thank you
