### DISCUSSION TITLE
Disable retry when request timeout

### DISCUSSION THREAD

**Discussion by hnhai** [Kong/kubernetes-ingress-controller#3231] [Q&A]
When I call request to service through Kong Ingress Controller.
If request timeout, request will be auto retry.
I want disable retry, but don't see any configuration.
Thank you

**Comment by danieldaeschle** [comment]
Unbelievable that this is not answered. I need the same. I have endpoints with long running tasks.

**Comment by pmalek** [comment]
Hi @danieldaeschle and @hnhai 👋 

You should be able to achieve this by setting the `konghq.com/retries` annotation on the `Service`:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/retries: "0"
  labels:
    app: httpbin
  name: httpbin-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
  type: ClusterIP
```

https://docs.konghq.com/kubernetes-ingress-controller/latest/reference/annotations/#konghqcomretries

That will set the `retries` on the underlying Kong service:

```
updated_at: 1724428717
port: 80
client_certificate: ~
ws_id: 0dc6f45b-8f8d-40d2-a504-473544ee190b
tls_verify: ~
id: 41e0df75-8715-5017-b56b-431e70ccd2ff
ca_certificates: ~
connect_timeout: 60000
read_timeout: 60000
path: /
write_timeout: 60000
host: httpbin-deployment.default.80.svc
created_at: 1724428717
protocol: http
tags:
  - k8s-name:httpbin-deployment
  - k8s-namespace:default
  - k8s-kind:Service
  - k8s-uid:ef15e1ca-7e5e-4dda-b189-6df728b01104
  - k8s-version:v1
name: default.httpbin-deployment.80
tls_verify_depth: ~
enabled: true
retries: 0
```
