### DISCUSSION TITLE
IngressClass not recognize by ingress-controller

### DISCUSSION THREAD

**Discussion by Tomelin** [Kong/kubernetes-ingress-controller#3595] [Q&A]
Hi all,

I'm configurating the Kong Ingress Controller and I want create one ingress controller by namespace but this moment doesn't working and I don't found the problem.

My configurations are:

**Ingress Class**
```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: myclass
spec:
  controller: ingress-controllers.konghq.com/kong
```

**Ingress**
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: konga
  annotations:
    konghq.com/strip-path: 'false'
spec:
  ingressClassName: myclass
  rules:
  - host: myhost.domain.com
    http:
      paths:
      - backend:
          service:
            name: mysvc
            port:
              number: 80
        path: /
        pathType: Prefix
```

Ingress Controller
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kong-ingress-controller
  name: kong-ingress-controller
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-ingress-controller
  template:
    metadata:
      annotations:
        kuma.io/gateway: enabled
        kuma.io/service-account-token-volume: kong-serviceaccount-token
        traffic.sidecar.istio.io/includeInboundPorts: ""
      labels:
        app: kong-ingress-controller
    spec:
      automountServiceAccountToken: false
      containers:
      - name: ingress-controller
        env:
        - name: CONTROLLER_INGRESS_CLASS
          value: myclass
        - name: CONTROLLER_KONG_ADMIN_SVC
          value: kong/kong-admin
        - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
          value: "true"
        - name: CONTROLLER_PUBLISH_SERVICE
          value: kong/kong-proxy
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KONG_DATABASE
          valuae: "off":
        image: kong/kubernetes-ingress-controller:2.8.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi   
          limits:
            cpu: 250m
            memory: 256Mi
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: webhook
          protocol: TCP
        - containerPort: 10255
          name: cmetrics
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kong-serviceaccount-token
          readOnly: true
      serviceAccountName: kong-serviceaccount
      volumes:
      - name: kong-serviceaccount-token
        projected:
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace

```

I don't what the problem in configuration, but the controller doesn't recognize a new ingressClass and doesn't create a new loadbalancer.
