### DISCUSSION TITLE
KIC upgrade to 2.10.0

### DISCUSSION THREAD

**Discussion by balait4** [Kong/kubernetes-ingress-controller#4159] [Q&A] [answered]
Hi, when I upgrade KIC to `2.10.0` from `2.8.1`,  I'm getting the below message in KIC. I have this in my OKD(openshift) cluster. 
Kong version `3.3.0`.

```
time="2023-06-09T20:12:52Z" level=error msg="error fetching EndpointSlices" error="EndpointSlices for Service dev-proxy/vector-statistics-least-conn not found" service_name=vector-statistics-least-conn service_namespace=dev-proxy service_port="&ServicePort{Name:app,Protocol:TCP,Port:8080,TargetPort:{0 8096 },NodePort:0,AppProtocol:nil,}"
time="2023-06-09T20:12:52Z" level=warning msg="no active endpoints" service_name=vector-statistics-least-conn service_namespace=dev-proxy service_port="&ServicePort{Name:app,Protocol:TCP,Port:8080,TargetPort:{0 8096 },NodePort:0,AppProtocol:nil,}"
time="2023-06-09T20:12:52Z" level=info msg="no targets could be found for kubernetes service dev-proxy/vector-statistics-least-conn" service_name=dev-proxy.ingress-vector-statistics-least-conn.vector-statistics-least-conn.8080
time="2023-06-09T20:12:52Z" level=info msg="no targets found to create upstream" service_name=dev-proxy.ingress-vector-statistics-least-conn.vector-statistics-least-conn.8080

```

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-vector-statistics-least-conn
  namespace: dev-proxy
  annotations:
    konghq.com/https-redirect-status-code: '301'
    konghq.com/protocols: https
    konghq.com/strip-path: 'true'
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: dev.com
      http:
        paths:
          - path: /vector-statistics
            pathType: ImplementationSpecific
            backend:
              service:
                name: vector-statistics-least-conn
                port:
                  number: 8080
```
