### DISCUSSION TITLE
regex issue

### DISCUSSION THREAD

**Discussion by balait4** [Kong/kubernetes-ingress-controller#4307] [General]
Hi Team,

Before upgrade KIC to 2.10 and kong to 3.3.0 the below regex worked fine.
`path: /test/(groups|locations|0|1|2|3)`

But after upgrade it is not working and we solved it by split it up like below:
```
path: /test/groups
path: /test/location
path: /test/0
path: /test/1
path: /test/2
path: /test/3
```

Is this expected behaviour? or did I miss anything part of upgrade?

Thanks

**Comment by pmalek** [comment]
Hi @balait4 👋 

Which version did you upgrade from? 2.7 included breaking changes w.r.t. regexes https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#breaking-changes-1

> - Ingress paths that begin with `/~` are now treated as regular expressions,
  and are translated into a Kong route path that begins with `~` instead of
  `/~`. To preserve the existing translation, set `konghq.com/regex-prefix` to
  some value. For example, if you set `konghq.com/regex-prefix: /@`, paths
  beginning with `/~` will result in route paths beginning in `/~`, whereas
  paths beginning in `/@` will result in route paths beginning in `~`.
  [#2956](https://github.com/Kong/kubernetes-ingress-controller/pull/2956)

**Reply by balait4** [reply]
yes from version `2.3.1` followed the upgrade path.

**Reply by pmalek** [reply]
Do you mean you followed this https://docs.konghq.com/kubernetes-ingress-controller/2.7.x/guides/upgrade-kong-3x/#update-ingress-regular-expression-paths-for-kong-3x-compatibility? Can you share what your ingress looked like before and after?

**Comment by balait4** [comment]
same version where my regex working fine on my staging and I have this problem in production.

**Comment by balait4** [comment]
Here is the ingress before and after upgrade. We had to split up otherwise it was not working.

`Before`
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/https-redirect-status-code: '301'
    konghq.com/protocols: https
    konghq.com/strip-path: 'false'
    kubernetes.io/ingress.class: kong
  name: ingress-test-least-conn
spec:
rules:
  - host: api.test.com
    http:
      paths:
        - path: /test/(groups|locations|0|1|2|3)
          pathType: ImplementationSpecific
          backend:
            service:
              name: test-least-conn
              port:
                number: 8080
  - host: api.test.com
    http:
      paths:
        - path: /edge-statistics/
          pathType: ImplementationSpecific
          backend:
            service:
              name: test-2019-least-conn
              port:
                number: 8080
  tls:
  - hosts:
    - api.test.com
    secretName: ssl-api-test-com
```
`After`
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-test-least-conn
  annotations:
    konghq.com/https-redirect-status-code: '301'
    konghq.com/protocols: https
    konghq.com/strip-path: 'false'
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - hosts:
        - api.test.com
      secretName: ssl-test
  rules:
    - host: api.test.com
      http:
        paths:
          - path: /test/groups
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-least-conn
                port:
                  number: 8080
          - path: /test/location
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-least-conn
                port:
                  number: 8080
          - path: /test/0
            pathType: ImplementationSpecific
            backend:
              service: 
                name: test-least-conn
                port:
                  number: 8080
          - path: /test/1
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-least-conn
                port:
                  number: 8080
          - path: /test/2
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-least-conn
                port:
                  number: 8080
          - path: /test/3
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-least-conn
                port:
                  number: 8080
    - host: api.test.com
      http:
        paths:
          - path: /test/
            pathType: ImplementationSpecific
            backend:
              service:
                name: test-2019-least-conn
                port:
                  number: 8080
```
