### DISCUSSION TITLE
Ingress controller wildcard certificate

### DISCUSSION THREAD

**Discussion by dariaguy** [Kong/kubernetes-ingress-controller#4361] [Q&A] [answered]
Hi, I'm working on a disconnected openshift environment where it's not possible to use Let's encrypt. I want to use a default wildcard certificate on the ingress controller, so that every ingress resource that is using the ingress controller will use the certificate. How can I achieve this?

**Comment by programmer04** [comment, marked as answer]
Create a secret with your wildcard certificate in the namespace where KIC is deployed

```sh
kubectl create secret tls kong-proxy-tls \
  --cert=path/to/cert/file \
  --key=path/to/key/file
```

For KIC installed with Helm add to your `values.yaml` the below for respective sections

```yaml

env:
  ssl_cert: /etc/secrets/kong-proxy-tls/tls.crt
  ssl_cert_key: /etc/secrets/kong-proxy-tls/tls.key

secretVolumes:
  - kong-proxy-tls

```

for a general case you can read more [in the docs](https://docs.konghq.com/gateway/latest/reference/configuration/#ssl_cert), respective environment variables of Kong Gateway are `KONG_SSL_CERT` and `KONG_SSL_CERT_KEY`.



> If the above answers your question please click `Mark as answer` to increase visibility for others.
