### DISCUSSION TITLE
How to set the ring-balancer to use latency algorithm?

### DISCUSSION THREAD

**Discussion by stricklandye** [Kong/kubernetes-ingress-controller#4613] [Q&A] [answered]
I want to set ring-balancer to use latency algorithm , following the [docs](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-kongingress-resource/) here I create a KongIngress resource but I go error message likes:
```
Unsupported value: "latency": supported values: "round-robin", "consistent-hashing", "least-connection
```
The [deploy file](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-postgres.yaml) seems that latency algorithm is not added in to CRD. So how should I use latency algorithm? Here are the algorithms available by default,quoted from previous mentioned deploy file.
```
    algorithm:
      description: Algorithm is the load balancing algorithm to use.
      enum:
      - round-robin
      - consistent-hashing
      - least-connections
```

**Comment by pmalek** [comment]
Hi @stricklandye 👋 

It seems that the `latency` option was only added in Gateway 3.2: https://github.com/Kong/kong/blob/master/CHANGELOG.md#320

> - Add a new load-balancing algorithm option latency to the Upstream entity. This algorithm will choose a target based on the response latency of each target from prior requests. https://github.com/Kong/kong/pull/9787

I suppose you're running an older version then 3.2 hence the reason for this.

**Reply by stricklandye** [reply]
Thanks for your response. I use kong 3.3 with kic 2.11 actually. Steps to reproduce:
KongIngress:
```yaml
# kong_lb_latency.yaml 
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-lb-latency
upstream:
  algorithm: latency
```
```
$kubectl describe pod kong-1691733995-kong-759f4484d-562zx -n kong  | grep Image
    Image:         kong:3.3
    Image ID:      docker-pullable://kong@sha256:88aad0fa3c603af1b2ced86f33f0c28f664bf7b53c92aec1256746136b8832ca
    Image:          kong/kubernetes-ingress-controller:2.11
    Image ID:       docker-pullable://kong/kubernetes-ingress-controller@sha256:ea24cfa6d2251aaaf050a245420259dc4e58314cf6fbeedb463cff2fe65becb7
    Image:          kong:3.3
    Image ID:       docker-pullable://kong@sha256:88aad0fa3c603af1b2ced86f33f0c28f664bf7b53c92aec1256746136b8832ca
$ k apply -f kong_lb_latency.yaml
The KongIngress "kong-lb-latency" is invalid: upstream.algorithm: Unsupported value: "latency": supported values: "round-robin", "consistent-hashing", "least-connections"
```
And, I think it's irrelevant to kong version, because the follwing properties in [deploy file](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-postgres.yaml) does not include the `latency` algorithm. So the right way is to append `latency` alogrithm to the manifest?
```yaml
    properties:
      algorithm:
        description: Algorithm is the load balancing algorithm to use.
        enum:
        - round-robin
        - consistent-hashing
        - least-connections
        type: string
```
