### DISCUSSION TITLE
controllers.Gateway: Reconciler error "service ref kong/kong-gateway-proxy did not match controller manager ref"

### DISCUSSION THREAD

**Discussion by mikyll** [Kong/kubernetes-ingress-controller#5321] [Q&A] [answered]
I'm sorry to be always bothering you all, but I'm stuck and I cannot debug this error:
```lang-none
2023-12-12T11:09:14Z    error   controllers.Gateway     Reconciler error        {"reconcileID": "0b9efaca-3efe-4740-90d0-cc45c018719b", "error": "service ref kong/kong-gateway-proxy did not match controller manager ref kong/kong-1702379291-kong-proxy or /"}
```
- What does it mean?
- How should I procede to solve it?

### Context

**System**: Windows with WSL2 and Docker Desktop
**Kubernetes Cluster**: minikube

I'm trying to deploy **KIC DB-backed**, to test Oauth2 plugin on a service. I'm using [kong/kong]() helm chart to deploy it:
```bash
helm install kong/kong --generate-name --create-namespace -n kong -f values.yaml
```
And the `values.yaml` file is the following (the username and password are set like this for testing purposes), which I edited from [minimal-k4k8s-with-kong-enterprise.yaml](https://github.com/Kong/charts/blob/main/charts/kong/example-values/minimal-k4k8s-with-kong-enterprise.yaml):
```yaml
image:
  repository: kong/kong-gateway
  tag: "3.5"

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

enterprise:
  enabled: false
  vitals:
    enabled: false
  portal:
    enabled: false
  rbac:
    enabled: false
  smtp:
    enabled: false

portal:
  enabled: false

portalapi:
  enabled: false

env:
  prefix: /kong_prefix/
  database: postgres
  pg_user: kong-db-user
  pg_password: kong-db-password-test

postgresql:
  enabled: true
  auth:
    database: kong
    username: kong-db-user
    password: kong-db-password-test

ingressController:
  enabled: true
```

Pods:
```bash
$ kubectl get pods -n kong
NAME                                         READY   STATUS      RESTARTS   AGE
kong-1702379291-kong-6f6f65cb9f-qtsph        2/2     Running     0          48s
kong-1702379291-kong-init-migrations-6q8np   0/1     Completed   0          48s
kong-1702379291-postgresql-0                 1/1     Running     0          47s
```

Is there anyone that could be so kind to help me out and tell how to solve it or just address me to some resource/documentation to that could be useful to understand it?
Should I use kong/ingress instead? How could I configure the DB with that chart?
