### DISCUSSION TITLE
How to set timeouts when using Gateway API

### DISCUSSION THREAD

**Discussion by heruscode** [Kong/kubernetes-ingress-controller#6468] [Q&A] [answered]
hey, I am using GatewayAPI and trying to customize the timeout values of a backend service in my cluster.

I tried to add `konghq.com` annotations to the http route:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    konghq.com/connect-timeout: "1800000"
    konghq.com/read-timeout: "1800000"
    konghq.com/write-timeout: "1800000"
  name: charmander-dev3-kong
  namespace: dev3
spec:
  hostnames:
  - charmander-dev3.dev3.mydomain.com
...
```
and also directly add the same annotations to the kong proxy Service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    konghq.com/connect-timeout: "1800000"
    konghq.com/read-timeout: "1800000"
    konghq.com/write-timeout: "1800000"
    meta.helm.sh/release-name: kong
    meta.helm.sh/release-namespace: kong
  labels:
    app.kubernetes.io/instance: kong
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway
    app.kubernetes.io/version: "3.6"
    enable-metrics: "true"
    helm.sh/chart: gateway-2.39.3
  name: kong-gateway-proxy
  namespace: kong
spec:
...
```

but when looking at the config dump, I still see the default timeout (`60000`) for the service:
```
 {
        "connect_timeout": 60000,
        "host": "httproute.dev3.charmander-dev3-kong.0",
        "id": "d675634f-e96b-5df7-b497-ff4ef13410c3",
        "name": "httproute.dev3.charmander-dev3-kong.0",
        "port": 28000,
        "protocol": "http",
        "read_timeout": 60000,
        "retries": 5,
        "write_timeout": 60000,
        "tags": [
          "k8s-name:charmander-dev3",
          "k8s-namespace:dev3",
          "k8s-kind:Service",
          "k8s-uid:0e9a3bd7-ef6a-4743-9d7f-c3f86f975aaa",
          "k8s-version:v1"
        ],
```

am I missing something?

**Comment by heruscode** [comment, marked as answer]
after some digging, I discovered that I needed to insert the annotations into Service resources

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "charmander-dev3"}'
    konghq.com/connect-timeout: "1800000"
    konghq.com/read-timeout: "1800000"
    konghq.com/write-timeout: "1800000"
  name: charmander-dev3
  namespace: dev3
```
