### DISCUSSION TITLE
How to globally set NGINX proxy timeouts on Kong via KIC

### DISCUSSION THREAD

**Discussion by mloskot** [Kong/kubernetes-ingress-controller#6662] [Q&A]
I deploy Kong 3.6 (KIC 3.2) to my Azure Kubernetes Services cluster with using Kong chart 2.40.0 with the aim to extend the default proxy timeouts, so I stick this into the values:

```yaml
    env:
      nginx_proxy_proxy_connect_timeout: 180s
      nginx_proxy_proxy_read_timeout: 180s
      nginx_proxy_proxy_send_timeout: 180s
```

I can see it gets translated to the following variables in Kong pods:/containers:

```yaml
KONG_NGINX_PROXY_PROXY_CONNECT_TIMEOUT : 180s
KONG_NGINX_PROXY_PROXY_READ_TIMEOUT : 180s
KONG_NGINX_PROXY_PROXY_SEND_TIMEOUT : 180s
```

Is there any way to verify the custom values do make it into Kong's proxy config?

In order to test slow responses do not time out, I have:
- deployed https://github.com/mccutchen/go-httpbin configured `MAX_DURATION=240s`
- request its `/delay` endpoint with time longer than NGINX default timeout of 60s but lower than my custom timeouts e.g. `/delay/63`

Unfortunately, Kong proxy shows HTTP 499 

```
2024/11/12 16:49:45 [error] 1322#0: *5800 upstream timed out (110: Connection timed out) while reading response header from upstream, client: XXX.XXX.XXX.142, server: kong, request: "GET /tests/httpbin/delay/63 HTTP/1.1", upstream: "http://10.244.1.59:8080/tests/httpbin/delay/63", host: "example.com", request_id: "d089960ad7c0a809f0a36d15d400a175"
```

and httpbin log 

```
time=2024-11-12T16:48:45.182Z level=WARN msg="499 GET /tests/httpbin/delay/63 60000.2ms" status=499 method=GET uri=/tests/httpbin/delay/63 size_bytes=0 duration_ms=60000.188138 user_agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0" client_ip=XXX.XXX.XXX.142
```

- What am I doing wrong?
- Is such **global setting of timeouts** even feasible?
- Or, are those feasible only via `KongIngress`, `Ingress` or `Service`, which I have not tried yet, as seems to be the case here
   - https://github.com/Kong/kubernetes-ingress-controller/issues/472
   - https://github.com/Kong/kubernetes-ingress-controller/issues/905
   - https://github.com/Kong/kubernetes-ingress-controller/issues/1386
   - https://discuss.konghq.com/t/timeout-configuration-in-db-less-mode-on-k8s/9284
   - https://discuss.konghq.com/t/kong-ingress-not-updating-service-timeouts/9848
   - https://docs.konghq.com/kubernetes-ingress-controller/3.3.x/reference/annotations/#konghqcomconnect-timeout

------

UPDATE: Here is dump of `nginx_proxy_*` part of the configuration requested directly from the Kong in my cluster (via accessed port forwarding):

![image](https://github.com/user-attachments/assets/983bfd2f-72f8-4c5e-9584-e226403bb5a9)

**Comment by mloskot** [comment]
## Kubernetes `Service` annotations work

The only configuration of the timeouts that seems to be working for me is via the `Service` annotations:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: tests
  annotations:
    konghq.com/connect-timeout: "240000"
    konghq.com/read-timeout: "240000"
    konghq.com/write-timeout: "240000"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: httpbin
    app.kubernetes.io/name: httpbin
  type: ClusterIP
```

then `curl http://example.com/tests/httpbin/delay/153` does not end up with HTTP 499 and timeout as in my report above, but Kong proxy logs:

```
XXX.XXX.XXX.142 - - [12/Nov/2024:19:30:37 +0000] "GET /tests/httpbin/delay/153 HTTP/1.1" 200 757 "-" "curl/8.5.0" kong_request_id: "c359352f213abf7ef34655460554741a"
```

and httpbin logs:

```
time=2024-11-12T19:30:37.749Z level=INFO msg="200 GET /tests/httpbin/delay/153 153095.4ms" status=200 method=GET uri=/tests/httpbin/delay/153 size_bytes=757 duration_ms=153095.361186 user_agent=curl/8.5.0 client_ip=XXX.XXX.XXX.142
```

and the `curl` command above receives the response after `153 seconds` of the delay as per `/delay/153` in the request:

```
$ curl http://example.com/tests/httpbin/delay/153
{
  "args": {},
  "headers": {
    "Accept": [
      "*/*"
    ],
    "Connection": [
      "keep-alive"
    ],
    "Host": [
      "example.com"
    ],
    "User-Agent": [
      "curl/8.5.0"
    ],
    "X-Forwarded-For": [
      "XXX.XXX.XXX.142"
    ],
    "X-Forwarded-Host": [
      "example.com"
    ],
    "X-Forwarded-Path": [
      "/tests/httpbin/delay/153"
    ],
    "X-Forwarded-Port": [
      "80"
    ],
    "X-Forwarded-Proto": [
      "http"
    ],
    "X-Kong-Request-Id": [
      "c359352f213abf7ef34655460554741a"
    ],
    "X-Real-Ip": [
      "XXX.XXX.XXX.142"
    ]
  },
  "method": "GET",
  "origin": "XXX.XXX.XXX.142",
  "url": "http://example.com/delay/153",
  "data": "",
  "files": {},
  "form": {},
  "json": null
}
```

## Question remains

Why these global settings (copied from my report above) on Kong do not work?

```
env:
  nginx_proxy_proxy_connect_timeout: 180s
  nginx_proxy_proxy_read_timeout: 180s
  nginx_proxy_proxy_send_timeout: 180s
```
