### DISCUSSION TITLE
TCPIngress not working

### DISCUSSION THREAD

**Discussion by josemrs** [Kong/kubernetes-ingress-controller#7276] [Q&A]
Hi,

I'm trying to set up a TCPIngress to a Redis cluster and I cannot figure out what is wrong.

I can see the open port in the AWS load balancer, the target group is correct and healthy pointing to the two Kong pods. Kong pods are listening for stream in 6379. However, when trying to connect using redis-cli the connection hangs for a while and fail. The service work because I connect just fine if I forward the port. I also tried connecting to the AWS LB address and Kong ports directly, same behaviour.

Thanks in advance for any help you can provide,
Jose

This is the TCPIngress:
```
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <REDACTED FQDN>
    konghq.com/preserve-host: 'false'
    konghq.com/protocols: tcp
    konghq.com/request-buffering: 'false'
    konghq.com/response-buffering: 'false'
    konghq.com/strip-path: 'false'
    kubernetes.io/ingress.class: kong-internal
  name: login-service-redis
  namespace: login-service-redis
spec:
  rules:
    - backend:
        serviceName: login-service-redis-leader
        servicePort: 6379
      port: 6379
status:
  loadBalancer:
    ingress:
      - hostname: >-
          k8s-kong-konginte-REDACTED.elb.us-east-1.amazonaws.com

```

In Kong Manager I can see the following configs:

Gateway Service
```
{
  "name": "login-service-redis.login-service-redis-leader.6379",
  "tags": [
    "k8s-name:login-service-redis-leader",
    "k8s-namespace:login-service-redis",
    "k8s-kind:Service",
    "k8s-uid:a932bd0a-329c-4c4d-9e50-d86abc90d9cb",
    "k8s-version:v1",
    "managed-by-kic-internal"
  ],
  "protocol": "tcp",
  "path": null,
  "read_timeout": 60000,
  "retries": 5,
  "host": "login-service-redis-leader.login-service-redis.6379.svc",
  "connect_timeout": 60000,
  "tls_verify_value": false,
  "tls_verify_enabled": false,
  "ca_certificates": null,
  "client_certificate": null,
  "write_timeout": 60000,
  "port": 6379
}
```

Route
```
{
  "name": "login-service-redis.login-service-redis.0",
  "protocols": [
    "tcp"
  ],
  "https_redirect_status_code": 426,
  "strip_path": false,
  "preserve_host": false,
  "request_buffering": false,
  "response_buffering": false,
  "tags": [
    "k8s-name:login-service-redis",
    "k8s-namespace:login-service-redis",
    "k8s-kind:TCPIngress",
    "k8s-uid:5dcde514-c42c-47bb-a59f-4b8f9f936b9d",
    "k8s-group:configuration.konghq.com",
    "k8s-version:v1beta1",
    "managed-by-kic-internal"
  ],
  "service": {
    "id": "a9f4f029-2f0f-568f-b30f-01d39180a984"
  },
  "methods": null,
  "hosts": null,
  "paths": null,
  "headers": null,
  "regex_priority": 0,
  "path_handling": "v0",
  "sources": null,
  "destinations": null,
  "snis": null
}
```

Upstream:
```
{
  "name": "login-service-redis-leader.login-service-redis.6379.svc",
  "slots": 10000,
  "algorithm": "round-robin",
  "hash_on": "none",
  "hash_fallback": "none",
  "healthchecks": {
    "threshold": 0,
    "active": {
      "type": "http",
      "headers": {},
      "healthy": {
        "interval": 0,
        "successes": 0
      },
      "unhealthy": {
        "interval": 0,
        "http_failures": 0,
        "tcp_failures": 0
      }
    },
    "passive": {
      "type": "http",
      "healthy": {
        "successes": 0
      },
      "unhealthy": {
        "timeouts": 0,
        "tcp_failures": 0,
        "http_failures": 0
      }
    }
  },
  "tags": [
    "k8s-name:login-service-redis-leader",
    "k8s-namespace:login-service-redis",
    "k8s-kind:Service",
    "k8s-uid:a932bd0a-329c-4c4d-9e50-d86abc90d9cb",
    "k8s-version:v1",
    "managed-by-kic-internal"
  ]
}
```
