### ISSUE TITLE
How to use consumer to create a credential for key-auth?

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/kubernetes-ingress-controller#1030]
Like I said, I couldn't figure out how to use consumer to create a credential for key-auth plugin or other plugins. Especially in the case of kongCredential deprecated.

For example, this is my route, service and plugin:
```yaml
apiVersion: configuration.konghq.com/v1
config:
  key_names:
  - apiKey
kind: KongPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: kong-key-auth
plugin: key-auth
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/methods: GET
    konghq.com/plugins: kong-key-auth
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
  name: admin
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: test-svc
          servicePort: 80
        path: /test
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: admin
username: admin
```

Then I request test-svc by `curl http://kong-proxy/test -H 'apiKey: xxx'`, But I don't know what the "xxx" should be? and the credential how to generate for key-auth?

Could you give me a example?
