### ISSUE TITLE
Configuring CORS plugin on Ingress results in Access-Control-Allow-Origin intermittently not included as part of response

### ISSUE THREAD

**Issue by rmmorrison** [Kong/kubernetes-ingress-controller#1116]
### Summary

We have deployed Kong as our Ingress controller in front of our application. Some of our customers wish to use our application in a headless-only mode, whereby they develop their own UIs/applications and integrating into our application using REST APIs. We are using Kong's support for CORS (via the plugin) to automatically inject the necessary headers to enable browsers to make cross-origin requests to our application's backend.

While this for the most part is functional, we discovered that intermittently the `Access-Control-Allow-Origin` header is not included as part of the response (while other headers added by the CORS plugin, such as `Access-Control-Allow-Credentials`, are always included). This causes browsers to reject cross-origin requests. Repeating the exact same request may (but not always) properly return _all_ CORS headers (`Access-Control-Allow-Origin` included). If not, continually re-trying the request will eventually result in Kong properly returning the `Access-Control-Allow-Origin` header, but in our testing it may take 10 or more attempts (with the exact same request) for Kong to return the header as expected.

**Kong Ingress controller version**

1.0

**Kong or Kong Enterprise version**

2.1 (also reproduced on 2.3)

### Kubernetes version

```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: AWS Elastic Kubernetes Service

### What happened

On some requests, Kong does not return the `Access-Control-Allow-Origin` header as part of the response when the CORS plugin is configured and a valid origin is provided by the request in the `Origin` header.

### Expected behavior

Kong should always return the `Access-Control-Allow-Origin` header on configured origins when the header is properly provided in the request.

### Steps To Reproduce

(Note the below configuration/setup has been scrubbed to remove proprietary/confidential information, but are directly taken from the affected environment.)

1. Configure the Kong plugin in Kubernetes:
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-customer
plugin: cors
config:
  origins:
  - "https://example.com"
  - "http://example2.com"
  - "http://example3.s3-website-us-east-1.amazonaws.com"
  methods:
  - GET
  - DELETE
  - HEAD
  - OPTIONS
  - POST
  - PUT
  headers:
  - Accept
  - Accept-Encoding
  - Connection
  - Content-Length
  - Content-MD5
  - Content-Type
  - Cookie
  - Date
  - Set-Cookie
  - Session
  - User-Agent
  credentials: true
  max_age: 3600
```
2. Configure the ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: cors-customer
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
  namespace: default
spec:
  rules:
  - host: '*.ourdomain.io'
    http:
      paths:
      - backend:
          serviceName: platform
          servicePort: 8080
        path: /platform/
        pathType: ImplementationSpecific
```
3. Perform a CORS preflight request (same as a browser, e.g. Chrome, would perform):
```
curl 'https://customer.ourdomain.io/platform/login' \
  -H 'authority: customer.ourdomain.io' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'origin: http://example3.s3-website-us-east-1.amazonaws.com' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://example3.s3-website-us-east-1.amazonaws.com/' \
  -H 'accept-language: en-US,en;q=0.9' \
  -X OPTIONS \
  -vvv
```
4. Observe the response and note the missing `Access-Control-Allow-Origin` header (while other CORS headers are properly included):
```
* Uses proxy env variable no_proxy == 'redacted'
*   Trying 10.26.56.70...
* TCP_NODELAY set
* Connected to genproxy (10.26.56.70) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to customer.ourdomain.io:443
> CONNECT customer.ourdomain.io:443 HTTP/1.1
> Host: customer.ourdomain.io:443
> User-Agent: curl/7.64.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< Date: Mon, 22 Mar 2021 20:01:48 GMT
< Proxy-Connection: Keep-Alive
< Via: 1.1 redacted
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=ourdomain.io
*  start date: Jun 10 00:00:00 2020 GMT
*  expire date: Jul 10 12:00:00 2021 GMT
*  subjectAltName: host "customer.ourdomain.io" matched cert's "*.ourdomain.io"
*  issuer: C=redacted; ST=redacted; L=redacted; O=redacted; OU=redacted; CN=redacted; emailAddress=redacted
*  SSL certificate verify ok.
> OPTIONS /platform/login HTTP/1.1
> Host: customer.ourdomain.io
> authority: customer.ourdomain.io
> user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
> content-type: application/json
> accept: */*
> origin: http://example3.s3-website-us-east-1.amazonaws.com
> sec-fetch-site: cross-site
> sec-fetch-mode: cors
> sec-fetch-dest: empty
> referer: http://example3.s3-website-us-east-1.amazonaws.com/
> accept-language: en-US,en;q=0.9
> 
< HTTP/1.1 200 
< Date: Mon, 22 Mar 2021 20:12:32 GMT
< Content-Length: 0
< X-B3-TraceId: 807421dd6a61d66d
< X-Tenant-ID: redacted
< Allow: POST,OPTIONS
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< vary: Origin
< Access-Control-Allow-Credentials: true
< X-Kong-Upstream-Latency: 3
< X-Kong-Proxy-Latency: 0
< Via: kong/2.1.4, HTTPS/1.1 redacted
< Age: 0
< 
* Connection #0 to host genproxy left intact
* Closing connection 0
```

We have tried removing all configured origins from the `KongPlugin` resource except for the one origin under test, as well as explicitly setting `preflight_continue` to false (even though it _should_ be the default). We also reproduced the issue on a non-AWS environment where there are no proxies in front of the Kubernetes cluster (unlike AWS in which we have AWS load balancers).
