### ISSUE TITLE
kong Plugin code kong.service.set_upstream is not work for a route

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/kubernetes-ingress-controller#1129]
I have a ingress and a plugin:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
    - image: mendhak/http-https-echo
      imagePullPolicy: Always
      name: test
      resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    app: test
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    konghq.com/strip_path: 'false'
    konghq.com/plugins: test-plugin
spec:
  rules:
    - http:
        paths:
          - path: /test
            backend:
              serviceName: test
              servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
plugin: test-plugin
metadata:
  name: test-plugin
  annotations:
    kubernetes.io/ingress.class: kong
config:
  customize:
    "on": "header"
    "name": "name"
    "range": 
    - "nick"
    "upstream": "test-b.default.80.svc"
```

I want if header has a key named `name`, and its value equal 'nick', then forward the request to another upstream named `test-test.default.80.svc`.
But I set kong.service.set_upstream('test-b.default.80.svc') is not work, it still forward to service `test`.
Anybody know why?
