### ISSUE TITLE
Support for Istio's Virtual Service

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kubernetes-ingress-controller#1152]
### Summary

Hey, I'd like to implement support for Istio's Virtual Service.

Istio has a concept of [Virtual Service](https://istio.io/latest/docs/reference/config/networking/virtual-service/). It is a Service that is recognizable by the host header defined in `hosts` section. Then based on the configuration in `http` section, the traffic is routed to a real Kubernetes Service.

The idea is to use `resource` in `IngressBackend` which takes `TypedLocalObjectReference`. Example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          resource:
            apiGroup: networking.istio.io/v1beta1
            kind: VirtualService
            name: backend
```

To implement this, Kong would have to make a request to any IP (can be non-routable 240.0.0.0) and port 80 with host header defined in VirtualService. Istio is capturing every outgoing traffic on port 80 and trying to match the destination by header.

I see that KIC goes through major refactoring. Is now a good time to implement this issue?
