### ISSUE TITLE
Kong cache upstream response

### ISSUE THREAD

**Issue by Ngob** [Kong/kubernetes-ingress-controller#123]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

It looks like Kong is caching the response's upstream. 
I am not sure about what HTTP header create this behavior.
I am trying to proxy google's document from their bucket via Kong
I am new to Kong and I did not find any ressource on the community edition documentation talking about response caching, so I am not sure if this a bug or a expected behavior.

**Kong Ingress controller version**
0.1.0

### Kubernetes version

**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.2", GitCommit:"384b4eaa132ca9a295fcb3e5dfc74062b257e7df", GitTreeState:"clean", BuildDate:"2018-08-15T00:10:14Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): COS
- **Kernel** (e.g. `uname -a`):
Linux gke-mycluster 4.14.22+ #1 SMP Wed May 30 13:49:27 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.00GHz GenuineIntel GNU/Linux
- **Install tools**:
- **Others**:

### What happened

I added a service, a Kongingress, an Ingress and some plugins with the following configuration:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ingress
  namespace:  foo
proxy:
  path: /foo/baz
  protocol: https
route:
  strip_path: true
---
apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace:  foo
spec:
  type: ExternalName
  externalName: storage.googleapis.com
  ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: transform-request-to-google
  namespace: foo
config:
  remove:
    headers: host
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: foo-cors-ingress
  namespace:  foo
disabled: false
config:
  origins: "my.domain.com"
  max_age: 86400
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: foo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    request-transformer.plugin.konghq.com: |
      transform-request-to-google
    cors.plugin.konghq.com: |
      foo-cors-ingress
spec:
  rules:
    - host: my.domain.com
      http:
        paths:
        - path: /foobazregex(/+.*$|$)
          backend:
            serviceName: svc
            servicePort: https
```

Now when i request https://my.domain.com/foobazregex/qdsfvdq, it return an outdated version of my document. On the first request, HTTP headers are following:
```
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-GUploader-UploadID: AEnB2UrFtNaFg5nxABuu5orrYiFBTpdojcTkHqsnnP71kg2Xo--ml7JnWCYZbAKLpHGhC8L-qZqyZD4Ew8Rmfp4BvIkRMfppSx5GJK4KRmGAAX46jAPwAvU
Date: Tue, 11 Sep 2018 14:13:03 GMT
Expires: Wed, 11 Sep 2019 14:13:03 GMT
Last-Modified: Tue, 11 Sep 2018 13:51:55 GMT
x-goog-generation: 1536673915869880
x-goog-metageneration: 1
x-goog-stored-content-encoding: gzip
x-goog-stored-content-length: 36
x-goog-hash: crc32c=d8Mp4Q==
x-goog-hash: md5=JysxZkRC22NL5N6yaHg8HA==
x-goog-storage-class: REGIONAL
Accept-Ranges: none
Server: UploadServer
Cache-Control: no-transform
Age: 3364
Vary: Accept-Encoding
X-Kong-Upstream-Latency: 5
X-Kong-Proxy-Latency: 32
Via: kong/0.13.1
```

On second and followings calls:

```
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-GUploader-UploadID: AEnB2UrFtNaFg5nxABuu5orrYiFBTpdojcTkHqsnnP71kg2Xo--ml7JnWCYZbAKLpHGhC8L-qZqyZD4Ew8Rmfp4BvIkRMfppSx5GJK4KRmGAAX46jAPwAvU
Date: Tue, 11 Sep 2018 14:13:03 GMT
Expires: Wed, 11 Sep 2019 14:13:03 GMT
Last-Modified: Tue, 11 Sep 2018 13:51:55 GMT
x-goog-generation: 1536673915869880
x-goog-metageneration: 1
x-goog-stored-content-encoding: gzip
x-goog-stored-content-length: 36
x-goog-hash: crc32c=d8Mp4Q==
x-goog-hash: md5=JysxZkRC22NL5N6yaHg8HA==
x-goog-storage-class: REGIONAL
Accept-Ranges: none
Server: UploadServer
Cache-Control: no-transform
Age: 3371
Vary: Accept-Encoding
X-Kong-Upstream-Latency: 2
X-Kong-Proxy-Latency: 0
Via: kong/0.13.1
```

`X-Kong-Proxy-Latency` being at 0 on second call, I suppose Kong is caching the document due to the cache policy

For information, headers returned by google:
```
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
X-GUploader-UploadID: AEnB2UrFtNaFg5nxABuu5orrYiFBTpdojcTkHqsnnP71kg2Xo--ml7JnWCYZbAKLpHGhC8L-qZqyZD4Ew8Rmfp4BvIkRMfppSx5GJK4KRmGAAX46jAPwAvU
Date: Tue, 11 Sep 2018 14:13:03 GMT
Expires: Wed, 11 Sep 2019 14:13:03 GMT
Last-Modified: Tue, 11 Sep 2018 13:51:55 GMT
x-goog-generation: 1536673915869880
x-goog-metageneration: 1
x-goog-stored-content-encoding: gzip
x-goog-stored-content-length: 36
x-goog-hash: crc32c=d8Mp4Q==
x-goog-hash: md5=JysxZkRC22NL5N6yaHg8HA==
x-goog-storage-class: REGIONAL
Accept-Ranges: none
Server: UploadServer
Cache-Control: no-transform
Age: 3364
Vary: Accept-Encoding
X-Kong-Upstream-Latency: 5
X-Kong-Proxy-Latency: 32
Via: kong/0.13.1
```
### Expected behvaior

Kong not caching responses or Kong apply the cache policy as a browser will do (on a force refresh, it recall the upstream)

### Steps To Reproduce

I did not re-test theses step, but this is what I do when I deploy:

1. Create a cluster on GKE
2. Add Kong
3. create a google storage bucket 
4. Create a file, deploy it as public using  `gsutil cp -z html -a public-read <file> gs://<bucket>`
5. add my configuration
6. Browse to https://my.domain.com/foobazregex/qdsfvdq
7. Update your file and redeploy using `gsutil cp -z html -a public-read <file> gs://<bucket>`
8. Browse to https://my.domain.com/foobazregex/qdsfvdq
