### ISSUE TITLE
Credential is never added when using Key-Auth plugin

### ISSUE THREAD

**Issue by jdevalk2** [Kong/kubernetes-ingress-controller#131]
### Summary
When creating a Kong Ingress controller, and specifying key authentication plugin, the credential / consumer combination is not added by Ingress Controller.

(Note I have debugged this issue and created a patch for this, see below)

Cause: It will call the wrong rest API endpoint.
For any other authentication form I am sure the called REST URL format is correct, but it's not for Key-Auth. 
Referencing  document: https://docs.konghq.com/hub/kong-inc/key-auth/ # Create A Key

**Kong Ingress controller version**

Latest (0.1.0)

### Kubernetes version

1.11.3

### Environment

Azure AKS
Docker images stock and unaltered.

### What happened

Create Kong Ingress controller inside Kubernetes cluster
Configure a service and a route.
Configure the route with key-auth plugin. This is the plugin that will compare a header value of incoming request against a list of known key values. If it does not match, the request is rejected.

The result is that the Consumer is added but the Credential is never added.
Credential never gets added.

### Expected behaviour

Expected to see both the Consumer and the Credential created in Kong.
Credential added to Kong.

### Steps To Reproduce

Sample config I am using:

```
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: stuff-ingress-rule
  annotations:
    kubernetes.io/ingress.class: "nginx"
proxy:
  path: "/urlendpoint/stuffdata"
route:
  methods:
  - GET
  - POST
  strip_path: true
  preserve_host: false
upstream:
  hash_on_cookie: "sessionAffinity"
  hash_on: "cookie"
  hash_fallback: "none"
  hash_on_cookie_path: "/"
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: stuff-consumer
username: stuffUser
---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: credential-stuff-consumer
consumerRef: stuff-consumer
type: key-auth
config:
  key: verysecretkey  
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-name
config:
  key_names: apiKey
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stuff-ingress-rule
  annotations:
    kubernetes.io/ingress.class: "nginx"
    key-auth.plugin.konghq.com: "key-auth-name"
spec:
  rules:
  - host: "*.cloudapp.net"
    http:
      paths:
      - path: /stuff/v1
        backend:
          serviceName: backend-service-hs
          servicePort: 8888
```
