### ISSUE TITLE
HashOnCookie and HashOnCookiePath are not propagated through the Ingress Controller

### ISSUE THREAD

**Issue by jdevalk2** [Kong/kubernetes-ingress-controller#132]
### Summary

How each request is routed to which backend server is determined by HashOn setting.

One strategy is to write a cookie in the request so that the next request that comes in can be routed to the same backend server (stick session).

Setting a route with HashOn strategy based on Cookie, the HashOnCookie and HashOnCookiePath are never parsed and thus ignored.  
By being empty the HashOn strategy can never be set to cookie in Kong Ingress Controller rule specification.

Note I have an initial patch for this below.

### Kubernetes version

1.11.3

### Environment

Azure AKS

### What happened

Trying to set the hash strategy to cookie, without success.
Upon investigation it seems that the code is not there to propagate HashOnCookie and HashOnCookiePath. So these values are always empty.

Because they are not parsed and empty, the Cookie setting itself is also flagged as invalid.

### Expected behaviour

I can set HashOn strategy to Cookie
I can set the HashOnCookie and HashOnCookiePath and when I then look in the Kong database, I can see those settings persisted and used by the Kong api gateway.

### Steps To Reproduce

```
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: stuff-ingress-rule
  annotations:
    kubernetes.io/ingress.class: "nginx"
proxy:
  path: "/urlendpoint/stuffdata"
route:
  methods:
  - GET
  - POST
  strip_path: true
  preserve_host: false
upstream:
  **hash_on_cookie: "sessionAffinity"
  hash_on: "cookie"
  hash_fallback: "none"
  hash_on_cookie_path: "/"**
```
