### ISSUE TITLE
KIC 2.0 - Fix certificate support

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1354]
Secret fetching appears to be broken currently, cascading on to issues loading certificates. With:

```
$ kubectl get secret -n helmgress test 
NAME   TYPE                DATA   AGE
test   kubernetes.io/tls   2      606d
```
Adding:

```
  tls: 
  - hosts:
    - strippy.example
    secretName: test
```
Results in:
```
time="2021-05-25T23:16:11Z" level=error msg="failed to fetch secret: Secret helmgress/test not found"
```
