### ISSUE TITLE
Cannot modify timeout using KongIngress and Service annotation

### ISSUE THREAD

**Issue by sergerad** [Kong/kubernetes-ingress-controller#1386]
I have tried following this [issue](https://github.com/Kong/kubernetes-ingress-controller/issues/472) to modify the default 60s timeout but nothing is changing.

Kong Ingress Controller I'm using is `kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:1.2`

Ingress is defined as such:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    konghq.com/https-redirect-status-code: "301"
    konghq.com/preserve-host: "false"
    konghq.com/protocols: https
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
    kubernetes.io/tls-acme: "true"
...
```
KongIngress is defined as such:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: abc
proxy:
  protocol: http
  path: /
  connect_timeout: 600000
  retries: 3
  read_timeout: 600000
  write_timeout: 600000
```

The relevant service is defined as below:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    configuration.konghq.com: abc
...
```

All that the ingress controller logs show are this:
```
time="2021-06-02T04:46:16Z" level=info msg="syncing configuration" component=controller
time="2021-06-02T04:46:16Z" level=info msg="no configuration change, skipping sync to kong" component=controller
```
I have tried running `/kong-ingress-controller --v 3` but the logs are the same.

Am I doing something wrong?
