### ISSUE TITLE
Omitting trailing slash results in 301 redirect to relevant Pod IP

### ISSUE THREAD

**Issue by sergerad** [Kong/kubernetes-ingress-controller#1440]
### Summary

Kong proxy is redirecting traffic directly to a Pod's IP via `location` header in 301 redirect response to requests where trailing slash is omitted. Adding trailing slash results in no redirect, works fine.

E.g. location header `location: http://10.244.0.29/docs/`. That IP is cluster local.

**Kong Ingress controller version**

kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:1.2

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"c1ad2bc44e0c7f19a9db0879f7182ff556a8e5b4", GitTreeState:"clean", BuildDate:"2021-05-19T22:27:45Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider**: GKE

### What happened

Relevant proxy logs output:
```
125.239.198.205 - - [16/Jun/2021:22:43:23 +0000] "GET /docs HTTP/1.1" 301 134 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"
```

Here is the Ingress YAML:
```
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/https-redirect-status-code: "301"
      konghq.com/preserve-host: "false"
      konghq.com/protocols: https
      konghq.com/strip-path: "false"
      kubernetes.io/ingress.class: kong
      kubernetes.io/tls-acme: "true"
...
  spec:
    rules:
    - host: deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane-www
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
    - host: www.deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane-www
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
    - host: downloads.deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane-downloads
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
    - host: cloud.deviceplane.com
      http:
        paths:
        - backend:
            serviceName: deviceplane
            servicePort: 80
          path: /
          pathType: ImplementationSpecific
```
Here is the KongIngress YAML (for timeouts):
```
apiVersion: v1
items:
- apiVersion: configuration.konghq.com/v1
  kind: KongIngress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"configuration.konghq.com/v1","kind":"KongIngress","metadata":{"annotations":{},"name":"deviceplane","namespace":"deviceplane"},"proxy":{"connect_timeout":60000,"read_timeout":60000,"write_timeout":60000}}
    creationTimestamp: "2021-06-02T05:49:07Z"
    name: deviceplane
    namespace: deviceplane
  proxy:
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
```

### Expected behavior

Expect no redirect at all. Or expect redirect to not aim at Pod IP but instead point to LB IP.

### Steps To Reproduce

1. Visit deviceplane.com/docs/ confirm success
2. Visit deviceplane.com/docs confirm failure
