### ISSUE TITLE
Basic auth credentials is sharing with all ingress when it is enabled on ingress

### ISSUE THREAD

**Issue by debu99** [Kong/kubernetes-ingress-controller#1490]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

The basic-auth plugin is shared with all ingress, even the ingress uses different basic auth credential

**Kong Ingress controller version**
Helm chart 
version: 2.1.0
appVersion: "2.4"

### Kubernetes version
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Environment
EKS 1.18

### What happened
The ingress should only use the basic auth credential defined in its annotation, other basic auth plugins should not be allowed in this ingress

### Expected behavior
If you use wrong credential or the credentials not defined in the annotation, the ingress should return "Invalid authentication credentials"

### Steps To Reproduce
```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: app-1
  namespace: test
consumerRef: app-1
config:
  hide_credentials: true
plugin: basic-auth
" | kubectl create -f -

echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: app-1
  namespace: test
  annotations:
    kubernetes.io/ingress.class: kong
username: user1
credentials:
- app-1
" | kubectl create -f -

echo '
apiVersion: v1
kind: Secret
metadata:
  name: app-1
  namespace: test
stringData:
  kongCredType: basic-auth
  username: user1
data:
  password: cGFzczE=' | kubectl create -f -

echo '
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-1
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/plugins: "app-1"
spec:
  rules:
  - host: "app-1.xxx.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: app-1
          servicePort: 80
' | kubectl create -f -

echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: app-2
  namespace: test
consumerRef: app-2
config:
  hide_credentials: true
plugin: basic-auth
" | kubectl create -f -

echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: app-2
  namespace: test
  annotations:
    kubernetes.io/ingress.class: kong
username: user2
credentials:
- app-2
" | kubectl create -f -

echo '
apiVersion: v1
kind: Secret
metadata:
  name: app-2
  namespace: test
stringData:
  kongCredType: basic-auth
  username: user2
data:
  password: cGFzczI=' | kubectl create -f -

echo '
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-2
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/plugins: "app-2"
spec:
  rules:
  - host: "app-2.xxx.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: app-2
          servicePort: 80
' | kubectl create -f -

kubectl run app-1 --image nginx -n test
kubectl run app-2 --image ealen/echo-server -n test
kubectl expose pod app-1 --port=80 --name=app-1 -n test
kubectl expose pod app-2 --port=80 --name=app-2 -n test
```
````
curl -u 'user2:pass2' -k -i 'https://application-loadbalancer-123456.elb.amazonaws.com' --header "Host: app-1.xxx.com" 
HTTP/2 200 
...
<title>Welcome to nginx!</title>
...
```
As app-1 ingress should only allow user1:pass1, the user2:pass2 should be rejected!
