### ISSUE TITLE
KIC 2.0 - Secret Finalizers Stuck

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1515]
Currently in KIC 2.0 secrets can get our finalizers attached to them:

```
 -n ingress get secrets default-token-mm99r -o yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 2c90e799-1f28-4020-991b-35d5b801e4e1
  finalizers:
  - configuration.konghq.com/ingress
```

However nothing automatically removes them, causing (among other things) namespaces to get stuck in deletion during CI cleanup.

Acceptance Criteria:
- [x] fix the finalizer issue, possibly by never setting the finalizer but more likely by cleaning it up
- [x] ensure the tests account for this going forward: tests should not pass if namespaces created for them can't clean up
