### ISSUE TITLE
Support for hash_secret property for OAuth2 credentials in KIC

### ISSUE THREAD

**Issue by anup-krai** [Kong/kubernetes-ingress-controller#1521]
### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
Kong - 2.4.1, ingress-controller - 1.2

Currently hash_secret property is not supported when OAuth 2 credentials are generated through ingress-controller.

Kong Consumer -
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test-consumer
  annotations:
    kubernetes.io/ingress.class: kong
username: test-consumer
credentials:
  - test-consumer-oauth2
```
Secret -
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-consumer-oauth2
type: Opaque
data:
  kongCredType: b2F1dGgy
  client_id: Y2xpZW50aWQtZ2VuZXJhdGVkLWZvci1vYXV0aDI=
  client_secret: Y2xpZW50c2VjcmV0LWdlbmVyYXRlZC1mb3Itb2F1dGgy
  redirect_uris: aHR0cHM6Ly9sb2NhbGhvc3Qv
  hash_secret: dHJ1ZQ==
```
Even if I pass hash_secret to true, client secret is not getting hashed in DB.

### Expected behavior

When hash_secret is passed as true then client secret should be hashed and stored in DB.

### Steps To Reproduce

1. Create oauth2 secret and deploy.
2. Create Kong consumer and attach oauth2 secret in Kong consumer credentials.
3. Deploy Kong consumer.

More details - [#7517](https://github.com/Kong/kong/issues/7517)
