### ISSUE TITLE
Proxy Pass not stripping path as expected

### ISSUE THREAD

**Issue by jgramoll** [Kong/kubernetes-ingress-controller#160]
### Summary

Trying to do proxy_pass, and unable to get it working. It could be working as expected, but I am using it wrong. I want to be able to create a catch all route `/` that always goes to `/index.html`.

**Kong Ingress controller version**

0.2.0

**Kong or Kong Enterprise version**

0.14.1

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

### Environment

AWS

### What happened

Trying to do a catch all proxy pass to `index.html`. But it does not strip the path as expected, returning 

`index.html/test/route`

### Expected behvaior

Route should be `/index.html`

### Steps To Reproduce

1. 
```
echo "
apiVersion: v1
kind: Namespace
metadata:
  name: dummy

---

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: dummy-app-ingress
  namespace: dummy
proxy:
  path: /index.html
  protocol: http
route:
  strip_path: true
  preserve_host: false

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-app-ingress
  namespace: dummy
  annotations:
    request-transformer.plugin.konghq.com: transform-request-to-dummy
spec:
  rules:
  - host: lvh.me
    http:
      paths:
      - path: /
        backend:
          serviceName: http-svc
          servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-svc
  namespace: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-svc
  template:
    metadata:
      labels:
        app: http-svc
    spec:
      containers:
      - name: http-svc
        image: gcr.io/google_containers/echoserver:1.8
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  namespace: dummy
  name: http-svc
  labels:
    app: http-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: http-svc
" | kubectl apply -f -
```

2. curl lvh.me/test/route
3. path is /index.html/test/route

**Comment by hbagdi** [comment]
`strip_path` doesn't do what you think it does. Reading the docs, it will strip the matching path portion defined in the ingress rule.
Reference: https://docs.konghq.com/0.14.x/admin-api/#route-object

You can solve the problem by defining a plugin on your default route and then use a [serverless](https://docs.konghq.com/hub/kong-inc/serverless-functions/) plugin as follows:
```yaml
kind: KongPlugin
metadata:
  name: set-path
  namespace: default
config:
  functions
  - "kong.service.request.set_path('/index.html')"
plugin: pre-function
```
