### ISSUE TITLE
<Feature request> Ability to configure a default KongIngress resource

### ISSUE THREAD

**Issue by bspaans** [Kong/kubernetes-ingress-controller#162]
The documentation mentions two ways to associate an Ingress with a KongIngress resource (deploying with the same name and annotationing), but it would be nice if there was a third option which would allow you to configure a default KongIngress configuration.

**Comment by hbagdi** [comment]
@bspaans 
I see that you're trying to use certbot with Kong.

You could currently use the annotation driven method to apply a single KongIngress resource to your select Ingress specs.
Have you tried using the annotation driven method?

I'm not sure if Ingress spec of Kubernetes specifies what to  do with `Host` header when proxying the request upstream and hence we're relying on the default behavior of Kong.

**Comment by bspaans** [comment]
Thanks for your reply @hbagdi. I am using KongIngress references myself for my own Ingress resources, but cert-manager creates a new Ingress resource to handle the ACME http01 validation, and that Ingress resource doesn't have this annotation (the issue I raised with them asks to make that configurable) and seems to rely on the default behaviour of the nginx controller. For reference here's an example of my Ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: escapekit-user-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    configuration.konghq.com: global-kong-ingress-rules
    certmanager.k8s.io/issuer: letsencrypt-escapekit
spec:
  tls: 
  - hosts:
    - "www.example.com"
    secretName: escapekit-cert
  rules:
  - host: "www.example.com"
    http:
      paths:
      - path: /api/v1/auth
        backend:
          serviceName: user-service
          servicePort: http
```

The Ingress spec does not prescribe what to do with the Host header as far as I'm aware, but I was under the impression that the Kong controller would be a drop-in replacement for the nginx controller, which does seem to default to forwarding the Host header (see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-nginx-upstream-vhost)
