### ISSUE TITLE
Clarify how ExternalName services should behave

### ISSUE THREAD

**Issue by johnharris85** [Kong/kubernetes-ingress-controller#2021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an ExternalName service:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: google
  name: google
  namespace: default
  annotations:
    konghq.com/protocol: "https"
spec:
  externalName: google.com
  ports:
  - name: high
    port: 8080
    protocol: TCP
    targetPort: 50500
  type: ExternalName
```
The ports are completely ignored and the port in the Ingress object referencing this service is used.

### Expected Behavior

Unclear (reason for this issue :D). Ports in an ExternalService in Kubernetes don't make sense as it's basically a CNAME record, so our _current_ behavior makes sense. However, ports _are_ allowed values in ExternalName services. Before 1.1.1 we had some broken issues with ExternalName services, and https://github.com/Kong/kubernetes-ingress-controller/commit/bf755d9ffe2a68c6c8aaf012080ad63422659c97 was added to fix them, however it also (inadvertently?) broke the existing behavior where if ports _were_ set for ExternalName services, we _would_ add those ports as upstreams etc...

So if someone _was_ using ports in their ExternalService prior to 1.1.1, that commit broke that behavior. I guess we just need to decide what we want to do here? Options:

- Keep existing behavior because ports don't make sense for ExternalServices
- Allow for ExternalName ports and create the upstreams as the user has defined (this is providing an 'additive' behavior over K8s)
