### ISSUE TITLE
Client reports ECONNREFUSED after long-running request

### ISSUE THREAD

**Issue by sivins** [Kong/kubernetes-ingress-controller#2042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a service finishes a long HTTP request, Kong logs a successful response, then the client reports ECONNREFUSED.  No error message is received from the server.  I have configured the read timeout of my ingress to be greater than the time taken to process the request

### Expected Behavior

The response should be returned to the client.  If a timeout threshold was being reached, I would expect a Gateway Timeout error.

### Steps To Reproduce

```markdown
1. Initiate long-running request
2. Wait for service to finish processing request
3. Service logs success response
4. Kong logs success response
5. Client reports ECONNREFUSED
```

### Kong Ingress Controller version

```shell
1.1
```

### Kubernetes version

```shell
1.18.14
```

### Anything else?

```
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}
  annotations:
    konghq.com/override: timeout-kong-ingress
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: {{ $.Chart.Name }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
spec:
  rules:
  - http:
      paths:
      - path: /{{ $.Chart.Annotations.route }}
        backend:
          serviceName: {{ $.Chart.Name }}
          servicePort: 80
---
kind: KongIngress
apiVersion: configuration.konghq.com/v1
metadata:
  annotations:
    kubernetes.io/ingress.class: "kong"
  name: timeout-kong-ingress
proxy:
  read_timeout: 1200000
```
![Fiddler-inspectors](https://user-images.githubusercontent.com/8433797/144234537-2df2cd0a-ec03-462d-b3a0-65977699a2a6.png)
![Fiddler-statistics](https://user-images.githubusercontent.com/8433797/144234538-7f47622c-1d78-4476-8590-352a9657d3cc.png)
![kong-success-log](https://user-images.githubusercontent.com/8433797/144234539-575470ea-9b59-47ac-8687-54448e69acb6.PNG)
![my-service-success-log](https://user-images.githubusercontent.com/8433797/144234541-b5e83ca7-94dc-441a-ab17-30ce5fe0bb25.png)
