### ISSUE TITLE
Feature to set secret for each value in KongPlugin/KongClusterPlugin

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2098]
Make it possible to pull only a single value from a plugin setting from a secret, as opposed to the whole configuration being pulled.

Here is an ideal example. Currently not supported.
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: correlation-id-demo
  namespace: echo
  annotations:
    kubernetes.io/ingress.class: kong 
  labels:
config:
  header_name:
    valueFrom:
      secretKeyRef:
        name: kong-config
        key: headername
```

Proposed solutions:
- Create a new api version and make a breaking change to the config/configFrom field
- Add a new field (mutually exclusive with what is there today to specify config) to the existing apiversion of Kong(Cluster)Plugin
