### ISSUE TITLE
request transformer not working on aks

### ISSUE THREAD

**Issue by eamonnmcevoy** [Kong/kubernetes-ingress-controller#210]
### Summary

I am using request-transformer plugin to set a header, it works as expected on my local docker cluster, but on aks the header is missing. Calling the admin api In both clusters, the routes, services, and plugins appear to be configured in the same way.

**Kong Ingress controller version**
2.2.0

**Kong or Kong Enterprise version**
0.14.1-centos

### Kubernetes version
aks:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Docker cluster:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AKS, docker local

### What happened

The following ingress configuration will correctly set the header when I use it in my local docker cluster, but when I use it on aks the header is not set. Calling the admin api on aks I see that the route and plugin are setup in the same way on both clusters.

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-request-transformer
  namespace: my-namespace
config:
  remove:
    headers: 
      - 'x-myheader'
  add:
    headers: 
      - 'x-myheader:my-header-value'
plugin: request-transformer

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: my-namespace
  annotations:
    plugins.konghq.com: my-request-transformer
spec:
  rules:
    - host: "myhost"
      http:
        paths:
          - path: /
            backend:
              serviceName: my-upstream-service
              servicePort: 80
```
### Expected behvaior
Header should be set.

### Steps To Reproduce

1. configure ingress as above
2. plugin working on local docker cluster
3. plugin not working on aks
