### ISSUE TITLE
grpc Ingress with KIC 2.0

### ISSUE THREAD

**Issue by echupriyanov** [Kong/kubernetes-ingress-controller#2116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've deployed current versions of Kong Ingress Controller and Kong Gateway using Helm chart provided by Kong.
Installed versions:
Kubernetes Ingress Gayeway: 2.0.6
Kong Gateway 2.6

Than, I followed the guide (https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/guides/using-ingress-with-grpc) to deploy demo grpc service with Ingress.

But, unfortunately, grpcurl can't reach gRPC application:
```
> grpcurl -d '{"greeting": "Kong Hello world!"}' -insecure demo-grpc.avlab.dev:443 hello.HelloService.SayHello
Error invoking method "hello.HelloService.SayHello": rpc error: code = Internal desc = failed to query for service descriptor "hello.HelloService": stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
>                                                                              
```

### Expected Behavior

gRPC request passed to the Application and gRPC response received

### Steps To Reproduce

My manifests are almost verbatim from the guide:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: grpcbin
  labels:
    app: grpcbin
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/protocols: grpcs
spec:
  ports:
  - name: grpc
    port: 9001
    targetPort: 9001
  selector:
    app: grpcbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcbin
  template:
    metadata:
      labels:
        app: grpcbin
    spec:
      containers:
      - image: moul/grpcbin
        name: grpcbin
        ports:
        - containerPort: 9001
```

And Ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/protocols: "grpc,grpcs"
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  rules:
  - host: demo-grpc.avlab.dev
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: grpcbin
            port:
              number: 9001
  tls:
    - hosts:
      - "demo-grpc.avlab.dev"
      secretName: demo-grpc-tls
```

### Kong Ingress Controller version

v2.0.6

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+rke2r1", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-16T16:16:29Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

### Anything else?

Deployment of manifests above produces following objects in the proxy:
Service:
```
{
  "connect_timeout": 60000,
  "tls_verify_depth": null,
  "tags": [
    "managed-by-ingress-controller"
  ],
  "ca_certificates": null,
  "path": "/",
  "retries": 5,
  "protocol": "http",
  "created_at": 1639999073,
  "updated_at": 1639999073,
  "port": 80,
  "write_timeout": 60000,
  "id": "a5f1b9b6-9412-4967-aa22-246d94eaa840",
  "read_timeout": 60000,
  "name": "demo-backend.grpcbin.pnum-9001",
  "client_certificate": null,
  "tls_verify": null,
  "host": "grpcbin.demo-backend.9001.svc"
}
```
Upstream:
```
{
  "hash_on": "none",
  "algorithm": "round-robin",
  "hash_on_header": null,
  "hash_on_cookie": null,
  "name": "grpcbin.demo-backend.9001.svc",
  "healthchecks": {
    "threshold": 0,
    "active": {
      "unhealthy": {
        "interval": 0,
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "http_failures": 0,
        "tcp_failures": 0,
        "timeouts": 0
      },
      "timeout": 1,
      "healthy": {
        "interval": 0,
        "successes": 0,
        "http_statuses": [
          200,
          302
        ]
      },
      "https_verify_certificate": true,
      "concurrency": 10,
      "type": "http",
      "http_path": "/",
      "https_sni": null
    },
    "passive": {
      "unhealthy": {
        "http_failures": 0,
        "http_statuses": [
          429,
          500,
          503
        ],
        "tcp_failures": 0,
        "timeouts": 0
      },
      "type": "http",
      "healthy": {
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          205,
          206,
          207,
          208,
          226,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ],
        "successes": 0
      }
    }
  },
  "created_at": 1640001320,
  "tags": [
    "managed-by-ingress-controller"
  ],
  "hash_on_cookie_path": "/",
  "host_header": null,
  "hash_fallback_header": null,
  "id": "8323ea90-b2b3-40e7-be8d-915fd870d614",
  "client_certificate": null,
  "hash_fallback": "none",
  "slots": 10000
}
```
Targets:
```
{
  "data": [
    {
      "tags": [
        "managed-by-ingress-controller"
      ],
      "id": "9b4b52cc-99f2-4bda-9fc8-1e8c0ca2c829",
      "target": "10.20.247.66:9001",
      "upstream": {
        "id": "8323ea90-b2b3-40e7-be8d-915fd870d614"
      },
      "created_at": 1639999073.091,
      "weight": 100
    }
  ],
  "next": null
}
```
Routes:
```
{
  "data": [
    {
      "protocols": [
        "grpc",
        "grpcs"
      ],
      "preserve_host": true,
      "hosts": [
        "demo-grpc.avlab.dev"
      ],
      "paths": [
        "/"
      ],
      "methods": null,
      "sources": null,
      "destinations": null,
      "tags": [
        "managed-by-ingress-controller"
      ],
      "strip_path": false,
      "request_buffering": true,
      "service": {
        "id": "a5f1b9b6-9412-4967-aa22-246d94eaa840"
      },
      "name": "demo-backend.demo.00",
      "updated_at": 1640001320,
      "snis": null,
      "https_redirect_status_code": 426,
      "headers": null,
      "id": "95429a53-b3f3-434c-b2e8-6e9980a405e9",
      "created_at": 1640001320,
      "response_buffering": true,
      "path_handling": "v0",
      "regex_priority": 100
    }
  ],
  "next": null
}
```

I wonder why the service is targeting upstream on port 80 (plain http) with protocol `http`, when Ingress explicitly states its grpc/grpcs

At the same time, If I manually create service with protocol grpc, pointing to grpcbin Kubernetes Service, everything works fine.

Service:
```
{
  "connect_timeout": 60000,
  "tls_verify_depth": null,
  "tags": [],
  "ca_certificates": null,
  "path": null,
  "retries": 5,
  "protocol": "grpcs",
  "created_at": 1640005789,
  "updated_at": 1640005789,
  "port": 9001,
  "write_timeout": 60000,
  "id": "a8eb5c63-7f38-4a4f-8a4a-e51ee1223d83",
  "read_timeout": 60000,
  "name": "qq",
  "client_certificate": null,
  "tls_verify": null,
  "host": "grpcbin.demo-backend.svc"
}
```
Routes:
```
{
  "data": [
    {
      "protocols": [
        "grpc",
        "grpcs"
      ],
      "preserve_host": false,
      "hosts": [
        "demo-grpc.avlab.dev"
      ],
      "paths": [
        "/"
      ],
      "methods": null,
      "sources": null,
      "destinations": null,
      "tags": null,
      "strip_path": false,
      "request_buffering": true,
      "service": {
        "id": "a8eb5c63-7f38-4a4f-8a4a-e51ee1223d83"
      },
      "name": "grpcbin",
      "updated_at": 1640005833,
      "snis": null,
      "https_redirect_status_code": 426,
      "headers": null,
      "id": "1f5b0d91-a8b9-40e8-a45c-eb4f239fdad1",
      "created_at": 1640005833,
      "response_buffering": true,
      "path_handling": "v1",
      "regex_priority": 0
    }
  ],
  "next": null
}
```

Result:
```
> grpcurl -v -d '{"greeting": "Kong Hello world!"}' -insecure demo-grpc.avlab.dev:443 hello.HelloService.SayHello

Resolved method descriptor:
rpc SayHello ( .hello.HelloRequest ) returns ( .hello.HelloResponse );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc
date: Mon, 20 Dec 2021 13:10:49 GMT
server: openresty
trailer: Grpc-Status
trailer: Grpc-Message
trailer: Grpc-Status-Details-Bin
via: kong/2.6.0
x-kong-proxy-latency: 1
x-kong-upstream-latency: 1

Response contents:
{
  "reply": "hello Kong Hello world!"
}

Response trailers received:
(empty)
Sent 1 request and received 1 response
>
```
