### ISSUE TITLE
Kong prometheus is not associating to the consumer

### ISSUE THREAD

**Issue by dcherniv** [Kong/kubernetes-ingress-controller#216]
### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.2.2

**Kong or Kong Enterprise version**

CE
### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.9-gke.5", GitCommit:"d776b4deeb3655fa4b8f4e8e7e4651d00c5f4a98", GitTreeState:"clean", BuildDate:"2018-11-08T20:33:00Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

### What happened
prometheus plugin is not associated to a consumer with the following plugin spec:
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
config:
  hide_credentials: true
disabled: false
consumerRef: lfs-others
metadata:
  name: lfs-others-prometheus
plugin: prometheus

apiVersion: v1
items:
- apiVersion: configuration.konghq.com/v1
  kind: KongConsumer
  metadata:
    name: lfs-others
  username: lfs-others
```
### Expected behvaior
prometheus plugin to be associated with a consumer and be listed under
```
/ # curl http://localhost:8001/consumers/bf9fd1ac-0641-11e9-b5a5-42010a8e0044/plugins
{"total":0,"data":[]}
/ # 
```
### Steps To Reproduce
Create the above mentioned specs.

**Comment by dcherniv** [comment]
Never mind this issue.
It was my own fault.
```
config:
  hide_credentials: true
```
is not a valid config for prometheus plugin and kong was not silently ignoring it, instead the plugin just failed to instantiate.
Another thing is, even though consumerRef is specified in the plugin, i could never get it to work properly. Though konga has no problems associating prometheus to a consumer i couldn't replicate this via kubernetes spec.
In the end, i ended up enabling the plugin at the ingress level.

**Comment by dcherniv** [comment]
Still there's an issue associating KongPlugins to KongConsumers. It doesn't appear that there's a way to do that.
Would be nice to have as a feature request.

**Comment by jmvizcainoio** [comment]
I have the same problem: 

**Kong**
```
kong-ingress-controller:0.3.0
image: kong:1.0.2
```

**Kubernetes**

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Kongplugin**

```
apiVersion: configuration.konghq.com/v1
consumerRef: username
kind: KongPlugin
metadata:
  generation: 1
  labels:
    app: kong-crd
    chart: kong-crd-0.0.1
    heritage: Tiller
    release: kong-crd
  name: prometheus
  namespace: default
plugin: prometheus
````

KongCredential

```
apiVersion: configuration.konghq.com/v1
config:
  key: XXXXXXXXXXXXXXXXXXXXXXXXX
consumerRef: username
kind: KongCredential
metadata:
  creationTimestamp: "2019-02-20T15:27:06Z"
  generation: 1
  labels:
    app: kong-crd
    chart: kong-crd-0.0.1
    heritage: Tiller
    release: kong-crd
  name: username
  namespace: default
type: key-auth

```

KongConsumer

```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  creationTimestamp: "2019-02-20T15:27:06Z"
  generation: 1
  labels:
    app: kong-crd
    chart: kong-crd-0.0.1
    heritage: Tiller
    release: kong-crd
  name: username
  namespace: default
username: username
````

On konga i can't see any plugin activated on this consumer

In older versions of kong seems to work. Any change in the config file to fix ?
