### ISSUE TITLE
Custom resources KongPlugin is incompatible with multiple Kong Ingress on same cluster

### ISSUE THREAD

**Issue by nmacherey** [Kong/kubernetes-ingress-controller#218]
### Summary

When deploying multiple KongIngresses on the same cluster, the KongPlugin with "global" label is not specific to a given KongIngress and creates conflicts in both databases.

**UPDATE**: The  problem is the same for KongConsumer. Which are also created in double.

**Kong Ingress controller version**
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.2.2

**Kong or Kong Enterprise version**
Kong 0.14.1

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-27T01:15:02Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: AWS EC2 with K8S-debian-strech-v1.11
- **OS** (e.g. from /etc/os-release): debian stretch
- **Kernel** (e.g. `uname -a`): N/A
- **Install tools**: N/A
- **Others**: N/A

### What happened

We are deploying multiple kong, using Kong ingresses on the same cluster for different applications. Therefore we are changing the `--ingress-class=kong-app1` and `--ingress-class=kong-app2`.  

When deploying 2 ingresses for 2 application and trying to apply the following `KongPlugin`:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-oauth2
  namespace: app1
  annotations:
    kubernetes.io/ingress.class: kong-app1
  labels:
    global: "true"
config:
  enable_password_grant: "true"
  enable_authorization_code: "true"
  enable_implicit_grant: "true"
  global_credentials: "true"
  scopes: email
plugin: oauth2
```

The plugin oauth2 become active in both kong applications.

### Expected behvaior

The plugin should respect the annotations:

```yaml
annotations:
    kubernetes.io/ingress.class: kong-app1
```

And be only available in the appropriate controller.

### Steps To Reproduce

**NOTE** that configuration files has been adapted from helm chart stable repository.

1. Create a Kong ingress in app1 namespace
```yaml
# This is a simple template that allows to deploy kong ingress (and kong) into a given
# namespace replace "app1" by your namespace.
# Deploys the Postgres SQL instance for Kong. You can skip this and change the corresponding variables
# in the kong deployment

---

apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: app1
  labels:
    app: app1
    component: kong
spec:
  ports:
  - name: kong-admin
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: app1
    component: kong

---

apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: app1
  labels:
    app: app1
    component: kong
spec:
  ports:
  - name: kong-proxy-https
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: kong-proxy-http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: app1
    component: kong

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kong-controller
  namespace: app1
  labels:
    app: app1
    component: kong-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      component: kong-controller
  template:
    metadata:
      labels:
        app: app1
        component: kong-controller
    spec:
      serviceAccountName: kong-sa
      initContainers:
      - name: wait-for-db
        image: "kong:0.14.1"
        env:
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "until kong start; do echo 'waiting for db'; sleep 1; done; kong stop" ]
      containers:
      - name: admin-api
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_PROXY_LISTEN
          value: 'off'
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8444
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        ports:
        - name: admin
          containerPort: 8444
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          {}

      - name: ingress-controller
        args:
        - /kong-ingress-controller
        # the kong URL points to the kong admin api server
        - --kong-url=http://localhost:8444
        # the default service is the kong proxy service
        - --default-backend-service=app1/kong-proxy
        # Service from were we extract the IP address/es to use in Ingress status
        - --publish-service=app1/kong-proxy
        # Change this to have a different annotation this is required if you want to have
        # Different kong ingresses in your cluster in different namespaces
        - --ingress-class=kong-app1
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.2.2"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          null

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kong
  namespace: app1
  labels:
    app: app1
    component: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
      component: kong
  template:
    metadata:
      labels:
        app: app1
        component: kong
    spec:
      initContainers:
      - name: wait-for-db
        image: "kong:0.14.1"
        env:
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        - name: KONG_DATABASE
          value: "postgres"
        command: [ "/bin/sh", "-c", "until kong start; do echo 'waiting for db'; sleep 1; done; kong stop" ]
      containers:
      - name: kong
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8444
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        - name: KONG_NGINX_DAEMON
          value: "off"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        ports:
        - name: admin
          containerPort: 8444
          protocol: TCP
        - name: proxy
          containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5

        resources:
          {}

      tolerations:
        []


---
# Source: kong/templates/migrations-on-upgrade.yaml

# Why is this Job duplicated and not using only helm hooks?
# See: https://github.com/helm/charts/pull/7362
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-upgrade-migrations
  namespace: app1
  labels:
    app: app1
    component: migrations
spec:
  template:
    metadata:
      name: kong-upgrade-migrations
      labels:
        app: app1
        component: migrations
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        env:
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done" ]
      containers:
      - name: kong-upgrade-migrations
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_NGINX_DAEMON
          value: "off"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: OnFailure

---
# Source: kong/templates/migrations.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: app1
  labels:
    app: app1
    component: kong
spec:
  template:
    metadata:
      name: kong-migrations
      labels:
        app: app1
        component: kong
    spec:
      initContainers:
      - name: wait-for-postgres
        image: "busybox:latest"
        env:
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done" ]
      containers:
      - name: kong-migrations
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_NGINX_DAEMON
          value: "off"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: OnFailure

```

2. Create an app2 ingress on second namespace

```yaml
# This is a simple template that allows to deploy kong ingress (and kong) into a given
# namespace replace "app2" by your namespace.
# Deploys the Postgres SQL instance for Kong. You can skip this and change the corresponding variables
# in the kong deployment

---

apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: app2
  labels:
    app: app2
    component: kong
spec:
  ports:
  - name: kong-admin
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: app2
    component: kong

---

apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: app2
  labels:
    app: app2
    component: kong
spec:
  ports:
  - name: kong-proxy-https
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: kong-proxy-http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: app2
    component: kong

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kong-controller
  namespace: app2
  labels:
    app: app2
    component: kong-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      component: kong-controller
  template:
    metadata:
      labels:
        app: app2
        component: kong-controller
    spec:
      serviceAccountName: kong-sa
      initContainers:
      - name: wait-for-db
        image: "kong:0.14.1"
        env:
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "until kong start; do echo 'waiting for db'; sleep 1; done; kong stop" ]
      containers:
      - name: admin-api
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_PROXY_LISTEN
          value: 'off'
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8444
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        ports:
        - name: admin
          containerPort: 8444
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          {}

      - name: ingress-controller
        args:
        - /kong-ingress-controller
        # the kong URL points to the kong admin api server
        - --kong-url=http://localhost:8444
        # the default service is the kong proxy service
        - --default-backend-service=app2/kong-proxy
        # Service from were we extract the IP address/es to use in Ingress status
        - --publish-service=app2/kong-proxy
        # Change this to have a different annotation this is required if you want to have
        # Different kong ingresses in your cluster in different namespaces
        - --ingress-class=kong-app2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.2.2"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          null

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kong
  namespace: app2
  labels:
    app: app2
    component: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      component: kong
  template:
    metadata:
      labels:
        app: app2
        component: kong
    spec:
      initContainers:
      - name: wait-for-db
        image: "kong:0.14.1"
        env:
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        - name: KONG_DATABASE
          value: "postgres"
        command: [ "/bin/sh", "-c", "until kong start; do echo 'waiting for db'; sleep 1; done; kong stop" ]
      containers:
      - name: kong
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8444
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        - name: KONG_NGINX_DAEMON
          value: "off"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        ports:
        - name: admin
          containerPort: 8444
          protocol: TCP
        - name: proxy
          containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: admin
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5

        resources:
          {}

      tolerations:
        []


---
# Source: kong/templates/migrations-on-upgrade.yaml

# Why is this Job duplicated and not using only helm hooks?
# See: https://github.com/helm/charts/pull/7362
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-upgrade-migrations
  namespace: app2
  labels:
    app: app2
    component: migrations
spec:
  template:
    metadata:
      name: kong-upgrade-migrations
      labels:
        app: app2
        component: migrations
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        env:
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done" ]
      containers:
      - name: kong-upgrade-migrations
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_NGINX_DAEMON
          value: "off"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: OnFailure

---
# Source: kong/templates/migrations.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  namespace: app2
  labels:
    app: app2
    component: kong
spec:
  template:
    metadata:
      name: kong-migrations
      labels:
        app: app2
        component: kong
    spec:
      initContainers:
      - name: wait-for-postgres
        image: "busybox:latest"
        env:
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done" ]
      containers:
      - name: kong-migrations
        image: "kong:0.14.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: KONG_NGINX_DAEMON
          value: "off"
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: kong-postgresql
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kong-postgresql
              key: postgres-password
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: OnFailure
```
3. Attach the oauth2 plugin globally on first ingress

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-oauth2
  namespace: app1
  annotations:
    kubernetes.io/ingress.class: kong-app1
config:
  enable_password_grant: "true"
  enable_authorization_code: "true"
  enable_implicit_grant: "true"
  global_credentials: "true"
  scopes: email
plugin: oauth2
```

4. The plugin becomes active in the second ingress app2
In addition if we now add the KongPlugin on the second namespace, it removes it from the database.
