### ISSUE TITLE
Routes with the same path but different methods don't work well

### ISSUE THREAD

**Issue by pmbanugo** [Kong/kubernetes-ingress-controller#2225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I apply the following resources, only the POST request works. The GET request returns Bad Request

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: hello-service-host-rewrite
  # The plugin must be created in the same namespace as the ingress.
  namespace: kong
plugin: request-transformer
config:
  add:
    headers:
      - 'Host: hello.default.svc.cluster.local'
  replace:
    headers:
      - 'Host: hello.default.svc.cluster.local'
---
# Create a Kong request transformer plugin to rewrite the original host header
# to the host header of Login service in order to redirect requests to Login
# service.
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: hi-service-host-rewrite
  # The plugin must be created in the same namespace as the ingress.
  namespace: kong
plugin: request-transformer
config:
  add:
    headers:
      - 'Host: hi.default.svc.cluster.local'
  replace:
    headers:
      - 'Host: hi.default.svc.cluster.local'
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: hello-service-host-rewrite
route:
  methods:
    - GET
  strip_path: true
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: hi-service-host-rewrite
route:
  methods:
    - POST
  strip_path: true
---
# Create an ingress that forwards an incoming request at example.com/login to
# "login-service.default.example.com" by updating the "Host" header to
# "login-service.default.example.com" and stripping the request path. This
# modified request is then forwarded to the Knative ingress (Kong) and routed
# to the service as usual.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hi-hello-post
  # The ingress must be created in the same namespace as the kong-proxy service.
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: hi-service-host-rewrite
    konghq.com/plugins: hi-service-host-rewrite
spec:
  rules:
    - host: hi-hello.localhost
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: kong-proxy
                port:
                  number: 80
---
# Create an ingress that forwards an incoming request at example.com/search to
# "search-service.default.example.com" by updating the "Host" header to
# "search-service.default.example.com" and stripping the request path. This
# modified request is then forwarded to the Knative ingress (Kong) and routed
# to the service as usual.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hi-hello-get
  # The ingress must be created in the same namespace as the kong-proxy service.
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: hello-service-host-rewrite
    konghq.com/plugins: hello-service-host-rewrite
spec:
  rules:
    - host: hi-hello.localhost
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: kong-proxy
                port:
                  number: 80
---

```

### Expected Behavior

GET and POST request should reach the respective service. Only the POST request works, while the GET returns Bad Request always

### Steps To Reproduce

```markdown
1. Create Kubernetes services exposed in port 80 (I'm using Knative Service)
2. Verify the services work with their individual IP/host
3. Apply the resources above
4. Test URL with POST and GET request
```

### Kong Ingress Controller version

```shell
v2.1
```

### Kubernetes version

```shell
1.21
```
