### ISSUE TITLE
2.1.1 Constant sync loop diffs

### ISSUE THREAD

**Issue by scirner22** [Kong/kubernetes-ingress-controller#2248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to kong 2.7.0 and kic 2.1.1 the kic update loop constantly detects changes to resources so it updates them on every loop. Previously, when no configuration would actually change it would log that it was in sync and not update anything that already exists.

### Expected Behavior

Log that there was no changes detected and not update existing kong resources.

### Steps To Reproduce

```markdown
Below are example ingress and service resources.
```

### Kong Ingress Controller version

```shell
2.1.1 with kong 2.7.0
```

### Kubernetes version

```shell
1.20
```

### Anything else?

Example of what currently happens on every sync loop.

```
updating <name>  {
   "algorithm": "round-robin",
   "hash_fallback": "none",
   "hash_on": "none",
   "hash_on_cookie_path": "/",
   "healthchecks": {
     "active": {
       "concurrency": 10,
       "healthy": {
         "http_statuses": [
           200,
           302
         ],
         "interval": 0,
         "successes": 0
       },
       "http_path": "/",
-      "https_verify_certificate": true,
       "timeout": 1,
       "type": "http",
       "unhealthy": {
         "http_failures": 0,
         "http_statuses": [
           429,
           404,
           500,
           501,
           502,
           503,
           504,
           505
         ],
         "interval": 0,
         "tcp_failures": 0,
         "timeouts": 0
       }
     },
     "passive": {
       "healthy": {
         "http_statuses": [
           200,
           201,
           202,
           203,
           204,
           205,
           206,
           207,
           208,
           226,
           300,
           301,
           302,
           303,
           304,
           305,
           306,
           307,
           308
         ],
         "successes": 0
       },
-      "type": "http",
       "unhealthy": {
         "http_failures": 0,
         "http_statuses": [
           429,
           500,
           503
         ],
         "tcp_failures": 0,
         "timeouts": 0
       }
     },
-    "threshold": 0
   },
   "host_header": "<name>",
   "id": "50e75021-c078-440f-ad72-0988e8b09535",
   "name": "<name>",
   "slots": 10000,
   "tags": [
     "managed-by-ingress-controller"
   ]
 }
...

creating certificate 9a9e1d9a-7eb1-43e8-bac8-de0f433eed33
updating <name>  {
   "certificate": {
-    "id": "35f22683-9119-47f3-a507-a60f282e1a30"
+    "id": "9a9e1d9a-7eb1-43e8-bac8-de0f433eed33"
   },
   "id": "8d35f194-2f80-4ddb-8b4a-3b43307e077d",
   "name": "<name>",
   "tags": [
     "managed-by-ingress-controller"
   ]
 }
...

{"level":"info","msg":"successfully synced configuration to kong.","subsystem":"proxy-cache-resolver","time":"2022-02-04T16:27:05Z"}
```

Example service

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/path: /
    konghq.com/protocol: http
    kubernetes.io/ingress.class: kong
  labels:
    app: docs-core-bank
    app.kubernetes.io/instance: "4074783313566591"
    fd: docs-core-bank
  name: docs-core-bank-kong
  namespace: core-banking
spec:
  clusterIP: <ip>
  clusterIPs:
  - <ip>
  ports:
  - name: http-docs-core-bank-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: docs-core-bank
  sessionAffinity: None
  type: ClusterIP
```

Example Ingress

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: frontend-error-handling
    konghq.com/preserve-host: "true"
    konghq.com/protocols: http, https
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
  generation: 12
  labels:
    app.kubernetes.io/instance: "4074783313566591"
    fd: docs-core-bank
  name: docs-core-bank-kong
  namespace: core-banking
spec:
  rules:
  - host: <host>
    http:
      paths:
      - backend:
          service:
            name: docs-core-bank-kong
            port:
              number: 80
        path: /banking
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - <host>
    secretName: <secret>
status:
  loadBalancer:
    ingress:
    - ip: <ip>
```
