### ISSUE TITLE
how to configure `kong.conf` for ingress ingress controller.

### ISSUE THREAD

**Issue by nautiyaldeepak** [Kong/kubernetes-ingress-controller#225]
I want to setup ssl certificate for my kong-ingress-controller.
Where can I get the kong.conf file for the ingress-controller if my ingress controller is runnning inside a cluster.

**Comment by dcherniv** [comment]
@nautiyaldeepak is the certificate intended to be used by apis served by kong or by kong admin api itself?
if the former then ssl is configured using secrets in kubernetes.
e.g.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: test-ing
  namespace: dev
spec:
  rules:
  - host: api.test.net
    http:
      paths:
      - backend:
          serviceName: test-service
          servicePort: 80
        path: /test
  tls:
  - hosts:
    - api.test.net
    secretName: api-tlscert
```
Where api-tlscert is created as follows manually.
```
kubectl create secret tls api-tlscert --key /tmp/tls.key --cert /tmp/tls.crt
```
Not entirely sure whether kong support cert-manager yet, but it is also possible to automate certificate provisioning https://github.com/jetstack/cert-manager
