### ISSUE TITLE
Plugin on Ingress or Service isn't created on /plugins

### ISSUE THREAD

**Issue by jerfer** [Kong/kubernetes-ingress-controller#227]
### Summary

Applying a KongPlugin to an Ingress or Service doesn't create the plugin in Kong.

**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
1.0.1 (Alpine Docker image)

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.15", GitCommit:"c2bd642c70b3629223ea3b7db566a267a1e2d0df", GitTreeState:"clean", BuildDate:"2018-07-11T17:52:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AWS/Kops
- **OS** (e.g. from /etc/os-release): kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-08-17
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Kops
- **Others**:

### What happened
Installed Kong using https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml with slight changes to use an RDS Postgres instance and Kong 1.0.1 instead of Kong 1.0.0.

Created resources using the following:
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: correlation-id
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
config:
  header_name: "A-Request-ID"
  echo_downstream: "true"
plugin: correlation-id

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoservice
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoservice
  template:
    metadata:
      labels:
        app: echoservice
    spec:
      containers:
        - name: echoservice
          image: gcr.io/google_containers/echoserver:1.8
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  name: echoservice
  namespace: kong
  labels:
    app: echoservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: echoservice

---

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: echoservice
  namespace: kong
proxy:
  path: /
route:
  protocols:
    - http
  strip_path: false
  preserve_host: true

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoservice
  namespace:  kong
  annotations:
    kubernetes.io/ingress.class: "kong"
    configuration.konghq.com: echoservice
    plugins.konghq.com: correlation-id
spec:
  rules:
    - host: kongtest.somewhere.com
      http:
        paths:
          - path: "/"
            backend:
              serviceName: echoservice
              servicePort: http

---
```

### Expected behaviour
Expected a "A-Request-ID" header to be added and passed to the service. Instead, this was the result:
```
$ curl kongtest.somewhere.com

Hostname: echoservice-79d4596986-8n7cq

Pod Information:
	node name:	ip-www.xxx.yyy.zzz.ec2.internal
	pod name:	echoservice-79d4596986-8n7cq
	pod namespace:	kong
	pod IP:	www.xxx.yyy.zzz

Server values:
	server_version=nginx: 1.13.3 - lua: 10008

Request Information:
	client_address=www.xxx.yyy.zzz
	method=GET
	real path=/
	query=
	request_version=1.1
	request_uri=http://kongtest.somewhere.com:8080/

Request Headers:
	accept=*/*
	connection=keep-alive
	host=kongtest.somewhere.com
	user-agent=curl/7.54.0
	x-forwarded-for=www.xxx.yyy.zzz
	x-forwarded-host=kongtest.somewhere.com
	x-forwarded-port=8000
	x-forwarded-proto=http
	x-real-ip=www.xxx.yyy.zzz

Request Body:
	-no body in request-
```

The KongPlugin is registered in Kubernetes:
```
$ kubectl describe -n kong kongplugins
Name:         correlation-id
Namespace:    kong
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"configuration.konghq.com/v1","config":{"echo_downstream":"true","header_name":"A-Request-ID"},"kind":"KongPlugin","metadata":{"annot...
              kubernetes.io/ingress.class=kong
API Version:  configuration.konghq.com/v1
Config:
  Echo _ Downstream:  true
  Header _ Name:      A-Request-ID
Kind:                 KongPlugin
Metadata:
  Cluster Name:
  Creation Timestamp:             2019-01-24T03:27:03Z
  Deletion Grace Period Seconds:  <nil>
  Deletion Timestamp:             <nil>
  Resource Version:               104758887
  Self Link:                      /apis/configuration.konghq.com/v1/namespaces/kong/kongplugins/correlation-id
  UID:                            eab7aae1-1f87-11e9-9d5d-0e98a8f8c5f4
Plugin:                           correlation-id
Events:                           <none>
```

The route is registered in Kong (from the ingress-controller pod):
```
$ curl localhost:8001/routes
{
   "next":null,
   "data":[
      {
         "created_at":1548300439,
         "methods":null,
         "id":"fbbf7a65-7ea3-466d-810c-5e1e4fcc1ccb",
         "service":{
            "id":"0dca173c-2aa2-4a69-a65c-dd865deecf98"
         },
         "name":null,
         "hosts":[
            "kongtest.somewhere.com"
         ],
         "updated_at":1548300439,
         "preserve_host":true,
         "regex_priority":0,
         "paths":[
            "\/"
         ],
         "sources":null,
         "destinations":null,
         "snis":null,
         "protocols":[
            "http"
         ],
         "strip_path":false
      }
   ]
}
```

But the plugin is never enabled or associated with the route (again, from the ingress-controller pod):
```
$ curl localhost:8001/plugins
{
   "next":null,
   "data":[

   ]
}
```
### Steps To Reproduce

1. Install the Kong kubernetes-ingress-controller
2. Define a new KongPlugin as above
3. Define a new deployment, service, ingress, and kongingress as above
