### ISSUE TITLE
Prometheus plugin is not enabled on consumers

### ISSUE THREAD

**Issue by jmvizcainoio** [Kong/kubernetes-ingress-controller#238]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Activate prometheus plugin to a consumer

**Kong Ingress controller version**

`````
kong-ingress-controller:0.3.0
`````

**Kong or Kong Enterprise version**

`````
kong:1.0.2
`````

### Kubernetes version

`````
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
`````

### Environment

- k8s: kops aws 

### What happened

When i activate a prometheus plugin to a consumer, doesn't activate

Konga show me that any plugin is activated in the consumer

![image](https://user-images.githubusercontent.com/44993815/53169686-4188b180-35de-11e9-84a9-f6986bf44879.png)

### Steps To Reproduce

**Kongplugin**

```
apiVersion: configuration.konghq.com/v1
consumerRef: username
kind: KongPlugin
metadata:
  generation: 1
  labels:
    app: kong-crd
    chart: kong-crd-0.0.1
    heritage: Tiller
    release: kong-crd
  name: prometheus
  namespace: default
plugin: prometheus
````

**KongCredential**

```
apiVersion: configuration.konghq.com/v1
config:
  key: XXXXXXXXXXXXXXXXXXXXXXXXX
consumerRef: username
kind: KongCredential
metadata:
  creationTimestamp: "2019-02-20T15:27:06Z"
  generation: 1
  labels:
    app: kong-crd
    chart: kong-crd-0.0.1
    heritage: Tiller
    release: kong-crd
  name: username
  namespace: default
type: key-auth

```

**KongConsumer**

```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  creationTimestamp: "2019-02-20T15:27:06Z"
  generation: 1
  labels:
    app: kong-crd
    chart: kong-crd-0.0.1
    heritage: Tiller
    release: kong-crd
  name: username
  namespace: default
username: username
````
