### ISSUE TITLE
KIC looping forever on Context Deadline exceeded

### ISSUE THREAD

**Issue by aroundthecode** [Kong/kubernetes-ingress-controller#2440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've a kong 2.7.1 + KIC 2.2.1 setup con GKE
I've ~50 namespace with 2 ingress resources each resulting in ~30 rules per namespaces so a total amount of ~1500 rules.
Some services aslo has plugins configured.

Once deployed KIC, starts to populate kong, but it periopdicaly fails on error such:
`{"error":"2 errors occurred: failed to sync all entities: context deadline exceeded while processing event: {Update} upstream *******.8080.svc failed: making HTTP request: Put "http://kong-kong-admin.kong-system:8001/upstreams/1e7b3b64-fdbf-4f51-9c9e-2cb43172d92b": context deadline exceeded
", "level":"error", "msg":"could not update kong admin", "subsystem":"proxy-cache-resolver"}`

on kong admin side matching error is:
`[error] 1097#0: *54395 [lua] events.lua:364: post_local(): worker-events: dropping event; waiting for event data timed out`

I've split my deployment in 3 standalone kong proxy/admin pods + 3 KIC pods using the kong services to spread load across the 3 admin nodes.

I've also tried to scale up kong pods up to 5 and reduce KIC concurrency to 1 but still error persists (the number in error log is  usually concurrency number+1 )

One KIC enters such error it continues looping on different services names flooding admin with requests.

Kong pods have no resources limit and each kong pod is allocated on a different VM, both CPU and RAM are NOT saturated.

Is there any other configuration tuning I can apply to avoid such loop?

### Expected Behavior

KIC should be able to send all configuration to kong and stop looping

### Anything else?

both kong and KIC are deployed via helm with such setup (concurrency has been lowered up to 1):

```
ingressController:
  installCRDs: false
  enabled: true
  env:
    kong_admin_tls_skip_verify: true
    kong_admin_url: "http://kong-kong-admin.kong-system:8001"
    publish_service: kong-system/kong-kong-proxy
    kong_admin_concurrency: 3
    log_format: json
    log_level: warn
```

and such custom setting in nginx template:
```
proxy_buffer_size   128k;
    proxy_buffers   4 256k;
    proxy_busy_buffers_size 256k;
```

such setups also suffers from #2422, I'm waiting for next release to upgrade to 2.8
