### ISSUE TITLE
Admission webhook fails "unique key constraint" validation for ACL group secret bound to KongConsumer

### ISSUE THREAD

**Issue by davidmontoyago** [Kong/kubernetes-ingress-controller#2480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given a **key-auth** KongPlugin and an **acl** KongPlugin configured on an Ingress, when creating a KongConsumer with the `credentials` field set to an ACL secret (already previously created), the admission webhook fails a "unique key constraint" validation that is irrelevant to the ACL secret.

Client error is:
```
failed to call webhook: an error on the server ("unique key constraint violated for key") has prevented the request from succeeding
```

Error on the admission webhook is:
```
level=error msg="failed to run validation: unique key constraint violated for key" component=admission-server
```

### Expected Behavior

- Admission webhook allows creating a KongConsumer with the `credentials` field pointing to a previously created ACL group secret.

### Steps To Reproduce

1. Create a Secret for the ACL group:

```markdown
cat <<EOF | k apply -f -
apiVersion: v1
stringData:
  group: example-app
  kongCredType: acl
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: "kong"
  name: test-acl-example-app
  namespace: my-consumers
EOF
```

2. Create a KongConsumer bound to the ACL secret:

```
cat <<EOF | k apply -f -
apiVersion: configuration.konghq.com/v1
credentials:
- test-acl-example-app
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    app.kubernetes.io/managed-by: "kong"
  name: test-consumer-example-app
  namespace: my-consumers
username: test-consumer-example-app-99
custom_id: test-consumer-example-app-99
EOF
```

### Kong Ingress Controller version

```shell
Controller: kong-ingress-controller:2.2
Proxy: kong-gateway:2.7.2.0-alpine
```

### Kubernetes version

```shell
1.22.8
```

### Anything else?

We run our Gateway in Db-less mode and provision Kong resources programmatically using the Go Kubernetes client.
