### ISSUE TITLE
Create both Ingress and Kong TcpIngress with same service:port cause sync rule failure.

### ISSUE THREAD

**Issue by gung-rgb** [Kong/kubernetes-ingress-controller#2519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ingress controller sync ingress failed, with msg: "failed to sync: insert upstream into state: inserting upstream  example-svc.default.8080.svc: entity already exists"

### Expected Behavior

ingress sync success OR  webhook validate this case and resource create failure.

### Steps To Reproduce

```yaml
step 1:  
create an KongTcpIngress.

spec:
  rules:
    - backend:
        serviceName:  example-svc
        servicePort: 8080
      port: 8080
```

step 2:
create an ingress relating to service  `example-svc:8080`.
```yaml
spec:
  rules:
    - host:  example.com
      http:
        paths:
          - backend:
              service:
                name: example-svc
                port:
                  number: 8080
```

### Kong Ingress Controller version

```shell
v1.3.1
```

### Kubernetes version

```shell
1.20
```

**Comment by randmonkey** [comment]
What was the version of your kong gateway, or, what was the image used for your `proxy`? 
I tried to reproduce the bug with this all-in-one manifest in v1.3.1: https://github.com/Kong/kubernetes-ingress-controller/blob/1.3.1/deploy/single/all-in-one-dbless.yaml, but I did not find the error log, and the ingress can be normally accessed by `curl -H"Host:example.com" http://$PROXY_IP` using your example ingress spec. 
My environment:
- k8s version: `v1.20.13` installed by `snap install microk8s --classic --channel=1.20/stable`
- KIC version: `v1.3.1`, image `kong/kubernetes-ingress-controller:1.3`
- kong version: `v2.4.1`,image `kong:2.4`

**Comment by gung-rgb** [comment]
> Could you please provide some more information of your environment?
> 
> * What was your kong version? Or, what was the image used for `proxy` container in your kic pod?
> * What was the exact image is used for `ingress-controller` pod?
> * How was the kubernetes cluster deployed?
> * Could you access the `ingress` and/or `tcpIngress` in the normal way? If not, what happened when you access them?
> 
> I tried to reproduce the bug with this all-in-one manifest in v1.3.1: https://github.com/Kong/kubernetes-ingress-controller/blob/1.3.1/deploy/single/all-in-one-dbless.yaml, but I did not find the error log, and the ingress could be normally accessed by `curl -H"Host:example.com" http://$PROXY_IP` using your example ingress spec. Also, using the latest version of KIC(2.3.1) in kubernetes 1.23 is OK for your situation, where the ingress is correctly synced. My environment:
> 
> * k8s version: `v1.20.13` installed by `snap install microk8s --classic --channel=1.20/stable`
> * KIC version: `v1.3.1`, image `kong/kubernetes-ingress-controller:1.3`
> * kong version: `v2.4.1`,image `kong:2.4`

Yes,  I try with the dbless manifest, no error product. But when I try with all-in-one-postgres manifest(https://github.com/Kong/kubernetes-ingress-controller/blob/1.3.1/deploy/single/all-in-one-postgres.yaml),
error reproduct again.

full ingress yaml is here:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host:  example.com
      http:
        paths:
          - path: / 
            pathType: Prefix
            backend:
              service:
                name: example-svc
                port:
                  number: 8080

---
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: eexample
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - backend:
        serviceName:  example-svc
        servicePort: 8080
      port: 8080
```
