### ISSUE TITLE
strip_path is always false

### ISSUE THREAD

**Issue by phantooom** [Kong/kubernetes-ingress-controller#258]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
1.1

### Kubernetes version

**paste `kubectl version` output**
1.9
### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
cnetos
- **Kernel** (e.g. `uname -a`):
3.10
- **Install tools**:
- **Others**:

### What happened

i want config  strip_path = true but, it always false
### Expected behvaior
strip_path = true 

### Steps To Reproduce

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: osg-default-ingress
  namespace: component
  annotations:
    configuration.konghq.com: kong-custom-ingress
spec:
  rules:
  - http:
      paths:
      - path: /components/osg-default/
        backend:
          serviceName: osg-default
          servicePort: 8087

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-custom-ingress
proxy:
  path: /
route:
  strip_path: true

    {
      "updated_at": 1553846351,
      "created_at": 1553846348,
      "strip_path": false,
      "snis": null,
      "hosts": null,
      "name": null,
      "methods": null,
      "sources": null,
      "preserve_host": false,
      "regex_priority": 0,
      "service": {
        "id": "1f73cc4e-b326-42ef-a49e-4d6305dc2a4b"
      },
      "paths": [
        "/components/osg-default/"
      ],
      "destinations": null,
      "id": "dc2251ee-23ad-4925-94a4-a36f99d69f72",
      "protocols": [
        "http"
      ],
      "tags": null
    }

**Comment by angelshila** [comment]
Hi. 

Not sure why this is not working for you. I am currently using something similar.  

KongIngress crd config:
`apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kongingress-api
route:
  strip_path: true
  protocols:
  - https
---`

Kong Ingress config:

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ********-apis
  annotations:
    configuration.konghq.com: kongingress-api
    plugins.konghq.com: ********-basic-auth
spec:
  rules:
  - host:
    http:
      paths:
      - path: /*****-ui
        backend:
          serviceName: robot-ui
          servicePort: 9000
---`

Maybe check the Kong Ingress Controller logs to locate the error.

**Comment by angelshila** [comment]
Hi. 

Not sure why this is not working for you. I am currently using something similar and it works fine. 

KongIngress crd config:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kongingress-api
route:
  strip_path: true
  protocols:
  - https
---
```

Kong Ingress config:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ********-apis
  annotations:
    configuration.konghq.com: kongingress-api
    plugins.konghq.com: ********-basic-auth
spec:
  rules:
  - host:
    http:
      paths:
      - path: /*****-ui
        backend:
          serviceName: *****-ui
          servicePort: 9000
---
```

Maybe check the Kong Ingress Controller logs to locate the error.

**Comment by angelshila** [comment]
Hi. 

Not sure why this is not working for you. I am currently using something similar and it works fine. 
However, I am using 1.0.3. So, maybe Kong 1.1 has issues.

KongIngress crd config:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kongingress-api
route:
  strip_path: true
  protocols:
  - https
---
```

Kong Ingress config:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ********-apis
  annotations:
    configuration.konghq.com: kongingress-api
    plugins.konghq.com: ********-basic-auth
spec:
  rules:
  - host:
    http:
      paths:
      - path: /*****-ui
        backend:
          serviceName: *****-ui
          servicePort: 9000
---
```

Route Object Details:

```
        {
            "created_at": 1552460368,
            "hosts": null,
            "id": "e31b3a10-6b47-4668-a020-2ef7b9e9f46a",
            "methods": null,
            "paths": [
                "/*****-ui"
            ],
            "preserve_host": false,
            "protocols": [
                "https"
            ],
            "regex_priority": 0,
            "service": {
                "id": "bfef6a0e-816d-4751-89e0-07b53265cd99"
            },
            "strip_path": true,
            "updated_at": 1553885925
        },

```

Maybe check the Kong Ingress Controller logs to locate the error.
