### ISSUE TITLE
Add OSS nightly tests when image available

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2706]
We did not include OSS images in the additional addition of nightly tests because the nightly `latest` tag isn't actually the latest master commit image, and there is no alternative tag that is. The enablement team has indicated they plan to add this but has not provided tracking info. The test steps are:

```
  integration-tests-dbless-nightly:
    runs-on: ubuntu-latest
    steps:

    - name: setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-codegen-

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: run integration tests
      run: make test.integration.dbless
      env:
        TEST_KONG_IMAGE: "kong/kong"
        TEST_KONG_TAG: "latest"

    - name: collect test coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.dbless.out


  integration-tests-postgres-nightly:
    runs-on: ubuntu-latest
    steps:

    - name: setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-codegen-

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: run integration tests
      run: make test.integration.postgres
      env:
        TEST_KONG_IMAGE: "kong/kong"
        TEST_KONG_TAG: "latest"

    - name: collect test coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.postgres.out
```
