### ISSUE TITLE
AWS ELB configuration changed

### ISSUE THREAD

**Issue by MilanDasek** [Kong/kubernetes-ingress-controller#292]
Hello,

I experienced weird situation where AWS classic ELB was changed.

I have these annotations on service (ingress service)

```
Annotations:
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: *
  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:redacted:certificate/redacted
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
```

which effectively creates ELB with settings that HTTP and HTTPS ports are set to backend ports which are dynamic like
image
![image](https://user-images.githubusercontent.com/12279315/57675074-2ba8ec80-7621-11e9-9099-cf3e31df8f65.png)

BUT Instance port for HTTPS is set to service nodePort 30864

    - name: kong-proxy-tls
      nodePort: 30864
      port: 443
      protocol: TCP
      targetPort: 8443
so I have changed HTTPS port manually to the same port as HTTP (I want decrypt SSL on ELB and send HTTP to EKS/Kong ingress) and it worked for 20 days.

After those 20 days, it has been changed back to HTTPS port (internal dynamic one).

I don't know why it was initiated.

Can you please help?

The best way would be to make sure it will stay like I want. Maybe somehow tell kube that it should ignore any changes?

Thank you

**Comment by hbagdi** [comment]
You shouldn't be manually changing the config of your load-balancer for exactly this reason. AWS controller might reset it anytime.

Any reason you can't actually apply this using k8s YAMLs?

Could you share the kong-proxy service YAML?

**Comment by MilanDasek** [comment]
@hbagdi - is it possible to achieve that using annotations?

I would like to terminate HTTPS on ELB.

this
```
Annotations:
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: *
  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:redacted:certificate/redacted
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443

```

creates ELB, but HTTP and HTTPS are set to respective dynamic ports, but I would like to have same dynamic port for HTTP and HTTPS on ELB (set to http dynamic - just like on the screenshot)

If I change Kong ingress to have just HTTP - using helm values

```
proxy:
  tls:
    enabled: false
```

it doesn't create HTTPS endpoint on ELB at all.


Please advise.

**Comment by hbagdi** [comment]
I'm not too familiar with AWS's integration for LoadBalancer but I'll share what I can understand:

What you really want is to forward HTTP and HTTPS traffic from the AWS ELB to the HTTP port in Kong.
So, you would like a k8s service like:
```
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: https
      port: 443
      targetPort: 8000
```


This involves enabling TLS section in the helm chart and setting the container port to 8000 for the TLS section:
```
  tls:
    enabled: true
    servicePort: 443
    containerPort: 8000
```

This gives you a k8s service with 80:8000 and 443:8000 mapping.

Now, you can configure AWS ELB using annotations to terminate 443 with SSL and then configure backend protocol as `http`.

**Comment by MilanDasek** [comment]
@hbagdi 

but kong-kong-proxy service is generated by helm chart. Default is something like 

```
  ports:
  - name: kong-proxy
    nodePort: 32062
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: kong-proxy-tls
    nodePort: 31109
    port: 443
    protocol: TCP
    targetPort: 8443

```

I think you cannot use same nodeport for 2 different targetports. Meaning I cannot use settings like:

```
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
    nodePort: 32000

  tls:
    enabled: true
    servicePort: 443
    containerPort: 8443
    nodePort: 32000
```

But maybe this could be solution (helm chart settings)

```
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  tls:
    enabled: true
    servicePort: 443
    containerPort: 8000
```

?
