### ISSUE TITLE
Can't create acl plugin at global level using yaml

### ISSUE THREAD

**Issue by pgold30** [Kong/kubernetes-ingress-controller#293]
---
### Summary
Can't create acl plugin at global level using yaml

**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
1.1.1

### Kubernetes version
1.11.10

### What happened
The plugin is not enabled

### Expected behvaior
The plugin is enabled, this works using api 

### Steps To Reproduce

1.kubectl apply -f file.yml
file.yml:
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: acl
  namespace: default
  labels:
    global: "true"
config:
  hide_group_header: true
  whitelist: "admin"
plugin: acl
```
2. when we query the api list of plugins enabled acl is not there
