### ISSUE TITLE
'~' prefix is not allowed in k8s ingress path

### ISSUE THREAD

**Issue by jasine** [Kong/kubernetes-ingress-controller#2945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

kong 3.0 requiring that any regular expression begin with a `~` prefix ,but '~' prefix is not allowed in k8s ingress path, when I set `~`  prefix to ingress path ,

```
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: example-service
            port:
              number: 80
        path: ~/api/v1/example/(.*)
```
it has following errors

```
 # ingresses.networking.k8s.io "in" was not valid:
 # * spec.rules[5].http.paths[0].path: Invalid value: "~/api/v1/example/(.*)": must be an absolute path
```

### Kong Ingress Controller version

```shell
2.6.0
```

### Kubernetes version

```shell
v1.20.6
```

**Comment by altais** [comment]
Having the same issue here, i can't update my path to match the v3.0.0.0 new format
Kubernetes path must start with / https://gitlab.com/kubernetes/kubernetes/blob/60f4fbf4f25764dbd94b7f8146d927ddc684514d/pkg/apis/extensions/validation/validation.go#L417-418
it seem nginx solved it with an annotation: `nginx.ingress.kubernetes.io/use-regex: "true"`
https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/

**Comment by rainest** [comment]
Yeah, that validation is pretty straightforward. For the time being, although it's labeled a temporary solution, you'll want to [enable the controller-side legacy heuristic](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/upgrade-kong-3x/#update-ingress-regular-expression-paths-for-kong-3x-compatibility) and write regular expression paths without the leading `~`.

We'll need to review with the gateway team to determine a long-term strategy. I don't think we'd use an annotation because it's not possible to apply those per path. We'd have to insert the prefix into all paths on the Ingress, and that would require splitting or rewriting existing Ingresses in many cases.

**Comment by jrsmroz** [comment]
As we have discussed internally, the solution is make the prefix controllable by an annotation. For example given the manifest:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  annotations:
    konghq.com/regex-prefix: "/~"
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - http:
      paths:
      - path: /~/example/[a-z0-9]*
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpbin-deployment
            port:
              number: 80
```

Then the path matches path regular expression `/example/[a-z0-9]*`.  For routes that does not start with `/~`, the regular expression matching would not be used. The users are free to define the value of `konghq.com/regex-prefix` that works for them, but we assume the `/~` will be used most often.

For the simplicity, the regular expression prefix could default to `/~` if the annotation is not specified. The `konghq.com/regex-prefix` annotation would be able to override the default.
