### ISSUE TITLE
No mapping found for HTTP request with URI [/]

### ISSUE THREAD

**Issue by MilanDasek** [Kong/kubernetes-ingress-controller#296]
Hi,

when I deploy kong ingress in dbless mode using 

helm install stable/kong --name kong --namespace ingress --values kong-values.yaml

```
ingressController:
  enabled: true
  replicaCount: 1

proxy:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:REDACTED:certificate/REDACTED

admin:
  useTLS: false
  type: ClusterIP


postgresql:
  enabled: false

env:
  database: "off"

  trusted_ips: 0.0.0.0/0,::0
  real_ip_recursive: "on"
  real_ip_header: X-Forwarded-For


readinessProbe:
  httpGet:
    scheme: HTTP
livenessProbe:
  httpGet:
    scheme: HTTP


podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8444"
```

Then my applications exposed via ingress reports

```
java_timestamp=2019-05-22T11:38:09,475 thread=http-nio-9010-exec-3 level=WARN  class=o.s.web.servlet.PageNotFound line=1176 x-amz-cf-id= x-amzn-trace-id= request_id=REDACTED account_id=no_account project_id=no_project No mapping found for HTTP request with URI [/] in DispatcherServlet with name 'dispatcherServlet'
```

Seems application doesn't receive context.

Ingress looks like:

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      flux.weave.works/antecedent: REDACTED-staging:helmrelease/REDACTED
      kubernetes.io/ingress.class: kong
    labels:
      app.kubernetes.io/instance: REDACTED
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: REDACTED
      helm.sh/chart: REDACTED-0.0.1
    name: REDACTED
    namespace: REDACTED-staging
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: REDACTED
            servicePort: http
          path: /rest/accounts.*
        - backend:
            serviceName: REDACTED
            servicePort: http
          path: /rest/oauth.*
  status:
    loadBalancer:
      ingress:
      - hostname: REDACTED
```

Is it because https://github.com/Kong/kubernetes-ingress-controller/blob/master/CHANGELOG.md#040---20190424

strip_path property of Routes in Kong is set to true by default. 

???

Should I then create this for each namespace?
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: strip-path
route:
  strip_path: false
```

or 

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: xxx
proxy:
  path: /
route:
  strip_path: true
```

thanks

**Comment by MilanDasek** [comment]
I forgot to mention that if I deploy using
`helm install stable/kong --name kong --namespace ingress --version 0.9.9 --values kong-values.yaml`
all apps works fine.

**Comment by MilanDasek** [comment]
@hbagdi ?

**Comment by MilanDasek** [comment]
well, this solved my problem

```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "service.fullname" . -}}
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: {{ $fullName }}
route:
  strip_path: {{ .Values.kongingress.strip_path }}
  preserve_host: {{ .Values.kongingress.preserve_host }}
  regex_priority: {{ .Values.kongingress.priority }}
{{- end }}  
```

strip_path: false
preserve_host: true
