### ISSUE TITLE
Schema violation (snis: <hostname-here> is duplicated) after upgrade from 0.3.0 -> 0.4.0

### ISSUE THREAD

**Issue by alexjantunen** [Kong/kubernetes-ingress-controller#297]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

After upgrading from ingress-controller 0.3.0 to 0.4.0 I started to get following error every ~3s:
```
E0521 19:10:30.906929       6 controller.go:117] unexpected failure updating Kong configuration:
1 errors occured:
	while processing event: {Update} failed: 400 Bad Request {"message":"schema violation (snis: my.hostname.test is duplicated)","name":"schema violation","fields":{"snis":"my.hostname.test is duplicated"},"code":2}
W0521 19:10:30.907136       6 queue.go:113] requeuing default/my-app, err 1 errors occured:
	while processing event: {Update} failed: 400 Bad Request {"message":"schema violation (snis: my.hostname.test is duplicated)","name":"schema violation","fields":{"snis":"my.hostname.test is duplicated"},"code":2}
```

Everything seems to work well though, but I don't dare to update production because of this.
Does this schema validation error really have impact on anything?

NOTE this was postgres db setup!

**Kong Ingress controller version**
0.4.0

**Kong or Kong Enterprise version**
1.1.2

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: Google Kubernetes Engine
- **OS**: Container-Optimized OS 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

We were running following ingress configurations on Kubernetes with ingress-controller 0.3.0 and kong 1.0.0 successfully:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: secured-api
  namespace: default
  labels:
    global: "false"
config:
    # allow credentials to pass so that app can see the Authorization header
    hide_credentials: false
plugin: basic-auth

---

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-configuration

route:
  preserve_host: true
  strip_path: false
  protocols:
  - http
  - https

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app
  annotations:
    kubernetes.io/ingress.class: "kong"
    configuration.konghq.com: "kong-configuration"
spec:
  tls:
  - hosts:
    - my.hostname.test
    secretName: my-tls-secret
  rules:
    - host: my.hostname.test
      http:
        paths:
          - path: "/"
            backend:
              serviceName: my-app-service
              servicePort: 80
          # list also following routes (prefixes), as these do not require auth plugin.
          - path: "/api/v02/public/"
            backend:
              serviceName: my-app-service
              servicePort: 80
          - path: "/api/v02/public-2/"
            backend:
              serviceName: my-app-service
              servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-app-secured-api-ingress
  annotations:
    kubernetes.io/ingress.class: "kong"
    plugins.konghq.com: secured-api
    configuration.konghq.com: "kong-configuration"
spec:
  tls:
  - hosts:
    - my.hostname.test
    secretName: my-tls-secret
  rules:
    - host: my.hostname.test
      http:
        paths:
          - path: "/api/v02/"
            backend:
              serviceName: my-app-service
              servicePort: 80
```

After upgrading to kong 1.1.2 and finally ingress-controller to 0.4.0 (db migrations up were done etc), the above mentioned error started to show up on logs periodically. I believe this is not related to upgrade/migration process itself and probably show up on fresh 0.4.0 setup as well.

### Expected behaviour

No errors in logs, I believe I haven't figured out yet what problems this would cause, and that's why I don't want to update production.
 
If duplicate SNIs are not supported anymore, I wish to get a workaround to my setup. And this should be mentioned in release notes.

### Steps To Reproduce

1. apply given ingresses to the Kong Kubernetes environment
2. see the logs on ingress-controller
