### ISSUE TITLE
Plugin OAuth2 not work with consumer and credentials, Service or Ingress

### ISSUE THREAD

**Issue by mcordovaake** [Kong/kubernetes-ingress-controller#300]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

I configure the plugin of oauth2 with the ingress/services and when consuming the api, it is not secure

**Kong Ingress controller version**
0.4.0

**Kong or Kong Enterprise version**
1.1.2

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
The plugin the Oauth2 not work

### Steps To Reproduce

1. I have the following yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: codificacion
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /
        backend:
          serviceName: codificacion-service
          servicePort: 8002

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-macordova
username: macordova

apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: oauth2-consumer-macordova
consumerRef: consumer-macordova
type: oauth2
config:
  name: credentials-oauth2
  client_id: client_id_01
  client_secret: client_secret_01
  redirect_uris: http://localhost:8000/

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: auth-oauth2
config:
  scopes: read,write
  mandatory_scope: true
  token_expiration: 180
  enable_password_grant: true
  accept_http_if_already_terminated: true
  global_credentials: true
  auth_header_name: authorization
  refresh_token_ttl: 1209600
plugin: oauth2

2. then I apply the change to ingress
kubectl patch ingress codificacion -p "{\"metadata\":{\"annotations\":{\"plugins.konghq.com\":\"auth-oauth2\"}}}"

3. when calling the api this does not request authorization
4.

**Comment by jatj** [comment]
Hey do you closed this issue because you got it working?  Do you mind sharing how did you make it worked?

**Comment by denislee** [comment]
This was the way I solved it. Hope it helps.

`apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test-consumer
  namespace: test
username: test
custom_id: test-credential
---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: test-credential
  namespace: test
consumerRef: test-consumer
type: oauth2
config:
  name: test-credential
  client_id: test
  client_secret: test
  redirect_uris:
  - "http://test"
`

**Comment by marcosdiez** [comment]
Just for the record, `KongCredential` is deprecated, hence one should now use a k8s `secret`:

```
---
kind: Secret
apiVersion: v1
metadata:
  name: test-credential
  namespace: test
data:
  client_id: dGVzdC1sb2dpbg==         # test-login
  client_secret: dGVzdC1wYXNzd29yZA== # test-password
  kongCredType: b2F1dGgy              # oauth2
  name: dGVzdC1jb25zdW1lcg==          # test-consumer
  redirect_uris: aHR0cDovL3Rlc3Q=     # http://test
type: Opaque
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: test-consumer
  namespace: test
credentials:
  - test-credential
username: test-consumer
```

**Comment by ccfishk** [comment]
Thanks for the record, here is the doc reference 
https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/concepts/custom-resources/#kongcredential-deprecated

**Comment by mdiez-modus** [comment]
Just for the record, I just found out how to type secrets without having to base64 encode everything and also that to add multiple `redirect_uris`, one has to separate them using comas. Example, similar as above,but with more `redirect_uris`
```
---
kind: Secret
apiVersion: v1
metadata:
  name: test-credential
  namespace: test
stringData:
  client_id: test-login
  client_secret: test-password
  kongCredType: oauth2
  name: test-consumer
  redirect_uris: http://test1.com,http://test2.com,http://test3.com
type: Opaque
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: test-consumer
  namespace: test
credentials:
  - test-credential
username: test-consumer
```
