### ISSUE TITLE
ingress rules that have matching  `<hostname><serviceName>` or  `<serviceName><port>` generate wrong kong config

### ISSUE THREAD

**Issue by jrsmroz** [Kong/kubernetes-ingress-controller#3004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue was found during code analysis.

When a combined routes feature is enabled  - `KONG_CONTROLLER_FEATURE_GATES="CombinedRoutes=true"` - the parser can combine routes into a single service, that should not be combined. 

The condition needed to trigger it is ingress rules that have matching `"<hostname><serviceName>" or "<serviceName><port>"`.

For example, given the Ingress with two rules that match the equality `"company.com"+"ad-service" == "company.co"+"ad-service"`:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - host: company.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ad-service
            port:
              number: 80
  - host: company.co
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: mad-service
            port:
              number: 80
```

the parser would generate a kong service for only one of the services (`mad-service`,  `ad-service`) and attach both rules to it.

The same issue can be triggered using service name and ports, i.e  `"ad-service1"+"8080" == "ad-service"+"18080"`:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: kong
  rules:
  - host: company.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ad-service1
            port:
              number: 8080
  - host: company.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ad-service
            port:
              number: 18080
```

### Expected Behavior

The ingress rules should be correctly recognized as pointing to different services.

### Steps To Reproduce

```markdown
This issue was found during code analysis and reproduced in unit tests.
```

### Kong Ingress Controller version

```shell
v2.7.0
```
