### ISSUE TITLE
Certificate error while deploying latest Kong ingress controller 

### ISSUE THREAD

**Issue by smartaquarius10** [Kong/kubernetes-ingress-controller#3036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Team,

Tried deploying latest helm chart and getting this error in ingress controller. 
Any suggestion please as I have to upgrade my kong version to the latest one.

Currently, my cluster details are
Azure Kubernetes version:- 1.23.5
Kong proxy version:- 2.7.0
Kong ingress controller:- 2.1.1

Error Logs:- 

> time="2022-10-07T13:53:48Z" level=error msg="Failed to get API Group-Resources" error="Get \"https://xxxxxx:443/api?timeout=32s\": x509: certificate specifies an incompatible key usage"
> Error: unable to start controller manager: Get "https://xxxxx:443/api?timeout=32s": x509: certificate specifies an incompatible key usage
> 

Regards,
Tanul

### Expected Behavior

Latest version of kong should be deployed

### Kong Ingress Controller version

```shell
v2.1.1
```

### Kubernetes version

```shell
1.23.5
```

**Comment by randmonkey** [comment]
This error message `Failed to get API Group-Resources` seems to be came from kubernetes controller runtime, and the controller failed to access kubenetes API server. The error message `x509: certificate specifies an incompatible key usage` looks like a configuration problem in your certificates of kubernetes cluster.
What was the original chart version you used, and what is the progress of upgrading kong? Have you updated kubernetes version or changed configuration of kubernetes cluster during the upgrade?

**Comment by smartaquarius10** [comment]
@randmonkey , I am trying to upgrade to chart 2.13.1 which is the latest one. In this version of Kong proxy is 3.0.0 and ingress controller in 2.7.0.

Currently my kong proxy version is 2.7.0 and ingress controller is 2.1.1 which is pretty old.

I haven't changed any configuration of Azure kubernetes cluster and if I'm not wrong, we are not allowed to make such level of changes in Azure kubernetes. Around 2.5 months back, I have updated the kubernetes version to v1.23.5

**Comment by smartaquarius10** [comment]
@pmalek, These are the values

```
replicaCount: 2
proxy:
  loadBalancerIP: aa.bbb.ccc.d
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  http:
    enabled: false
ingressController:
  installCRDs: false
  image:
    repository: myregistry.azurecr.io/kong-ingress-controller
    tag: v2.7.0
image:
  repository: myregistry.azurecr.io/kong
  tag: 3.0.0
```

The same AKS version is unavailable in Azure portal because we have raised vulnerability which have been accepted by microsoft and now it is not showing at all. But there is one version available with same minor release only patch version has updated  i.e. 1.23.8. 

I have created a fresh cluster and deployed on it. Same error is coming. This is the pipeline we are using to build the image.

trigger: none

pool:
  vmImage: ubuntu-latest
  
```
parameters:
- name: ALPINE_VERSION
  displayName: The Alpine Linux tag to use as base
  type: string
  default: latest
- name: KONG_PROXY_TAG
  displayName: The Kong Proxy tag to use as base
  type: string
  default: 3.0.0
- name: KONG_INGRESS_CONTROLLER_REPO_TAG
  displayName: The Kong Ingress Controller tag to use as base
  type: string
  default: v2.7.0
- name: KONG_CHART_VERSION
  displayName: The Kong Helm chart tag to use as base
  type: string
  default: kong-2.13.1

stages:
- stage: 'build'
  displayName: 'Kong Custom Images Build'
  jobs:
  - job: 'build'
    displayName: 'Kong Custom Images Build'
    steps:
    - task: Bash@3
      name: 'downloadEditCodePrepareArtifacts'
      displayName: 'Download Kong Repos, Edit Code and Prepare Artifacts'
      inputs:
        targetType: inline
        script: |
          git clone https://github.com/Kong/docker-kong.git
          cd docker-kong
          git checkout ${{ parameters.KONG_PROXY_TAG }}
          sed -i 's/^FROM alpine:.*$/FROM alpine:${{ parameters.ALPINE_VERSION }}/g' alpine/Dockerfile
          sed -i 's/ zip / /g' alpine/Dockerfile
          cd ..
          
          git clone https://github.com/Kong/kubernetes-ingress-controller.git
          cd kubernetes-ingress-controller
          git checkout ${{ parameters.KONG_INGRESS_CONTROLLER_REPO_TAG }}
          sed -i 's/^FROM registry\.access\.redhat\.com.*$/FROM alpine:${{ parameters.ALPINE_VERSION }}/g' Dockerfile
          sed -i '$!N; /^\(.*\)\n\1$/!P; D' Dockerfile
          sed -i 's/groupadd/addgroup/g' Dockerfile
          cd ..
          
          cp k8s/my-kong-values.yaml $(Build.ArtifactStagingDirectory)/values.yaml
          sed -i 's/KONG_PROXY_TAG/${{ parameters.KONG_PROXY_TAG }}/g' $(Build.ArtifactStagingDirectory)/values.yaml
          sed -i 's/KONG_INGRESS_CONTROLLER_TAG/${{ parameters.KONG_INGRESS_CONTROLLER_REPO_TAG }}/g' $(Build.ArtifactStagingDirectory)/values.yaml
          
    - task: Docker@2
      name: 'buildPushKong'
      displayName: 'Build and Push Kong Proxy'
      inputs:
        containerRegistry: 'WEUACRImGovernanceProd'
        repository: 'kong'
        command: 'buildAndPush'
        Dockerfile: 'docker-kong/alpine/Dockerfile'
        tags: ${{ parameters.KONG_PROXY_TAG }}

    - task: Docker@2
      name: 'buildPushIngressController'
      displayName: 'Build and Push Kong Ingress Controller'
      inputs:
        containerRegistry: 'WEUACRImGovernanceProd'
        repository: 'kong-ingress-controller'
        command: 'buildAndPush'
        Dockerfile: 'kubernetes-ingress-controller/Dockerfile'
        tags: ${{ parameters.KONG_INGRESS_CONTROLLER_REPO_TAG }}
    
    - task: PublishBuildArtifacts@1
      name: 'publishValues'
      displayName: 'Publish Values'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'values'
        publishLocation: 'Container'
    
```

**Comment by smartaquarius10** [comment]
I'm unable to understand why it is throwing such errors when building and deploying. Whereas, if I directly use kong helm chart then no error occurs

**Comment by rainest** [comment]
From the [community Slack channel](https://kubernetes.slack.com/archives/CDCA87FRD/p1665513843635229?thread_ts=1665151018.022489&cid=CDCA87FRD) this is a weird effect from accidentally building the FIPS variant of the controller and deploying it to a cluster that is presumably not FIPS-compliant and possibly using an API server cert with unsupported cryptographic primitives.

Not sure why it'd result in a key usage error, but in any case it's a non-issue unless the FIPS variant isn't functioning on FIPS-compliant clusters. The FIPS variant isn't officially released either, so even less of a concern.

**Comment by smartaquarius10** [comment]
@rainest I have checked my node pool and FIPS is not enabled. You got it correct. Thank you so much for the help. Really appreciate

**Comment by rainest** [comment]
@smartaquarius10 FWIW the linked PR makes distroless the last target in the Dockerfile, so buildx will now default to it.

**Comment by smartaquarius10** [comment]
@rainest Thank you so much travis. But azure devops `Docker@2 task ` doesn't support buildx command yet.  And with build command we have to pass the argument, right?

**Comment by pmalek** [comment]
@smartaquarius10 You should be able to do it with vanilla `docker` as well, as documented in https://docs.docker.com/engine/reference/commandline/build/#options

Name, shorthand | Default | Description
-- | -- | --
`--target` |   | Set the target build stage to build.

**Comment by smartaquarius10** [comment]
@pmalek , Hey.. Hope all is good there 😃 . Yesterday, it worked while discussing on slack. Created task like this:

```
- task: Docker@2
      name: 'buildIngressController'
      displayName: 'Build Kong Ingress Controller'
      inputs:
        repository: 'kong-ingress-controller'
        command: 'build'
        containerRegistry: 'myacrregistry'
        Dockerfile: 'kubernetes-ingress-controller/Dockerfile'
        tags: v2.7.0
        arguments: --target distroless
```
