### ISSUE TITLE
KIC doesn't detect Gateway's faulty condition while pushing configuration

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Customer pushed some configuration to k8s.
2. KIC sent that config to the Gateway, Gateway got stalled, and the user got no feedback in logs.
3. Customer pushed some other configuration to k8s.
4. KIC failed to push that other config, but the user got no feedback in logs again. 

### Expected Behavior

It's expected that in 2) and 4) KIC should detect Gateway faulty condition and log an error.

### Steps To Reproduce

1. Configure an Ingress with an incompatible regex path
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: test-default
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
          imagePullPolicy: IfNotPresent
          name: echo
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: nginx.conf
                path: nginx.conf
            name: echo-nginx-conf
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/override: test-default
  name: test-default
  namespace: default
spec:
  clusterIP: 172.20.88.85
  clusterIPs:
    - 172.20.88.85
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: high
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: low
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: echo
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/override: test-default
    konghq.com/snis: <abc.example.com>
  labels:
    PathConfig: Default
  name: bad-config
  namespace: default
spec:
  ingressClassName: <kong>
  rules:
    - host: <abc.example.com>
      http:
        paths:
          - backend:
              service:
                name: test-default
                port:
                  number: 8080
            path: /~/\/*$
            pathType: ImplementationSpecific
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: test-default
  namespace: default
proxy: {}
route:
  https_redirect_status_code: 308
  preserve_host: false
  protocols:
    - https
  strip_path: false
upstream:
  host_header: test-default.default.svc
  slots: 5000
```
2. Gateway should get stalled (@mflendrich - what do we exactly mean by 'stalled' here?)
3. Fix the Ingress' path manually in the manifests. 
4. KIC doesn't propagate the fixed configuration to the Gateway and reports no errors in logs.

### Kong Ingress Controller version

```shell
KIC: v2.7.0 
Gateway: v3.0.0
KONG_ROUTER_FLAVOR=traditional_compatible
```

**Comment by mflendrich** [comment]
This is the config I have used to reproduce this issue on KIC 2.7.0 Gateway 3.0.0 (kong router flavor `traditional_compatible`)

Step 1: apply this

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deployment
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kong/httpbin:0.1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpbin
  name: httpbin-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpbin
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  annotations:
    httpbin.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: 'true'
spec:
  rules:
  - http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: httpbin-deployment
            port:
              number: 80
```
Observe that the app is up and running, and that going with your web browser to `/foo` shows the httpbin index page.

Step 2: apply the breaking config
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress-2
  annotations:
    httpbin.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - http:
      paths:
      - path: '/~/delay/(?<delay>[^\/]+)$'
        pathType: ImplementationSpecific
        backend:
          service:
            name: httpbin-deployment
            port:
              number: 80
```

Step 3: once KIC has had enough time to send `httpbin-ingress-2` to Kong, try making a change in `httpbin-ingress`, for example `kubectl edit ingress httpbin-ingress` and change `spec.rules[0].http.paths[0].path` from `/foo` to `/bar`.

Then navigate your browser to `foo` and then to `/bar`.
Desired behavior: `/foo`: Kong 404 `no Route matched with those values`, `/bar`: the httpbin page
Actual behavior: `/foo`: the httpbin page, `/bar`: Kong 404 `no Route matched with those values`
