### ISSUE TITLE
Remove non-combined route generation

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#3131]
Following the addition of HTTPRoute combined route generation support, traditional route generation is deprecated and will be removed in a future release. Combined route generation results in significant reductions in configuration size in many configurations and improves config apply time, while not affecting request routing. There are no known benefits to traditional route generation over combined route generation, and only a minor transition hurdle due to changing route names and IDs.

Please comment on this issue if you observe any issues with combined route generation or gaps in functionality between it and traditional route generation.

**Comment by robinmanuelthiel** [comment]
For me, the combined routes don't support wildcards: #3311

**Comment by Clint-Chester** [comment]
Unfortunately we recently upgraded our KIC from v2 to v2.8 and didn't realise that the route generation was now rolled up. We were using the non-combined route generation so that we could do performance monitoring on the individual routes with the [Kong Grafana Dashboard](https://grafana.com/grafana/dashboards/7424-kong-official/). The upgrade resulted in breaking our monitoring capability by route.

Since #3132 was feature flagged, could this just be exposed as an annotation to give users choice on whether they'd like the routes rolled up? Or is there another way that we can monitor the routes in a service? Happy to go into more detail with the use case if you like 😄

**Comment by Clint-Chester** [comment]
Yeah in our dashboards it rolled up all our routes into one, so we lost our analytics of individual paths. I'll go through the example we were using.

So we have the ingress defined below as an example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
spec:
  rules:
  - host: "test.com"
    http:
      paths:
      - pathType: Prefix
        path: "/validate/email"
        backend:
          service:
            name: backend-service
      - pathType: Prefix
        path: "/validate/mobile"
        backend:
          service:
            name: backend-service
```
Even though they are going to the same backend / host / port, we want to specify the individual paths so that we can get statistics on the individual route in terms of latency and upstream processing performance. I thought this was a nice little feature to be able to start breaking down individual routes for performance monitoring, without being intrusive on adjusting an application's architecture.

Unfortunately in the above example, this would all get rolled into one route and specify multiple paths within that route.

The ideal target state that we were looking for in the implementation is the ability to get metrics on different paths hitting the same backend for performance analysis and localising where errors are coming from (which we could before the change).

Happy to provide more info if needed 😄
