### ISSUE TITLE
Use kong ingress controller 0.5.0 got TLS error

### ISSUE THREAD

**Issue by zhigang** [Kong/kubernetes-ingress-controller#327]
### Summary

Update kong Ingress controller version "0.3.0" to "0.5.0". I got some error.  It can't work. 

**Kong Ingress controller version**
0.5.0

**Kong version**
1.2

### Kubernetes version
Kubernetes Cluster version v1.10 (v1.10.12) - git (clean) commit c757b93cf034d49af3a3b8ecee3b9639a7a11df7 - platform linux/amd64

### What happened

I have same tls secret in different namespaces. kong ingress controller can't create routes use my tls. 

example:
test-ssl in namespace "a-ns" and "b-ns".
a-api.yaml in namespace "a-ns".
b-api.yaml in namespace "b-ns".

test-ssl.yaml
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test-ssl
data:
  tls.crt: "xxxxxxxxx"
  tls.key: "xxxxxxxxxx"
```
a-api.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: a
  namespace: a-ns
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - secretName: test-ssl
      hosts:
      - a.test.com
  rules:
  - host: "a.test.com"
    http:
      paths:
      - path: /a-api
        backend:
          serviceName: a-api
          servicePort: 80
```
b-api.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: b
  namespace: b-ns
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - secretName: test-ssl
      hosts:
      - b.test.com
  rules:
  - host: "b.test.com"
    http:
      paths:
      - path: /b-api
        backend:
          serviceName: b-api
          servicePort: 80
```
kong ingress controller error:
```
E0710 10:36:08.561167       1 controller.go:125] unexpected failure updating Kong configuration: 
error creating a valid state for Kong: duplicate certificate definitions found for the following certificate:
```

**Comment by hbagdi** [comment]
We can make Ingress Controller smarter to de-duplicate these same secrets and not throw this error.

Meanwhile, here is what I'd recommend:
Do not copy the TLS secret across namespaces and specify all the hosts that should be served under the same Ingress resource.
Is it possible to do this in your use-case?

**Comment by zhigang** [comment]
> We can make Ingress Controller smarter to de-duplicate these same secrets and not throw this error.
> 
> Meanwhile, here is what I'd recommend:
> Do not copy the TLS secret across namespaces and specify all the hosts that should be served under the same Ingress resource.
> Is it possible to do this in your use-case?

Sorry about that. We use load balance with tls  in production environment. So that can work well. But we don't have it in our test environment. And our namespace create by business. Its subdomain is different. So we can't make true that specify all the hosts in the same ingress resource.
Now we still use kong ingress controller 0.3.0 in test environment.

**Comment by hbagdi** [comment]
> And our namespace create by business. Its subdomain is different. So we can't make true that specify all the hosts in the same ingress resource.

That makes sense and I suspected this would be an issue in such a setup.
I've opened up https://github.com/hbagdi/deck/issues/32 to solve this problem in decK, which powers the Ingress Controller, and which is where the issue lies.

**Comment by zhigang** [comment]
> That makes sense and I suspected this would be an issue in such a setup.
> I've opened up [hbagdi/deck#32](https://github.com/hbagdi/deck/issues/32) to solve this problem in decK, which powers the Ingress Controller, and which is where the issue lies.
Thanks for solved this.

**Comment by zhigang** [comment]
@hbagdi Sorry. I got another error on ingress controller 0.5.0
error:
```
E0722 12:39:24.220304       1 controller.go:125] unexpected failure updating Kong configuration:
error creating a valid state for Kong: duplicate upstream definitions found for: 'test-api.staging.svc'
W0722 12:39:24.220345       1 queue.go:113] requeuing staging/test-api, err error creating a valid state for Kong: duplicate upstream definitions found for: 'test-api.staging.svc'
```
This is my ingress yaml , there have two ports need setting.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: need-strip-path
    kubernetes.io/ingress.class: kong
  labels:
    app: test-api
  name: test-api
  namespace: staging
spec:
  rules:
  - host: test.mydomain.com
    http:
      paths:
      - backend:
          serviceName: test-api
          servicePort: 5000
        path: /test-api
      - backend:
          serviceName: test-api
          servicePort: 5001
        path: /test-socket
```
