### ISSUE TITLE
Port name seems not supported with CombinedRoutes

### ISSUE THREAD

**Issue by seb-inf** [Kong/kubernetes-ingress-controller#3296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: demo-test
  namespace: demo-test
spec:
  clusterIP: 10.23.1.120
  clusterIPs:
  - 10.23.1.120
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
```

Ingress

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/regex-priority: "110"
    konghq.com/strip-path: "false"
    kubernetes.io/ingress.class: kong
  creationTimestamp: "2022-11-25T15:03:20Z"
  generation: 4
  name: demo-test-backend
  namespace: demo-test
  resourceVersion: "77594872"
  uid: 20d6eee3-6ef1-4796-b325-929068620b6f
spec:
  rules:
  - host: demo.test.company.com
    http:
      paths:
      - backend:
          service:
            name: demo-test
            port:
              name: http
        path: /~/(api|docs)
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.23.14.50
```

Kong configuration:

```
router_flavor = traditional
```

Current behavior: 503

> {"message": "failure to get a peer from the ring-balancer"}

In logs:

```
kong-kong-6d6b957cff-kp2j9 ingress-controller time="2022-12-21T10:48:52Z" level=error msg="resource processing failed: can't find port for backend kubernetes service: no suitable port found" GVK="networking.k8s.io/v1, Kind=Ingress" name=demo-test-backend namespace=demo-test                                                         │
kong-kong-6d6b957cff-kp2j9 ingress-controller time="2022-12-21T10:48:52Z" level=info msg="no targets found to create upstream" service_name=demo-test.demo-test-backend.demo-test.0                                                                                                                                         │
kong-kong-6d6b957cff-kp2j9 ingress-controller time="2022-12-21T10:49:01Z" level=error msg="resource processing failed: can't find port for backend kubernetes service: no suitable port found" GVK="networking.k8s.io/v1, Kind=Ingress" name=demo-test-backend namespace=demo-test                                                         │
kong-kong-6d6b957cff-kp2j9 ingress-controller time="2022-12-21T10:49:01Z" level=info msg="no targets found to create upstream" service_name=demo-test.demo-test-backend.demo-test.0
```

### Expected Behavior

The requests should be routed to BE. 

### Steps To Reproduce

```markdown
1. Create Ingress and Service as above
2. Deploy Kong 3.1 and KIC 2.8
3. Make request to ingress
```

### Kong Ingress Controller version

```shell
2.8
```

### Kubernetes version

```shell
v1.22.15-gke.100
```
