### ISSUE TITLE
Kong Ingress Controller & Istio Integration

### ISSUE THREAD

**Issue by ismailbaskin** [Kong/kubernetes-ingress-controller#330]
**Problem:** 
As you know Ingress controller translates pods's endpoints instead of service's cluster ip to Kong Upstream Target ([design doc](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/design.md#translation)). This approach has a lot of benefits but it does not work with Istio because if its design.

**Workaround**
Creating an ExternalName service which is pointing actual service's local DNS.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service-for-kong
  namespace: default
spec:
  externalName: my-service.default.svc.cluster.local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ExternalName
```

**Solution Options**

1. Using [Nginx Ingress `service upstream` annotation.](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#service-upstream) Annotations are hacky but it can be useful for nginx ingress compability.
2. Adding a useClusterIP flag to KongIngress CRD. 
3. Leave it as is and suggest ExternalName Service workaround solution on documentation.

**References**
I've found this unsuccessful attempt. https://github.com/Kong/kubernetes-ingress-controller/pull/48

Useful links: 
* [https://github.com/kubernetes/ingress-nginx/issues/2126](https://github.com/kubernetes/ingress-nginx/issues/2126)
* [Nginx Ingress `service upstream` annotation.](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#service-upstream)
