### ISSUE TITLE
Generating route fails for wildcard hosts due to invalid name

### ISSUE THREAD

**Issue by robinmanuelthiel** [Kong/kubernetes-ingress-controller#3311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following ingress

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wildcard-domain
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/preserve-host: 'true'
spec:
  ingressClassName: 'kong'
  rules:
  - host: '*.foo.com'
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: foo-service
            port:
              number: 80
```

tries to generate a route object that looks like this

```json
{
  "protocols": [
    "http",
    "https"
  ],
  "paths": [
    "/"
  ],
  "methods": null,
  "sources": null,
  "hosts": [
    "*.foo.com"
  ],
  "name": "sbc-dev.wildcard-domain.foo-service.*.foo.com.80", // <-- invalid due to the asterisk (*)
  "created_at": 1672412759,
  "updated_at": 1672412759,
  "headers": null,
  "request_buffering": true,
  "response_buffering": true,
  "https_redirect_status_code": 426,
  "tags": null,
  "destinations": null,
  "preserve_host": true,
  "regex_priority": 0,
  "strip_path": true,
  "snis": null,
  "service": {
    "id": "cf59b775-dcf7-52e1-add6-ce91f55acba9"
  },
  "path_handling": "v0",
  "id": "f37b8676-2de6-567b-9cf6-90d9d1bcb5cb"
}
```

This won't be accepted by the Admin API giving the following error (from the `kong-proxy` logs):

```
time="2022-12-30T15:26:23Z" level=error msg="could not update kong admin" error="posting new config to /config: HTTP status 400 (message: \"declarative config is invalid: {services={{routes={[2]={name=\\\"invalid value 'sbc-dev.subscriptions-ingress.subscriptions-spaceblocks-subscriptions-main.*.subscriptions.eu1.dev.spaceblocks.cloud.80': the only accepted ascii characters are alphanumerics or ., -, _, and ~\\\"}}}}}\")" subsystem=dataplane-synchronizer
```

### Expected Behavior

The route should be generated successfully.

### Steps To Reproduce

See above. Pls note, that the service and ingress resource are in the same namespace, which is different from the kong namespace

### Kong Ingress Controller version

```shell
v3.1
```

### Anything else?

1.23
