### ISSUE TITLE
Support setting Proxy Port on KongIngress

### ISSUE THREAD

**Issue by kenXengineering** [Kong/kubernetes-ingress-controller#336]
### Summary

The KongIngress proxy section allows you to set variables such as protocol, but not port.  I am seeing instances where all my services default to port 80 and I need to override it.

**Kong Ingress controller version**
v0.5.0

**Kong or Kong Enterprise version**
v1.2

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-20T22:55:20Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Kernel** (e.g. `uname -a`): Ubuntu
- **Install tools**: Kops
- **Others**:

### What happened
I have a service that listens on port 443, however when the service is created in Kong it defaults to port 80.  I created a KongIngress to modify the proxy:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kubernetes-dashboard-ingress
  namespace: kube-system
proxy:
  port: 443
  protocol: https
route:
  https_redirect_status_code: 301
  protocols:
  - https
```

### Expected behvaior
Kong Service would have its Protocol set to HTTPS and Port set to 443

**Comment by hbagdi** [comment]
This is actually intended.
Why are you not using `ServicePort` in the Ingress definition to specify this?
https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules

**Comment by kenXengineering** [comment]
Let me post the service and ingress definition.  We are setting the `servicePort` field in the k8s ingress to port 443, and the k8s service port to 443.  However in Kong the service port is set to 80 and the protocol is set to HTTP.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: kong-internal
    plugins.konghq.com: kubernetes-dashboard-request-transformer
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  rules:
  - host: kube.initech.net
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
  tls:
  - hosts:
    - kube.initech.net
    secretName: kube.initech.net
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
  sessionAffinity: None
  type: ClusterIP
```

This is what gets configured in Kong, via Konga:

![Screenshot from 2019-07-30 14-07-11](https://user-images.githubusercontent.com/91260/62153870-87574d80-b2d3-11e9-8638-6a749e46727a.png)
