### ISSUE TITLE
KongIngress Proxy values are not changed when set on an Ingress via Annotation

### ISSUE THREAD

**Issue by kenXengineering** [Kong/kubernetes-ingress-controller#338]
### Summary

As per the documentation found [here](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/custom-resources.md#kongingress), we should be able to set the annotation `configuration.konghq.com` on a K8s Ingress and see our changes reflected in Kong.  I created a KongIngress with both `proxy` and `route` values set.  However I am not seeing the `proxy` values updated in the Kong Service.  It only applies the `proxy` values when you set the Annotation on the K8s Service, not Ingress. 

I'm not sure if this is expected behavior, but based on the documentation it should be overriding the Kong Service with the KongIngress `proxy` settings when set on a K8s Ingress.  Else the documentation should be updated that to apply the `proxy` settings you must set the annotation on the K8s Service.

I'm wondering if we may want to split the `proxy` settings from the KongIngress object since the `proxy` settings apply to the Kong Service, which maps to a K8s Service.  You can have multiple Ingresses/Routes pointing to the same Service, and if you have multiple KongIngress objects with different `proxy` values, how would you reconcile it?

Also should `proxy` be changed to `service` since its values map to a Kong Service?  Initially I was confused on where the `proxy` values were set in Kong. 

**Kong Ingress controller version**
v0.5.0

**Kong or Kong Enterprise version**
v1.2

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"archive", BuildDate:"2019-06-20T22:55:20Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Kernel** (e.g. `uname -a`): Ubuntu
- **Install tools**: Kops
- **Others**:

### What happened
Created KongIngress with `route` and `proxy` settings:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kubernetes-dashboard
proxy:
  protocol: https
  port: 443
route:
  https_redirect_status_code: 301
  protocols:
    - https
```

Create K8s Ingress with annotation set:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: kong-internal
spec:
  rules:
  - host: kube.navistone.net
    http:
      paths:
        - backend:
            serviceName: kubernetes-dashboard
            servicePort: 443
          path: /
```

### Expected behvaior

Kong Service values would be overwritten with KongIngress `proxy` values.

### Workaround(?)

Set the Annotation on the K8s Service as well:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    configuration.konghq.com: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
