### ISSUE TITLE
Regex paths with ImplementationSpecifics take precedence over Exact match

### ISSUE THREAD

**Issue by sgrzemski** [Kong/kubernetes-ingress-controller#3394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Hello KIC team,
I have recently updated Kong Ingress Controller to 2.8 (and Kong to 3.1.1 as well). Prior to the upgrade, I had the following configuration:
1. Top level ingress:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-super-service
  annotations:
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
spec:
  ingressClassName: kong
  rules:
    - host: super.service.com
      http:
        paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name:  my-super-service
              port:
                number: 8080
```
2. Multiple ingresses with Exact match path type, e.g.:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: some-modified-path
  annotations:
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
    konghq.com/plugins: "some-plugin"
spec:
  ingressClassName: kong
  rules:
    - host: super.service.com
      http:
        paths:
        - path: /some/path
          pathType: Exact
          backend:
            service:
              name: my-super-service
              port:
                number: 8080
```
3. All of the ingresses point to the same service, but a couple of particular paths are modified with additional Kong Plugins. Based on https://github.com/Kong/kubernetes-ingress-controller/blob/c50f862b6dfb50d88ec0391b11b92866e87674cb/internal/dataplane/parser/translate_ingress.go#L27, all Exacts took precedence over the root ingress and it all worked like a charm.

With the migration to KIC 2.8 and removal of regex path detection, I have rewritten the main ingress to the following form:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-super-service
  annotations:
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
spec:
  ingressClassName: kong
  rules:
    - host: super.service.com
      http:
        paths:
        - path: /~/*
          pathType: ImplementationSpecific
          backend:
            service:
              name:  my-super-service
              port:
                number: 8080
```
but it made Kong match ALL incoming requests to this ingress, making other paths not available. It looks like now regex paths take precedence over Exact (highest prio so far). Am I right or I am missing something?

### Proposed Solution

Make Exact path priority great again :)
