### ISSUE TITLE
Question : Need to hide or redirection on URL

### ISSUE THREAD

**Issue by mmaryo** [Kong/kubernetes-ingress-controller#346]
Hello 

This is a question because I cannot find in documentation how to hide an url 

For example, I would like to hide /config/* urls 

Is there a solution with Kong ?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  tls:
    - hosts:
        - toto.app.com
      secretName: cert
  rules:
    - host:
      http:
        paths:
          - path: /
            backend:
              serviceName: myapp
              servicePort: 8080
```
