### ISSUE TITLE
Cannot get key-auth plugin to work on Mac M1

### ISSUE THREAD

**Issue by jeff-bonevich** [Kong/kubernetes-ingress-controller#3518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I follow the instructions to install KIC (based on minikube instructions) on a MacBookPro with M1 Max processor (running Monterray) and running Docker for Mac with Kubernetes enabled (Docker Desktop 4.5.0 (74594) / Kubernetes v1.22.5), I cannot get key-auth plugin to work when configured for an ingress to echo-service.  

### Expected Behavior

Instead I expect an actual 200 and valid echo result.

### Steps To Reproduce

1. Install KIC on a MacBrookPro with M1 Max processor running OSX Monterray and Docker Desktop for Mac with Kubernetes enabled:
```
k create -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/v2.8.0/deploy/single/all-in-one-dbless.yaml
```

2. Install echo-server for the M1:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
spec:
  ports:
    - port: 8080
      name: high
      protocol: TCP
      targetPort: 8080
    - port: 80
      name: low
      protocol: TCP
      targetPort: 8080
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo
    spec:
      containers:
        - image: k8s.gcr.io/echoserver-arm:1.8
          name: echo
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources: {}
```
3. Configure key-auth plugin:
```
apiVersion: v1
kind: Secret
metadata:
  name: kong-key-auth-credential
type: Opaque
stringData:
  kongCredType: key-auth
  key: <key>
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: kong-key-auth-consumer
  annotations:
    kubernetes.io/ingress-class: kong
username: someuser
credentials:
  - kong-key-auth-credential
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-key-auth-plugin
plugin: key-auth
```
4. Setup an ingress for echo server:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  annotations:
    konghq.com/plugins: kong-key-auth-plugin
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
    - host: localhost
      http:
        paths:
          - path: /echo
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo
                port:
                  number: 80
```
5. Port-forward to KIC:
```
k -n kong  port-forward service/kong-proxy 8000:80
```
6. Fetch the echo service URL:
```
curl -i http://localhost:8000/echo -H'apikey:<key>'
```

I get a 401:
```
HTTP/1.1 401 Unauthorized
Date: Thu, 09 Feb 2023 01:43:46 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 52
X-Kong-Response-Latency: 2
Server: kong/3.0.2

{
  "message":"Invalid authentication credentials"
}
```

### Kong Ingress Controller version

```
image: kong/kubernetes-ingress-controller:2.8.0
```

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/arm64"}
```

### Anything else?

I have also tried installing KIC via helm, and have tried the basic-auth plugin with the same/similar results.
