### ISSUE TITLE
Use bigger GKE VMs to prevent throttling and e2e tests timing out

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#3555]
It seems that our GKE e2e tests are taking longer to execute and sometimes are timing out.

Related PR: #3554

After inspecting the test clusters themselves it seems that the clusters that we create are using up  nearly 100% of allocatable CPU.

Having in mind that:

- we create 1 node clusters by default
- the nodes we use by default (implicitly) are `e2-medium` (2 vCPU, 4GB RAM)

```
  allocatable:
    cpu: 940m
    ephemeral-storage: "47060071478"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 2877136Ki
    pods: "110"
  capacity:
    cpu: "2"
    ephemeral-storage: 98831908Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 4022992Ki
    pods: "110"
```

We might consider bumping this, especially since some of the e2e tests deploy more than just 1 Pod with Gateway and KIC running.
