### ISSUE TITLE
proxy path doesn't work in dbless mode with ingress controller 

### ISSUE THREAD

**Issue by jdomag** [Kong/kubernetes-ingress-controller#359]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.5.0

**Kong or Kong Enterprise version**
1.2.1

### Kubernetes version
1.11.7
**paste `kubectl version` output**

k version                   
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:32:00Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**: helm
- **Others**:
installed with stable/kong chart in db less mode

### What happened
I've installed kong in dbless mode with ingress. I try to use KongIngress to redirect all traffic from /echo/ to /bar/echo as described in example "with Service resource" from: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-kongingress-resource.md
I use Ingress instead of Service. 

Ingress and KongIngress config:
```
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kongingress-echo
proxy:
  path: /bar/
route:
  strip_path: false 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
  annotations:
    configuration.konghq.com: kongingress-echo
spec:
  rules:
  - http:
      paths:
      - path: /echo
        backend:
          serviceName: echo
          servicePort: 80
```
When i hit my Loadbalancer for kong-proxy http://myip/echo/  i got following response from echo service:

```
Hostname: echo-d778ffcd8-r8z4p

Pod Information:
	node name:	ip-10-10-1-43
	pod name:	echo-d778ffcd8-r8z4p
	pod namespace:	default
	pod IP:	100.96.53.70

Server values:
	server_version=nginx: 1.12.2 - lua: 10010

Request Information:
	client_address=100.96.38.7
	method=GET
	real path=/echo/
	query=
	request_version=1.1
	request_scheme=http
	request_uri=http://my_ELB:8080/echo/
```
Based on real_path i see that strip_path parameter in KongIngress works just fine, but proxy: path:  doesn't. 
I saw suggestions to use https://docs.konghq.com/hub/kong-inc/serverless-functions/
but not sure what is the difference between the plugin and proxy: path from KongIngress.

### Expected behvaior
Echo client return real_path that contains "/bar/"

### Steps To Reproduce

1. Install kong in dbless mode with ingress enabled
2. Install echo service as described in https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-kongingress-resource.md
3. Configure Ingress and KongIngress as i described

**Comment by hbagdi** [comment]
Did you patch your service to add `configuration.konghq.com` annotation to your Kubernetes echo service as described below?

```
kubectl patch service echo -p '{"metadata":{"annotations":{"configuration.konghq.com":"demo-customization"}}}'
```

The `proxy` and `upstream` sections are associated with a Kubernetes Service, while the `route` part need to be associated with Ingress resource.

**Comment by jdomag** [comment]
Hi @hbagdi , 
I haven't seen in the documentation that proxy and upstream are associated with Service and route with Ingress, i though i can use either Ingress or Service.
Hence proxy path is associated with services how can i achieve below configuration:

http://load_balancer/url1/  --->> http://my_service/path_A/
http://load_balancer/url2/  --->> http://my_service/path_B/

I could create 2 separate services associated with the same pod, but it doesn't seems like following DRY methodology.

**Comment by hbagdi** [comment]
> I could create 2 separate services associated with the same pod, but it doesn't seems like following DRY methodology.

Although this solution works, I think it's important to take a step back and define the separate of service and Ingress.

What you are really looking for a way to change your path before you proxy the request to your service.
You should use URL [rewrite plugin](https://docs.konghq.com/hub/stone-payments/kong-plugin-url-rewrite/) or use serverless plugin in Kong to change the URL before it is sent upstream.

Usually, you want to do the following:

If you have the following:
```
http://load_balancer/url1/ --->> http://my_service/some/path/path_A/
http://load_balancer/url2/ --->> http://my_service/some/path/path_B/
```

`http://my_service/some/path/` belongs to your service configuration and then the customization of `path_A` or `path_B` belongs to your Ingress or Route definition. 

Hope this helps.
If your question is answered, please close this issue. Thanks!

**Comment by jdomag** [comment]
Hi @hbagdi, 
Thanks for your response. I've checked both plugins and i see both of them are barely documented plus rewrite plugin is a 3rd party maintained with last commit a year ago. 
Is this kong ingress behavior subject to a change in a future or there are great reasons why it was designed and implemented like this? Don't get me wrong, but trying the go from simple kong config like below:
```
 - name: my-service-path1
        host: my-service
        port: 8080
        path: /path1
        routes:
        - name: loadbalancer-url1
          paths: [/url1]
          strip_path: true
 - name: my-service-path2
        host: my-service
        port: 8080
        path: /path2
        routes:
        - name: loadbalancer-url2
          paths: [/url2]
          strip_path: true

```
I need to add Ingress, KongIngress and external plugin to make it work which introduces additional complexity.
