### ISSUE TITLE
Gateway discovery in the Helm chart does TLS encryption by default

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3618]
## Acceptance Criteria
- [ ] The example values.yaml for all the setups with gateway discovery enabled (#702) enable Admin API encryption by default (but with no authentication - just encryption with self-signed certs)

**Comment by randmonkey** [comment]
In default values we have 
```
  tls:
    # Enable HTTPS listen for the admin API
    enabled: true
    servicePort: 8444
    containerPort: 8444
```
in `env` section. So by default, helm charts does TLS encryption for admin APIs.
