### ISSUE TITLE
How to config hmac-auth plugin?

### ISSUE THREAD

**Issue by lionel1993** [Kong/kubernetes-ingress-controller#363]
**Kong Ingress controller version**
kong:1.2

**Kong or Kong Enterprise version**
kong:1.2

### Kubernetes version
1.11.5

### Steps To Reproduce
1.install plugin
```
echo "apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: hmacbin-auth
plugin: hmac-auth
config:
  enforce_headers: date,request-line
  algorithms: hmac-sha1,hmac-sha256
" | kubectl apply -n ai-test -f - 
```
2.provision user
```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: alice
username: alice
" | kubectl apply -n ai-test -f -
```
3.create credential
```
echo "apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: alice-hamc
consumerRef: alice
type: hmacauth_credentials
config:
  username: alice123
  secret: secret  
" | kubectl apply -n ai-test -f -
```
4.config ingress
```
kubectl -n ai-test patch ingress test-ingress \
-p '{"metadata":{"annotations":{"plugins.konghq.com":"hmacbin-auth\n"}}}'
```

But the plugin didn't work,Why?

![image](https://user-images.githubusercontent.com/54263115/63247475-b4c26600-c297-11e9-8e8e-e5866b791562.png)

thx

**Comment by hbagdi** [comment]
Please share the logs of the controller to inspect what is going wrong.

I cannot say for certain but it is likely that the following is the root cause:

In the following YAML: `enforce_headers` is a string, but Kong expects it to be an array of string:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: hmacbin-auth
plugin: hmac-auth
config:
  enforce_headers: date,request-line
  algorithms: hmac-sha1,hmac-sha256
```

If you change it to:
```yaml
config:
  enforce_headers:
  - date
  - request-lien
```

It should work.
