### ISSUE TITLE
test(conformance): fix `httpHeaderMatching` conformance test

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Context extracted from https://github.com/Kong/kubernetes-ingress-controller/issues/3305#issuecomment-1441018095.

The new test added in https://github.com/kubernetes-sigs/gateway-api/pull/1370 makes the single test HTTPRoute's ruleset this:
```
[2]
    matches:
    - headers:
      - name: version
        type: Exact
        value: two
...
[4]
    matches:
    - headers:
      - name: color
        type: Exact
        value: blue
      path:
        type: PathPrefix
        value: /
    - headers:
      - name: color
        type: Exact
        value: green
```

The corresponding spec language is https://github.com/kubernetes-sigs/gateway-api/blob/a3f769e5c690546140b6b9f0db5aea4d766b8f68/apis/v1beta1/httproute_types.go#L161-L163, i.e. that (ignoring higher-precedence tiebreakers that only apply when there are multiple HTTPRoutes) the lowest rule by array index wins.

KIC generates the following routes (among others) from the test HTTPRoute's rules:

```
$ curl -s 172.22.0.100:8001/routes/a1193384-1f5a-51c7-96a5-a9aae8ba7bc4 | jq
{
  "hosts": null,
  "created_at": 1677103911,
  "name": "httproute.gateway-conformance-infra.header-matching.3.0",
  "headers": {
    "color": [
      "blue"
    ]
  },
  "paths": [
    "/"
  ],
  "regex_priority": 0,
  "service": {
    "id": "3f637fd5-d492-5c33-b9e4-2b5925270c9c"
  },
  "id": "a1193384-1f5a-51c7-96a5-a9aae8ba7bc4",
}

$ curl -s 172.22.0.100:8001/routes/76b4eda4-ea3f-5212-8837-c58f5e6afed9 | jq
{                                                                                           
  "hosts": null,
  "created_at": 1677103911,
  "name": "httproute.gateway-conformance-infra.header-matching.1.0",
  "headers": {
    "version": [
      "two"
    ]
  },
  "paths": [
    "/"
  ],
  "regex_priority": 0,
  "service": {
    "id": "809e9da2-9a53-5e72-b3a2-71ba24da5aed"
  },
  "id": "76b4eda4-ea3f-5212-8837-c58f5e6afed9",
}
```

The test request ambiguously matches either rule because it includes both a version and color header with values matching the rule header matches, and includes nothing that violates a rule match requirement.
We need to reflect the `HTTPRoute` matching precedence in Kong.

### Proposed Solution

The new Expression router we plan to introduce (https://github.com/Kong/kubernetes-ingress-controller/issues/3730) would provide a way of defining priorities on routes, i.e., we could reflect the matches priority in Kong.

### Acceptance Criteria

- [ ] the HTTPHeaderMatching conformance test is enabled and successful.
