### ISSUE TITLE
Support secretkeypath support for plugin configuration

### ISSUE THREAD

**Issue by ilyesAj** [Kong/kubernetes-ingress-controller#3666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

k8s secret are base64 encoded and not encrypted. for some critical workload, we need to use [Kubernetes Secrets Store CSI Driver](https://secrets-store-csi-driver.sigs.k8s.io/#kubernetes-secrets-store-csi-driver) to store secrets securely and mount them as volumes . 

### Proposed Solution

plugins should be able to import credentials from mounted location in ìngress-controller`or `proxy`pod 

as-is :
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: users
credentials:
  - apikey
username: ilyes
```
suggested solution:
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: users
credentials:
  secretkeypath:
  - /etc/secrets/kong/apikey
username: ilyes
```
where `secretkeypath` is mounted on `proxy` pod as a volume

### Acceptance Criteria

- [ ] as a user, I can import credentials/secrets from a mounted volume in the `proxy` pod
