### ISSUE TITLE
How to config rate-limit plugin on a combination of service/route/+consumer?

### ISSUE THREAD

**Issue by lionel1993** [Kong/kubernetes-ingress-controller#367]
**Kong Ingress controller version**
![image](https://user-images.githubusercontent.com/54263115/63513097-e9dceb80-c517-11e9-9b14-38145fcd550b.png)

### What happened
The rate-limiting plugin only works for the specified ingress,no matter what the user

### Expected behvaior

The rate-limiting plugin only works  for the specified user and the specified ingress

### Steps To Reproduce
1.install rate-limiting plugin and key-auth plugin
```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-rate-limit
consumerRef: user1
config:
  minute: 5
  policy: redis
  redis_host: redis
plugin: rate-limiting
" | kubectl apply -n ai-test -f  - 
```

2.create user and credential
```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user1
username: user1
" | kubectl apply -n ai-test -f - 

  
echo "
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: user1-key
consumerRef: user1
type: key-auth
config:
  key: user1-secret1
  " | kubectl apply -n ai-test -f -  
  
 
echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user2
username: user2
" | kubectl apply -n ai-test -f - 
  
  
echo "
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: user2-key
consumerRef: user2
type: key-auth
config:
  key: user2-secret
  " | kubectl apply -n ai-test -f -  

```
3.associate rate-limiting plugin with user1
```
kubectl -n ai-test patch KongConsumer user1 \
-p '{"metadata":{"annotations":{"plugins.konghq.com":"my-rate-limit\n"}}}' 
```

4.add annotations to service(ingress)
```
kubectl -n ai-test patch ingress aigeomancyjava-test-ingress \
-p '{"metadata":{"annotations":{"plugins.konghq.com":"httpbin-auth,my-rate-limit\n"}}}'   
```

5.call url
*  test user1
![image](https://user-images.githubusercontent.com/54263115/63513502-04fc2b00-c519-11e9-83cb-9f3c06552d73.png)

* test user2
![image](https://user-images.githubusercontent.com/54263115/63513550-29580780-c519-11e9-8f8a-55874c92789c.png)

### in addition
While,I saw it on konga
![image](https://user-images.githubusercontent.com/54263115/63513606-4bea2080-c519-11e9-96ea-eb706be5ab5c.png)

thx for help!
