### ISSUE TITLE
Ingresses don't get an IP, when `spec.tls[].secretName` is missing - 2.8.x

### ISSUE THREAD

**Issue by drdkmkkr** [Kong/kubernetes-ingress-controller#3711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ingresses don't get an IP, when `spec.tls[].secretName` is missing.
No apparent error is logged regarding this.

But when spec.tls[].secretName is defined, the ingress get an IP assigned.

### Expected Behavior

Ingresses do not require `spec.tls[].secretName` to be defined. 

Prior to 2.8.x, it was possible to use the default certificate by defining following to Kong (tested in 2.7.0)
```
env:
  ssl_cert: /etc/secrets/.../tls.crt
  ssl_cert_key: /etc/secrets/.../tls.key
```
And then we didn't need to define `spec.tls[].secretName` in all ingresses.

### Steps To Reproduce

1. Add an ingress with `spec.tls[].hosts[] = host`, like:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-example-ingress
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  tls:
  - hosts:
      - https-example.foo.com
  rules:
  - host: https-example.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
```
2. See no IP is provided for the ingress
3. Now add `spec.tls[].secretName = secretName`, like
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-example-ingress
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  tls:
  - hosts:
      - https-example.foo.com
    secretName: testsecret-tls # This is new
  rules:
  - host: https-example.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
```
4. See an IP now is provided for the ingress

### Kong Ingress Controller version

```shell
v2.8.x
```

### Kubernetes version

1.24
