### ISSUE TITLE
Path matching failed

### ISSUE THREAD

**Issue by chxcode** [Kong/kubernetes-ingress-controller#3789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i write an ingress yaml file，there are two sets of paths inside, with rules.

```yaml

...

  - http:
      paths:
      - backend:
          service:
            name: AService
            port:
              number: 80
        path: /~/api/v2/(.*)
        pathType: ImplementationSpecific
  - http:
      paths:
      - backend:
          service:
            name: BService
            port:
              number: 80
        path: /~/api/v2/(media/.*)
        pathType: ImplementationSpecific

...

```

But all requests for /api/v2/media/xxxx have been sent to AService.

### Expected Behavior

I want all requests from /api/v2/media/xxxx to be sent to BService

### Kong Ingress Controller version

```shell
v2.8.0
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.5-tke.12", GitCommit:"95c3fe5ca0c07374aaf4ef4af1aad0a662a1a5f0", GitTreeState:"clean", BuildDate:"2023-02-28T05:39:31Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```
