### ISSUE TITLE
Kong requests-transfomer plugin not rerouting

### ISSUE THREAD

**Issue by sinannoureddine** [Kong/kubernetes-ingress-controller#3801]
I am trying to use KONG plugin "Request-transformer" to reroute calling API endpoint

For example, I have a microservice deployed on EKS cluster with the following endpoint "kong.serviceB.com/admin/getUsers". This Endpoint returns all signed-up users for instance.

I want to call that endpoint using the following link "**_kong.serviceB.com/users_**" and I want Kong to reroute this endpoint to "**_kong.serviceB.com/admin/getUsers_**".

First step, i created an ingress routing configuration for the endpoint "kong.serviceB.com/users":

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: route-serviceB-users
  annotations:
    konghq.com/plugins: request-transformer-plugin
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - host: kong.serviceB.com
    http:
      paths:
      - path: /users
        pathType: Exact
        backend:
          service:
            name: serviceB-aws
            port:
              number: 80
```
Step 2, i created Kong Transfomer-request yaml file to replace the endpoints:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-plugin    
config:
    replace:
      uri:
      - /admin/getusers
plugin: request-transformer
```

I tried this approach but i get a 404 error on Postman when i call kong.serviceB.com/users. It works when i call **_kong.serviceB.com/admin/getUsers_**

Any idea what am i doing wrong here? and how can i do that task?
