### ISSUE TITLE
How can I configure service/path?

### ISSUE THREAD

**Issue by subicura** [Kong/kubernetes-ingress-controller#39]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Kong Ingress controller version**:
0.0.3

**Kubernetes version** (use `kubectl version`):
1.9.6

**Environment**:
Docker for mac

**What happened**:
I can't configure service/path.
I want to "http://localhost/sample" to "http://sample-http/external".

**What you expected to happen**:
Use Ingress or KongIngress .

Ingress (ingress.kubernetes.io/rewrite-target is not working)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-http
  annotations:
    ingress.kubernetes.io/rewrite-target: "/external"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /sample
        backend:
          serviceName: sample-http
          servicePort: 80
```

KongIngress (service is not working)

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: sample-http
service:
  path: /external
route:
  strip_path: true
```

**Comment by subicura** [comment]
https://github.com/Kong/kubernetes-ingress-controller/blob/master/internal/ingress/controller/kong.go#L245

It needs pull request?

**Comment by daiyoung** [comment]
You can try to add an annotation named "request-transformer.plugin.konghq.com" to the Ingress. see more info in https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/minikube.md

**Comment by subicura** [comment]
@daiyoung thanks for reply!

But, I want to tranform "path".

For example, I create 2 api(service/route).

- 'http://localhost/user-service/v1/users' => 'http://kube-user-service/external/v1/users'
- 'http://localhost/report-service/v1/reports' => 'http://kube-report-service/external/v1/reports'

Is it possible to use request-transformer?

**Comment by daiyoung** [comment]
@subicura kubernetes-ingress-controller for kong is released just a few days, the document is not very perfect. I also get some problems,like I can't create the jwt credential bound one consumer.
Yours issue is same to me, I will try again and then tell you.

**Comment by elboletaire** [comment]
Sorry to revive this post but I can't get this working :confused: 

I'm trying to configure a service using the `/doc` path.

~~~yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: html2doc-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /doc
        backend:
          serviceName: html2doc-svc
          servicePort: 80
~~~

My service receives calls at `/{format}` where format can be, among others, `pdf`.

~~~yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: html2doc-kongingress
proxy:
  path: /
route:
  strip_path: true
~~~

Even after adding the above KongIngress controller nothing seems to change. When I call `/doc` I can see in my pod logs that it's trying to access `/doc`:

![imatge](https://user-images.githubusercontent.com/153305/50169207-64040300-02ed-11e9-83d0-b5065131006a.png)

Am I doing something wrong? BTW sorry to bother you, I'm kinda newbie in k8s....

**Comment by elboletaire** [comment]
Ok, I got it... the Ingress controller and the KongIngress controller need to have the same `metadata.name`. BTW if anyone can confirm me I'm not doing something evil, I'll thank them.

**Comment by hbagdi** [comment]
@elboletaire That's correct.
Reference: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/custom-resources.md#kongingress

**Comment by Raghavendarlokineni** [comment]
> @elboletaire That's correct.
> Reference: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/custom-resources.md#kongingress

this seems to be a broken link now

**Comment by hbagdi** [comment]
> this seems to be a broken link now

Here is the new one: 
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/concepts/custom-resources.md

**Comment by zeusro** [comment]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample-http
  annotations:
    konghq.com/strip-path: "true"    
    kubernetes.io/ingress.class: kong    
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /sample
        backend:
          serviceName: sample-http
          servicePort: 80
```
