### ISSUE TITLE
Translation Event not produced for some configurations which result in Gateway returning 500

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#3928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some configurations can cause KIC to not produce Events (with reason `KongConfigurationApplyFailed`) which should be produced.

### Expected Behavior

In case of an incorrect configuration, an Event with `KongConfigurationApplyFailed` is produced indicating what has failed.

### Steps To Reproduce

1. Apply the following configuration

    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: nginx
      name: nginx-sample-1
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx-sample-1
      template:
        metadata:
          labels:
            app: nginx-sample-1
        spec:
          containers:
          - image: nginx
            name: nginx-sample-1
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80
              name: http
    ---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        konghq.com/methods: GET
        kubernetes.io/ingress.class: kong
      name: nginx-sample-1
      namespace: default
    spec:
      rules:
      - http:
          paths:
          - backend:
              service:
                name: nginx-sample-1
                port:
                  number: 80
            path: /sample/1
            pathType: ImplementationSpecific
    ---
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        ingress.kubernetes.io/service-upstream: 'true'
        konghq.com/plugins: nginx-sample-1 #,nginx-sample-1-rate # removing this breaks Kong but it does not validate on webhook
      name: nginx-sample-1
      namespace: default
    spec:
      ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
      selector:
        app: nginx-sample-1
    ---
    apiVersion: configuration.konghq.com/v1
    config:
      allow:
      - nginx-sample-1
      - app
      hide_groups_header: false
    kind: KongPlugin
    metadata:
      name: nginx-sample-1
      namespace: default
    plugin: acl
    ---
    apiVersion: configuration.konghq.com/v1
    config:
      allow:
      - nginx-sample-2
      - app
      hide_groups_header: false
    kind: KongPlugin
    metadata:
      name: nginx-sample-2
      namespace: default
    plugin: acl
    ---
    apiVersion: configuration.konghq.com/v1
    config:
      fault_tolerant: true
      hide_client_headers: false
      limit_by: consumer
      policy: local
      second: 2000
    kind: KongPlugin
    metadata:
      name: nginx-sample-1-rate
      namespace: default
    plugin: rate-limiting
    ---
    apiVersion: v1
    data:
      kongCredType: YmFzaWMtYXV0aA==
      password: NmVmNzI4ZGUtYmE2OC00ZTU5LWFjYjktNmU1MDJjMjhhZTBi
      username: Nzc0Zjg0NDYtNjQyNy00M2Y5LTk5NjItY2U3YWI4MDk3ZmU0
    kind: Secret
    metadata:
      name: app-cred
      namespace: default
    ---
    apiVersion: v1
    data:
      group: YXBw
      kongCredType: YWNs
    kind: Secret
    metadata:
      name: app-acl
      namespace: default
    ---
    apiVersion: configuration.konghq.com/v1
    config:
      fault_tolerant: true
      hide_client_headers: false
      limit_by: consumer
      policy: local
      second: 2000
    kind: KongPlugin
    metadata:
      name: nginx-sample-2-rate
      namespace: default
    plugin: rate-limiting
    ---
    apiVersion: configuration.konghq.com/v1
    credentials:
    - app-acl
    - app-cred
    kind: KongConsumer
    metadata:
      annotations:
        kubernetes.io/ingress.class: kong
        konghq.com/plugins: nginx-sample-1-rate,nginx-sample-2-rate # This is necessary for nginx-sample-1 Service to break Kong's config
      name: app
      namespace: default
    username: 774f8446-6427-43f9-9962-ce7ab8097fe4
    ```

1. Observe in KIC logs an error about pushing configuration

    ```
     time="2023-04-21T16:48:52Z" level=error msg="could not update kong admin" error="performing update for https://10.244.0.26:8444 failed: failed posting new config to /config: got status code 500\nperforming update for https://10.244.0.27:8444 failed: failed posting new config to /config: got status code 500" subsystem=dataplane-synchronizer
    ```

1. Observe errors logs in Gateway about internal server error

    ```
    2023/04/21 16:49:43 [error] 1204#0: *299 [lua] api_helpers.lua:516: handle_error(): /usr/local/share/lua/5.1/lapis/application.lua:424: /usr/local/share/lua/5.1/kong/db/errors.lua:790: attempt to index local 'entity' (a string value)
    stack traceback:
          /usr/local/share/lua/5.1/kong/db/errors.lua: in function 'add_entity_errors'
          /usr/local/share/lua/5.1/kong/db/errors.lua:797: in function 'add_entity_errors'
          /usr/local/share/lua/5.1/kong/db/errors.lua:853: in function 'flatten_errors'
          /usr/local/share/lua/5.1/kong/db/errors.lua:970: in function 'declarative_config_flattened'
          /usr/local/share/lua/5.1/kong/api/routes/config.lua:136: in function 'fn'
          /usr/local/share/lua/5.1/kong/api/api_helpers.lua:287: in function </usr/local/share/lua/5.1/kong/api/api_helpers.lua:270>
    stack traceback:
          [C]: in function 'error'
          /usr/local/share/lua/5.1/lapis/application.lua:424: in function 'handler'
          /usr/local/share/lua/5.1/lapis/application.lua:146: in function 'resolve'
          /usr/local/share/lua/5.1/lapis/application.lua:183: in function </usr/local/share/lua/5.1/lapis/application.lua:181>
          [C]: in function 'xpcall'
          /usr/local/share/lua/5.1/lapis/application.lua:189: in function 'dispatch'
          /usr/local/share/lua/5.1/lapis/nginx.lua:231: in function 'serve'
          /usr/local/share/lua/5.1/kong/init.lua:1572: in function 'admin_content'
          content_by_lua(nginx-kong.conf:320):2: in main chunk, client: 10.244.0.28, server: kong_admin, request: "POST /config?check_hash=1&flatten_errors=1 HTTP/2.0", host: "10.244.0.26:8444"
    10.244.0.28 - - [21/Apr/2023:16:49:43 +0000] "POST /config?check_hash=1&flatten_errors=1 HTTP/2.0" 500 42 "-" "Go-http-client/2.0"
    ```

### Kong Ingress Controller version

```shell
2.9.3
```
