### ISSUE TITLE
Route strip_path reset

### ISSUE THREAD

**Issue by Gadnief** [Kong/kubernetes-ingress-controller#395]
### Summary

Im setting the strip_path viariable in kong ingress controller to false for a route. After a while it is automatically set back to true.

**Kong Ingress controller version**
0.5.0

**Kong or Kong Enterprise version**
1.2

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: Azure AKS
- **Install tools**: plain yml

### What happened
To set the strip_path variable on a route i port-forwarded the kong-ingress-controller service and made a PATCH on the correct route. The Ingress behaves how it should until the ingress-controller synced to kong as said in the log with: 
```I0912 05:24:37.887449       1 controller.go:128] successfully synced configuration to Kong```

After that the strip_path attribute is set back to true. I already tried to made the configurations directly in the service and ingress yml:

Ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibanaingress
  namespace: logging
  annotations:
    configuration.konghq.com: kibanaconfig
spec:
  rules:
  - http:
      paths:
      - path: /kibana
        backend:
          serviceName: kibana
          servicePort: 5601
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kibanaconfig
route:
  strip_path: false
  protocols:
  - http
  - https
```

Service:
```
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
  annotations:
    configuration.konghq.com: kibanaconfig
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
```

Output after PATCH:
```
{
    "id": "aad65176-6890-4dbf-ab42-5c5a0c81786d",
    "tags": [
        "managed-by-ingress-controller"
    ],
    "paths": [
        "/kibana"
    ],
    "destinations": null,
    "protocols": [
        "http",
        "https"
    ],
    "created_at": 1568265271,
    "snis": null,
    "hosts": null,
    "name": "logging.kibanaingress.00",
    "preserve_host": true,
    "regex_priority": 0,
    "strip_path": false,
    "sources": null,
    "updated_at": 1568265391,
    "https_redirect_status_code": 426,
    "service": {
        "id": "3fca6451-ed38-44a7-ba78-fc3748bb9d53"
    },
    "methods": null
}
```

Output after sync:
```
{
    "id": "aad65176-6890-4dbf-ab42-5c5a0c81786d",
    "tags": [
        "managed-by-ingress-controller"
    ],
    "paths": [
        "/kibana"
    ],
    "destinations": null,
    "protocols": [
        "http",
        "https"
    ],
    "created_at": 1568265871,
    "snis": null,
    "hosts": null,
    "name": "logging.kibanaingress.00",
    "preserve_host": true,
    "regex_priority": 0,
    "strip_path": true,
    "sources": null,
    "updated_at": 1568265871,
    "https_redirect_status_code": 426,
    "service": {
        "id": "3fca6451-ed38-44a7-ba78-fc3748bb9d53"
    },
    "methods": null
}
```

### Expected behvaior
strip_path still on false

### Steps To Reproduce

1. port-forward ingress-controller service from 8001 to 8001
2. PATCH route with ```{
    "strip_path": false
}```
3. Wait for sync
