### ISSUE TITLE
Create e2e/integration test to cover Service with multiple EnpointSlices

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

PR https://github.com/Kong/kubernetes-ingress-controller/pull/3997 eradicated `Endpoints`. KIC now relies on `EndpoinSlice`, setting proper routing is core function of KIC, so it should be tested well. 

`EndpointSlice` by default handles 100 endpoints (it can be adjusted). `Service` can have multiple `EndpointSlice`. Test that `Service` with multiple `EndpointSlice` that have multiple endpoints is handled correctly. 

### Proposed Solution

- [K8s controller manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) has `--max-endpoints-per-slice` flag to configure number of allowed endpoints per EndpointSlice can be adjusted
- Kind environment can be configured with 
    ```yml
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    kubeadmConfigPatches:
    - |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      controllerManager:
        extraArgs:
          max-endpoints-per-slice: "2"
    ```
    on such cluster e.g. creating `Deployment` with 5 replicas and `Service` results in creation of 3 `EndopointSlice`
- Write a test that verify routing by Kong traffic to every `Pod` exposed by such configuration

### Additional information

- maybe some enchantments in KTF needs to be done to run Kind with custom config comfortably

### Acceptance Criteria

- [ ] test that verifies proper working of `Service` with multiple `EndopointSlice`with multiple `Endpoints` on K8s cluster
