### ISSUE TITLE
Store + send last known good configuration

### ISSUE THREAD

**Issue by mheap** [Kong/kubernetes-ingress-controller#4048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

New DP pods cannot spin up when there is an invalid configuration on the k8s API server. This means that scale out events for customers lead to errors.

### Proposed Solution

- Only support deployments with Gateway Discovery
- Store the last known good config and apply that if the current state is invalid (potentially only when the DP's config hash is empty?)
- If I scale up Service pods, they do not need to be added to the list of active upstreams in my Kong configuration

### Additional information

Example ingress to break your config:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /~/demo/**
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo
                port:
                  number: 1027
```

### Acceptance Criteria

- [ ] As a user I can scale up my DP pods and have them handle traffic when I have an invalid configuration on the k8s API server
- [ ] As a user I have documentation on how to enable `service-upstream` if I need service scaling to be autodetected when a bad config is stored on the k8s API server
