### ISSUE TITLE
KongIngress CRD paths not respected

### ISSUE THREAD

**Issue by dwin** [Kong/kubernetes-ingress-controller#405]
### Summary

Adding `paths` to `KongIngress` CRD resource has no affect on configuration, but this limitation is not documented, here: [custom-resources.md#kongingress](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/concepts/custom-resources.md#kongingress) or here: [using-kongingress-resource.md](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-kongingress-resource.md).

I did find a workaround, but this is confusing and it's not clear if this is the way it is intended to work.

**Kong Ingress controller version**
`0.5.0`

**Kong or Kong Enterprise version**
`1.3`

### Kubernetes version

`v1.14.6-eks-5047ed`

### Environment

- **Cloud provider or hardware configuration**: `AWS EKS`
- **OS** (e.g. from /etc/os-release): `Amazon Linux 2`
- **Kernel** (e.g. `uname -a`): `4.14.128-112.105.amzn2.x86_64`
- **Install tools**: `eksctl` & `helm`
- **Others**:

### What happened

Using the `KongIngress` CRD below (`example.kong_ingress.yaml`), I expected the service/route configuration to have the paths added to the service routes based on [https://docs.konghq.com/1.3.x/admin-api/#add-route](https://docs.konghq.com/1.3.x/admin-api/#add-route) but instead I see the output shown in `route.json`.

`example.ingress.yaml`:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: ingress-config-name
    external-dns.alpha.kubernetes.io/hostname: my.host.tld
    kubernetes.io/ingress.class: kong
  labels:
    app.kubernetes.io/managed-by: Tiller
  name: pro-wordpress
  namespace: core-staging
spec:
  rules:
  - host: my.host.tld
    http:
      paths:
      - backend:
          serviceName: pro-wordpress
          servicePort: 80
        path: /
```

`example.kong_ingress.yaml`:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ingress-config-name
  namespace: my-namespace
route:
  strip_path: false
  paths:
    - /news
    - /blog
  regex_priority: 10
  preserve_host: true
  https_redirect_status_code: 301
  protocols:
    - https
```

`route.json`:
```json
{
  "id": "6758299f-aa69-4f9b-a682-8b486b4e623b",
  "tags": [
    "managed-by-ingress-controller"
  ],
  "updated_at": 1568862390,
  "destinations": null,
  "headers": null,
  "protocols": [
    "https"
  ],
  "created_at": 1568862390,
  "snis": null,
  "service": {
    "id": "8877d34e-f926-412f-8041-8f15c295114a"
  },
  "name": "my.service.00",
  "preserve_host": true,
  "regex_priority": 25,
  "strip_path": false,
  "sources": null,
  "paths": [
    "/"
  ],
  "https_redirect_status_code": 301,
  "hosts": [
    "my.host.example"
  ],
  "methods": null
}
```
### Expected behvaior

Expected `paths` entered in `KongIngress` CRD to be reflected in configuration.

### Steps To Reproduce

See above examples.

### Other Notes

I was able to **workaround** this issue by adding additional paths to the Kubernetes Ingress, as shown below:

`working.ingress.yaml`:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: ingress-config-name
    external-dns.alpha.kubernetes.io/hostname: my.host.example
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: my.host.example
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
        path: /news
      - backend:
          serviceName: my-service
          servicePort: 80
        path: /blog
```
