### ISSUE TITLE
How to enable access only on port 443 with https

### ISSUE THREAD

**Issue by smartaquarius10** [Kong/kubernetes-ingress-controller#4095]
Hello,

I have tried this network policy in Azure kubernetes but kong is still accessible on port 80 with http. Can anyone suggest why kong is not behaving as per network policy and how to enable only 443 port. Is it not possible to apply network policy on ingress-controllers

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-kong.policy
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 443
  egress: 
  - ports:    
    - port: 443
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
```
