### ISSUE TITLE
Support a `konghq.com/rewrite` annotation

### ISSUE THREAD

**Issue by mheap** [Kong/kubernetes-ingress-controller#4308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We've had a customer request to implement https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/rewrite/README.md as a way to manage URI rewriting.

Using the `request-transformer` plugin directly is not an option here. They are looking for syntactic sugar

### Proposed Solution

- Generate a `request-transformer` plugin and attach it to every route in the specified ingress. 
- Use `uri.replace` to implement the rewrite
- Release behind a feature gate as Alpha quality for the first release

### Additional information

Proposed UX:

```yaml
$ echo '
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  annotations:
    konghq.com/rewrite: "/demo/$1"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /~/api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo
                port:
                  number: 1027
' | kubectl create -f -
```

Would result in the following config (some items removed for brevity):

```yaml
_format_version: "3.0"
services:
- enabled: true
  host: echo
  plugins:
  - config:
      replace:
        uri: /request/demo/$(uri_captures[1])
    enabled: true
    name: request-transformer
  routes:
  - paths:
    - ~/api/(.*)
```

It's important to note that request transformer is 1-indexed. `$(uri_captures[0])` captures the whole request URI

### Acceptance Criteria

- [ ] As a user I can rewrite the URI of an incoming request using an annotation
- [ ] As a user I can use number indexed capture groups when building my upstream URI
