### ISSUE TITLE
Redundant error logged constantly when KongConsumer and credential Secret is misconfigured

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**The first example**, for the below
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: key-auth
username: consumer-1
credentials:
  - the-missing-one
```
where `KongConsumer` references in the `credentials` field non-existing K8s `Secret` **every 3 seconds** the below is logged

```log
ERRO[2016] failed to fetch secret          error="Secret default/the-missing-one not found" kongconsumer_name=consumer-1 kongconsumer_namespace=default secret_name=the-missing-one secret_namespace=default
ERRO[2016] failed to fetch KongPlugin      error="no KongPlugin or KongClusterPlugin was found" kongplugin_name=key-auth kongplugin_namespace=default
```

**Second example**, for the below
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: key-auth
username: consumer-1
credentials:
  - secret-key
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
data:
  foo: Yy0x
  bar: a2V5LWF1dGg=
```

where K8s `Secret` that is passed to the `credentials` field does not follow the expected format for the section `data`
```yaml
  key: Yy0x
  kongCredType: a2V5LWF1dGg=
```
and no existing plugin `key-auth` is referenced **every 3 seconds** the below is logged
```log
ERRO[2856] failed to provision credential          error="invalid credType: " kongconsumer_name=consumer-1 kongconsumer_namespace=default secret_name=secret-key secret_namespace=default
ERRO[2856] failed to provision credential          error="invalid credType: " kongconsumer_name=consumer-1 kongconsumer_namespace=default secret_name=secret-key secret_namespace=default
ERRO[2856] failed to fetch KongPlugin              error="no KongPlugin or KongClusterPlugin was found" kongplugin_name=key-auth kongplugin_namespace=default
```

**Conclusion**
Those log entries unnecessarily consume the resources of a monitoring system. Moreover K8s `event` is not produced for those situations.

Other situations may exist for such cases, please verify them.

### Expected Behavior

KIC does not spam with redundant log messages and respective K8s `event` is generated.

To consider: when deciding to leave the log entry for the first appearance of such misconfiguration maybe do not log it with an error level (because KIC operates normally)

### Steps To Reproduce

```markdown
1. Apply one of the examples YAMLs from the **Current behavior** section
2. Observe K8s events and logs from KIC
```

### Kong Ingress Controller version

```shell
`main` branch
```

### Kubernetes version

```shell
Irrelevant
```
