### ISSUE TITLE
Associating some KongPlugins with KongConsumers results in broken configuration for Kong Gateway

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Plugins can be global or scoped, different plugins allow different configuration
- e.g.  [key-auth](https://docs.konghq.com/hub/kong-inc/key-auth/) or [jwt](https://docs.konghq.com/hub/kong-inc/jwt/) can be scoped to
	- Services
	- Routes
- e.g. [rate-limiting](https://docs.konghq.com/hub/kong-inc/rate-limiting/) or [request-termination](https://docs.konghq.com/hub/kong-inc/request-termination/), can be scoped to
	- Services
	- Routes
	- Consumers

KIC does not prevent assigning any plugin to a consumer with [konghq.com/plugins annotation](https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/custom-resources/#kongplugin). It results in a broken config sent by KIC to Gateway - **every 3 seconds** the below is logged
```log
ERRO[0021] failed parsing resource errors    error="could not unmarshal config error: json: cannot unmarshal object into Go struct field ConfigError.flattened_errors of type []sendconfig.FlatEntityError" update_strategy=InMemory url="https://localhost:8444"
ERRO[0021] could not update kong admin       error="performing update for https://localhost:8444 failed: failed posting new config to /config: got status code 400" subsystem=dataplane-synchronizer
```
Two distinct issues can be spotted
- invalid configuration sent to Gateway, KIC receives `400`
- error during the parsing response from Gateway to present it in an error message

Body of the `400` response from Gateway looks like that
```json
{
    "fields": {},
    "flattened_errors": {},
    "name": "invalid declarative configuration",
    "message": "declarative config is invalid: {}",
    "code": 14
}
```

### Expected Behavior

Some mechanism prevents such misconfiguration, such as a proper message logged, and not being spammed with logs.

### Steps To Reproduce

1. Apply the below - assigning `KongPlugin` `key-auth` to `KongConsumer`
```yml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: key-auth
username: consumer-1
credentials:
  - consumser-1
---
apiVersion: v1
kind: Secret
metadata:
  name: consumser-1
type: Opaque
data:
  key: Yy0x
  kongCredType: a2V5LWF1dGg=
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
  annotations:
    kubernetes.io/ingress.class: kong
config:
  key_names:
    - apikey
  anonymous: anonymous
  hide_credentials: true
plugin: key-auth
```

2. Observe logs from KIC

### Kong Ingress Controller version

```shell
current `main`
```

### Kubernetes version

```shell
irrelevant
```
