### ISSUE TITLE
{"message":"failure to get a peer from the ring-balancer"} when trying to expose Admin API

### ISSUE THREAD

**Issue by WoodyFleurant** [Kong/kubernetes-ingress-controller#434]
### Summary

**Kong Ingress controller version**
0.6.1

### Kubernetes version

v1.13.6

### Environment

- **Google Cloud**:
- **OS** (e.g. containerOS):

### What happened

When trying to expose Kong Admin API via a service I get {"message":"failure to get a peer from the ring-balancer"} when trying to access it from curl

### Expected behvaior

It should work right ?

### Steps To Reproduce

1. Install Kong Ingress controller from documentation
2. Create a new service

```
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: kong
spec:
  ports:
  - name: high
    port: 8080
    protocol: TCP
    targetPort: 8001
  - name: admin
    port: 80
    protocol: TCP
    targetPort: 8001
  - name: admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: ingress-kong
---
```
3. Create an Ingress

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-admin-api
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - host: kong.MYDOMAIN.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: kong-admin
          servicePort: admin
---
```
