### ISSUE TITLE
IPv6 port appended to endpoint, causing connection failures.

### ISSUE THREAD

**Issue by pnathan** [Kong/kubernetes-ingress-controller#4369]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- Note that this Forum thread describes this behavior as well: https://discuss.konghq.com/t/kong-confuse-the-target-ip-in-ipv6/10979/2

### Current Behavior

The IPv6 endpoint has the Port inappropriately appended to it and connection issues result.  This is a sample error from the log:

```
2023-07-18 11:58:36 | 2023-07-18T18:58:36.180124312Z stderr F 2023/07/18 18:58:36 [error] 1259#0: *1304 connect() failed (113: No route to host) while connecting to upstream, client: 2600:1f13:57a:9d06:a0cd:7272:c2da:a538, server: kong, request: "GET / HTTP/1.1", upstream: "http://[2600:1f13:57a:9d05:b0b2:0:6:8080]:8000/", host: "hello.redacted"
-- | --
```

The final octet of the IP is properly `6`, but instead the port (see endpoint slice) is appended.

The EndpointSlice: 

```
hello-node-h2rsp   IPv6          8080    2600:1f13:57a:9d05:b0b2::6   21h
```

Note that the Port is 8080.

I believe that internal/dataplane/parser/parser.go#L846 is the likely cause of this.
```
	for _, endpoint := range endpoints {
		target := kongstate.Target{
			Target: kong.Target{
				Target: kong.String(endpoint.Address + ":" + endpoint.Port),
			},
		}
		targets = append(targets, target)
	}
```

In the case of IPv6, brackets should surround the address before the Port.

I am not sure where the log's `8000` comes from, however.

### Expected Behavior

I expect that connections are properly routed to the pod's correct IP and port.

### Steps To Reproduce

```markdown
1. Set up an EKS cluster with IPv6 only. This must not have any Internal ipv4 routing!
   (note that we have not verified this bug on non-EKS clusters). We also have https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html installed. 
2. `helm upgrade kong kong  --install --create-namespace  --repo https://charts.konghq.com --version 2.25.0  -n ingress -f kong-2.25-values.yaml`
3. `kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080`
4. `kubectl expose deployment hello-node --type=ClusterIP --port=8080`
5. Validate with `kubectl port-forward svc/hello-node 8080` and curl'ing localhost:8080
6. apply ingress file as below.


apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  ingressClassName: kong
  rules:
  - host: hello.redacted
    http:
      paths:
      - backend:
          service:
            name: hello-node
            port:
              number: 8080
        path: /
        pathType: Prefix
```

7. from an IPv6-routing node, `curl  -v6 hello.redacted` and observe the outcome.
```


### Kong Ingress Controller version

```shell
kong/kubernetes-ingress-controller:2.10
kong 3.3


chart 2.25 as per above.
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.15-eks-a5565ad", GitCommit:"af0b16a331376384fe84445fe2f8d4cb468b4148", GitTreeState:"clean", BuildDate:"2023-06-16T17:35:37Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

```

### Anything else?

relevant values file from above:

```yaml
autoscaling:
  enabled: true
  maxReplicas: 24
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  minReplicas: 3
env:
  dns_order: LAST,SRV,A,AAAA,CNAME
  nginx_proxy_client_body_timeout: 600s
  nginx_proxy_proxy_buffer_size: 160k
  nginx_proxy_proxy_buffers: 64 160k
  controller_log_level: "debug"
ingressController:
  installCRDs: false
  env:
    controller_log_level: "debug"
  ingressClass: kong

proxy:
  address: '[::]'
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
  type: LoadBalancer
replicaCount: "3"
resources:
  limits:
    cpu: "2"
    memory: 1.5Gi
  requests:
    cpu: "2"
    memory: 20Mi
status:
   address: '[::]'
```
