### ISSUE TITLE
Modifying a route configured with Kubernetes using kong REST API get rollbacked

### ISSUE THREAD

**Issue by WoodyFleurant** [Kong/kubernetes-ingress-controller#438]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Using Kubernetes ingress controller I configured an ingress and service

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: konga
  name: konga-svc
  namespace: kong
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 1337
  selector:
    app: konga
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: konga
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - host: konga.mydomain.net
    http:
      paths:
      - path: /
        backend:
          serviceName: konga-svc
          servicePort: http
```

Then if I modify this route to only be accessible from HTTPS, modification is performed, but after a while is automatically rolled back

**Kong Ingress controller version**
kong:1.4
kong-ingress:1.6

### Kubernetes version

**Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.10", GitCommit:"8cea5f8ae165065f0d35e5de5dfa2f73617f02d1", GitTreeState:"clean", BuildDate:"2019-10-05T00:08:10Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}t**

### Environment

- **Cloud provider or hardware configuration**: Google Cloud 
- **OS** (e.g. from /etc/os-release): cOS

### What happened

The route modification done using Admin API is roll-back after a while

### Expected behvaior

Modification should not be rollback

### Steps To Reproduce

1. Install kong-ingress using official documentation
2. Create a Service and Ingress in kubernetes
3. Modify the route using Rest API
4. Wait some time to see rollback
