### ISSUE TITLE
Default Service Port with use Kong Ingress

### ISSUE THREAD

**Issue by thanhtai9606** [Kong/kubernetes-ingress-controller#4457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 I cannot set default service port when I use kong Ingress 
example: My pod container https protocol and port is 3000
I cannot use default with that port and protocol. It just show like this
![kong](https://github.com/Kong/kubernetes-ingress-controller/assets/4544983/f535e4e0-3c44-4b11-b05f-dd40eeb2188c)

### Expected Behavior

I want, it auto set default port and protocol already use in service!!

![image](https://github.com/Kong/kubernetes-ingress-controller/assets/4544983/50d224cb-bf71-45a5-b435-f2ef299a8b78)

### Kong Ingress Controller version

```shell
2.10.
```

### Kubernetes version

1.23

**Comment by randmonkey** [comment]
Hello @thanhtai9606, What is the GUI of Kong are you using? It does not look like Kong Manager, and seems to be a third party GUI tool. Also, how did you deploy your ingresses and services? Are you using helm charts and can you provide the full content of the chart?

When you install Kong Ingress Controller (KIC), the configuration is controlled by KIC and the configuration from you GUI will be overwritten when KIC updates Kong configuration. If you want to set service port in KIC, you could configure the `backend` field of your `Ingress` like this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-golang-dev
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /go
        pathType: ImplementationSpecific
        backend:
          service:
            name: golang-dev
            port:
              number: 3000
```
