### ISSUE TITLE
Kong not passing the exact call to service

### ISSUE THREAD

**Issue by nicolasdonoso** [Kong/kubernetes-ingress-controller#448]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Using Kubernetes ingress controller I configured an ingress, a service and a plugin:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
    cors.plugins.konghq.com: cors
  name: <service-name>
  namespace: <namespace>
spec:
  rules:
  - host: <api-url>
    http:
      paths:
      - path: /api/v[1-2]/auth
        backend:
          serviceName: <service-name>
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    cors.plugin.konghq.com: cors
    external-dns.alpha.kubernetes.io/hostname: <DNS>
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
  labels:
    name: <service-name>
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5001
      protocol: TCP
      name: http
  selector:
    name: <service-name>
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
disabled: false
config:
  origins: 
  $ORIGINS
  methods: 
  - GET
  - HEAD
  - PATCH
  - POST
  - PUT
  - DELETE
  headers: 
  - Authorization
  - Origin
  - Referer
  - Content-Type
  - Access-Control-Allow-Origin
  - Access-Control-Allow-Headers
  - Accept
  - Accept-Version
  - encoding
  - accept
  - language
  - authorization
  - cache-control
  - cache
  - language
  preflight_continue: false
plugin: cors
```

**kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.4.0**

**kong:1.0.0**

### Kubernetes version

**Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}**

### Environment

- **Cloud provider or hardware configuration**: AWS

### What happened

The route requested gets lost from kong to the service.
1. Calling https://<URL>/api/v1/auth/login 
2. kong receives the same "POST /api/v1/auth/login HTTP/1.1"
3. The service only receives the last part of the call "POST /login"

### Expected behvaior

1. Calling https://<URL>/api/v1/auth/login 
2. kong receives the same "POST /api/v1/auth/login"
3. The service only receives the last part of the call "POST /api/v1/auth/login"

### Steps To Reproduce

1. Deploy kong with kong-ingress controller versions mentioned above
2. Create ingress, service, and plugin
3. Call the endpoint

**Comment by hbagdi** [comment]
This happens because Kong is striping the path it sees in the Ingress rule by default.
You want to use KongIngress resource:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-kongingress-resource.md#use-kongingress-with-ingress-resource

**Comment by nicolasdonoso** [comment]
Thanks for the quick response.

I created the following kong ingress:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: sample
route:
  methods:
  - GET
  - HEAD
  - PATCH
  - POST
  - PUT
  - DELETE
  strip_path: false
```

And added configuration.konghq.com: sample to the ingress annotations and everything is working as expected now. A good thing to have in mind is that they must be on the same namespace.

Thanks again!
