### ISSUE TITLE
CORS plugin not working as expected

### ISSUE THREAD

**Issue by nicolasdonoso** [Kong/kubernetes-ingress-controller#449]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Using Kubernetes ingress controller I configured a kongingress, an ingress, a service, and a plugin:
```
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: sample
  namespace: dev
route:
  methods:
  - GET
  - HEAD
  - PATCH
  - POST
  - PUT
  - DELETE
  strip_path: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
    configuration.konghq.com: sample
    plugins.konghq.com: cors
  name: sample
  namespace: dev
spec:
  rules:
  - host: $API_URL
    http:
      paths:
      - path: /api/v[1-2]/auth
        backend:
          serviceName: sample
          servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
disabled: false
config:
  origins: 
  - https://$ORIGIN
  methods: 
  - GET
  - HEAD
  - PATCH
  - POST
  - PUT
  - DELETE
  headers: 
  - Authorization
  - Origin
  - Referer
  - Content-Type
  - Access-Control-Allow-Origin
  - Access-Control-Allow-Headers
  - Accept
  - Accept-Version
  preflight_continue: false
plugin: cors
```

**kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.4.0**

**kong:1.0.0**

### Kubernetes version

**Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:04:30Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}**

### Environment

- **Cloud provider or hardware configuration**: AWS

### What happened

When calling https://<URL>/api/v1/auth/login I get the followin console error:
```
Access to XMLHttpRequest at 'https://$URL/api/v1/auth/login' from origin 'https://$ORIGIN' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

### Expected behvaior

1. Calling https://$URL/api/v1/auth/login 
2. Get a 200

### Steps To Reproduce

1. Deploy kong with kong-ingress controller versions mentioned above
2. Create kongingress, ingress, service, and plugin
3. Call the endpoint
