### ISSUE TITLE
creating a kongplugin resource on minikube does not create a plugin on /plugins

### ISSUE THREAD

**Issue by devdavidkarlsson** [Kong/kubernetes-ingress-controller#46]
**Kong Ingress controller version**:
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.0.3

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
**Environment**:

- **OS** (e.g. from /etc/os-release): minikube version: v0.26.1

**What happened**:
I followed some steps to add a plugin to some consumer.
https://kubeless.io/docs/http-triggers/#enable-kong-security-plugins

The plugin does not show up on the plugins endpoint.

**What you expected to happen**:

${KONG_ADMIN_IP}:${KONG_ADMIN_PORT}/plugins

 would contain the basic-auth plugin.

**How to reproduce it** (as minimally and precisely as possible):

```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth
consumerRef: basic-auth
config:
  hide_credentials: false
" | kubectl create -f -
kongplugin "basic-auth" created
```

```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: basic-auth
username: user
" | kubectl create -f -
kongconsumer "basic-auth" created
```

```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: basic-auth
consumerRef: basic-auth
type: basic-auth
config:
  username: user
  password: pass
" | kubectl create -f -
kongcredential "basic-auth" created
```

```
kubectl patch ingress get-python \
 -p '{"metadata":{"annotations":{"basic-auth.plugin.konghq.com":"basic-auth"}}}'
```

The plugin should have been activated. Verification:

```
export KONG_ADMIN_PORT=$(minikube service -n kong kong-ingress-controller --url --format "{{ .Port }}")
export KONG_ADMIN_IP=$(minikube service   -n kong kong-ingress-controller --url --format "{{ .IP }}")
export PROXY_IP=$(minikube   service -n kong kong-proxy --url --format "{{ .IP }}" | head -1)
export HTTP_PORT=$(minikube  service -n kong kong-proxy --url --format "{{ .Port }}" | head -1)

curl ${KONG_ADMIN_IP}:${KONG_ADMIN_PORT}/plugins |jq .
```
