### ISSUE TITLE
Unable to add certificate

### ISSUE THREAD

**Issue by jimcullenaus** [Kong/kubernetes-ingress-controller#461]
### Summary

We have a plugin which requires a configured TLS certificate in order to work. When we add the certificate through the management API it works fine. But we are unable to add the certificate to Kong via the kubernetes-ingress-controller with `kubectl`.

**Kong Ingress controller version**

0.6.1

**Kong or Kong Enterprise version**

1.4.0

### Kubernetes version

1.12.0

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: running locally with minikube version: v1.5.2
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.3 LTS (Bionic Beaver)
- **Kernel** (e.g. `uname -a`): 4.15.0-70-generic
- **Install tools**:
- **Others**:

### What happened

We run `kubectl create -f <our file>` on a file containing

```yaml
apiVersion: v1
data:
  key: <our key, base64 encoded>
  cert: <our cert, base64 encoded>
kind: Secret
metadata:
  name: ids-cert
  namespace: kong
type: Opaque
```

### Expected behaviour

The certificate would appear in Kong as a certificate which our plugin can use to function successfully.

### Steps To Reproduce

1. Run `minikube start --kubernetes-version v1.12.0` to start minikube.
2. Run
```bash
curl -sL https://bit.ly/kong-ingress > kong-ingress.yaml
 
kubectl create -f kong-ingress.yaml
```
3. `kubectl create -f <our certificate file>` (as above)
4. View the "Certificates" page in Konga. It appears empty.

**Comment by hbagdi** [comment]
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

You need to configure an Ingress resource with TLS section for Kong to serve the traffic using the above certificate.

**Comment by jimcullenaus** [comment]
We figured it out. Should have been

```yaml
  - apiVersion: v1
    data:
      tls.crt: <our cert, base64 encoded>
      tls.key: <our key, base64 encoded>
    kind: Secret
    metadata:
      name: ...
      namespace: ...
    type: kubernetes.io/tls
```
