### ISSUE TITLE
`KongIngress` doesn't support `latency` ring-balancer algorithm for `upstream`

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4616]
### Problem statement

I want to set ring-balancer to use `latency` algorithm , following the [docs](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-kongingress-resource/) here I create a KongIngress resource but I go error message likes:
```
Unsupported value: "latency": supported values: "round-robin", "consistent-hashing", "least-connection
```
The [deploy file](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-postgres.yaml) seems that latency algorithm is not added in to CRD. So how should I use latency algorithm? Here are the algorithms available by default,quoted from previous mentioned deploy file.
```
    algorithm:
      description: Algorithm is the load balancing algorithm to use.
      enum:
      - round-robin
      - consistent-hashing
      - least-connections
```

_Originally posted by @stricklandye in https://github.com/Kong/kubernetes-ingress-controller/discussions/4613_

--- 

Gateway introduced the `latency` algorithm in 3.2 https://github.com/Kong/kong/blob/master/CHANGELOG.md#320 but KIC didn't add it in its CRD yet.

### Proposed solution

Add `latency` to the validation enum in https://github.com/Kong/kubernetes-ingress-controller/blob/57daa5df7c643e958afc4cae86233cdf8408d13a/pkg/apis/configuration/v1/kongingress_types.go#L165

### Open Questions

Do we want to add any sort of version checks for this or do we want to defer this to Gateway to reject unsupported values?
