### ISSUE TITLE
Deprecate the deploy manifests in favor of Helm

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#4712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

After KIC's documentation on [deployment instructions](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/k4k8s/):

> Kustomize manifests are provided for illustration purposes only and are not officially supported by Kong. There is no guarantee of backwards compatibility or upgrade capabilities for our Kustomize manifests. For a production setup with Kong support, use the [Helm Chart](https://github.com/kong/charts).

Unification brings benefits:
- plain manifests only partially install the webhook #1438 
- one installation method is easier to maintain, explain and use

### Proposed Solution

- For 3.0+, not provide any manifests in `/deploy`
- Instead recommend use of the Helm chart for all cases
- For users not interested in running Helm in their deployments, they always have the option to render the `kubectl apply`icable manifests using `helm template`

This will break anyone who's on a KIC version <3.x and pulls their manifests from `main`.

In that case, they'll need to update their download paths to instead refer to the tag of the KIC version they use.

For the tests that currently rely on deploy manifests: and interim solution might be moving the manifests in use by tests under `/test`.

### Additional information

To ease the breakage, the manifests removed from `deploy/` on `main` might be replaced with something akin to

```yaml
# DEPRECATED
#
# For Kong Ingress Controller 3.0+, please use Helm instead:
# 
#   $ helm repo add kong https://charts.konghq.com
#   $ helm repo update
#   $ helm install kong/kong --generate-name --set ingressController.installCRDs=false
#
# If you intend to use an older version, Helm is recommended but you still have the option
# to install using manifests. In that case, replace the 'main' branch in your link with the
# KIC tag. For example:
# kubectl apply -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/v2.11.1/deploy/single/all-in-one-dbless.yaml
#

apiVersion: please-use-helm-to-install-kong
kind: Deprecated
```

which gives a "somewhat friendly" message when trying to apply:

```
error: resource mapping not found for name: "" namespace: "" from "deprecated.yaml": no matches for kind "None" in version "deprecated/please-use-helm-to-install-kong"
ensure CRDs are installed first
```

### Acceptance Criteria

- [ ] KIC 3.0 comes with Helm as the only installation method
- [ ] on `main` there are no manifests in the `deploy` directory except for the deprecation warnings
- [ ] the manifests have been moved to the `test` directory (so that they're not available for end users, but tests can keep relying on them until we migrate the tests to Helm)
