### ISSUE TITLE
How to set timeout 

### ISSUE THREAD

**Issue by vivianforzj** [Kong/kubernetes-ingress-controller#472]
### Version

1. kong version: 1.3.0, installed by helm chart
2. kubectrl version:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

### What happened
I install kong by helm, and use KongIngress as proxy, but the timeout settings does not work as expected.

The KongIngress yaml:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: custom-kongingress
route:
  strip_path: false
upstream:
  algorithm: least-connections
proxy:
  protocol: http
  path: /
  connect_timeout: 600000
  retries: 3
  read_timeout: 600000
  write_timeout: 600000
```

and I use this KongIngress as ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: "kong"
    configuration.konghq.com: custom-kongingress
spec:
  rules:
    - http:
        paths:
          - path: /xxxx
            backend:
               serviceName: web
               servicePort: 80
```

I may use the timeout settings in a wrong way, so it does work. How can I set timeout correctly? Thanks.

**Comment by vivianforzj** [comment]
@hbagdi hi, I create a new issue here. Please help check my yaml. Thank you.

**Comment by hbagdi** [comment]
Proxy timeouts are a configuration setting related to a Kubernetes service.
You need to apply the `configuration.konghq.com` annotation to the specific Kubernetes service (and not an Ingress resource) for this to take effect.

**Comment by vivianforzj** [comment]
Yes, it works. Thanks.

**Comment by phlegx** [comment]
@hbagdi, @vivianforzj May I ask what exactly how you set the timeouts? I tried now to set annotations in the service like this:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    configuration.konghq.com/connect_timeout: "1800000"
    configuration.konghq.com/read_timeout: "1800000"
    configuration.konghq.com/write_timeout: "1800000"
  creationTimestamp: "2020-05-12T12:09:09Z"
  name: nlu-training
  namespace: nlu
  resourceVersion: "34304322"
  selfLink: /api/v1/namespaces/nl/services/training
  uid: 6b987d82-6623-477c-a7c0-5851c8330a6e
spec:
  clusterIP: 10.43.57.250
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: training
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

But I still get a timeout after aproximately 1 minute.

Can anyone tell me what and where to set so that the timeourts are applied?

thanks!

**Comment by NICK-DUAN** [comment]
@hbagdi I use same way to set kong connect_timeout, but it not work for me. this is my yaml file, can you point out my problem?

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  annotations:
  name: ci-console-kong-ing
  namespace: ci
proxy:
  connect_timeout: 3000000
  protocol: http
  read_timeout: 3000000
  retries: 10
  write_timeout: 3000000
route:
  protocols:
    - http
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: ci-console-kong-ing
  name: ci-webconsole-server
  namespace: ci
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/override: ci-console-kong-ing
    kubernetes.io/ingress.class: kong
  name: ci-webconsole-server-ing
  namespace: ci
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ci-webconsole-server
              servicePort: 8080
            path: /api/ci-ws/console
```
