### ISSUE TITLE
Editing KongIngress does not trigger an immediate sync

### ISSUE THREAD

**Issue by dsem** [Kong/kubernetes-ingress-controller#474]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Editing a KongIngress resource does not trigger an immediate sync of the Kubernetes configuration with the Kong configuration.  Instead, the configuration is only propagated at the next regular sync interval (10 minutes, I believe).

**Kong Ingress controller version**

v0.6

**Kong or Kong Enterprise version**
Kong

### Kubernetes version

**paste `kubectl version` output**

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

I am running `kubectl edit KongIngress/<name>` to edit an existing KongIngress. After making a change like modifying the `route.methods` array, I save the session. However, as I tail the the Kong kubernetes-ingress-controller admin-api logs, I notice that there are no calls to the various admin endpoints that would indicate the configuration is syncing.

### Expected behavior

After editing a KongIngress with `kubectl edit KongIngress/<name>`, the changed configuration is synced with Kong.

### Steps To Reproduce

1. Watch the kubernetes-ingress-controller logs: `kubectl logs -f deploy/kong-ingress-controller admin-api`
2. Edit a KongIngress resource. Be sure to actually change the configuration. `kubectl edit kongingress/<name>`
3. Watch the logs from step 1 and notice that there are no calls to `/upstreams`, `/routes`, etc. endpoints.

**Comment by hbagdi** [comment]
Are you using the DB version or the DB-less version here? It is probably DB, but I want to make sure.

Also, could you please paste here the Ingress and KongIngress resources that you are editing and applying?

**Comment by dsem** [comment]
Yes, using the DB version (postgres).

### KongIngress
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: app-blue
  namespace: prod
proxy:
  connect_timeout: 60000
  path: /api/v1
  protocol: https
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
route:
  methods:
  - GET
  - POST
  - PUT
  - PATCH
  preserve_host: false
  protocols:
  - https
  regex_priority: 0
  strip_path: true
```

### Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: app-blue
    kubernetes.io/ingress.class: prod-kong
  name: app-blue
  namespace: prod
spec:
  rules:
  - host: <host redacted>
    http:
      paths:
      - backend:
          serviceName: app-blue
          servicePort: 443
        path: /api/v1
      - backend:
          serviceName: app-blue
          servicePort: 443
        path: /ui/v1
status:
  loadBalancer:
    ingress:
    - ip: <ip redacted>
```
