### ISSUE TITLE
Custom names for Service/Route resources

### ISSUE THREAD

**Issue by ltartarini** [Kong/kubernetes-ingress-controller#4753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Is there any chance to define a custom Service/Route name for the Kong resources deployed in a DB-less Kubernetes cluster? 

For example, let's say I need to deploy the following Kong resources:

- Service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/path: /external/
  labels:
    app: account
  name: account-dev-service
  namespace: backend
spec:
  ...
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: account
    environment: dev
  ...
```

- Route:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/preserve-host: "false"
    konghq.com/regex-priority: "0"
    konghq.com/strip-path: "false"
    kubernetes.io/ingress.class: kong
  name: account-public-routes
  namespace: backend
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: account-dev-service
            port:
              number: 80
        path: /v0/accounts$
        pathType: ImplementationSpecific
      ...
```

Once deployed, If I query the Admin-API, I get the following responses:

- Service:
```
...
{
  "host": "account-dev-service.backend.80.svc",
  ...
  "name": "backend.account-public-routes.account-dev-service.80",
  ...
},
...
```

- Route:
```
...
{
  ...
  "name": "backend.account-public-routes.account-dev-service..80",
  "service": {
    "id": "<service_id>"
  },
  ...
  "paths": [
    ...
  ],
  ...
},
...
```

Is it possible (maybe via `annotation`?) to properly define a custom Service/Route `name` instead of having `<namespace>.<route_name>.<service_name>.<port>`?

Thanks in advance.
