### ISSUE TITLE
ServicePort != Port?

### ISSUE THREAD

**Issue by chriskolenko** [Kong/kubernetes-ingress-controller#488]
I'm just getting my head around how to use the ingress controller. 

I'm having issues with my servicePort being: 8080. But I notice it's set to 80 in the parse. Is this by design?

https://github.com/Kong/kubernetes-ingress-controller/blob/9bd6a8c9169b024a999aaf7dffa4a4abb7349d29/internal/ingress/controller/parser/parser.go#L459

**Comment by hbagdi** [comment]
> I'm having issues with my servicePort being: 8080. But I notice it's set to 80 in the parse. Is this by design?

You can safely ignore the hard-coded 80 port. The actual port being used is in the `target` entity of the corresponding upstream.

**Comment by ehdieunguyen** [comment]
@hbagdi I am thinking about how to configure the port of kong service.

I am expecting the below ingress, that will set the port of kong service is `8989` but it is `80` as it is a hardcore value. So, how to do as I expected?

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /podinfo
        backend:
          serviceName: podinfo
          servicePort: 8989
```

![Screen Shot 2020-05-27 at 3 17 32 PM](https://user-images.githubusercontent.com/39895269/82995027-403e0400-a02d-11ea-950f-1e217d576ed1.png)
