### ISSUE TITLE
Credentials secrets are not validated if not referenced by a consumer

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#4885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a Kubernetes Secret that cannot be properly translated into a valid KongCredential (like described in the Credentials secrets are not validated if not referenced by a consumer), KIC's admission webhook doesn't reject it.

### Expected Behavior

When I create a Kubernetes Secret that uses invalid `kongCredType` or doesn't have required keys for a given `kongCredType`, it's rejected by the admission webhook despite whether it's associated with any consumer or not.

### Steps To Reproduce

```markdown
1. Deploy KIC with admission webhook.
2. Execute `kubectl` commands from the [guide](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/admission-webhook/#verify-incorrect-credential-secrets) 
2. Kubernetes API accepts invalid credentials Secrets.
```

### Kong Ingress Controller version

```shell
v2.12.0
```

**Comment by pmalek** [comment]
We could consider using https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/ for this as well.

The problem with those is that they require selection resources on which to perform the validation which could not be feasible for us (we don't know beforehand what namespaces with what labels users will be deployed those Secrets in).

**Comment by czeslavo** [comment]
> We could consider using https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/ for this as well.
> 
> The problem with those is that they require selection resources on which to perform the validation which could not be feasible for us (we don't know beforehand what namespaces with what labels users will be deployed those Secrets in).

Yeah, probably that would be doable to define VAP that would be equivalent to [ValidateCredentials](https://github.com/Kong/kubernetes-ingress-controller/blob/ccd0f75049fb4e3d2487406adb1d96b126ef6764/internal/admission/validation/consumers/credentials/validation.go#L17). We'll have a label that will allow us to filter Secrets accordingly: https://github.com/Kong/kubernetes-ingress-controller/pull/4825 

Anyway, I think that's something that we should postpone to 3.0+ with the following prerequisites:
- `kongCredType` key in credentials Secrets is no longer supported (only `konghq.com/credential` label)
- [ValidatingAdmissionPolicy feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is turned on by default in all Kubernetes versions we support (it's still turned off for 1.28).

Having them satisfied, we could drop the basic admission webhook validation.

**Comment by pmalek** [comment]
For posterity this is what I managed to make work on kind 1.28 with the following config:

```
featureGates:
  ValidatingAdmissionPolicy: true
runtimeConfig:
  "admissionregistration.k8s.io/v1alpha1": true
  "admissionregistration.k8s.io/v1beta1": true
```

policy:

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: secret-policy
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["secrets"]
  validations:
    - expression: "has(object.data.kongCredType) && object.data.kongCredType == 'YmFzaWMtYXV0aA==' && has(object.data.password) && has(object.data.username)"
      reason: Invalid
      messageExpression: "'secret \"' + string(object.metadata.name) + '\" with \"kongCredType\" set to \"basic-auth\" has to have username and password set'"
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: secret-policy-binding
spec:
  policyName: secret-policy
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchLabels:
        kong: system
```

error:

```
The secrets "kong-config" is invalid: : ValidatingAdmissionPolicy 'secret-policy' with binding 'secret-policy-binding' denied request: secret "kong-config" with "kongCredType" set to "basic-auth" has to have username and password set
```
