### ISSUE TITLE
New Topic: Using custom nginx.conf reference

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As a user I'd like to use a custom `nginx.conf` file on my Kong Gateway pods    

### Acceptance Criteria

* Provide instructions how to use a custom `nginx.conf` file with Kong Gateway on Kubernetes
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by mheap** [comment]
From @randmonkey:

If they just want to load the template to some path inside the kong  container, they can save it to some ConfigMap  or Secret  and mount it into the container, like:

```
deployment:
  userDefinedVolumes:
  - name: custom-template
    configMap:
      name: custom-template
      items:
      - key: "nginx_kong.lua"
        path: "nginx_kong.lua"
  userDefinedVolumeMounts:
  - mountPath: "/var/kong" # the template where you want to put
    name:custom-template
    readOnly: true
    subPath: "nginx_kong.lua"
```
