### ISSUE TITLE
glog currently doesn't support passing configuration via environment variables

### ISSUE THREAD

**Issue by vivianforzj** [Kong/kubernetes-ingress-controller#506]
### Summary

**Kong Ingress controller version**
0.7.0

**Kong version**
1.4

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

### What happened

I want kong ingress controller to write logs to files. So according to  https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/cli-arguments.md, I modify the ingressController env settings in the kong values.yaml as followings:

```
ingressController:
  enabled: true
  image:
    repository: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller
    tag: 0.7.0

  # Specify Kong Ingress Controller configuration via environment variables
  env:
    LOG_DIR: /var/log/ingress_controller
    LOGTOSTDERR: false
    ALSOLOGTOSTDERR: false
    STDERRTHRESHOLD: "2"
    V: 0
```

and when I descirbed the kong pod, I saw the following env for ingress-controller container:
```
    Environment:
      POD_NAME:                    r-kong-kong-5444b7fdc4-h7ksw (v1:metadata.name)
      POD_NAMESPACE:               default (v1:metadata.namespace)
      CONTROLLER_ALSOLOGTOSTDERR:  false
      CONTROLLER_LOGTOSTDERR:      false
      CONTROLLER_LOG_DIR:          /var/log/ingress_controller
      CONTROLLER_STDERRTHRESHOLD:  2
      CONTROLLER_V:                0
```

but the logs are still writen to stdout rather than to file. 

### Expected behavior

The kong ingress-controller logs are written to file.
