### ISSUE TITLE
migrating existing project to helm 

### ISSUE THREAD

**Issue by dmuley17** [Kong/kubernetes-ingress-controller#5100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to migrate my existing project with `kong` to helm (without changing any values as such ) which is failing with error as below 

```
install.go:231: [debug] CHART PATH: /home/ec2-user/.cache/helm/repository/icedq-0.0.11.tgz

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "icedq-kong-global-cors" namespace: "" from "": no matches for kind "KongClusterPlugin" in version "configuration.konghq.com/v1"
ensure CRDs are installed first
helm.go:84: [debug] resource mapping not found for name: "icedq-kong-global-cors" namespace: "" from "": no matches for kind "KongClusterPlugin" in version "configuration.konghq.com/v1"
ensure CRDs are installed first
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:322
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:306
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:152
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.7.0/command.go:992
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598
[ec2-user@ip-172-31-88-156 echo-server]$
[ec2-user@ip-172-31-88-156 echo-server]$
[ec2-user@ip-172-31-88-156 echo-server]$
[ec2-user@ip-172-31-88-156 echo-server]$
[ec2-user@ip-172-31-88-156 echo-server]$
[ec2-user@ip-172-31-88-156 echo-server]$
[ec2-user@ip-172-31-88-156 echo-server]$ helm version
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/kubernetes/admin.conf
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

```
my kong clustre plugin looks like below 

```
{{ if .Values.discovery_config.embedded_ing_controller }}
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: icedq-kong-global-cors
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  origins: 
  - "*"
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  - PATCH
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - X-Auth-Token
  - Authorization
  - Referer
  - Origin
  exposed_headers:
  - X-Auth-Token
  credentials: false
  max_age: 3600
  preflight_continue: true
plugin: cors
{{ end }}
```

### Expected Behavior

it should apply the plugin as its working as expected on my existing project.

### Kubernetes version

```shell
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.25.9
```
