### ISSUE TITLE
bug: controller panics for default backend services.

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#511]
### Summary

If default backend is declared in an Ingress resource, the controller panics

**Kong Ingress controller version**

0.7.0
This is not a problem with 0.6.0

**Kong or Kong Enterprise version**

1.4.3

### Kubernetes version

1.15

### Environment

- **Cloud provider or hardware configuration**: GKE

### Steps To Reproduce
```
echo "apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  backend:
    serviceName: billing
    servicePort: 80
  tls:
  - hosts:
    - foo.com
    secretName: tls-secret" | kubectl apply -f -
```

The controller crashes due to a nil pointer reference.
