### ISSUE TITLE
Implement `ServiceFacade` behind an alpha feature gate

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#5152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Implement an abstraction between the Kubernetes `Service` and Kong `Service` (proposed name: `ServiceFacade` - suggestions welcome) that will be usable as a `backendRef` in Gateway API routes and Ingress.

Design doc [link](https://docs.google.com/document/d/1rSdGUMq5zXo340KH_DbaKqDj6_XYuQHbaaw7Z2nV128/edit).

This feature should be opt-in:
- the CRD should not be installed "by default" by the user who comes to KIC
- the support for this feature should be hidden behind an alpha feature gate

### Proposed Solution

1. create a new `ServiceFacade` CRD (distributed separately) similar to the resource below:
    ```yaml
    apiVersion: configuration.konghq.com/v1beta1
    kind: ServiceFacade
    metadata:
      name: payments-service-group1
      annotations:
        konghq.com/plugins: acl-l1
    spec:
      isFacadeFor:
        apiGroup: v1
        kind: Service
        name: payments-service
      port: 8080
    ```
2. Support `ServiceFacade` in rule types in KIC:
    1. Ingress. allow `ServiceFacade` to be set as `defaultBackend` and individual rules' backend
    2. Gateway API: allow all kinds of Gateway API routes to have `ServiceFacade` as a backendRef
    3. Explicitly not supported (to be optionally implemented later if necessary): TCPIngress, UDPIngress
3. Ensure that setting customizations work on ServiceFacade. This includes
    1. Attaching plugins to a `ServiceFacade`
    2. More broadly speaking: attaching other types of settings (including `proxy`/`upstream`) settings

### Additional information

Diagram of the desired use:
![image](https://github.com/Kong/kubernetes-ingress-controller/assets/2715147/c8dcb827-875b-491d-8f02-84e7339bd87a)

### Acceptance Criteria

- [ ] The `ServiceFacade` CRD exists and is *not* installed by default
- [ ] The service facade semantics are implemented and only enabled if the service facade alpha feature gate is enabled
- [ ] An installation and usage guide for ServiceFacade exists (including alpha warnings)
- [ ] If enabled, ServiceFacade works as a backend for `Ingress`
- [ ] Plugin attaching to a `ServiceFacade` works
- [ ] All other customizations configurable on a `Service` (annotations) work
