### ISSUE TITLE
question: Why not synchronize event change data immediately?

### ISSUE THREAD

**Issue by chenjinxuan** [Kong/kubernetes-ingress-controller#519]
Modifying kongIngress will not be updated immediately. Is this the right design? Can only wait for sync-period to take effect to synchronize data?
![image](https://user-images.githubusercontent.com/25172225/73273269-adc45a00-421e-11ea-8028-9eea106697a1.png)

**Comment by hbagdi** [comment]
I'm not sure what you are pointing at here. `IsValidIngressClass` filters changes to unrelated resources. On a change to `KongIngress` resource, the event is immediately sent to the `update` channel and processed.

**Comment by chenjinxuan** [comment]
So when the kongingress resource changes, no event notification will be sent
![image](https://user-images.githubusercontent.com/25172225/73280078-faad2e00-4228-11ea-8fcf-a72473496977.png)

**Comment by hbagdi** [comment]
If the KongIngress resource does not belong to the correct Ingress class, then yes, no notification will be sent.

**Comment by chenjinxuan** [comment]
The KongIngress resource does not need to set annotations ingress class, so when I set a custom class instead of Kong, the changes of kongIngress will never trigger event notification
![image](https://user-images.githubusercontent.com/25172225/73289756-38fe1980-4238-11ea-8fbd-6a9648ce0b9e.png)
![image](https://user-images.githubusercontent.com/25172225/73290061-ba55ac00-4238-11ea-826d-3f65a8d0c05d.png)

**Comment by hbagdi** [comment]
> The KongIngress resource does not need to set annotations ingress class

Interesting. I don't think we clarify if that's necessary or not in docs but in code it should be needed.
We enforce that for KongConsumer and KongPlugin resources as well.

**Comment by chenjinxuan** [comment]
My English is not very good, please forgive me.
Now, I set the ingress class of kubernetes-ingress -controller to gd-kong,
When the CRD of kongingress, kongplugin and so on is changed, the event notification will not be triggered immediately. It can only wait for timing synchronization

**Comment by hbagdi** [comment]
> My English is not very good, please forgive me.

No problem! We will try our best to support you.

>  When the CRD of kongingress, kongplugin and so on is changed, the event notification will not be triggered immediately. It can only wait for timing synchronization

That does sound like a bug.
Can you share the steps we can follow to reproduce this?

**Comment by chenjinxuan** [comment]
![image](https://user-images.githubusercontent.com/25172225/73291682-a19ac580-423b-11ea-8fa4-b0929e27e92a.png)

kubctl  apply -f Ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gd-kong
    configuration.konghq.com: configuration-demo
  name: example-app1
spec:
  rules:
  - host: xxx.xxx.xxx
    http:
      paths:
      - backend:
          serviceName: example-app
          servicePort: 10000
        path: /
```
kubectl apply -f kongIngress.yaml
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: configuration-demo
router:
   methods:
   - POST
```
When I modify kongingress, it will not take effect immediately
kubectl apply -f kongIngress.yaml
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: configuration-demo
router:
   methods:
   - POST
   - GET
```

**Comment by hbagdi** [comment]
I can replicate this.

This is interesting. So it seems that we currently allow users to associate a KongIngress resource that doesn't have the ingress-class annotation with an Ingress resource which has the ingress-class annotation.

So, we either fix the event mechanism or we disallow KongIngress references without the Ingress-class association. I'd recommend to do the later.

@chenjinxuan If you instead use the following KongIngress resource, then your problem will be solved:

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: configuration-demo
  annotations:
    kubernetes.io/ingress.class: gd-kong
route:
   methods:
   - POST
   - GET

```
