### ISSUE TITLE
not able to create acl group for consumer

### ISSUE THREAD

**Issue by droger88** [Kong/kubernetes-ingress-controller#5202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

we have deployed kong as ingress controller in our EKS cluster with db-less mode, and it works well. 
what we are trying to do is to setup a basic authentication mechanism so that only certain consumer can access certain api.
The plugin we are using is `acl` and `key-auth`, however I can't find a way to configure the acl group to consumer mapping.
According to the doc, it can be configured either via API or declarative configuration, since we try to manage everything using CRD is there an option that we can create acl group using CRD? 

### Expected Behavior

able to create acl group using CRD

### Steps To Reproduce

```markdown
1. create `key-auth` plugin

 apiVersion: configuration.konghq.com/v1
 kind: KongPlugin
 metadata:
   name: key-auth
   namespace: apps
 plugin: key-auth
 config:
   key_names:
   - apikey
```
2. create acl plugin
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: acl-fake-api
  namespace: apps
plugin: acl
config:
  allow:
  - fake-api
  hide_groups_header: true

```
3. create consumer 
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: fake-consumer
  namespace: kong
  annotations:
      kubernetes.io/ingress.class: kong
username: fake-consumer
credentials:
 - fake-consumer-key
consumerGroups:
  - fake-group
```
where should i create the acl group that maps to consumer?
```


### Kong Ingress Controller version

```shell
kong/kubernetes-ingress-controller:3.0
kong/kong-gateway:3.4
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.7-eks-4f4795d", GitCommit:"3719c8491f81867f591e895a43b4f5aab4145794", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:04Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by droger88** [comment]
i think i have missed the documentation here https://docs.konghq.com/kubernetes-ingress-controller/latest/plugins/acl/
The acl to consumer mapping can be created using secret
```
apiVersion: v1
data:
  group: cHJvZHVjdC1hcGk=
  kongCredType: YWNs
kind: Secret
metadata:
  name: acl-product-api-group
  namespace: kong
  labels:
    konghq.com/credential: acl
```
then, add the group to the consumer credentials
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-one
  namespace: kong
  annotations:
      kubernetes.io/ingress.class: kong
username: consumer-one
credentials:
 - consumer-one-key
 - acl-product-api-group
consumerGroups:
  - group-one
```
