### ISSUE TITLE
The TCPRoute cannot be attached to its gateway

### ISSUE THREAD

**Issue by mohammadll** [Kong/kubernetes-ingress-controller#5209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey everyone ! I'm trying to use TCPRoute instead of TCPIngress but it cannot be attached to the gateway, even though the parent information such as name and sectionName is provided correctly . I installed kong/kong helm chart using the below custom-values:
```yaml
proxy:
  stream:
    - containerPort: 9000
      servicePort: 9000
      protocol: TCP
      nodePort: 32080
```

My configuration files:
01-GatewayClass:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: 'true'
spec:
  controllerName: konghq.com/kic-gateway-controller
```
02-Gateway:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
 name: kong
spec:
 gatewayClassName: kong
 listeners:
 - name: proxy
   port: 80
   protocol: HTTP
 - name: stream-9000
   port: 9000
   protocol: TCP
   allowedRoutes:
      kinds:
      - kind: TCPRoute
```
03-TCPRoute:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: echo-tcp
spec:
  parentRefs:
  - name: kong
    sectionName: stream-9000
  rules:
  - backendRefs:
    - name: echo
      port: 1025
```
### Expected Behavior

I expect TCPRoute to be attached to its gateway, while this issue does not exist for HTTPRoute

### Kong Ingress Controller version

v3.0

### Kubernetes version

v1.27.3

**Comment by mohammadll** [comment]
`status` doesn't exist in my `TCPRoute`, but i can see that in my `HTTPRoute`, both of them are using the same gateway. i'm using `sectionName` for my `TCPRoute`. so what is the problem ? i followed this link https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/services/tcp/

**Comment by programmer04** [comment]
@mohammadll 

The initial configuration of the Kong Ingress Controller is wrong. First of all Helm chart `kong/kong` is considered deprecated, please follow the instructions on a fresh cluster.

**Install Kong Kubernetes Ingress Controller** 

Firstly install the required gateway-api CRDs

```sh
kubectl apply -f  https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/experimental-install.yaml
```

Next, install the properly configured Kong Kubernetes Ingress Controller

`valuse.yml`
```yml
gateway:
  proxy:
    stream:
      - containerPort: 9000
        servicePort: 9000
        protocol: TCP
        nodePort: 32080
controller:
  ingressController:
    env:
      # Required for all Gateway API stuff that still belongs to the experimental channel, e.g. TCPRoute.
      feature_gates: GatewayAlpha=true
```

installation

```sh
helm repo update
helm install kong kong/ingress --values values.yml --namespace kong --create-namespace
```

**Test configuration with an example**

Example echo service

```sh
kubectl apply -f https://docs.konghq.com/assets/kubernetes-ingress-controller/examples/echo-service.yaml
```

Your configuration

`example-tcp-route.yml`

```yml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: 'true'
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
 name: kong
spec:
 gatewayClassName: kong
 listeners:
 - name: proxy
   port: 80
   protocol: HTTP
 - name: stream-9000
   port: 9000
   protocol: TCP
   allowedRoutes:
      kinds:
      - kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: echo-tcp
spec:
  parentRefs:
  - name: kong
    sectionName: stream-9000
  rules:
  - backendRefs:
    - name: echo
      port: 1025
```

```sh
kubectl apply -f example-tcp-route.yml
```

After a short period of time routing is configured, check it out

```sh
export PROXY_IP=$(kubectl get svc --namespace kong kong-gateway-proxy -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
echo $PROXY_IP
```

```sh
nc $PROXY_IP 9000
```

results with

```txt
Welcome, you are connected to node kong-test-control-plane.
Running on Pod echo-74c66b778-qjzg6.
In namespace default.
With IP address 10.244.0.8.
```

---

Please let me know whether it helps, and do not hesitate to ask any questions
