### ISSUE TITLE
Provide a specific error for synch failed due to KongConsumers with the same username, or make the creation fail

### ISSUE THREAD

**Issue by mikyll** [Kong/kubernetes-ingress-controller#5226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When adding two or more KongConsumers with the same `username` field, the configuration synching blocks and prevents you from applying any further changes, but logs don't tell you what's the actual issue:
```
2023-11-23T08:42:00Z    error   Failed parsing resource errors  {"url": "https://10.244.0.142:8444", "update_strategy": "InMemory", "error": "could not unmarshal config error: json: cannot unmarshal object into Go struct field ConfigError.flattened_errors of type []sendconfig.FlatEntityError"}
2023-11-23T08:42:00Z    error   dataplane-synchronizer  Could not update kong admin     {"error": "performing update for https://10.244.0.142:8444 failed: failed posting new config to /config: got status code 400"}
```

### Proposed Solution

Maybe something like this showing up in controller logs:
```
[...]
[timestamp]    error   Cannot have username shared between different KongConsumers [user-consumer1, user-consumer2]
```

Or avoid it a priori (but I don't think it's possible):
```
kongconsumer.configuration.konghq.com/user-consumer1 created
kongconsumer.configuration.konghq.com/user-consumer2 creation failed (username already existing)
```

Or even automatically deleting the last one

### Steps to Reproduce
1. Minikube cluster setup:
```
minikube start --driver=docker
minikube tunnel
```

2. CRDs installation:

```
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml

echo "
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: 'true'

spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
" | kubectl apply -f -
```

3. Kong installation:
```
helm repo add kong https://charts.konghq.com
helm repo update
helm install kong kong/ingress -n kong --create-namespace 
```

4. Create 2 consumers with the same username:
```
echo "apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
 name: user-consumer1
 annotations:
   kubernetes.io/ingress.class: kong
username: user
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
 name: user-consumer2
 annotations:
   kubernetes.io/ingress.class: kong
username: user # Same username of user-consumer1
" | kubectl apply -f -
```

5. Watch logs:
```
kubectl logs -n kong -f <kong_controller_pod>
```

### Kong Ingress Version
KIC Release: 3.0.0

### Kubernetes Version
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.26.3

### Note
I know it should be obvious that 2 users cannot share the same username, but I spent hours trying to figure out what was the issue, because I have many YAML files and the error appeared a little generic to me. Maybe something like an additional line of log addressing the specific issue could be helpful

### Acceptance Criteria

- [ ] As a user, I'd like to know, just by looking at the controller logs, that I have 2 KongConsumer resources with the same username
