### ISSUE TITLE
ParentRefs does not support resources other than gateway.networking.k8s.io/Gateway

### ISSUE THREAD

**Issue by fr-kinoshita** [Kong/kubernetes-ingress-controller#5227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed kong ingress controller using helm chart 0.9.0

I created the following HTTPRoute.

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: echo
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: kong
    namespace: kong
    group: ""
    kind: Service
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo
    backendRefs:
    - name: echo
      kind: Service
      port: 1027
```

I got this error, and this route cannot be used in kong.

```
2023-11-23T09:29:49Z    error   controllers.HTTPRoute   Reconciler error        {"reconcileID": "b522b343-7d28-480d-84fd-3c524bbf530d", "error": "unsupported parent kind /Service"}
```

### Expected Behavior

As mentioned in the API document, it should accept Service resource as parentRefs.

https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.ParentReference

### Steps To Reproduce

```markdown
Install the Gateway API CRDs.


kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
```

Install kong ingress controller.

```
$ helm repo add kong https://charts.konghq.com
$ helm repo update
$ helm install kong kong/ingress -n kong --create-namespace --values values.yaml
```

values.yaml is as follows.

```
$ cat values.yaml
controller:
  ingressController:
    admissionWebhook:
      enabled: false
gateway:
  env:
    plugins: "bundled"
  proxy:
    type: ClusterIP
    http:
      servicePort: 8000
    tls:
      enabled: false
  manager:
    enabled: false
  portal:
    enabled: false
  containerSecurityContext:
    readOnlyRootFilesystem: false
```

Deploy the echo service.

```
kubectl apply -f https://docs.konghq.com/assets/kubernetes-ingress-controller/examples/echo-service.yaml
```

Then try to create a route.

```
$ cat route.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: echo
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: kong
    namespace: kong
    group: ""
    kind: Service
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo
    backendRefs:
    - name: echo
      kind: Service
      port: 1027
$ kubectl apply -f route.yaml
```

Check logs from the kong ingress controller, and the error is found.
```


### Kong Ingress Controller version

```shell
v3.0.0
```

### Kubernetes version

```shell
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```
