### ISSUE TITLE
Document how to support multiple GatewayClass instances

### ISSUE THREAD

**Issue by mheap** [Kong/kubernetes-ingress-controller#5237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

From @battlebyte:

Following the [example in the GatewayClass documentation](https://gateway-api.sigs.k8s.io/api-types/gatewayclass/) about creating two GatewayClass resources for Internet facing traffic and private facing traffic, we could create two GatewayClass definitions like the following:

```
kind: GatewayClass
metadata:
  name: internet
spec:
  controllerName: "konghq.com/internet-controller"
---
kind: GatewayClass
metadata:
  name: private
spec:
  controllerName: "konghq.com/private-controller"
```

I deploy two different instances of KIC and I want one instance to process “internet” manifests and the other instance “private” manifests. The GatewayClass specification says that the GatewayClass.spec.controller field determines the controller implementation responsible for managing the GatewayClass . What parameter/value do I need to use in the Helm chart to link a KIC deployment to [konghq.com/internet-controller](http://konghq.com/internet-controller)  and the other deployment to [konghq.com/private-controller](http://konghq.com/private-controller) ?

And a follow up question: is it possible for one single KIC deployment to be the implementation for multiple GatewayClasses?

### Proposed Solution

From @czeslavo:

You can set `ingressController.env.gateway_api_controller_name` to `konghq.com/internet-controller`) or `konghq.com/private-controller` to make KIC reconcile the GatewayClasses you've created.

Currently, we only support a single GatewayClass per KIC instance (analogically to a single IngressClass).

### Additional information

Where does this live on docs.konghq.com? Maybe under Guides->Security?

### Acceptance Criteria

- [ ] As a user I know how to deploy a KIC instance using a non-default `controllerName` by reading docs.konghq.com

**Comment by xiaoronglv** [comment]
Hi @mlavacca, @mheap and @rainest ,

Good day!

> From @czeslavo:
> You can set `ingressController.env.gateway_api_controller_name` to konghq.com/internet-controller) or konghq.com/private-controller to make KIC reconcile the GatewayClasses you've created.

I would like to follow this instruction and deploy two instances of Kong Gateway to my AWS EKS cluster. Here is my values.yaml for my second Kong instance, but it seems not to be working:


```
gateway:

  proxy:
    http:
      enabled: true
  autoscaling:
    enabled: true
  ingressController:
    env:
      gateway_api_controller_name: 'konghq.com/Kong-two-controller'

```

I used the following command to deploy the second instance:

```
helm install kong-2 kong/ingress -n kong -f ./values.yaml
```

Did you deploy your two Kong instances through Helm? How did you configure the Gateway Controller Name in the values.yaml file?

I couldn't find the definition either in the source code of [ingress helm chart](https://github.com/Kong/charts/blob/main/charts/ingress/values.yaml#L15)  or [kong helm chart](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml). 

I would appreciate it if you could share your values files as an example.
