### ISSUE TITLE
Secret-based credentials don't use hash suffix

### ISSUE THREAD

**Issue by kingwill27** [Kong/kubernetes-ingress-controller#533]
### Summary

By default, secrets are created with a hash appended to the end of the suffix, e.g.

```
secretGenerator:
  - name: auth
    namespace: test
    env: auth.env
```

might create a secret with the name `auth-5gghf7d256`.

If the name of the secret is specified in the consumer like so

```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: auth-user
  namespace: test
username: auth-user
credentials:
- auth
```

then the ingress controller fails to discover the secret:

```
error fetching credential secret 'test/auth': secret test/auth was not found
```

Is there any way to make it so that defining the secret and consumer in this way works, and the hash suffix does not prevent the controller from finding the secret?

**Kong Ingress controller version**: 0.7.1

**Kong or Kong Enterprise version**: 1.3

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
