### ISSUE TITLE
Plugin attachment to a group of resources from different namespaces

### ISSUE THREAD

**Issue by liyangau** [Kong/kubernetes-ingress-controller#5355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently I am using kong gateway to create plugins that is scoped at **BOTH** service and consumer. 

A deck state file snippet as below.

```yaml
- consumer: test
  name: rate-limiting-advanced
  service: loopback-route-svc
- consumer: test
  name: rate-limiting-advanced
  service: echo-svc
```

I am trying to achieve the same with KIC but it seems it is not possible to do this with `KongPlugin` or `KongClusterPlugin` because `KongConsumer` is scoped _Namespaced_ and the services are in different namespaces.

```yaml
  names:
    categories:
      - kong-ingress-controller
    kind: KongConsumer
    listKind: KongConsumerList
    plural: kongconsumers
    shortNames:
      - kc
    singular: kongconsumer
  scope: Namespaced
``` 

### Additional information

My goal is to implement per-consumer, per-service rate limiting with the rate limiting plugin. This means each consumer would have dedicated rate limits for each service they access.

This can be achieved with gateway easily. This feature request aims to enhance KIC's applicability to support this gateway feature.

### Acceptance Criteria

- [ ] if is possible to define a plugin that is attached to a combination of resources (e.g. service and consumer) that live in different namespaces
