### ISSUE TITLE
Problem with strip_path in 0.0.4

### ISSUE THREAD

**Issue by Daniel-Rei** [Kong/kubernetes-ingress-controller#54]
**BUG REPORT**

**Kong Ingress controller version**:
Kong Ingress controller version: 0.0.4

**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T18:09:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"} 

```

**Environment**:

- Cloud provider or hardware configuration: OSX 10.12.6
- OS(e.g. from /etc/os-release): minikube version: v0.26.1
- Install tools: Helm

**What happened**:

Adding mockbin ingress resource like [this](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/examples/externalname.md) but with an added path /mockbin as path in kong-ingress-controller:0.0.3 and kong-ingress-controller:0.0.4 behaves differently. Trying `curl ${PROXY_IP}:${HTTP_PORT}/mockbin` in V:0.04 gives 404 Not Found, whilst in 0.0.3 we reach the mockbin, i.e. the path is being stripped properly to call mockbin.org directly (without path). 

In the working example in 0.0.3 we used a ingress resource and kongIngress resource with strip_path like this (from our helm charts):

Ingress resource:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxy-from-k8s-to-mockbin
  namespace: kong-test
  annotations:
    ingress.plugin.konghq.com: proxy-from-k8s-to-mockbin
    request-transformer.plugin.konghq.com: |
      transform-request-to-mockbin
spec:
  rules:
  - host: api.dev.oltd.de
    http:
      paths:
      - path: /mockbin
        backend:
          serviceName: proxy-to-mockbin
          servicePort: 80
```

KongIngress resource:

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: proxy-from-k8s-to-mockbin
  namespace: kong-test
upstream:
  hash_on: none
  hash_fallback: none
  healthchecks:
    active:
      concurrency: 10
      healthy:
      http_statuses:
        - 200
        - 302
      interval: 0
      successes: 0
      http_path: "/mockbin"
      timeout: 1
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        interval: 0
        tcp_failures: 0
        timeouts: 0
    passive:
      healthy:
      http_statuses:
        - 200
      successes: 0
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 503
        tcp_failures: 0
        timeouts: 0
    slots: 10
proxy:
  path: /mockbin
  connect_timeout: 10000
  retries: 10
  read_timeout: 10000
  write_timeout: 10000
route:
  methods:
  - POST
  - GET
  - DELETE
  - HEAD
  regex_priority: 0
  strip_path: true
  preserve_host: false
```

**What you expected to happen**:
The results differ on kong's routes and services I would expect them to be the same for 0.0.3 and 0.0.4:

```
## Routes:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   344    0   344    0     0  90123      0 --:--:-- --:--:-- --:--:--  111k
{
  "next": null,
  "data": [
    {
      "created_at": 1527236461,
      "strip_path": true,
      "hosts": [
        "api.dev.oltd.de"
      ],
      "preserve_host": false,
      "regex_priority": 0,
      "updated_at": 1527236461,
      "paths": [
        "/mockbin"
      ],
      "service": {
        "id": "8838cb0f-866e-4fb2-9857-8210706652ab"
      },
      "methods": [
        "POST",
        "GET",
        "DELETE",
        "HEAD"
      ],
      "protocols": [
        "http"
      ],
      "id": "c5bb6ecc-e5f0-4c1a-8067-3948bc520e11"
    }
  ]
}
## Services:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   322    0   322    0     0  62463      0 --:--:-- --:--:-- --:--:-- 64400
{
  "next": null,
  "data": [
    {
      "host": "kong-test.proxy-to-mockbin.80",
      "created_at": 1527236461,
      "connect_timeout": 10000,
      "id": "8838cb0f-866e-4fb2-9857-8210706652ab",
      "protocol": "http",
      "name": "kong-test.proxy-to-mockbin.80",
      "read_timeout": 10000,
      "port": 80,
      "path": "/mockbin",
      "updated_at": 1527236461,
      "retries": 10,
      "write_timeout": 10000
    }
  ]
}
```

Previously the ingress and kong ingress resulted in the similar service but the route had a different: `path: /`
