### ISSUE TITLE
GRPCRoute status set incorrectly with missing listener

### ISSUE THREAD

**Issue by mheap** [Kong/kubernetes-ingress-controller#5411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `status` field says that the route was accepted, but `Programmed` stays as `Unknown`

```json
{
  "parents": [
    {
      "conditions": [
        {
          "lastTransitionTime": "2024-01-08T19:22:59Z",
          "message": "",
          "observedGeneration": 1,
          "reason": "Accepted",
          "status": "True",
          "type": "Accepted"
        },
        {
          "lastTransitionTime": "2024-01-08T19:22:59Z",
          "message": "",
          "observedGeneration": 1,
          "reason": "Unknown",
          "status": "Unknown",
          "type": "Programmed"
        }
      ],
      "controllerName": "konghq.com/kic-gateway-controller",
      "parentRef": {
        "group": "gateway.networking.k8s.io",
        "kind": "Gateway",
        "name": "kong",
        "namespace": "default"
      }
    }
  ]
}
```

### Expected Behavior

`status` should contain useful information. Something like: 

```json
{
  "parents": [
    {
      "conditions": [
        {
          "lastTransitionTime": "2024-01-08T19:22:59Z",
          "message": "",
          "observedGeneration": 1,
          "reason": "Missing listener for port 443",
          "status": "False",
          "type": "Accepted"
        }
      ],
      "controllerName": "konghq.com/kic-gateway-controller",
      "parentRef": {
        "group": "gateway.networking.k8s.io",
        "kind": "Gateway",
        "name": "kong",
        "namespace": "default"
      }
    }
  ]
}
```

### Steps To Reproduce

Create a `Gateway` and `GatewayClass`:

```yaml
echo "
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: 'true'

spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
" | kubectl apply -f -
```

Install Kong

```bash
helm install kong kong/ingress -n kong --create-namespace 
```

Enable `GatewayAlpha`

```bash
kubectl set env -n kong deployment/kong-controller CONTROLLER_FEATURE_GATES="GatewayAlpha=true" -c ingress-controller
```

Deploy GRPCBin

```yaml
echo "---
apiVersion: v1
kind: Service
metadata:
 name: grpcbin
 labels:
   app: grpcbin
spec:
 ports:
 - name: plaintext
   port: 9000
   targetPort: 9000
 - name: tls
   port: 9001
   targetPort: 9001
 selector:
   app: grpcbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: grpcbin
spec:
 replicas: 1
 selector:
   matchLabels:
     app: grpcbin
 template:
   metadata:
     labels:
       app: grpcbin
   spec:
     containers:
     - image: kong/grpcbin
       name: grpcbin
       ports:
       - containerPort: 9000
       - containerPort: 9001
" | kubectl apply -f -
```

Create a `GRPCRoute`

```yaml
echo 'apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
 name: grpcbin
spec:
 parentRefs:
 - name: kong
 hostnames:
 - "example.com"
 rules:
 - backendRefs:
   - name: grpcbin
     port: 9001
' | kubectl apply -f -
```

Look at the `status`:

```
kubectl get grpcroutes.gateway.networking.k8s.io grpcbin -o jsonpath='{.status}'
```
