### ISSUE TITLE
AWS NLB with proxy protocol v2 enabled causes bad request scheme

### ISSUE THREAD

**Issue by rparsonsbb** [Kong/kubernetes-ingress-controller#549]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

AWS NLB proxy protocol v2 causes bad http captures (maybe?) I'm not familiar enough with kong to understand the logged responses (below) however no ingress functions when proxy protocol v2 is enabled on the NLB target groups and the logs are filled with the messages below.

**Kong Ingress controller version**
0.7.0

**Kong or Kong Enterprise version**

### Kubernetes version
```Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}        Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}```

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): aws-linux2
- **Kernel** (e.g. `uname -a`): default eks nodes
- **Install tools**: eksctl / helm
- **Others**:

### What happened
```proxy 2020/02/23 03:24:40 [warn] 24#0: *3548782 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.4.186, server: kong, request: ""
proxy 10.35.4.186 - - [23/Feb/2020:03:24:40 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:41 [warn] 24#0: *3548785 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.18.164, server: kong, request: ""
proxy 10.35.18.164 - - [23/Feb/2020:03:24:41 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:41 [warn] 24#0: *3548786 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.4.186, server: kong, request: ""
proxy 10.35.4.186 - - [23/Feb/2020:03:24:41 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:42 [warn] 24#0: *3548800 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.12.170, server: kong, request: ""
proxy 10.35.12.170 - - [23/Feb/2020:03:24:42 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:45 [warn] 24#0: *3548841 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.4.186, server: kong, request: ""
proxy 10.35.4.186 - - [23/Feb/2020:03:24:45 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:45 [warn] 24#0: *3548842 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.18.164, server: kong, request: ""
proxy 10.35.18.164 - - [23/Feb/2020:03:24:45 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:45 [warn] 24#0: *3548843 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.4.186, server: kong, request: ""
proxy 10.35.4.186 - - [23/Feb/2020:03:24:45 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:46 [warn] 24#0: *3548856 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.12.170, server: kong, request: ""
proxy 10.35.12.170 - - [23/Feb/2020:03:24:46 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:47 [warn] 24#0: *3548869 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.18.164, server: kong, request: ""
proxy 10.35.18.164 - - [23/Feb/2020:03:24:47 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:49 [warn] 24#0: *3548901 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.18.164, server: kong, request: ""
proxy 10.35.18.164 - - [23/Feb/2020:03:24:49 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:51 [warn] 24#0: *3548929 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.18.164, server: kong, request: ""
proxy 10.35.18.164 - - [23/Feb/2020:03:24:51 +0000] "\x00" 400 12 "-" "-"
proxy 2020/02/23 03:24:53 [warn] 24#0: *3548957 [lua] reports.lua:73: log(): [reports] unknown request scheme: http while logging request, client: 10.35.18.164, server: kong, request: ""
proxy 10.35.18.164 - - [23/Feb/2020:03:24:53 +0000] "\x00" 400 12 "-" "-"
```

### Expected behavior
kong provides the client ip when following the steps detailed in [preserve client ip guide](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/preserve-client-ip.md)

### Steps To Reproduce

1. Create base eksctl cluster
2. Install kong-ingress 0.7.0 helm chart using [this values.yaml](https://gist.github.com/rparsonsbb/4ec2d9a8c00bf2a5904d7e1f64643f21)
3. Watch kong logs

**Comment by hbagdi** [comment]
I'm always confused between NLB and ELB.
Can you try with ELB once? We will investigate the differences if it works with ELB.

**Comment by rparsonsbb** [comment]
I had tested with ELB also and it doesn't work their either.  I was able to use the `externalTrafficPolicy: Local` but if the dns of the vpc is modified from default this would break.

**Comment by hbagdi** [comment]
@artburkart got it to work in his setup recently and could help out here.

**Comment by artburkart** [comment]
I haven't used proxy protocol with NLBs, because I believe I was getting the client IP passed through anyway, but the mvp kong helm values file required to get proxy protocol to work with a CLB was this:

```yaml
env:
  proxy_listen: 0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol
  real_ip_header: proxy_protocol
  trusted_ips: $cidr_where_nlb_lives
```

which would translate to:

```shell
KONG_PROXY_LISTEN="0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol"
KONG_REAL_IP_HEADER="proxy_protocol"
KONG_TRUSTED_IPS="$cidr_where_nlb_lives"
```

My guess is that what is in the [current values.yaml](https://gist.github.com/rparsonsbb/4ec2d9a8c00bf2a5904d7e1f64643f21#file-values-yaml-L32-L34) doesn't translate correctly:

```yaml
env:
  KONG_TRUSTED_IPS: 0.0.0.0/0,::/0  # This trusts all IPs
  KONG_PROXY_LISTEN: "0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol"
  KONG_REAL_IP_HEADER: x-forwarded-for
```

probably becomes:

```shell
KONG_KONG_TRUSTED_IPS="0.0.0.0/0,::/0"  # This trusts all IPs
KONG_KONG_PROXY_LISTEN=""0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol""
KONG_KONG_REAL_IP_HEADER="x-forwarded-for"
```

**Comment by rparsonsbb** [comment]
@artburkart this is correct circling back to this issue.  Gonna open a pull request to detail the comments on the env params in the helm chart since it can be confusing that kong docs prefix everything with `KONG_` but then its not required in the chart itself.

Thanks!

**Comment by austince** [comment]
Hey all, I'm running into the same issue and tried to fix it with `"service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "ssl"` but I'm seeing broken headers in the kong logs. Should I open up a new issue or do you all think this is related/ a misconfiguration? 

```
kong/kong-kong-66c967df55-5pmvb[proxy]: 2020/04/16 22:43:12 [error] 23#0: *2563 broken header: "}y#����O�����n(Ǔ����5��V%,g�3G��+&�+�/�#�'�	��,�0�$�(��
" while reading PROXY protocol, client: 24.188.101.150, server: 0.0.0.0:8443
```

Full proxy service annotations: 
```yaml
annotations:
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:..."
      # Balance across zones
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
      # Allow any protocol
      "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "ssl"
```


Kong chart `env`:

```yaml
  env:
    trusted_ips: "0.0.0.0/0,::/0"  # This trusts all IPs
    proxy_listen: "0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol"
    real_ip_header: x-forwarded-for
```
