### ISSUE TITLE
[Ingress with http path regex] regex parse error: look-around, including look-ahead and look-behind, is not supported

### ISSUE THREAD

**Issue by tantm3** [Kong/kubernetes-ingress-controller#5497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi everyone!

I am deploying the Kong ingress controller (PostgreSQL DB mode) in k8s env using ArgoCD.
I attached the values here: 
[kong-ingress-controller.zip](https://github.com/Kong/kubernetes-ingress-controller/files/14070825/kong-ingress-controller.zip)

There is an error when I am trying to apply this ingress resource:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: "true"
  name: dashboard
  namespace: iam-vmonitor
spec:
  ingressClassName: kong
  rules:
  - host: dev-test.tech
    http:
      paths:
      - path: /~/test-api(?![^/])
        pathType: ImplementationSpecific
        backend:
          service:
            name: vstorage-gateway
            port:
              number: 8080

```

The kong ingress controller pod showed an error after I apply the ingress resource above.
```
time="2024-01-27T03:33:43Z" level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: 1 errors occurred:\n\twhile processing event: {Create} route iam-vmonitor.dashboard.vstorage-gateway.dev-test.tech.8080 failed: HTTP status 400 (message: \"schema violation (Router Expression failed validation:  --> 1:2\\n  |\\n1 | (http.path ~ \\\"^/test-api(?![^/])\\\")\\n  |  ^------------------------------^\\n  |\\n  = regex parse error:\\n    ^/test-api(?![^/])\\n              ^^^\\nerror: look-around, including look-ahead and look-behind, is not supported)\")\n" subsystem=dataplane-synchronizer
```
There is a weird character "^" from the regex and I have no idea where it come from and I think that character make the error appear.
But when I deployed the kong ingress controller directly using the helm command utils, the error above disappear and the Kong proxy works fine.
I am using this command helm here
```
helm install -n gateway kong kong/kong --version 2.27.0 -f values.yaml
```
And here is the helm values: 
[values.zip](https://github.com/Kong/kubernetes-ingress-controller/files/14070833/values.zip)

### Expected Behavior

When I apply the ingress resource below, it's will create the Kong Services, Route, Upstream without an error
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: "true"
  name: dashboard
  namespace: iam-vmonitor
spec:
  ingressClassName: kong
  rules:
  - host: dev-test.tech
    http:
      paths:
      - path: /~/test-api(?![^/])
        pathType: ImplementationSpecific
        backend:
          service:
            name: vstorage-gateway
            port:
              number: 8080

```

### Steps To Reproduce

```markdown
1. Deploy Kong ingress Controller using argocd
2. Apply the ingress resource with http path regex config
3. Error appear 

time="2024-01-27T03:33:43Z" level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: 1 errors occurred:\n\twhile processing event: {Create} route iam-vmonitor.dashboard.vstorage-gateway.dev-test.tech.8080 failed: HTTP status 400 (message: \"schema violation (Router Expression failed validation:  --> 1:2\\n  |\\n1 | (http.path ~ \\\"^/test-api(?![^/])\\\")\\n  |  ^------------------------------^\\n  |\\n  = regex parse error:\\n    ^/test-api(?![^/])\\n              ^^^\\nerror: look-around, including look-ahead and look-behind, is not supported)\")\n" subsystem=dataplane-synchronizer
```
4. Switch to install using helm util
5. The error disappears
```


### Kong Ingress Controller version

```shell
Kong version: 3.3
kong/kubernetes-ingress-controller: 2.11
```

### Kubernetes version

```shell
Kubernetes v1.26.6
```
