### ISSUE TITLE
TLSRoute has unkown status after being accepted

### ISSUE THREAD

**Issue by dennisarmbruster95** [Kong/kubernetes-ingress-controller#5554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i deploy a test setup with TLSRoute like:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
  namespace: test
spec:
  gatewayClassName: kong
  listeners:
  - name: stream1883
    port: 1883
    protocol: TCP
  - name: stream8883
    port: 8883
    protocol: TLS
    tls:
      mode: Terminate
      certificateRefs:
      - name: acme-http01-cert-issued-default
    allowedRoutes:
      kinds:
      - kind: TLSRoute
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: echo-plaintext
  namespace: test
spec:
  parentRefs:
  - name: test-gateway
    sectionName: stream1883
  rules:
  - backendRefs:
    - name: echo
      port: 1025
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: echo-tls
  namespace: test
spec:
  parentRefs:
    - name: test-gateway
      sectionName: stream8883
  hostnames:
    - sandbox.digitaltwin-vwgroup.net
  rules:
    - backendRefs:
      - name: echo
        port: 1025
```

If i now want to test the concetion with following command, i don't get a response:
`echo "hello" | openssl s_client -connect $PROXY_ADDRESS:9443 -servername $PROXY_ADDRESS -quiet 2>/dev/null`
TCP connection without TLS via port 1883 works.

Status of TLSRoute looks like:
```
Name:         echo-tls
Namespace:    test
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1alpha2
Kind:         TLSRoute
Metadata:
  Creation Timestamp:  2024-02-04T12:55:33Z
  Generation:          2
  Resource Version:    129269301
  UID:                 4e705e12-8d49-401d-a435-5ac2a8f316d5
Spec:
  Hostnames:
    sandbox.digitaltwin-vwgroup.net
  Parent Refs:
    Group:         gateway.networking.k8s.io
    Kind:          Gateway
    Name:          test-gateway
    Section Name:  stream8883
  Rules:
    Backend Refs:
      Group:   
      Kind:    Service
      Name:    echo
      Port:    1025
      Weight:  1
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-02-04T12:58:47Z
      Message:               
      Observed Generation:   2
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-02-04T12:58:47Z
      Message:               
      Observed Generation:   2
      Reason:                Unknown
      Status:                Unknown
      Type:                  Programmed
    Controller Name:         konghq.com/kic-gateway-controller
    Parent Ref:
      Group:         gateway.networking.k8s.io
      Kind:          Gateway
      Name:          test-gateway
      Namespace:     test
      Section Name:  stream8883
Events:              <none>
```

### Expected Behavior

I excpect following output like in the kong example:
```
hello
```

### Steps To Reproduce

```markdown
- Kong version 3.4.2
- stream_listen: 0.0.0.0:1883, 0.0.0.0:8883 ssl
- Proxy stream enabled on 1883 and 8883 for TCP
- feature_gates: GatewayAlpha=true
```

### Kong Ingress Controller version

```shell
3.0.2
```

### Kubernetes version

```shell
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

### Anything else?

In my normal setup i want to use two TLSRoutes. I use for them the same hostname and same certificate, but in the logs is following message:
```
2024-02-04T13:52:39Z	error	Same SNI requested for multiple certs, can only serve one cert	{"served_secret_cert": "3fa9b05f-df0a-493a-9ab4-873a2d1336e3", "requested_secret_cert": "3ecf5b39-bbdc-4f76-b59d-a738954d3207", "sni": "*"}
```

**Comment by sonnysideup** [comment]
Any response or movement on this issue? I'm facing something very similar where I create a `Gateway` with a `TLS` route, configure termination, and try to route to a `TCPRoute`. The gateway is marked as accepted but hitting the endpoint results in an error message `no Route found with those values while prereading client data ...`.

**Comment by dennisarmbruster95** [comment]
Unfortunately, the problem has not changed from my side. I am also not aware of any more detailed information.

**Comment by sonnysideup** [comment]
Bumping this issue. Can anyone provide any feedback on this issue?

**Comment by dennisarmbruster95** [comment]
Kong configuration in Helmchart:
```
env:
  stream_listen: 0.0.0.0:1883, 0.0.0.0:8883 ssl, 0.0.0.0:8888 ssl
proxy:
  enabled: true
  stream:
    - containerPort: 1883
      servicePort: 1883
      protocol: TCP
    - containerPort: 8883
      servicePort: 8883
      protocol: TCP
    - containerPort: 8888
      servicePort: 8888
      protocol: TCP
```
Then i use two TCPIngress:
1. with following annotations for MQTT:
```
annotations:
  konghq.com/protocols: "tcp"
  kubernetes.io/ingress.class: kong
```

2. for MQTTS and WSS:
```
annotations:
  konghq.com/protocols: "tls"
  kubernetes.io/ingress.class: kong
```

In the TCPIngress for MQTTS or WSS, I refer to the TLS secrets.
