### ISSUE TITLE
HTTPRoute with RedirectURI feature

### ISSUE THREAD

**Issue by dweber019** [Kong/kubernetes-ingress-controller#5576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: user
  annotations:
    konghq.com/rewrite: '/requests/users_svc/$1'
    konghq.com/strip-path: 'true'
```

Not working for HTTPRoutes.

### Expected Behavior

According to https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/requests/rewrite-annotation/ I should be able to use the HTTPRoute example provided in the guide and be able to rewrite URI's.

### Steps To Reproduce

```markdown
You can actually use the guide.
```

### Kong Ingress Controller version

```shell
3.0.2
```

### Anything else?

I enabled the plugin [request-transformer](https://docs.konghq.com/hub/kong-inc/request-transformer/) and enabled the feature gate with `feature_gates: RewriteURIs=true`.

I found the working code for Ingress at https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/dataplane/translator/subtranslator/ingress.go#L629 but could not find any the code for HTTPRoutes.
