### ISSUE TITLE
key-auth allowing from another namespace

### ISSUE THREAD

**Issue by dgoradia** [Kong/kubernetes-ingress-controller#570]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

When using the key-auth plugin using 2 different secrets, each in 2 different namespaces, both api keys work for both deployments. 

**Kong Ingress controller version**
0.7.1

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
### Environment

- **Cloud provider or hardware configuration**: AWS EKS (1.15)

### What happened
When I have 2 namespaces with the app deployed to both with separate secrets for the apikey, I'm able to access the api with either key on both ingresses. 
All namespaces use the same network load balancer in aws but each namespace and ingress has different hostnames assigned to the ingress.

### Expected behavior
Cannot for example use the development api key for the production api endpoint and vice versa

### Steps To Reproduce
```
apiVersion: configuration.konghq.com/v1
credentials:
- apiuser-apikey
kind: KongConsumer
metadata:
  labels:
    app: dso-api
  name: dso-api-my-development
  namespace: dso-api-development
username: apiuser
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  labels:
    app: dso-api
  name: dso-api-ingress-development
  namespace: dso-api-development
route:
  methods:
  - GET
  - HEAD
  strip_path: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  labels:
    app: dso-api
  name: dso-api-auth-development
  namespace: dso-api-development
plugin: key-auth
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    plugins.konghq.com: dso-api-auth-development
  labels:
    app: dso-api
  name: dso-api-ingress-development
  namespace: dso-api-development
spec:
  rules:
  - host: dso-api-dev.domain.com
    http:
      paths:
      - backend:
          serviceName: dso-api-development
          servicePort: 80
        path: /*
```
