### ISSUE TITLE
Any configuration error breaks synchronization loop

### ISSUE THREAD

**Issue by rafal-roch** [Kong/kubernetes-ingress-controller#571]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

When synching configuration any configuration error stops ingress-controller from processing rest of queued changes. This is PITA when running a cluster with multiple applications and multiple development teams working on them: one configuration mistake breaks ingress-controller for everyone.

**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
1.1.2-centos

### Kubernetes version

lient Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"202
0-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-rancher1", GitCommit:"96573de545affa0a5db720a830b5d2bdf6e80b3b", GitTreeState:"clean", Buil
dDate:"2019-03-27T02:08:41Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

Error in one Ingress configuration prevents ingress-controller from processing other Ingresses.

### Expected behavior

Error in an Ingress should not affect other Ingresses.

### Steps To Reproduce

1. Create a faulty Ingress object (kong-status-ingress). For example put double slash in "path"field, resulting in "path cannot have empty segments" error

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-http-config
  namespace: kong
route:
  protocols:
  - http
  strip_path: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: kong-http-config
    kubernetes.io/ingress.class: kong
  name: kong-status-ingress
  namespace: kong
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kong-admin
          servicePort: kong-admin
        path: //status
````

2. Create a second Ingress object (kong-metrics-ingress), with correct configuration. Since ingress controller is stuck on creating kong-status-ingress, kong-metrics-ingress never gets created

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: kong-http-config
    kubernetes.io/ingress.class: kong
  name: kong-metrics-ingress
  namespace: kong
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kong-admin
          servicePort: kong-admin
        path: /metrics
```
