### ISSUE TITLE
knative: support for path based routing

### ISSUE THREAD

**Issue by mahartma** [Kong/kubernetes-ingress-controller#584]
the new knative support of the ingress controller ist awesome, but there is no way to create a path based routing to it behind a frontend api. the knative service is only accessible directly through the knative url. But I want to decouple it by a frontend api, managed by an ingress resource.

I have created a knative service and an ingress resource for it:
```
apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: go # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go # The URL to the image of the app
          env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Go Sample v1"
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: knative-ingress
spec:
  rules:
  - host: api.test.de
    http:
      paths:
      - backend:
          serviceName: helloworld-go
          servicePort: 80
        path: /go
```
```
kubectl get svc
NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP                      PORT(S)                             AGE
go                    ExternalName   <none>          go.test.de          <none>                              92m
```

```
kubectl get ing
NAME              HOSTS                     ADDRESS        PORTS   AGE
knative-ingress   *   192.168.64.8   80      141m
```

**Kong Ingress controller version**
0.8.0

**Kong or Kong Enterprise version**
2.0.0

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:40:44Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

### What happened
the problem is that Kong does not set host header correctly to the knative request:

```
http api.test.de/go
HTTP/1.1 503 Service Temporarily Unavailable
Connection: keep-alive
Content-Length: 58
Content-Type: application/json; charset=utf-8
Date: Sat, 28 Mar 2020 11:16:20 GMT
Server: kong/2.0.2
X-Kong-Response-Latency: 1

{
    "message": "failure to get a peer from the ring-balancer"
}
```

If I talk directly to the knative service  it works fine:

```
http go.test.de
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 20
Content-Type: text/plain; charset=utf-8
Date: Sat, 28 Mar 2020 11:17:36 GMT
Via: kong/2.0.2
X-Kong-Proxy-Latency: 1
X-Kong-Upstream-Latency: 1902

Hello Go Sample v1!
```

### Expected behavior
kong sets the correct ( **host: go.test.de** ) host header to the knative request
