### ISSUE TITLE
Events for cluster scoped resource like `KongClusterPlugin`s are not created because events require namespaces

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#5847]
### Problem statement

KIC supports emitting kubernetes native events https://docs.konghq.com/kubernetes-ingress-controller/latest/production/observability/events/ like `KongConfigurationApplyFailed`

These are created for all resources that are found to be relevant for an issue.

This system fails to create events for cluster scoped resources because events need to be created in a concrete namespace.

### Acceptance criteria 

- TBD

**Comment by rainest** [comment]
Do we have an example broken plugin to easily replicate this?

I'd recommend our install namespace, though still using the kind/name/etc. for the affected object. We can leave `namespace` in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#objectreference-v1-core blank; it's not required.

We _should_ have permission to our own namespace always, but won't necessarily have access to `default`. That said, I'm not sure if we have the `watchNamespaces` chart role generation set to always include our own namespace (offhand it looks like we don't, we just use the value directly and don't append our namespace to it). Adding our own namespace should be less a concern than adding `default` assuming we do need to fix that.

That said, it looks like we have no control over this unless we use a hack to forcibly add a namespace to an object that wouldn't normally have one (dunno if we actually can do that--probably, but I didn't try). We just [call `eventRecorder.Event()`](https://github.com/Kong/kubernetes-ingress-controller/blob/fe45e584e9d10b838166f43cab53fc82747508ba/internal/dataplane/kong_client.go#L719-L738), which is a [a type and method implemented by client-go](https://pkg.go.dev/k8s.io/client-go/tools/record#EventRecorder). That just says the Event is "created in the same namespace as the reference object", and we don't provide it with a namespace separately, just the `runtime.Object`.

Digging through the implementation [confirms that it does use `default` as an arbitrary fallback when the subject object has none set](https://github.com/kubernetes/client-go/blob/master/tools/record/event.go#L483-L485), so unless we modify the input object, that's what we'll get. Others have [raised this issue](https://github.com/kubernetes/client-go/issues/1262) a few times upstream, but it's never gotten traction, just stalebotted.

**Comment by pmalek** [comment]
From the options mentioned in https://github.com/kubernetes/client-go/issues/781 it seems  that 

> setting event' namespace to our CRD controller's namespace (app-specific): this seems to be the most reasonable option, however, its rejected by the server due to "[involved object's namespace does not match event.namespace](https://github.com/kubernetes/kubernetes/blob/a7f43a72032028b7e92acd70a3de1d6e6bc19cbe/pkg/apis/core/validation/events.go#L45)":

can't be done because the event and object namespace have to match.

https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/apis/core/validation/events.go#L152-L155

---

As for an example that would actually trigger this:

```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
config:
  config:
    latency_metrics: true
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
  name: prometheus
plugin: prometheus
```

```
k get events --field-selector reason=KongConfigurationApplyFailed -A
NAMESPACE   LAST SEEN   TYPE      REASON                         OBJECT                         MESSAGE
default     3s          Warning   KongConfigurationApplyFailed   kongclusterplugin/prometheus   invalid config.config: unknown field
```

<details>
  <summary>or a full working manifest:</summary>
 

```
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: registry.k8s.io/e2e-test-images/agnhost:2.40
          command:
            - /agnhost
            - netexec
            - --http-port=8080
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 10m
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: "true"
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: echo
      kind: Service
      port: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
config:
  config:
    latency_metrics: true
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
  name: prometheus
plugin: prometheus
```
  
</details>
