### ISSUE TITLE
Unable to use TCPIngress with Kong installed on externalIP

### ISSUE THREAD

**Issue by onyxet** [Kong/kubernetes-ingress-controller#586]
### Summary

Hi all!

I've installed kong helm chart into K8S cluster on bare-metal env where currently there is no possibility to use K8S service type: `LoadBalancer`

Main reason why I'm here I wanted to test `TCPIngress` with kong and found that it's not possible when Kong is deployed with service type which is not `LoadBalancer`

**Kong Ingress controller version**
kong:2.0

**Kong or Kong Enterprise version**
N/A
### Kubernetes version

**paste `kubectl version` output**
```Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}```
```Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}```

### Environment

- Bare-metal Kubernetes cluster built with kube-spray

### What happened

I've deployed Kong OSS release with service type `ClusterIP` for all services

I've patched kong service and deployment in order to support custom tcp port as it's described here:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-tcpingress.md

Than I deployed this manifest to cluster:
```
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: echo-plaintext
  namespace: infra-tools
spec:
  rules:
  - port: 9000
    backend:
      serviceName: tcp-echo
      servicePort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo
  namespace: infra-tools
  labels:
    app: tcp-echo
spec:
  ports:
  - name: tcp
    port: 9000
  selector:
    app: tcp-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo-v1
  namespace: infra-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
      version: v1
  template:
    metadata:
      labels:
        app: tcp-echo
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - name: tcp-echo
        image: docker.io/istio/tcp-echo-server:1.2
        imagePullPolicy: IfNotPresent
        args: [ "9000,9001,9002", "one" ]
        ports:
        - containerPort: 9000
        - containerPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-echo-v2
  namespace: infra-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-echo
      version: v2
  template:
    metadata:
      labels:
        app: tcp-echo
        version: v2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - name: tcp-echo
        image: docker.io/istio/tcp-echo-server:1.2
        imagePullPolicy: IfNotPresent
        args: [ "9000,9001,9002", "two" ]
        ports:
        - containerPort: 9000
        - containerPort: 9001
```

and found that `ProxyIP` is wrong in tcpingress spec:
```
kubectl get tcpingresses echo-plaintext  -n infra-tools 
NAME             ADDRESS         AGE
echo-plaintext   192.168.174.3   29m
```

main kong services are:
```
kong-kong-admin                                ClusterIP   10.97.116.248    193.178.146.210   8001/TCP,8444/TCP                                                                                                                                 25m
kong-kong-proxy                                ClusterIP   10.107.175.199   193.178.146.210   9000/TCP,80/TCP,443/TCP  
```
And when I tried to reach my service I've got:

```
telnet 193.178.146.210 9000 
Trying 193.178.146.210...
telnet: connect to address 193.178.146.210: Connection refused
telnet: Unable to connect to remote host
```

### Expected behavior

When I install TCPIngress with custom port Kong will handle requests to backend

### Steps To Reproduce

1. Install Kong helm chart `1.4.2` version with all services `clusterIP` type
2. Patch Kong proxy service in order to use custom TCP port for traffic forwarding
3. Follow instruction from: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-tcpingress.md
