### ISSUE TITLE
Failure to build working config when using a consumer with basic-auth credentials and a service/route using the same plugin twice

### ISSUE THREAD

**Issue by agaffney** [Kong/kubernetes-ingress-controller#587]
### Summary

A config that consists of a consumer with `basic-auth` credentials and an Ingress that happens to use the same plugin twice will cause the ingress controller to generate an invalid config. This took a ridiculous amount of trial and error to determine. This happens using either the deprecated `KongCredential` resource or the newer secrets-based method for specifying consumer credentials.

**Kong Ingress controller version**

0.8.0

**Kong or Kong Enterprise version**

2.0.2

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

Reproducible with:
- EKS/AWS
- k3d in Ubuntu

### What happened

Applying a config that worked with older Kong when using the API causes weird errors with the ingress controller.

The ingress controller throws angry log messages like:

```
E0331 17:02:30.259270       1 controller.go:119] unexpected failure updating Kong configuration:
posting new config to /config: 400 Bad Request {"fields":{"consumers":[{"basicauth_credentials":[{"@entity":["all or none of these fields must be set: 'password', 'consumer.id'"]}]}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {consumers={{basicauth_credentials={{[\"@entity\"]={\"all or none of these fields must be set: 'password', 'consumer.id'\"}}}}}}"}
```

### Expected behavior

Everything works.

### Steps To Reproduce

1. Deploy kong and the ingress controller using the default configuration of the helm chart
2. Apply the following manifest:

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-test
username: consumer-test
---
apiVersion: configuration.konghq.com/v1
config:
  password: some_password
  username: some_user
consumerRef: consumer-test
kind: KongCredential
metadata:
  name: consumer-test-basic-auth
type: basic-auth
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: kong-ingress-test
    kubernetes.io/ingress.class: kong
    plugins.konghq.com: kong-ingress-test-0, kong-ingress-test-1
  name: kong-ingress-test
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - backend:
          serviceName: kong-ingress-test
          servicePort: 80
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: kong-ingress-test
spec:
  externalName: google.com
  type: ExternalName
---
apiVersion: configuration.konghq.com/v1
config:
  append:
    headers:
    - X-Some-Header:test
  remove:
    headers:
    - X-Some-Header
kind: KongPlugin
metadata:
  name: kong-ingress-test-0
plugin: request-transformer
---
apiVersion: configuration.konghq.com/v1
config:
  append:
    headers:
    - X-Another-Header:foo
  remove:
    headers:
    - X-Another-Header
kind: KongPlugin
metadata:
  name: kong-ingress-test-1
plugin: request-transformer
```
3. Watch the world burn
