### ISSUE TITLE
how to access kong ingress controller admin api from aws kubernetes?

### ISSUE THREAD

**Issue by arunk16** [Kong/kubernetes-ingress-controller#59]
**Is this a request for help?**:
yes
**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kong ingress controller in aws kubernetes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
no

**Kong Ingress controller version**:
Installed using this command - 
```
curl https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml \
| kubectl create -f -
```

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Amazon linux
- **Kernel** (e.g. `uname -a`):  Linux ip-172-31-46-44 4.14.33-51.37.amzn1.x86_64 #1 SMP Thu May 3 20:07:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
I have tried https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/minikube.md in my laptop and it works well. I managed to create ingress resource for another api exposed as a service.

Now trying the same with AWS kubernetes cluster created by kops with k8s.local gossip private network (not a subdomain of a domain from AWS Route53 with public network) and able to deploy ingress controller, services and ingress routes for them using kubectl utility in the cluster and now stuck at accessing the kong admin and proxy apis. There is a elastic load balancer created in aws and its set to listen on port 443 and Kubernetes API is accessible only through https.

**_Is there any documentation explains how to setup access via AWS ELB to Kong admin and proxy apis running in kubernetes cluster?_**

This is my cluster in AWS - output from kops edit cluster command.

```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-05-29T13:51:32Z
  name: k8slab.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-lab-kops-state-store/k8slab.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-1a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.9.3
  masterInternalName: api.internal.k8slab.k8s.local
  masterPublicName: api.k8slab.k8s.local
  networkCIDR: 172.31.0.0/16
  networkID: vpc-7d8a061a
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.48.0/20
    name: eu-west-1a
    type: Public
    zone: eu-west-1a
  - cidr: 172.31.64.0/20
    name: eu-west-1b
 topology:
    dns:
      type: Public
    masters: public
    nodes: public
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Create a kubernetes cluster using this guide - https://dzone.com/articles/how-to-create-a-kubernetes-cluster-on-aws-in-few-m and deploy kong ingress controller and necessary services and ingress routes using https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/minikube.md document.

**Anything else we need to know**:

**Comment by Ngob** [comment]
Did you try to change the type of the service `kong-proxy` to `LoadBalancer` ? the type `NodePort` mean the service will be exposed on the node so it probably does not create any loadbalancer in AWS ELB. Can you try something like:
```
kubectl delete svc kong-proxy -n kong
echo "
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  type: NodePort
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-ssl
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong
" | kubectl apply -f -
```

**Comment by arunk16** [comment]
@Ngob  thanks for that, I have used the type: LoadBalancer to solve this already.

**Comment by Ngob** [comment]
@arunk16 You are welcome
@gerred I can help to improve the deployment documentation on GKE / AWS Kubernetes, feel free to assign me

**Comment by engmsaleh** [comment]
I'm using the same setup but I have configured it on a subdomain on Route53
I have the same issue, I couldn't connect to the Kong proxy or Admin API also, I have done as suggested by @Ngob 

Could you please advise?

**Comment by Ngob** [comment]
@engmsaleh I do not know about AWS deployment or Route53, but I will try to help:
I think this is a AWS specific problem (and the kubernetes deployment), so this is probably **not** a kong issue. From what I know, if you configure a subdomain you will need something like the [route53 mapper](https://github.com/kubernetes/kops/tree/master/addons/route53-mapper)
Let me know if this help.
I think your question should be posted on [Kong Nation](https://discuss.konghq.com/c/kubernetes).

**Comment by jaskiratr** [comment]
Hi,
I'm able to access the Proxy API via the LoadBalancer. Which Pod or Service needs to be exposed to access the **Admin API**?
I'm trying to setup the [Admin API Loopback](https://docs.konghq.com/1.3.x/secure-admin-api/#kong-api-loopback), but I'm not sure how to access it.
Thank you

```sh
kubectl apply -f https://bit.ly/kong-ingress

kubectl get all -n kong

NAME                                READY   STATUS      RESTARTS   AGE
pod/ingress-kong-74f469bbb6-hlxkf   2/2     Running     1          13m
pod/kong-migrations-qztcl           0/1     Completed   0          13m
pod/postgres-0                      1/1     Running     0          13m

NAME                              TYPE           CLUSTER-IP       EXTERNAL-IP                                                                     PORT(S)                      AGE
service/kong-proxy                LoadBalancer   100.71.102.112   xxxxxx.elb.us-west-2.amazonaws.com   80:32500/TCP,443:30156/TCP   13m
service/kong-validation-webhook   ClusterIP      100.65.114.214   <none>                                                                          443/TCP                      13m
service/postgres                  ClusterIP      100.67.213.155   <none>                                                                          5432/TCP                     13m

NAME                           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-kong   1         1         1            1           13m

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-kong-74f469bbb6   1         1         1       13m

NAME                        DESIRED   CURRENT   AGE
statefulset.apps/postgres   1         1         13m

NAME                        COMPLETIONS   DURATION   AGE
job.batch/kong-migrations   1/1           17s        13m
```

**Comment by jaskiratr** [comment]
I was able to edit yaml to create `kong-admin` service.
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: kong
spec:
  type: NodePort
  ports:
  - name: admin
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: ingress-kong
  type: ClusterIP
---
```
Additionally, I modified the `ingress-kong` deployment
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ingress-kong
  name: ingress-kong
  namespace: kong
spec:
  ...
  template:
    ...
    spec:
      containers:
        - env:
            ...
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001,0.0.0.0:8444 ssl
            - name: KONG_PROXY_LISTEN
              value: 0.0.0.0:8000,0.0.0.0:8443 ssl
          image: kong:1.3
          name: proxy
          ports:
            - containerPort: 8001
              name: admin
              protocol: TCP
            - containerPort: 8444
              name: admin-ssl
              protocol: TCP
            - containerPort: 8000
              name: proxy
              protocol: TCP
            - containerPort: 8443
              name: proxy-ssl
              protocol: TCP
            - containerPort: 9542
              name: metrics
              protocol: TCP
...
```

Once the Admin-API is created, I'm able to port forward it to my local machine by issuing following command
```sh
# Port forward Admin API service to localhost:8080
kubectl port-forward -n kong svc/kong-admin 8080:8001
```
From there, I can setup the Admin API Loopback by creating a consumer and key credentials associated with that. Finally, remove the Admin-API service and just access the loopback endpoint via the proxy service `LoadBalancer`.

Is there a better strategy?
