### ISSUE TITLE
AWS NLB w/ SSL creates broken headers to proxy

### ISSUE THREAD

**Issue by austince** [Kong/kubernetes-ingress-controller#605]
### Summary

Running into an issue with configuring an AWS NLB with SSL to the Kong proxy where requests were returned with a 400 Bad Request, saying the http request was sent to the https port. After enabling `"service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "ssl"` I'm seeing broken headers in the Kong logs.

Possibly related to:
- https://github.com/Kong/kubernetes-ingress-controller/issues/549
- https://github.com/kubernetes/kubernetes/issues/73297

**Kong Ingress controller version**

0.8.0

**Kong or Kong Enterprise version**

2.0

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T20:08:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): aws-linux2
- **Kernel** (e.g. `uname -a`): aws eks defaults (on node version v1.15.10-eks-bac369)
- **Install tools**: helm
- **Others**:

### What happened

```
kong/kong-kong-66c967df55-5pmvb[proxy]: 2020/04/16 22:43:12 [error] 23#0: *2563 broken header: "}y#����O�����n(Ǔ����5��V%,g�3G��+&�+�/�#�'�	��,�0�$�(��
" while reading PROXY protocol, client: 24.188.101.150, server: 0.0.0.0:8443
```

Proxy service values: 
```yaml
externalTrafficPolicy: Local
annotations:
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:..."
      # Balance across zones
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
      # Allow any protocol
      "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "ssl"
```

Kong chart `env`:

```yaml
  env:
    trusted_ips: "0.0.0.0/0,::/0"  # This trusts all IPs
    proxy_listen: "0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 ssl proxy_protocol"
    real_ip_header: x-forwarded-for
```

### Expected behavior

The NLB should forward requests over TLS to the correct Kong proxy port without breaking them.

### Steps To Reproduce

1. Create an eks cluster
2. Install kong + the ingress controller with an AWS NLB with the above annotations
3. Access the proxy over https
4. See broken headers in the logs

**Comment by austince** [comment]
This might be because I just don't need TLS termination at the load balancer level, though it seems like this could be exposing different issues.

**Comment by hbagdi** [comment]
I'm pretty sure this is due to the mismatch of ciphers in TLS negotiation.
Can you set `KONG_SSL_CIPHER_SUITE=intermediate` and try again?

**Comment by hbagdi** [comment]
Closing due to lack of activity. Please re-open if needed.

**Comment by vothanhbinhlt** [comment]
I have had same issue here https://github.com/Kong/kubernetes-ingress-controller/issues/1135

**Comment by nam-topie** [comment]
I think I have this solution, maybe solve the problem of your

```
externalTrafficPolicy: Local
annotations:
      "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": "arn:..."
      # Balance across zones
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
      # Allow any protocol
      "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
      "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http"
```
 ```
 env:
    trusted_ips: "0.0.0.0/0,::/0"  # This trusts all IPs
    proxy_listen: "0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 proxy_protocol"
    real_ip_header: x-forwarded-for
```
you should remove "ssl" on proxy_listen if you don't have cert local and you used cert of aws
