### ISSUE TITLE
Fallback configuration exploratory testing

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#6091]
The goal of this issue is to ensure that someone who, preferably, wasn't involved in the feature implementation will ensure this is working as expected.

Suggested ways to test:

- turn off the admission webhook to be able to generate invalid configuration that will be rejected by Kong
- verify the generated fallback configuration is correct
- make sure objects that were not related to broken ones are not affected and can be changed
- observe logs, metrics, and debug endpoints responses to make sure they provide enough data to debug potential issues

**Comment by czeslavo** [comment]
@pmalek I think the docs [draft PR](https://github.com/Kong/docs.konghq.com/pull/7463) should be good to take it on a ride. 👍

**Comment by pmalek** [comment]
I've followed the guide from the linked docs PR and everything worked as designed. I'll keep digging ⛏️ 


One question regarding the diagnostics: is there a way to see (apart from looking at the logs) to know which objects where rejected? As far as I can see the only way to get this information is to look at the last emitted `KongConfigurationApplyFailed` events for this information (which is helpful but not explicitly calls out the exclusion of those from the fallback config, also we do not know which dependents were also excluded)

```
[ingress-controller] 2024-06-05T13:52:48Z       debug   Adding failure  {"v": 1, "resource_name": "key-auth", "source": "config.keys", "problem": "unknown field"}
[ingress-controller] 2024-06-05T13:52:48Z       error   recording a Warning event for object    {"name": "key-auth", "namespace": "default", "kind": "KongPlugin", "apiVersion": "configuration.konghq.com/v1", "reason": "KongConfigurationApplyFailed", "message": "invalid config.keys: unknown field", "error": "object failed to apply"}
[ingress-controller] 2024-06-05T13:52:48Z       debug   Shipping config to diagnostic server    {"url": "https://10.244.0.23:8444", "v": 1}
[ingress-controller] 2024-06-05T13:52:48Z       debug   No change in config status, not notifying       {"v": 1}
[ingress-controller] 2024-06-05T13:52:48Z       debug   fallback-generator      Excluded object from fallback cache     {"v": 1, "object_kind": "&TypeMeta{Kind:KongPlugin,APIVersion:configuration.konghq.com/v1,}", "object_name": "key-auth", "object_namespace": "default"}
[ingress-controller] 2024-06-05T13:52:48Z       debug   fallback-generator      Excluded object from fallback cache     {"v": 1, "object_kind": "&TypeMeta{Kind:HTTPRoute,APIVersion:gateway.networking.k8s.io/v1,}", "object_name": "route-b", "object_namespace": "default"}
```

**Comment by czeslavo** [comment]
> I've followed the guide from the linked docs PR and everything worked as designed. I'll keep digging ⛏️
> 
> One question regarding the diagnostics: is there a way to see (apart from looking at the logs) to know which objects where rejected? As far as I can see the only way to get this information is to look at the last emitted `KongConfigurationApplyFailed` events for this information (which is helpful but not explicitly calls out the exclusion of those from the fallback config, also we do not know which dependents were also excluded)
> 
> ```
> [ingress-controller] 2024-06-05T13:52:48Z       debug   Adding failure  {"v": 1, "resource_name": "key-auth", "source": "config.keys", "problem": "unknown field"}
> [ingress-controller] 2024-06-05T13:52:48Z       error   recording a Warning event for object    {"name": "key-auth", "namespace": "default", "kind": "KongPlugin", "apiVersion": "configuration.konghq.com/v1", "reason": "KongConfigurationApplyFailed", "message": "invalid config.keys: unknown field", "error": "object failed to apply"}
> [ingress-controller] 2024-06-05T13:52:48Z       debug   Shipping config to diagnostic server    {"url": "https://10.244.0.23:8444", "v": 1}
> [ingress-controller] 2024-06-05T13:52:48Z       debug   No change in config status, not notifying       {"v": 1}
> [ingress-controller] 2024-06-05T13:52:48Z       debug   fallback-generator      Excluded object from fallback cache     {"v": 1, "object_kind": "&TypeMeta{Kind:KongPlugin,APIVersion:configuration.konghq.com/v1,}", "object_name": "key-auth", "object_namespace": "default"}
> [ingress-controller] 2024-06-05T13:52:48Z       debug   fallback-generator      Excluded object from fallback cache     {"v": 1, "object_kind": "&TypeMeta{Kind:HTTPRoute,APIVersion:gateway.networking.k8s.io/v1,}", "object_name": "route-b", "object_namespace": "default"}
> ```

Unfortunately, this is something that we haven't managed to implement yet. It is in the scope of https://github.com/Kong/kubernetes-ingress-controller/issues/5932.

**Comment by pmalek** [comment]
By running the latest version from main with `make run.skaffold SKAFFOLD_RUN_PROFILE=multi_gw`, disabling the webhook via

```
diff --git a/config/variants/multi-gw/dev/kustomization.yaml b/config/variants/multi-gw/dev/kustomization.yaml
index b564141ce..b0ee4b7d8 100644
--- a/config/variants/multi-gw/dev/kustomization.yaml
+++ b/config/variants/multi-gw/dev/kustomization.yaml
@@ -7,5 +7,5 @@ resources:
 - ../base/
 
 components:
-- ../../../components/manager_dev_webhook
+# - ../../../components/manager_dev_webhook
 - ../../../components/manager_dev_patch
```

I was able to successfully apply broken configs, e.g. 

```
# This configuration file presents fallback configuration (feature gate FallbackConfiguration=true),
# it contains a plugin that is misconfigured and will not work. The whole route /for-auth-users won't
# be configured. Only the route /httproute-testing will be configured.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-1
  labels:
    app: echo-1
spec:
  selector:
    matchLabels:
      app: echo-1
  template:
    metadata:
      labels:
        app: echo-1
    spec:
      containers:
      - name: echo-1
        image: kong/go-echo:0.3.0
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-1
  name: echo-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1027
  selector:
    app: echo-1
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: "true"
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-testing
  annotations:
    konghq.com/strip-path: "true"
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /httproute-testing
    backendRefs:
    - name: echo-1
      kind: Service
      port: 80
      weight: 75
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-testing2
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: rate-limit-1 #,rate-limit-2
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /httproute-rate-limiting
    backendRefs:
    - name: echo-1
      kind: Service
      port: 80
      weight: 75
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
plugin: key-auth
config:
  key_names:
  - "key"
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-1
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 5
  policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-2
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 30
  policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: rate-limit-user-1,rate-limit-user-2
username: consumer1
credentials:
- consumer1-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-user-1
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 10
  policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-user-2
  annotations:
    kubernetes.io/ingress.class: kong
config:
  minute: 20
  policy: local
plugin: rate-limiting
---
apiVersion: v1
kind: Secret
metadata:
  name: consumer1-auth
  labels:
    konghq.com/credential: key-auth
type: Opaque
stringData:
  key: password
```

The events are properly generated 

```
k get events -n kong | grep Kong
83s         Normal    KongConfigurationSucceeded           pod/ingress-kong-785fc96455-k9zdx    successfully applied Kong configuration to https://10.244.0.140:8444
83s         Normal    KongConfigurationSucceeded           pod/ingress-kong-785fc96455-k9zdx    successfully applied Kong configuration to https://10.244.0.141:8444
74s         Warning   KongConfigurationApplyFailed         pod/ingress-kong-785fc96455-k9zdx    failed to apply Kong configuration to https://10.244.0.141:8444: failed posting new config to /config: got status code 400
74s         Warning   KongConfigurationApplyFailed         pod/ingress-kong-785fc96455-k9zdx    failed to apply Kong configuration to https://10.244.0.140:8444: failed posting new config to /config: got status code 400
74s         Normal    FallbackKongConfigurationSucceeded   pod/ingress-kong-785fc96455-k9zdx    successfully applied fallback Kong configuration to https://10.244.0.141:8444
74s         Normal    FallbackKongConfigurationSucceeded   pod/ingress-kong-785fc96455-k9zdx    successfully applied fallback Kong configuration to https://10.244.0.140:8444
```

The metrics are emitted correctly:

```
# HELP ingress_controller_fallback_cache_generation_duration_milliseconds How long it took to generate a fallback cache, in milliseconds. `success` describes whether the cache generation was successful (`true`) or not (`false`).
# TYPE ingress_controller_fallback_cache_generation_duration_milliseconds histogram
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="0.005"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="0.01"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="0.025"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="0.05"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="0.1"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="0.25"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="0.5"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="1"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="2.5"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="5"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="10"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_bucket{success="true",le="+Inf"} 1
ingress_controller_fallback_cache_generation_duration_milliseconds_sum{success="true"} 0
ingress_controller_fallback_cache_generation_duration_milliseconds_count{success="true"} 1
# HELP ingress_controller_fallback_configuration_push_broken_resource_count The number of resources not accepted by Kong when attempting to push fallback configuration. `dataplane` describes the dataplane that was the target of the configuration push.
# TYPE ingress_controller_fallback_configuration_push_broken_resource_count gauge
ingress_controller_fallback_configuration_push_broken_resource_count{dataplane="https://10.244.0.140:8444"} 0
ingress_controller_fallback_configuration_push_broken_resource_count{dataplane="https://10.244.0.141:8444"} 0
# HELP ingress_controller_fallback_configuration_push_count Count of successful/failed fallback configuration pushes to Kong. `dataplane` describes the dataplane that was the target of configuration push. `protocol` describes the configuration protocol (`db-less` or `deck`) in use. `success` describes whether there were unrecoverable errors (`false`) or not (`true`). `failure_reason` is populated in case of `success="false"` and describes the reason of failure (one of `conflict`, `network`, `other`).
# TYPE ingress_controller_fallback_configuration_push_count counter
ingress_controller_fallback_configuration_push_count{dataplane="https://10.244.0.140:8444",failure_reason="",protocol="db-less",success="true"} 1
ingress_controller_fallback_configuration_push_count{dataplane="https://10.244.0.141:8444",failure_reason="",protocol="db-less",success="true"} 1
# HELP ingress_controller_fallback_configuration_push_duration_milliseconds How long it took to push the fallback configuration to Kong, in milliseconds. `dataplane` describes the dataplane that was the target of configuration push. `protocol` describes the configuration protocol (`db-less` or `deck`) in use. `success` describes whether there were unrecoverable errors (`false`) or not (`true`).
# TYPE ingress_controller_fallback_configuration_push_duration_milliseconds histogram
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="0.005"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="0.01"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="0.025"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="0.05"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="0.1"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="0.25"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="0.5"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="1"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="2.5"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="5"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="10"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true",le="+Inf"} 1
ingress_controller_fallback_configuration_push_duration_milliseconds_sum{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true"} 13
ingress_controller_fallback_configuration_push_duration_milliseconds_count{dataplane="https://10.244.0.140:8444",protocol="db-less",success="true"} 1
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="0.005"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="0.01"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="0.025"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="0.05"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="0.1"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="0.25"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="0.5"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="1"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="2.5"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="5"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="10"} 0
ingress_controller_fallback_configuration_push_duration_milliseconds_bucket{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true",le="+Inf"} 1
ingress_controller_fallback_configuration_push_duration_milliseconds_sum{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true"} 12
ingress_controller_fallback_configuration_push_duration_milliseconds_count{dataplane="https://10.244.0.141:8444",protocol="db-less",success="true"} 1
# HELP ingress_controller_fallback_configuration_push_last The time of the last successful fallback configuration push. `dataplane` describes the dataplane that was the target of the configuration push.
# TYPE ingress_controller_fallback_configuration_push_last gauge
ingress_controller_fallback_configuration_push_last{dataplane="https://10.244.0.140:8444"} 1.718034215980832e+09
ingress_controller_fallback_configuration_push_last{dataplane="https://10.244.0.141:8444"} 1.7180342159803948e+09
# HELP ingress_controller_fallback_translation_broken_resource_count The number of resources that the controller cannot successfully translate to Kong configuration in fallback mode.
# TYPE ingress_controller_fallback_translation_broken_resource_count gauge
ingress_controller_fallback_translation_broken_resource_count 0
# HELP ingress_controller_fallback_translation_count Count of translations from Kubernetes state to Kong state in fallback mode. `success` describes whether there were unrecoverable errors (`false`) or not (`true`). Unrecoverable error in this case means KIC wasn't able to translate a Kubernetes object to Kong model.
# TYPE ingress_controller_fallback_translation_count counter
ingress_controller_fallback_translation_count{success="true"} 1
```

The related objects are excluded from the configuration:

```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: rate-limit-user-1,rate-limit-user-2
username: consumer1
credentials:
- consumer1-auth
```

```
curl -k https://localhost:8444/consumers
{"data":[],"next":null}%
```

Debug endpoints worked with the exception of `/debug/config/problems`. The above mentioned scenario should include the `HTTPRoute` IIUC but it only contained:

```
curl -s localhost:10256/debug/config/problems | jq .
{
  "hash": "",
  "brokenObjects": [
    {
      "UID": "d0bb0043-510d-470d-b0ea-b9cc97d29185",
      "Group": "configuration.konghq.com",
      "Kind": "KongPlugin",
      "Namespace": "default",
      "Name": "rate-limit-2"
    }
  ]
}
```

Will #6159 fix that or is this a different issue?
