### ISSUE TITLE
Subdomain wildcard certificate domains not working with HTTPS

### ISSUE THREAD

**Issue by pawandhiman10** [Kong/kubernetes-ingress-controller#6216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have added multiple wildcard certificates to the same gateway as below:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
  namespace: test-gateway
spec:
  gatewayClassName: test-gateway
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: gateway-ssl-certs-one-internal-tls
    port: 443
    protocol: HTTPS
    hostname: "*.one.internal.example.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: gateway-ssl-certs-one-internal
        namespace: secrets
    allowedRoutes:
      namespaces:
        from: All
  - name: gateway-ssl-certs-one-tls
    port: 443
    protocol: HTTPS
    hostname: "*.one.example.com"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: gateway-ssl-certs-one
        namespace: secrets
    allowedRoutes:
      namespaces:
        from: All
  - name: gateway-ssl-certs-tls
    port: 443
    protocol: HTTPS
    hostname: "*.[example.com](http://example.com/)"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: gateway-ssl-certs
        namespace: secrets
    allowedRoutes:
      namespaces:
        from: All
        ```
But HTTPS is only running successfully if we pass *.example.com domain and failing for others.
It is not working for both wildcard subdomain certificates (one level and two level).

### Expected Behavior

HTTPS to work successfully with `*.one.example.com` and `*.one.internal.example.com` domains.

### Steps To Reproduce

```markdown
Have shared the yaml code as above.
```

### Kong Ingress Controller version

```shell
v3.2.x (from Helm Chart 2.39.0 https://artifacthub.io/packages/helm/kong/kong)
```

### Kubernetes version

```shell
GKE cluster v1.29.4-gke.1043002
Gateway API v1.0.0
```
