### ISSUE TITLE
Routing  an IBM AppConnect using Custom path 

### ISSUE THREAD

**Issue by Rockyjr-git** [Kong/kubernetes-ingress-controller#6321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have deployed IBM AppConnect in the Anthos Bare Metal Cluster and Kong Ingress Controller is deployed using Helm chart. I want to route the AppConnect using custom path (/foo) instead of root path (/).
Curl -i http://<ip>/Echo is working, but blank is displayed with prefix /Echo. whereas it is working for root path.
Please suggest the steps or any documents for the custom path routing.
Tried using rewrite transformer, but it did not work.
![Screenshot 2024-07-16 180708](https://github.com/user-attachments/assets/2ca22eb1-9487-46b7-86e8-6bedc0e2b322)

### Expected Behavior

Expected to work on the Custom path (/Echo)

### Steps To Reproduce

```markdown
Anthos Bare metal Cluster on the Air Gapped Environment.
```

### Kong Ingress Controller version

```shell
v3.1
```

### Kubernetes version

v1.27

**Comment by randmonkey** [comment]
Do you want the requests to `/Echo/*` to be forwarded to `/foo/*`? You can use the `konghq.com/rewrite` annotation: https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/requests/rewrite-annotation/. The feature needs you to set `RewriteURIs` feature gate to `true`. KIC 3.1 supports the feature.

**Comment by Rockyjr-git** [comment]
@randmonkey Thanks for the suggestion.

IBM AppConnect web page is displaying blank screen after adding the annotation. Can you Please help me here.

![Screenshot 2024-07-17 190243](https://github.com/user-attachments/assets/24e1323e-8db9-4ed5-84ca-e5c120049d2a)
![Screenshot 2024-07-17 190159](https://github.com/user-attachments/assets/68439136-d543-4978-ad34-100982a26228)

**Comment by randmonkey** [comment]
@Rockyjr-git Did you enable the `RewirteURIs` feature gate? If the feature gate is not enabled, the rewrite does not take effect. 
Please look at this doc to configure feature gates in KIC: https://docs.konghq.com/kubernetes-ingress-controller/3.1.x/reference/feature-gates/.

**Comment by Rockyjr-git** [comment]
@randmonkey Rewriteuri is already enabled, IBM AppConnect is working on root path. I am trying to route to other than root path.
![rewrite-uri](https://github.com/user-attachments/assets/a0ad582e-2842-4d59-848f-98f5bd65ff12)

**Comment by randmonkey** [comment]
@Rockyjr-git Similar to the example in the doc https://docs.konghq.com/kubernetes-ingress-controller/3.1.x/guides/requests/rewrite-annotation/ , you can define your `Ingress` like this to keep your path after the matched prefix:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ace-ingress-rewrite
  namespace: appconnect
  annotations:
    konghq.com/rewrite: "/$1"
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /~/echo/(\w+)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ace-service-7600
            port:
              number: 7600
```
