### ISSUE TITLE
Consumer Declaration Config Broken

### ISSUE THREAD

**Issue by HsinHeng** [Kong/kubernetes-ingress-controller#640]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.8.1

**Kong or Kong Enterprise version**
2.0.0
2.0.4

### Kubernetes version
1.15

**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-ee8ff", GitCommit:"ee8ffc99be2f6c6caab3cfe890227151b37faf8d", GitTreeState:"clean", BuildDate:"2019-09-24T21:49:34Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
### Environment

- **Cloud provider or hardware configuration**:
aws eks
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
apply hmac plugin/secret/consumer

### Expected behavior
enable hmac plugin

### Steps To Reproduce

1. apply followd yaml
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: hmac-auth
  namespace: dev
  labels:
    global: "false"
  annotations:
    kubernetes.io/ingress.class: "dev"
plugin: hmac-auth
config:
  enforce_headers: ["x-request-id", "date"]
  algorithms: ["hmac-sha256"]
  validate_request_body: false
```
```
apiVersion: v1
kind: Secret
metadata:
  name: hmac-secret
  namespace: dev
type: Opaque
data:
  kongCredType: ".."
  username: "..."
  secret: "..."
```
```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: hmac-auth-consumer
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "dev"
    konghq.com/plugins: hmac-auth
username: hmac-auth-consumer
credentials:
  - hmac-secret
```
2. ingress controller error log
```
err posting new config to /config: 400 Bad Request {"fields":{"plugins":[{"consumer":"value must be null"}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {plugins={{consumer=\"value must be null\"}}}"}
```

is  it a bug of consumer yaml username parse error?
