### ISSUE TITLE
ConfigPatch not working as expected for rate limiting plugin

### ISSUE THREAD

**Issue by meadows12** [Kong/kubernetes-ingress-controller#6446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to deploy rate-limiting plugin referring secret to extract redis password. Below is my configuration 
```
apiVersion: v1
kind: Secret
metadata:
  name: rate-limiting-redis-secret
  namespace: exmaple
type: Opaque
stringData:
  redis_password: '\"PASSWORD\"'
```
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: example-1-rate-limiting
config:
  redis:
    database: 1
    host: "redis-master.dummy.svc.cluster.local"
    port: 6379
  strategy: redis
  sync_rate: 0
  namespace: example
  limit:
    - 2
  window_size:
    - 10
  window_type: sliding
  identifier: ip
plugin: rate-limiting
configPatches:
  - path: /redis/password
    valueFrom: 
      secretKeyRef:
        name: rate-limiting-redis-secret # This is the name of the secret.
        key: redis_password 
```

I am using the below versions of kong 
kong-ingresscontoller tag version `3.1` 
kong-proxy image version `3.6.1.5`
kong chart version `2.38`

When I try to apply these changes, I am getting below error from validation webhook of kong. 

> admission webhook "validations.kong.konghq.com" denied the request: could not parse plugin configuration: invalid state detected

### Expected Behavior

Kongplugin should be installed successfully, using secret as reference for passwords.

### Kong Ingress Controller version

```shell
Tag version 3.1
```

### Kubernetes version

```shell
1.29
```

**Comment by randmonkey** [comment]
@meadows12 Can you confirm the namespaces of your `Secret` and `KongPlugin`? Looks like `Secret` is in `exmaple` (misspell of `example`?) but `KongPlugin` does not have a namespace.  They must be in the same namespace to correctly reference the secret.

**Comment by meadows12** [comment]
@randmonkey its installed in same namespace, I can confirm that. I tried using same configuration as mentioned in kong plugin [document](https://docs.konghq.com/kubernetes-ingress-controller/3.1.x/guides/security/plugin-secrets/), but still getting the same error. 

This is the config: 
```
apiVersion: v1
kind: Secret
metadata:
  name: rate-limit-redis
  namespace: default
stringData:
  password: '\"PASSWORD\"'
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  namespace: default
  name: rate-limiting-example
plugin: rate-limiting
config: # You can define the non-sensitive part of the config explicitly here.
  minute: 10
  policy: redis
  redis_host: redis-master
configPatches:
  - path: /redis_password # This is the path to the field in the plugin's configuration this patch will populate.
    valueFrom:
      secretKeyRef:
        name: rate-limit-redis # This is the name of the secret.
        key: password 

```

**Comment by randmonkey** [comment]
Changing your `Secret` to this could work. single quoted string does not require the `\` to escape.
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: rate-limit-redis
  namespace: default
stringData:
  password: '"PASSWORD"'
```
