### ISSUE TITLE
Method not found for PUT /upstream for route registration using ingress controller

### ISSUE THREAD

**Issue by onfla11** [Kong/kubernetes-ingress-controller#666]
kong version 0.14.1
kong ingress controller : 0.8.1
using Cassandra as backed-db.

 ```
- env:
        - name: CONTROLLER_KONG_ADMIN_URL
          value: https://0.0.0.0:8444
        - name: CONTROLLER_KONG_ADMIN_TLS_SKIP_VERIFY
          value: "true"
        - name: CONTROLLER_PUBLISH_SERVICE
          value: kong/kong-proxy
```
Created required CRDs and tried following sample examples(https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md) to create routes using ingress. Running into following issue when created Ingress for echo-service.

Method not found for PUT /upstreams

```
127.0.0.1 [15/May/2020:04:03:15 +0000] "PUT /upstreams/9ef5acc0-8877-4df1-892c-5b89145a9f94 HTTP/1.1" 405 "Go-http-client/1.1" 33 - - - - 0.000 de758e96f3815e94d0e855dec0d25cd9
2020/05/15 04:03:15 [error] 337#0: *499 lua coroutine: runtime error: don't know how to respond to PUT
stack traceback:
coroutine 0:
	[C]: ?
coroutine 1:
	[C]: in function 'resume'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:215: in function 'serve_admin_api'
	content_by_lua(nginx.conf:332):4: in function <content_by_lua(nginx.conf:332):1>, client: 127.0.0.1, server: , request: "PUT /upstreams/9ef5acc0-8877-4df1-892c-5b89145a9f94 HTTP/1.1", host: "0.0.0.0:8444"
```
service object is created successfully. Error on route creation.

```
{
   "next" : null,
   "data" : [
      {
         "retries" : 5,
         "read_timeout" : 60000,
         "connect_timeout" : 60000,
         "host" : "echo.sample-system.80.svc",
         "updated_at" : 1589517547,
         "port" : 80,
         "protocol" : "http",
         "path" : "/",
         "write_timeout" : 60000,
         "name" : "sample-system.echo.80",
         "id" : "164db3b3-d91a-402f-aa0f-2e7d3f6c5707",
         "created_at" : 1589517547
      }
   ]
}
```

Could you please help with some pointers? Thanks
