### ISSUE TITLE
is there possiable to set different config args to kongplugin use extensionRef or annotations in HttpRoute 

### ISSUE THREAD

**Issue by miniboxhaha** [Kong/kubernetes-ingress-controller#6682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### assume a plugin like below
```
--schema.lua
return {
    name = "myheader",
    fields = {{
        config = {
            type = "record",
            fields = {{
                header_value = {
                    type = "string",
                    default = "roar"
                }
            }}
        }
    }}
}

-- handler.lua
local MyHeader = {}
MyHeader.PRIORITY = 1000
MyHeader.VERSION = "1.0.0"
function MyHeader:header_filter(conf)
    -- do custom logic here
    kong.response.set_header("myheader", conf.header_value)
end

return MyHeader
```
#### create a configmap and install with helm
```
deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: "{{ .Release.Name }}-gateway-proxy"

  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true
    image:
      repository: registry.cluster.local:30443/kong/kubernetes-ingress-controller
      tag: "3.3.1"

    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

  podAnnotations:
    kuma.io/gateway: enabled
    # This port must match your Kong admin API port. 8444 is the default.
    # If you set gateway.admin.tls.containerPort, change these annotations
    # to use that value.
    traffic.kuma.io/exclude-outbound-ports: "8444"
    traffic.sidecar.istio.io/excludeOutboundPorts: "8444"

gateway:
  # replicaCount: 2
  plugins:
    configMaps:
      - name: my-kong-pluning-header
        pluginName: my-header
  proxy:
    type: NodePort
    http:
      nodePort: 32000
  enabled: true
  image:
    repository: registry.cluster.local:30443/kong
    tag: "3.7"
  deployment:
    kong:
      enabled: true

  admin:
    enabled: true
    # type: ClusterIP
    # clusterIP: None
    http:
      enabled: true
      nodePort: 32080
      servicePort: 32080
      containerPort: 32080

  ingressController:
    enabled: false

  env:
    role: traditional
    database: "off"

``` 

#### create two Service
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/upstream-policy: 'consistent-hashing-up-stream-policy'
  namespace: ha
  name: test-app-service1
spec:
  type: ClusterIP
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/upstream-policy: 'consistent-hashing-up-stream-policy'
  namespace: ha
  name: test-app-service2
spec:
  type: ClusterIP
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
```

#### create httproute
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: ha
  annotations:
    konghq.com/strip-path: 'true'
    #konghq.com/plugins: my-header
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test_app1
    # filters:
    #     - type: ExtensionRef
    #       extensionRef:
    #         kind: KongPlugin
    #         name: my-header
    backendRefs:
    - name: test-app-service1
      kind: Service
      port: 3000
  ######################################################
  - matches:
    - path:
        type: PathPrefix
        value: /test_app2
    # filters:
    #     - type: ExtensionRef
    #       extensionRef:
    #         kind: KongPlugin
    #         name: my-header
    backendRefs:
    - name: test-app-service1
      kind: Service
      port: 3001
```

### Expected Behavior

like [doc](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/requests/rewrite-annotation/)
```
Alternatively, you can define this in a plugin configuration.
plugins:
- name: request-transformer
  service: SERVICE_NAME|ID
  config:
    replace:
      uri: "/requests/users_svc/$(uri_captures[1])"
```
but not in kong's declarative configuration, in httproute somewhere

**Comment by miniboxhaha** [comment]
#### update another question:
when i set dblessConfig sector in value.yaml with helm like below
```
deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: "{{ .Release.Name }}-gateway-proxy"

  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true
    image:
      repository: registry.cluster.local:30443/kong/kubernetes-ingress-controller
      tag: "3.3.1"

    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

  podAnnotations:
    kuma.io/gateway: enabled
    # This port must match your Kong admin API port. 8444 is the default.
    # If you set gateway.admin.tls.containerPort, change these annotations
    # to use that value.
    traffic.kuma.io/exclude-outbound-ports: "8444"
    traffic.sidecar.istio.io/excludeOutboundPorts: "8444"

gateway:
  # replicaCount: 2
  plugins:
    configMaps:
      - name: my-kong-pluning-header
        pluginName: my-header
  proxy:
    type: NodePort
    http:
      nodePort: 32000
  manager:
    type: NodePort
    http:
      nodePort: 32100
  
  enabled: true
  image:
    repository: registry.cluster.local:30443/kong
    tag: "3.7"
  dblessConfig:
    config: |
    _format_version: "1.1"
    _transform: true
    # 
    services:
    - name: my-first-service
      protocol: http
      port: 3000
      host: test-app-service.ha:3000
      path: /test_header
      # url: https://example.com
      # plugins:
      # - name: key-auth
      routes:
      - name: my-first-route
        paths:
        - /test_app
  deployment:
    kong:
      enabled: true

  admin:
    enabled: true
    # type: ClusterIP
    # clusterIP: None
    http:
      enabled: true
      nodePort: 32080
      servicePort: 32080
      containerPort: 32080

  ingressController:
    enabled: false

  env:
    role: traditional
    database: "off"

```
after pod running, i can't see any configuration in manager.
i try get services info use http api, and response:
```
{
	"data": [],
	"next": null
}
```
