### ISSUE TITLE
dblessConfig is not working

### ISSUE THREAD

**Issue by miniboxhaha** [Kong/kubernetes-ingress-controller#6718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i use helm to deploy KIC, set declarative configuration in value.yaml like below, but is not effectd
```
deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: "{{ .Release.Name }}-gateway-proxy"

  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true
    image:
      repository: registry.cluster.local:30443/kong/kubernetes-ingress-controller
      tag: "3.3.1"

    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

  podAnnotations:
    kuma.io/gateway: enabled
    # This port must match your Kong admin API port. 8444 is the default.
    # If you set gateway.admin.tls.containerPort, change these annotations
    # to use that value.
    traffic.kuma.io/exclude-outbound-ports: "8444"
    traffic.sidecar.istio.io/excludeOutboundPorts: "8444"

gateway:
  # replicaCount: 2
  plugins:
    configMaps:
    - name: my-kong-plugin-header
      pluginName: my-header
  proxy:
    type: NodePort
    http:
      nodePort: 32000
  manager:
    type: NodePort
    http:
      nodePort: 32100
  admin:
    enabled: true
    http:
      enabled: true
      nodePort: 32080
      servicePort: 32080
      containerPort: 32080
  enabled: true
  image:
    repository: registry.cluster.local:30443/kong
    tag: "3.7"
  dblessConfig:
    config: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: my-first-service
      protocol: http
      port: 3000
      host: my-first-upstreams
      path: /test_header
      routes:
      - name: my-first-route
        plugins:
        - name: my-header
          config: 
              header_value: haha
        paths:
          - /test_app/test_header
    upstreams: 
    - name: my-first-upstreams
      # properties:
      # algorithm: consistent-hashing
      # hash_on: ip
      targets:
      - target: test-app-service.ha:3000
  deployment:
    kong:
      enabled: true

  

  ingressController:
    enabled: false

  env:
    role: traditional
    database: "off"
```

but i can set this with http /config api with @kong.yml

**Comment by pmalek** [comment]
Hi 👋 

you're deploying with the ingress controller enabled. As per https://github.com/Kong/charts/blob/0b3ad20b750913006bd8cba30c998bd50f0e08e7/charts/kong/README.md?plain=1#L161-L169 this option is only for deployments without the ingress controller.

Secondly your config is not indented properly, it should be 

```
gateway:
  dblessConfig:
    config: |
      _format_version: "3.0"
      _transform: true

      services:
      - name: my-first-service
        protocol: http
        port: 3000
        host: my-first-upstreams
        path: /test_header
        routes:
        - name: my-first-route
          paths:
            - /test_app/test_header
```

Let us know if you have any other questions on this.
