### ISSUE TITLE
Set proper status on `GRPCRoute`, `TCPRoute`, `TLSRoute` and `UDPRoute`

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#6749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

For each of these routes, apply configuration that misses a target `Service`.

## `GRPCRoute`

```yml
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2024-12-02T10:13:37Z"
        message: ""
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-12-02T10:13:37Z"
        message: ""
        observedGeneration: 1
        reason: Unknown
        status: Unknown
        type: Programmed
      controllerName: konghq.com/kic-gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: example-udproute
        namespace: default
```

Expected message with proper level is logged

```txt
[ingress-controller] 2024-12-02T09:53:20Z        debug   Object requested backendRef to target, but it does not exist, skipping...       {"object_name": "gateway.networking.k8s.io/v1, Kind=GRPCRoute default/grpcbin-via-http", "target_kind": "Service", "target_namespace": "default", "target_name": "grpcbin-via-http", "v": 1}
```

but wrong status is set for this route

```yml
...
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-12-02T09:48:49Z"
      message: ""
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-12-02T09:48:50Z"
      message: ""
      observedGeneration: 1
      reason: ConfiguredInGateway
      status: "True"
      type: Programmed
    controllerName: konghq.com/kic-gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: default
...
```

## `TCPRoute`

```yml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: example-tcproute
  annotations:
    konghq.com/gatewayclass-unmanaged: "true"
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-tcproute
spec:
  gatewayClassName: example-tcproute
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: tcp
      protocol: TCP
      port: 8888
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcpecho
spec:
  parentRefs:
    - name: example-tcproute
  rules:
    - backendRefs:
        - name: tcpecho
          port: 8888
```

Nothing is logged and status is unkown

```yml
...
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-12-02T09:54:57Z"
      message: ""
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-12-02T09:54:57Z"
      message: ""
      observedGeneration: 1
      reason: Unknown
      status: Unknown
      type: Programmed
    controllerName: konghq.com/kic-gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: example-tcproute
      namespace: default
```

## `TLSRoute`

```yml
apiVersion: v1
kind: Secret
metadata:
  name: tlsroute-example
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGekNDQXYrZ0F3SUJBZ0lVZTFvWnRWQVBOM1V2bXRkSHo5OFpYcDd2a3Znd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZZ3hDekFKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJREFwRFlXeHBabTl5Ym1saE1SWXdGQVlEVlFRSApEQTFUWVc0Z1JuSmhibU5wYzJOdk1SSXdFQVlEVlFRS0RBbExiMjVuSUVsdVl5NHhHREFXQmdOVkJBc01EMVJsCllXMGdTM1ZpWlhKdVpYUmxjekVlTUJ3R0ExVUVBd3dWZEd4emNtOTFkR1V1YTI5dVp5NWxlR0Z0Y0d4bE1DQVgKRFRJME1EY3dOVEUwTlRjek5sb1lEekl4TWpRd05qRXhNVFExTnpNMldqQ0JpREVMTUFrR0ExVUVCaE1DVlZNeApFekFSQmdOVkJBZ01Da05oYkdsbWIzSnVhV0V4RmpBVUJnTlZCQWNNRFZOaGJpQkdjbUZ1WTJselkyOHhFakFRCkJnTlZCQW9NQ1V0dmJtY2dTVzVqTGpFWU1CWUdBMVVFQ3d3UFZHVmhiU0JMZFdKbGNtNWxkR1Z6TVI0d0hBWUQKVlFRRERCVjBiSE55YjNWMFpTNXJiMjVuTG1WNFlXMXdiR1V3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQgpEd0F3Z2dFS0FvSUJBUURleklnV1E4L1crYUx4VERPanZvOGY5OVpGYVBoOWQrTkFYQ1NmSTFLcS9TdVdrMnJyClcxKyt2QzA4MERWTnc4dmx3Z0VRUUlhV3c2bVh6V2hQNmppdHIvemxSVGg4TWFwSFMvTXhXbjN0WnFKZ3ZVdVoKMkFnMTBXUE14UHV4UUlaU2FucU95M0RNeDJDcGlMQ1c0SVBERlRhQm5XT1hOeFg4bEMvQit6QlZYYzBIYVdUUwpqUFViUUZONGVGcEFtcHlxak1Dak53Y1VSd3BBVSs0cXpDeVZ2ZU5VU0RLWHpoN04rUDlPRkFiVjNqL0IyOXpqCk9sVFZKNTUvZ2VUeGJqZVZCa0ZDZXAvQkh4UEY4MnhtWUJOQnJ2WVU5dFkyc0JCZmh6OGFUNFJaMmx5NXJxVnYKRnZ4TDF1R3ZmU29CeUdoVTVFWDg0NmZVYm5uc2xJSDdBKzdOQWdNQkFBR2pkVEJ6TUIwR0ExVWREZ1FXQkJTdwp2c2VNR08wN1JXMXpxVWNsOFZEeXY2M25HakFmQmdOVkhTTUVHREFXZ0JTd3ZzZU1HTzA3UlcxenFVY2w4VkR5CnY2M25HakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQ0FHQTFVZEVRUVpNQmVDRlhSc2MzSnZkWFJsTG10dmJtY3UKWlhoaGJYQnNaVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBa3JJQWp6Ulhadm51bjAvMGc2NHNnK0laaDZXLwo0UWFsYklwWlh0Z2JrKzE3d1FVN0hrTFNaS2tmL2IwZHlTR1RpLzBDMUdYK1lxRTlKb2NtWjdjUWI2Y0RheDl3CjBUeFZ1NVRxYWVTQVlLZktGZlExcjB5VzhjYVc3TFhoYVZ3Lzh2YTVQMWRzdnkwNUs0K3dydCtBK1NudFRxL2EKYzV2T0ZQcmk3ZlBMWEZ5SVE5eXhVZXdSYnphdUY2SEE5eDY4bWt3WUVvSTUxMnM1SjBtUVByUGhPN1VhRnFwVApQL3NqdXdHNk1qR0t1MzU2VXJKTGlFV1NkZmtiTkU0bGFLa3Z2U0paMjh3MXVGemsrOUl5QWpiRzQ3RXl3dTVICjJ0ZzZzV3VTa29xT2hwc3JTMjBteFlkVHU0dVpWZXdlR1FjbmZXUGNjNlRQME8vQzZCZGpRVFB3Nmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRGV6SWdXUTgvVythTHgKVERPanZvOGY5OVpGYVBoOWQrTkFYQ1NmSTFLcS9TdVdrMnJyVzErK3ZDMDgwRFZOdzh2bHdnRVFRSWFXdzZtWAp6V2hQNmppdHIvemxSVGg4TWFwSFMvTXhXbjN0WnFKZ3ZVdVoyQWcxMFdQTXhQdXhRSVpTYW5xT3kzRE14MkNwCmlMQ1c0SVBERlRhQm5XT1hOeFg4bEMvQit6QlZYYzBIYVdUU2pQVWJRRk40ZUZwQW1weXFqTUNqTndjVVJ3cEEKVSs0cXpDeVZ2ZU5VU0RLWHpoN04rUDlPRkFiVjNqL0IyOXpqT2xUVko1NS9nZVR4YmplVkJrRkNlcC9CSHhQRgo4MnhtWUJOQnJ2WVU5dFkyc0JCZmh6OGFUNFJaMmx5NXJxVnZGdnhMMXVHdmZTb0J5R2hVNUVYODQ2ZlVibm5zCmxJSDdBKzdOQWdNQkFBRUNnZ0VBR2V4dmV6TzV0N2hGT3RGVWd0MTExdERtQ0I1K0owOHZUSHBNTW80UUhPQW4KVmJaaWJ1OHJWVXljOE9JRENjRFo5U3BkS0ZCeHVKSWNwaEthN0EyRE9jWnI1UnRvUnA4YXduLzJWSXhFY2I2Swo3em1uVmNlNnNOUmp5ZHd6c3Z5Z2hHOXFRam91cmswV2xMTllaTDNMNXdPTlc0aCtJWWFoMHNsRlEwdGdaTlkxCkNSSEZ5ZThnSHlBV2pEMWpqNitNVFFPZ2tGVTJoZmhuMThsTXh3NG9OZnp6a1dKcVlsWXFZa0ZUSGpZTnYwS3UKWWV0dkQxNWRjd05uYXhxQTF6WFlUVDNGYkpBT3h3Y2pXNlF4V3A5K3JTbzFlc2FHYWxKT2RIVWlmUmlkT1Q5YgowdndxT2gwM3phck91Z3lHdS9uQUZqcTFpRVN4dVBuV2EwUmhRSEZKMFFLQmdRRCtOV0F4aUtSYmFpaFQ2OWlUCm5CbjlMNXU4eTZPQmRNK3J3dHh0blkzTlRnTHEvOVFGdEZ4ZDlFNTRwWGFha0Z3WE5Qb1VHSzJBd1MyOVVoblcKcHY1ekhiSW56S2lHUFpBdnNSaHdxbjRVTGQrZ1dId2QwTFdBblQ5U3RGNlpxRkIvV250ak02OEtpcTVwa29SdQo5amFoeFJqK1oyT3Z0Qzg1OFJXR1hraWdWUUtCZ1FEZ1huMHg0M2ZEc3J0UmI2ZHJqM2RYUkFWU3ZKTk8vdTN1CjhTN215REtRRnFCaEpWWXYyZC94MFNwZTdPMWtUZlEvSDdKVTVGbzFaL1hXSmh0MjAxR0U0UEUxZHVtU1VYMHYKanNrZm1ET0lISFZidG1jYnJMVGtLbThKUHNiQnhqL2FrdXJucFljUlprcjcvTE5wb2xLMWw0b0dSWERjd21tYQpuMFBQOVZlc21RS0JnR05ZWUx0Njl5QnlvRWdMeDV3SVNXL1ZCendGS1dVU1RZYUdwTGFCK0VUZjArd2JCclVrCkEyVUVjUlpkTTdpNzZnRjN4clBMNFNLTVhGKzhralI5RnJ2T1F5MmlvY20wallEVjZRTSszZjdzM3BRL2dHSDIKaXJnMHUrYUtidDRHRlU5d0FRQ0gxa1I4WmlVRUNaV0R5MTMxTlF0WFJISUtMTnFzQ1FsMkYxUHhBb0dBZWlwNAp1SVZHWE1RZ3drS3RRaCtudDFoT0hiS1g4dGRUN2xwY1UwU0dZM1l1ZFRiREt1TFMwUFEyd2VEM2tUbncxNzRHCmQ3cXVjNDNiaVhMT1dYRE9YaStzcHBQTXNlSzA2d1F2OW9nRTV3TzMwdXdLVUVORmEwYS9scVVieTc2S1hoVEkKMnNDQ1ByTVgrUVNyRzhWS2k1MnJoYWFod1ZJSjlpcnAzWDJVODJFQ2dZQnRCQjdzejc1SU1wbThqelduQmh3SAo5YVlRQTVqczd0NXRpT3I4OXNaR0xmUDg5dDdrR0RPajA1S1B0OCtrS1lEdXdFVUxZOGpzNnpUcmdvdStBQlEyCmNlSjFoVmZxWC8yTWYvb3F1eUEzS2dMemRLS0M2clFCY1hTVUR2SVR2SlFuWHV3eGsyQS9nZ09jNTZoRW1sNm4KdXdqN1JPQkRiUzNaVUwyZXFYb2s3QT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kong
  annotations:
    konghq.com/gatewayclass-unmanaged: "true"
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kong
spec:
  gatewayClassName: kong
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: tls
      protocol: TLS
      port: 8899
      hostname: tlsroute.kong.example
      tls:
        mode: Passthrough
        certificateRefs:
          - name: tlsroute-example
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: tlsecho
spec:
  parentRefs:
    - name: kong
  hostnames:
    - tlsroute.kong.example
  rules:
    - backendRefs:
        - name: tlsecho
          port: 8899
```

The below is constantly logged

```txt
[ingress-controller] 2024-12-02T10:31:30Z        debug   controllers.TLSRoute    Listener is not ready   {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "parentRef.gateway": "default/kong", "listener": "tls", "v": 1, "reason": "listener not programmed yet"}
[ingress-controller] 2024-12-02T10:31:30Z        debug   controllers.TLSRoute    Checking if the tlsroute's gateways are ready   {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "tlsecho"}
[ingress-controller] 2024-12-02T10:31:30Z        debug   controllers.TLSRoute    Ensuring status contains Gateway associations   {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "tlsecho"}
[ingress-controller] 2024-12-02T10:31:30Z        debug   controllers.TLSRoute    TLSRoute not configured, requeueing     {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "tlsecho"}
[ingress-controller] 2024-12-02T10:31:31Z        debug   controllers.TLSRoute    Processing tlsroute     {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "tlsecho"}
[ingress-controller] 2024-12-02T10:31:31Z        debug   controllers.TLSRoute    Checking deletion timestamp     {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "tlsecho"}
[ingress-controller] 2024-12-02T10:31:31Z        debug   controllers.TLSRoute    Retrieving GatewayClass and Gateway for route   {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "tlsecho"}
[ingress-controller] 2024-12-02T10:31:31Z        debug   controllers.TLSRoute    Listener does not support this route    {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "parentRef.gateway": "default/kong", "listener": "http", "v": 1, "reason": "unsupported route kind"}
[ingress-controller] 2024-12-02T10:31:31Z        debug   controllers.TLSRoute    Listener is not ready   {"GatewayV1Alpha2TLSRoute": {"name":"tlsecho","namespace":"default"}, "parentRef.gateway": "default/kong", "listener": "tls", "v": 1, "reason": "listener not programmed yet"}
```

status is unknown

```yml
...
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-12-02T10:31:30Z"
      message: ""
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-12-02T10:31:30Z"
      message: ""
      observedGeneration: 1
      reason: Unknown
      status: Unknown
      type: Programmed
    controllerName: konghq.com/kic-gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: default
```

## `UDPRoute`

```yml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: example-udproute
  annotations:
    konghq.com/gatewayclass-unmanaged: "true"
spec:
  controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-udproute
spec:
  gatewayClassName: example-udproute
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: udp
      protocol: UDP
      port: 9999
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: udpecho
spec:
  parentRefs:
    - name: example-udproute
  rules:
    - backendRefs:
        - name: udpecho
          port: 9999
---
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2024-12-02T10:13:37Z"
        message: ""
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-12-02T10:13:37Z"
        message: ""
        observedGeneration: 1
        reason: Unknown
        status: Unknown
        type: Programmed
      controllerName: konghq.com/kic-gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: example-udproute
        namespace: default
```

logs constantly

```txt
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    Processing udproute     {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "udpecho"}
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    Checking deletion timestamp     {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "udpecho"}
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    Retrieving GatewayClass and Gateway for route   {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "udpecho"}
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    Listener does not support this route    {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "parentRef.gateway": "default/example-udproute", "listener": "http", "v": 1, "reason": "unsupported route kind"}
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    Listener is not ready   {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "parentRef.gateway": "default/example-udproute", "listener": "udp", "v": 1, "reason": "listener not programmed yet"}
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    Checking if the udproute's gateways are ready   {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "udpecho"}
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    Ensuring status contains Gateway associations   {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "udpecho"}
[ingress-controller] 2024-12-02T10:36:20Z        debug   controllers.UDPRoute    UDPRoute not configured, requeueing     {"GatewayV1Alpha2UDPRoute": {"name":"udpecho","namespace":"default"}, "v": 1, "namespace": "default", "name": "udpecho"}
[ingress-controller] 2024-12-02T10:36:23Z        debug   controllers.KongLicense No KongLicense available        {"v": 1}
```

and status is 

```yml
status:
  parents:
  - conditions:
    - lastTransitionTime: "2024-12-02T10:35:39Z"
      message: ""
      observedGeneration: 1
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-12-02T10:35:39Z"
      message: ""
      observedGeneration: 1
      reason: Unknown
      status: Unknown
      type: Programmed
    controllerName: konghq.com/kic-gateway-controller
    parentRef:
      group: gateway.networking.k8s.io
      kind: Gateway
      name: example-udproute
      namespace: default
```

### Proposed Solution

It works the same way as for `HTTPRoute`, see https://github.com/Kong/kubernetes-ingress-controller/pull/6746

### Acceptance Criteria

- [ ] proper staus for object is reported
- [ ] informative debug level logs
