### ISSUE TITLE
`ExtensionRef` plugins on `HTTPRoute`s may cause errors like `uniqueness violation: 'plugins' entity with primary key set to ...`

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#6761]
### Problem statement

Setting an `ExtensionRef` plugin on `HTTPRoute` like so:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth-plugin
  namespace: default
config:
  hide_credentials: true
plugin: basic-auth
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo
    filters:
    - type: ExtensionRef
      extensionRef:
        group: configuration.konghq.com
        kind: KongPlugin
        name: basic-auth-plugin
    backendRefs:
    - name: echo
      kind: Service
      port: 1027
```

leads to errors like:

```
2024-12-03T07:47:50Z    error   recording a Warning event for object    {"name": "basic-auth-plugin", "namespace": "default", "kind": "KongPlugin", "apiVersion": "configuration.konghq.com/v1", "reason": "KongConfigurationApplyFailed", "me
ssage": "invalid plugin:basic-auth: uniqueness violation: 'plugins' entity with primary key set to '7eaf1096-7fcb-5391-8533-51de677513fb' already declared", "error": "object failed to apply"}
2024-12-03T07:47:50Z    error   dataplane-synchronizer  Could not update kong admin     {"error": "performing update for https://10.244.0.4:8444/ failed: HTTP status 400 (message: \"failed posting new config to /config\")"}
```

### Anything else

This seems to happen becuase [`SetRoutePlugins`](https://github.com/Kong/kubernetes-ingress-controller/blob/eb19b4edab38af6c6072fd03e4a7ff995f9d6e40/internal/dataplane/translator/subtranslator/httproute.go#L862) (specifically [`generateKongRouteModifierFromExtensionRef`](https://github.com/Kong/kubernetes-ingress-controller/blob/eb19b4edab38af6c6072fd03e4a7ff995f9d6e40/internal/dataplane/translator/subtranslator/httproute.go#L1033) works on the `*kongstate.Route` object's `Annotations` which share the underlying `map` with the `HTTPRoute` via:

- https://github.com/Kong/kubernetes-ingress-controller/blob/eb19b4edab38af6c6072fd03e4a7ff995f9d6e40/internal/dataplane/translator/translate_httproute.go#L233-L234
- https://github.com/Kong/kubernetes-ingress-controller/blob/eb19b4edab38af6c6072fd03e4a7ff995f9d6e40/internal/dataplane/translator/subtranslator/httproute.go#L325-L326
- https://github.com/Kong/kubernetes-ingress-controller/blob/eb19b4edab38af6c6072fd03e4a7ff995f9d6e40/internal/dataplane/translator/subtranslator/httproute.go#L305

depending on the code path.

This can be solved via deep copying the annotations map in [`FromK8sObject`](https://github.com/Kong/kubernetes-ingress-controller/blob/fbfdbeb0f0e8d7d184f5e1d298cee6c0159e188b/internal/util/objectmeta.go#L32) or deduplicating the annotations in `generateKongRouteModifierFromExtensionRef`.

The latter solution wouldn't solve the problem of saving the annotations on the route in the store (which is done via `UpdateCache` in `internal/dataplane/kong_client.go`) so the proposal is to solve this with deep copying the annotations.

### Acceptance criteria

- [ ] `ExtensionRef` plugins set on `HTTPRoute` do not cause errors.
```
