### ISSUE TITLE
Custom entities: using unknown field doesn't create a corresponding Kubernetes event

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#6793]
### Problem statement

When using `KongCustomEntity` with invalid fields, e.g. :

```
apiVersion: configuration.konghq.com/v1alpha1
kind: KongCustomEntity
metadata:
  namespace: default
  name: degraphql-route-example
  annotations:
    a: a
spec:
  type: degraphql_routes
  fields:
    uri: /contacts
    queryy: "query{ contacts { name } }" # Mark the misspelled field name 
  controllerName: kong
  parentRef:
    group: configuration.konghq.com
    kind: KongPlugin
    name: degraphql-example
```

Kubernetes event is not created.

This is a consequence of the response body not having the appropriate tags. The response from Kong has the following body:

```
{
  "message": "declarative config is invalid: {}",
  "name": "invalid declarative configuration",
  "fields": {},
  "code": 14,
  "flattened_errors": [
    {
      "entity": {
        "uri": "/contacts",
        "service": {
          "id": "93e37996-f51b-5d53-8776-529c3bfd6421"
        },
        "queryy": "query{ contacts { name } }"
      },
      "entity_type": "degraphql_route",
      "errors": [
        {
          "type": "field",
          "message": "unknown field",
          "field": "queryy"
        },
        {
          "type": "field",
          "message": "required field missing",
          "field": "query"
        }
      ]
    }
  ]
}
```

Which KIC cannot use to produce an event because of lack of metadata to use to match the offending resource.

### More information

Providing the tags does make Kong return them in the response but also returns an `unknown field` error:

```
{
  "message": "declarative config is invalid: {}",
  "name": "invalid declarative configuration",
  "fields": {},
  "code": 14,
  "flattened_errors": [
    {
      "entity": {
        "tags": [
          "k8s-name:c1",
          "k8s-namespace:default",
          "k8s-kind:KongConsumer",
          "k8s-uid:aebfbebc-6145-4428-9ac6-e408737f52b4",
          "k8s-group:configuration.konghq.com",
          "k8s-version:v1"
        ],
        "uri": "/contacts",
        "service": {
          "id": "93e37996-f51b-5d53-8776-529c3bfd6421"
        },
        "queryy": "query{ contacts { name } }"
      },
      "entity_type": "degraphql_route",
      "entity_tags": [
        "k8s-name:c1",
        "k8s-namespace:default",
        "k8s-kind:KongConsumer",
        "k8s-uid:aebfbebc-6145-4428-9ac6-e408737f52b4",
        "k8s-group:configuration.konghq.com",
        "k8s-version:v1"
      ],
      "errors": [
        {
          "type": "field",
          "message": "unknown field",
          "field": "tags"
        },
        {
          "type": "field",
          "message": "unknown field",
          "field": "queryy"
        },
        {
          "type": "field",
          "message": "required field missing",
          "field": "query"
        }
      ]
    }
  ]
}
```

Probable direction forward is to discuss with Gateway whether this can be made possible. If yes, then implement setting tags on configuration generation from `KongCustomEntity`. If not, then document that events are not going to be triggered for invalid fields in `KongCustomEntity`.

Related: #6629

### Acceptance criteria

- [ ] As a user I can expect that a Kubernetes event is created when I create `KongCustomEntity` with invalid fields
