### ISSUE TITLE
Custom entities: invalid objects do not cause status conditions' update

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#6794]
### Problem statement

When providing invalid configuration of `KongCustomEntity` like:

```
apiVersion: configuration.konghq.com/v1alpha1
kind: KongCustomEntity
metadata:
  namespace: default
  name: degraphql-route-example
  annotations:
    a: a
spec:
  type: degraphql_routes
  fields:
    uri: /contacts
    queryy: "query{ contacts { name } }" # Mark the misspelled field name 
  controllerName: kong
  parentRef:
    group: configuration.konghq.com
    kind: KongPlugin
    name: degraphql-example
```

The status conditions are not updated properly.

- When invalid object is created then it retains 
    ```
    status:
      conditions:
      - lastTransitionTime: "2024-12-08T21:58:37Z"
        message: Object is pending configuration in Kong.
        observedGeneration: 1
        reason: Pending
        status: "False"
        type: Programmed
    ```

- When invalid configuration is applied after a successful config then previous `observedGeneration` can be observed on `Programmed` condition:

### Acceptance criteria

- [ ] As a user I expect the status conditions of `KongCustomEntity` to be updated
