### ISSUE TITLE
Point to K8s Events emitted for misconfigured objects in their statuses automatically

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#6842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

Discovered during work on 

- https://github.com/Kong/kubernetes-ingress-controller/pull/6814

that mechanism for setting appropriate values in the object's `status` field automatically when a K8s `Event` with Warning severity is generated for such an object is only implemented for generated controllers with the helper [EnsureProgrammedCondition](https://github.com/Kong/kubernetes-ingress-controller/blob/67c8a9596a3ec1c8d1d87a269c12eb491dbf25da/internal/controllers/utils/conditions.go#L36-L107).

Hence, for e.g. `HTTPRoute` in such a situation, something like this happens

```yml
...
  status:
    parents:
    - conditions:
      - lastTransitionTime: "2024-12-12T16:06:22Z"
        message: ""
        observedGeneration: 1
        reason: Accepted
        status: "True"
        type: Accepted
      - lastTransitionTime: "2024-12-12T16:06:22Z"
        message: ""
        observedGeneration: 1
        reason: ResolvedRefs
        status: "True"
        type: ResolvedRefs
      - lastTransitionTime: "2024-12-12T16:06:22Z"
        message: ""
        observedGeneration: 1
        reason: Unknown
        status: Unknown
        type: Programmed
      controllerName: konghq.com/kic-gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: kong
        namespace: default
```

having `reason` and `status` set to `Unknown` is not the best user experience. Even generic information is provided by the helper [EnsureProgrammedCondition](https://github.com/Kong/kubernetes-ingress-controller/blob/67c8a9596a3ec1c8d1d87a269c12eb491dbf25da/internal/controllers/utils/conditions.go#L36-L107) to check K8s `Event`s generated for a respective object is much better user experience. e.g.

### Proposed Solution

Adjust and reuse [EnsureProgrammedCondition](https://github.com/Kong/kubernetes-ingress-controller/blob/67c8a9596a3ec1c8d1d87a269c12eb491dbf25da/internal/controllers/utils/conditions.go#L36-L107) to provide properly set status for an object when a Warning K8s `Event` is registered for it. So for the example mentioned above instead of `Unknown` something like the below should be populated.

```yml
...
  status:
    conditions:
    - lastTransitionTime: "2024-12-06T14:35:10Z"
      message: Object failed to be configured in Kong - see its attached Events for
        more information.
      observedGeneration: 1
      reason: Invalid
      status: "False"
      type: Programmed
 ```

It's a baseline and a nice default. Of course, having as detailed as possible statuses in addition to K8s `Event` makes KIC easier to use. Actual handling should be decided case by case.

### Acceptance Criteria

- [ ] For any configured K8s object, when a K8s `Event` with severity Warning is emitted, `status` is set accordingly as it happens for cgenerated controllersgenerated
