### ISSUE TITLE
HTTPRoute requestRedirect filter adds a whitespace to the Location header

### ISSUE THREAD

**Issue by konsti** [Kong/kubernetes-ingress-controller#6851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have an `HTTPRoute` that should forward users from the root domain to a path under the same domain:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-example
  namespace: default
spec:
  hostnames:
    - demo.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: system
  rules:
    - filters:
        - requestRedirect:
            hostname: demo.example.com
            path:
              replaceFullPath: /path
              type: ReplaceFullPath
            port: 443
            scheme: https
            statusCode: 302
          type: RequestRedirect
      matches:
        - path:
            type: Exact
            value: /
```

It works, but the response from Kong adds an unnecessary whitespace in front of the redirect URL in the `Location` header:

```
➜ curl -I https://demo.example.com
HTTP/2 302
date: Tue, 17 Dec 2024 08:27:23 GMT
content-type: text/html
content-length: 110
location:  https://demo.example.com:443/path
vary: Origin
x-kong-response-latency: 0
server: kong/3.8.0
x-kong-request-id: b425e72301e97e288ee9511affc34b75
```

This is hard to spot, but the whitespace is there. Browsers like Chrome or Firefox ignore it and redirect correctly.
**Safari, however and mobile browsers** (I tested Chrome and Safari on iOS) **URL encode the whitespace** and interpret the `Location` header as a path `https://demo.example.com/%20https://demo.example.com:443/path` This of course does not work and leads to

```
Error

no Route matched with those values.

request_id: 47006b77756a8d438b57f07ef6eb9757
```

### Expected Behavior

Kong should not add a whitespace in front of the `Location` header when using the `requestRedirect` filter.

### Steps To Reproduce

```markdown
1. Setup Kong Ingress Controller
2. Create a gateway with a listener on 443
3. Add the HTTPRoute from this issue with a working domain.
```

### Kong Ingress Controller version

```shell
v3.3.1
```

### Kubernetes version

```shell
Server Version: v1.29.10
```

### Anything else?

Kong version: 3.8.0
