### ISSUE TITLE
js custom plugin problem with set get config args

### ISSUE THREAD

**Issue by miniboxhaha** [Kong/kubernetes-ingress-controller#6873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

custom plugin
```
'use strict';
// This is an example plugin that add a header to the response
const jwt = require('jsonwebtoken');

class KongPlugin {
  constructor(config) {
    this.config = config
  }

  async access(kong) {
      kong.response.setHeader("jwt-info1", this.config.permitrole)
    ])
  }
}

module.exports = {
  Plugin: KongPlugin,
  Schema: [
    { permitrole: { type: "string" } },
  ],
  Version: '0.1.0',
  Priority: 0,
}

```
KongPlugin and httproute 
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-jwt
config:
  permitrole: USER
plugin: myjwt

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: ha
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test_app
      method: GET
    filters:
    - type: ExtensionRef
      extensionRef: 
        group: configuration.konghq.com
        kind: KongPlugin
        name: my-jwt
    backendRefs:
    - name: test-app-service
      kind: Service
      port: 3000
```
logs
```
2024/12/19 02:32:28 [error] 1343#0: *1503 [kong] init.lua:409 [myjwt] ...cal/share/lua/5.1/kong/runloop/plugin_servers/mp_rpc.lua:157: invalid header value for "jwt-info1": got nil, expected array of string, string, number or boolean, client: 10.233.121.192, server: kong, request: "GET /test_app/test_header HTTP/1.1", host: "192.168.8.215:32000", request_id: "f5b53606dbc20e6d284900186c4ee
e3e"
```

but use declarative-config can works
```
dblessConfig:
    config: |
      _format_version: "3.0"
      _transform: true

      services:
      - name: my-first-service
        protocol: http
        port: 3000
        host: my-first-upstreams
        path: /test_header
        routes:
        - name: my-first-route
          plugins:
          - name: myjwt
            config:
              permitrole: USER
          paths:
            - /test_app/test_header
      upstreams: 
      - name: my-first-upstreams
        algorithm: consistent-hashing
        hash_on: ip
        targets:
        - target: test-app-service.ha:3000
```
