### ISSUE TITLE
KongIngress Service Upstream HTTPS

### ISSUE THREAD

**Issue by Ngob** [Kong/kubernetes-ingress-controller#69]
**Is this a request for help?**:

No

**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

- `kongingress`
- ssl

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug request
**Kong Ingress controller version**:

0.0.4

**Kubernetes version** (use `kubectl version`):

Server: v1.10.4-gke.0
Client : v1.9.7

**Environment**:

- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): I am using the Container Optimized OS provided by google:

```
BUILD_ID=10452.101.0
NAME="Container-Optimized OS"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=66
ID=cos
```

- **Kernel** (e.g. `uname -a`): Linux gke-prod-1-default-pool-560ebb10-xx4d 4.14.22+
- **Install tools**:  I used the basic getting started provided by your [blog](https://konghq.com/blog/kubernetes-ingress-controller-for-kong/) 
- **Others**:

**What happened**:

 I am trying to add an external service (a google cloud function https trigger) using https. I try to proxy my serverless function using kong. This is what I am trying to achieve:

     | Incoming Request | ----- http://foo.baz.local/foo -----> | Kong | ------ https:// myproject.cloudfunctions.net/foo-prod -----> | Google Function |

Using the following configuration, kong keep making request to the service through http.

    kind: Service
    apiVersion: v1
    metadata:
      name: fooservice
      namespace: foo
    spec:
      type: ExternalName
      externalName: myproject.cloudfunctions.net
      ports:
      - name: http
        port: 80
        protocol: TCP
      - name: https
        port: 443
        protocol: TCP

    ---
    apiVersion: configuration.konghq.com/v1
    kind: KongIngress
    metadata:
      name: foo-ingress
      namespace: foo
    proxy:
      path: /foo-prod
      protocol: https
    route:
      strip_path: true
    ---
    apiVersion: configuration.konghq.com/v1
    kind: KongPlugin
    metadata:
      name: transform-request-to-external
      namespace: foo
    config:
      remove:
        headers: host
    ---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: foo-ingress
      namespace: foo
      annotations:
        request-transformer.plugin.konghq.com: |
          transform-request-to-external
    spec:
      rules:
        - host: foo.baz.local
          http:
            paths:
            - path: /foo
              backend:
                serviceName: fooservice
                servicePort: https

Now if i run something similar to `curl -X GET --url http://localhost:8001/services` on the admin-api pods, it responds:

    {"next":null,"data":[{"host":"foo.fooservice.https","created_at":1530465759,"connect_timeout":60000,"id":"xxxx-2866-xxxx-92fb-xxxx","protocol":"http","name":"foo.fooservice.https","read_timeout":60000,"port":80,"path":"\/foo-prod","updated_at":1530465759,"retries":5,"write_timeout":60000}]}

The port used by kong is "443" (the correct target is configured) BUT the protocol is "http", how can I ensure kong is making theses requests through HTTPS? I tryed to add `ingress.kubernetes.io/secure-backends: "true"` (from NGINX ingress spec) but this does not work. I can notice `if upstream.Secure` in file https://github.com/Kong/kubernetes-ingress-controller/blob/master/internal/ingress/controller/kong.go but I can not figure where ".Secure" comes from

I also tryed to dynamically update `path` of my `KongIngress` but **it looks like the ingress controller does not update the `path` of my service**. It seems as the `KongIngress.proxy` does not update the created service in kong. Should i report another bug on this?
**What you expected to happen**:

The protocol set to `https`

**Anything else we need to know**:

I opened a similar topic here: https://discuss.konghq.com/t/question-secure-service-backend-on-kong-ingress-and-proxy-path/1356

**Comment by Ngob** [comment]
Thanks you for the fix, I will try it as soon as possible.

**Comment by NICK-DUAN** [comment]
@hbagdi Can you provide a demo or a document? Because it failed when I try the above example. Only a little different
that is I didn't use a plugin.

This is my yaml file:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: fooservice
  namespace: test
spec:
  type: ExternalName
  externalName: tke.kubernetes.oa.com
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP

---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: foo-ingress
  namespace: test
proxy:
  path: /foo-prod
  protocol: https
route:
  strip_path: true
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "egress"   # this is my kong ingress controller
spec:
  rules:
    - host:
      http:
        paths:
        - path: /foo
          backend:
            serviceName: fooservice
            servicePort: https
```

when I try to execute: `curl https://egress-kong-proxy.infr/foo`
It returned:`Client sent an HTTP request to an HTTPS server.`

And I also tried path: `https://egress-kong-proxy.infr/foo-prod`，It returned the same data.

**Comment by jam01** [comment]
having seemingly the same issue, however curl is giving me `Warning: Binary output can mess up your terminal.`

**Comment by jam01** [comment]
@hbagdi it seems there's a bug where 

```
kind: KongIngress
proxy:
  protocol: https
``` 

does not do anything, whereas annotating a service like

```
kind: Service
  annotations:
    konghq.com/protocol: https
```

fixes the issue.

I can create a new issue if you'd like. I'm using Helm Chart 1.11.0 and Kong tag 2.2 btw.

**Comment by NICK-DUAN** [comment]
Hey @jam01, You could follow my example.
```yaml
kind: Service
apiVersion: v1
metadata:
  name: stke-egress-svc
  annotations:
    konghq.com/client-cert: stke-egress-secret
    konghq.com/protocol: https
spec:
  type: ExternalName
  externalName: tke.kubernetes.oa.com
  ports:
  - name: https
    port: 443
    targetPort: 443 
    protocol: TCP
---
kind: Secret
apiVersion: v1
metadata:
  name: stke-egress-secret
type: kubernetes.io/tls
data:
  tls.crt: $YOUR_TLS_CRT
  tls.key: $YOUR_TLS_KEY
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: stke-egress-ing
  annotations:
    kubernetes.io/ingress.class: "kong"
proxy:
  protocols:
    - https
route:
  protocols:
    - https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stke-egress-ing
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/override: stke-egress-ing
    konghq.com/strip-path: "true"
    konghq.com/protocols: https
spec:
  rules:
    - host:
      http:
        paths:
        - path: /external/stke
          backend:
            serviceName: stke-egress-svc
            servicePort: https
```

**Comment by jam01** [comment]
@NICK-DUAN I see you have `konghq.com/protocol: https` on your Service so that works. The issue is that my Service is created by a Helm Release and there's no way to add the annotation before creation. 

My understanding is that `proxy: https` on the KongIngress is an equivalent, but it seems broken currently.

**Comment by NICK-DUAN** [comment]
> @NICK-DUAN I see you have `konghq.com/protocol: https` on your Service so that works. The issue is that my Service is created by a Helm Release and there's no way to add the annotation before creation.
> 
> My understanding is that `proxy: https` on the KongIngress is an equivalent, but it seems broken currently.

No, it's not equal.
I also use a helm chart to deploy my https service, you can make a custom chart for it. And add this annotations in your `values.yaml`.

This is my chart yaml file, it's a quite simple chart, but works for me.

```yaml
---
{{ $ingressClass := .Values.ingressController.ingressClass }}

{{- range .Values.custom_plugins }}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: egress-plugin-{{ .name }}
  annotations:
    kubernetes.io/ingress.class: {{ $ingressClass | quote }}
  {{- if .global }}
  labels:
    global: 'true'
  {{- end }}
plugin: {{ .plugin_name }}
config:
  {{- toYaml .config | nindent 2 }}
---
{{- end }}

{{- range .Values.routes }}
kind: KongIngress
apiVersion: configuration.konghq.com/v1
metadata:
  name: {{ .name }}-egress-ing
route:
  preserve_host: {{ .preserve_host | default "false" }}
  {{- if .route }}
  {{- range $key, $value := .route }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
upstream:
  host_header: {{ .host_header | default .url }}
  {{- if .upstream }}
  {{- range $key, $value := .upstream }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
---

{{- if .endpoint }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}-egress-svc
subsets:
  - addresses:
    - ip: {{ .endpoint }}
    ports:
    - port: {{ .external_port | default 80 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-egress-svc
  annotations:
    {{- if .service_path }}
    konghq.com/path: {{ .service_path }}
    {{- end }}
    konghq.com/override: {{ .name }}-egress-ing
spec:
  ports:
  - port: 80
    targetPort: {{ .external_port | default 80 }}
    protocol: {{ .protocol | default "TCP" }}
---
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-egress-svc
  annotations:
    {{- if .service_path }}
    konghq.com/path: {{ .service_path }}
    {{- end }}
    konghq.com/override: {{ .name }}-egress-ing
spec:
  type: ExternalName
  externalName: {{ .url }}
  ports: 
    - name: {{ .port_name | default "http" }}
      port: {{ .port | default 80 }}
      targetPort: {{ .external_port | default 80 }}
      protocol: {{ .protocol | default "TCP" }}
---
{{- end }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}-egress-ing
  annotations:
    kubernetes.io/ingress.class: {{ $ingressClass | quote }}
    {{- if .plugin_string }}
    konghq.com/plugins: {{ .plugin_string }}
    {{- end }}
    {{- if .strip_path }}
    konghq.com/strip-path: {{ .strip_path | quote }}
    {{- end }}
    {{- if .https }}
    konghq.com/override: {{ .name }}-egress-ing
    konghq.com/protocols: "https"
    {{- end }}
spec:
  rules:
  - host:
    http:
      paths:
      - path: {{ .path }}
        backend:
          serviceName: {{ .name }}-egress-svc
          servicePort: {{ .port | default "http" }}
---
{{- end }}
```

And you can make your service config like this:
```yaml
routes:
  - name: stkeapi
    https: true
    cert: xxxxxxx
    key: xxxxxxxx
    port: 443
    external_port: 443
    path: /external/stke/api
    strip_path: true
    url: api.kubernetes.oa.com
  - name: stke
    https: true
    cert: xxxxxxxx
    key: xxxxxxx
    port: 443
    external_port: 443
    path: /external/stke
    strip_path: true
    url: tke.kubernetes.oa.com
```

**Comment by jam01** [comment]
Right, a custom chart is indeed a workaround, but not one that makes sense for us. We'd still like to confirm with @hbagdi whether we're using the proxy property incorrectly or if it's a bug.

**Comment by NICK-DUAN** [comment]
@jam01 Could you show your yaml file?

**Comment by yousafsyed-bg** [comment]
I know its an old and closed issue and after upgrading kong from 1.3 to 2.4. we have faced the same issue and the fix was to add the new annotation in the service for ExternalName

`konghq.com/protocol: https,`

**Comment by zffocussss** [comment]
> @jam01 Could you show your yaml file?

if you want to make kong proxy to https://**myproject.cloudfunctions.net**
there are some points to make it:

1. in the ingress definition , make sure konghq.com/host-header: "**myproject.cloudfunctions.net**" and onghq.com/preserve-host: "false"
2. make an externalName service to point to **myproject.cloudfunctions.net** and the port is 443(default https port)
3. a kongingress resoure to imply you are using https to connect with upstream external services

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: demo-KongIngress
proxy:
  **protocol: https**
  connect_timeout: 10000
  retries: 3
  read_timeout: 10000
  write_timeout: 10000

kind: Service
apiVersion: v1
metadata:
  name: demo-service
  annotations:
    konghq.com/override: demo-KongIngress
spec:
  ports:
  - protocol: TCP
    **port: 443**
  **type: ExternalName**
  **externalName: myproject.cloudfunctions.net**

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    **konghq.com/preserve-host: "false"**
    **konghq.com/host-header: "myproject.cloudfunctions.net"**
    konghq.com/strip-path: "false"
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: demo-service
          servicePort: 443

```

**Comment by zffocussss** [comment]
@NICK-DUAN 


if you want to make kong proxy to https://**myproject.cloudfunctions.net**
there are some points to make it:

1. in the ingress definition , make sure konghq.com/host-header: "**myproject.cloudfunctions.net**" and onghq.com/preserve-host: "false"
2. make an externalName service to point to **myproject.cloudfunctions.net** and the port is 443(default https port)
3. a kongingress resoure to imply you are using https to connect with upstream external services

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: demo-KongIngress
proxy:
  protocol: https
  connect_timeout: 10000
  retries: 3
  read_timeout: 10000
  write_timeout: 10000

kind: Service
apiVersion: v1
metadata:
  name: demo-service
  annotations:
    konghq.com/override: demo-KongIngress
spec:
  ports:
  - protocol: TCP
    port: 443
  type: ExternalName
  externalName: myproject.cloudfunctions.net

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/preserve-host: "false"
    konghq.com/host-header: "myproject.cloudfunctions.net"
    konghq.com/strip-path: "false"
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: demo-service
          servicePort: 443

```

**Comment by thaonguyen-ct** [comment]
the annotation `konghq.com/host-header` only works with service not for ingress, but it seems not work with service with ExternalName type

**Comment by zffocussss** [comment]
> konghq.com/preserve-host: "false"

please try konghq.com/preserve-host: "true" in ingress annotations

**Comment by zffocussss** [comment]
@thaonguyen-ct 
**KongPlugin** defination
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: static
plugin: static
config:
  host: myproject.cloudfunctions.net
  port: 443
```
**handler.lua**
```

local kong = kong
local re_match = ngx.re.match

local plugin = {
    PRIORITY = 101, -- set the plugin priority, which determines plugin execution order
    VERSION = "0.1"
}

-- runs in the 'access_by_lua_block'
function plugin:access(plugin_conf)
    do
        local host = plugin_conf.host
        local port = plugin_conf.port
        kong.service.set_target(host, port)
    end
end

return plugin

```
**schema.lua**
```
local typedefs = require "kong.db.schema.typedefs"

-- Grab pluginname from module name
local plugin_name = ({...})[1]:match("^kong%.plugins%.([^%.]+)")

local schema = {
    name = plugin_name,
    fields = {
        -- the 'fields' array is the top-level entry with fields defined by Kong
        {consumer = typedefs.no_consumer}, -- this plugin cannot be configured on a consumer (typical for auth plugins)
        {protocols = typedefs.protocols_http}, {
            config = {
                -- The 'config' record is the custom part of the plugin schema
                type = "record",
                fields = {
                    {host = {type = "string", required = true}},
                    {port = {type = "number", required = true}}
                }
            }
        }
    }
}

return schema
```
```

----
kind: Service
apiVersion: v1
metadata:
  name: demo-service
  annotations:
    konghq.com/protocol: https
spec:
  ports:
  - protocol: TCP
    port: 443
  type: ExternalName
  externalName: myproject.cloudfunctions.net

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/preserve-host: "false"
    konghq.com/plugins: static
    konghq.com/strip-path: "false"
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
          serviceName: demo-service
          servicePort: 443
```

**Comment by wadexu007** [comment]
Thanks, I got answer here finally to fix this problem "400 The plain HTTP request was sent to HTTPS port"

```
konghq.com/protocol: https
```
This annotations should be added in External service.


My full YAML for reference.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/preserve-host: "false"
  name: test-gateway-kong-ingress
  namespace: sh-staging
spec:
  ingressClassName: kong
  rules:
  - host: resource.project-44.cn
    http:
      paths:
      - backend:
          service:
            name: my-external-service
            port:
              number: 443
        path: /api
        pathType: Prefix
  tls:
  - hosts:
    - resource.xxx.com
    secretName: resource-tls-secret

---
apiVersion: v1
kind: Service
metadata:
  name: my-external-service
  namespace: sh-staging
  annotations:
    konghq.com/protocol: https
spec:
  type: ExternalName
  externalName: api.stage.xxx.com
```
