### ISSUE TITLE
Only Terminate mode is supported. Route TLSRoute not supported.

### ISSUE THREAD

**Issue by mlalam** [Kong/kubernetes-ingress-controller#6922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deployed following manifest:

```
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: kong
  namespace: kong-system
spec:
  gatewayClassName: kong
  listeners:
  - name: wildcard-tls
    protocol: TLS
    port: 443
    hostname: "*.example.com"
    tls:
      mode: Passthrough
      certificateRefs:
      - group: ''
        kind: Secret
        name: default-ingress-cert      
    allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TLSRoute    
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
```

### Expected Behavior

TLS listener with passthrough mode must be created successfully.

### Steps To Reproduce

```markdown
Deploy the above manifest using KIC 3.4.1 on kubernetes 1.29
```

### Kong Ingress Controller version

```shell
3.4.1
```

### Kubernetes version

```shell
1.29
```

### Anything else?

Gateway created with following listener exception.
FYI - I'm using AWS ALB Controller component for provisioning NLB.

Status:
  Addresses:
    Type:   Hostname
    Value:  xxxxxx
  Conditions:
    Last Transition Time:  2025-01-06T22:50:30Z
    Message:               Listener 0 is not accepted.
    Observed Generation:   14
    Reason:                ListenersNotValid
    Status:                False
    Type:                  Accepted
    Last Transition Time:  2025-01-06T22:50:30Z
    Message:               There are other conditions that are not yet ready
    Observed Generation:   14
    Reason:                Pending
    Status:                False
    Type:                  Programmed
    Last Transition Time:  2025-01-06T19:13:03Z
    Message:
    Observed Generation:   8
    Reason:                Ready
    Status:                True
    Type:                  DataPlaneReady
    Last Transition Time:  2025-01-06T19:13:03Z
    Message:
    Observed Generation:   8
    Reason:                Ready
    Status:                True
    Type:                  ControlPlaneReady
    Last Transition Time:  2025-01-06T19:13:03Z
    Message:
    Observed Generation:   8
    Reason:                Ready
    Status:                True
    Type:                  GatewayService
  Listeners:
    Attached Routes:  0
    Conditions:
      Last Transition Time:  2025-01-06T22:50:30Z
      Message:
      Observed Generation:   14
      Reason:                NoConflicts
      Status:                False
      Type:                  Conflicted
      Last Transition Time:  2025-01-06T22:50:30Z
      Message:
      Observed Generation:   14
      Reason:                UnsupportedProtocol
      Status:                False
      Type:                  Accepted
      Last Transition Time:  2025-01-06T22:50:30Z
      Message:
      Observed Generation:   14
      Reason:                Pending
      Status:                False
      Type:                  Programmed
      Last Transition Time:  2025-01-06T22:50:30Z
      Message:               **Only Terminate mode is supported. Route TLSRoute not supported.**
      Observed Generation:   14
      Reason:                InvalidRouteKinds
      Status:                False
      Type:                  ResolvedRefs
    Name:                    wildcard-tls
    Supported Kinds:
Events:  <none>

**Comment by mlalam** [comment]
Refer to https://github.com/Kong/kubernetes-ingress-controller/issues/6912 details as well.

**Comment by mlalam** [comment]
@mheap, any suggestion?

**Comment by mlalam** [comment]
Anyone faced similar exception/error? Hoping to get some help on TLS pass-through implementation with KIC/Kong Gtw using KGO.

**Comment by mlalam** [comment]
@pmalek , any suggestion/recommendations? thanks.

**Comment by pmalek** [comment]
@mlalam TLSListener is not supported yet as per https://github.com/Kong/gateway-operator/blob/20f084194be07bb17d149e0b1b68e603e05a9ccd/controller/gateway/controller_reconciler_utils.go#L524-L534 and the fact that #64 is still open.

You should observe something like in your Gateway's status:

```
conditions:
  - lastTransitionTime: "2025-01-09T16:57:40Z"
    message: Listener 0 is not accepted.
    observedGeneration: 1
    reason: ListenersNotValid
    status: "False"
    type: Accepted
  - lastTransitionTime: "2025-01-09T16:57:40Z"
    message: There are other conditions that are not yet ready
    observedGeneration: 1
    reason: Pending
    status: "False"
    type: Programmed
listeners:
  - attachedRoutes: 0
    conditions:
      - lastTransitionTime: "2025-01-09T16:57:40Z"
        message: ""
        observedGeneration: 1
        reason: NoConflicts
        status: "False"
        type: Conflicted
      - lastTransitionTime: "2025-01-09T16:57:40Z"
        message: ""
        observedGeneration: 1
        reason: UnsupportedProtocol
        status: "False"
        type: Accepted
      - lastTransitionTime: "2025-01-09T16:57:40Z"
        message: ""
        observedGeneration: 1
        reason: Pending
        status: "False"
        type: Programmed
      - lastTransitionTime: "2025-01-09T16:57:40Z"
        message: Only Terminate mode is supported. Referenced secret kong-system/default-ingress-cert does not exist. Route TLSRoute not supported.
        observedGeneration: 1
        reason: InvalidRouteKinds
        status: "False"
        type: ResolvedRefs
    name: wildcard-tls
    supportedKinds: []
```

note the `UnsupportedProtocol` and `ResolvedRefs` listener conditions.

Hope that helps.
