### ISSUE TITLE
Bug when creating Consumer

### ISSUE THREAD

**Issue by heitorganzeli** [Kong/kubernetes-ingress-controller#70]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kong Ingress controller version**:  0.0.5
**Kong version**:  0.14.0

**Kubernetes version** (use `kubectl version`):
```txt
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Environment**:

- **Cloud provider or hardware configuration**:on premise kubernetes
- **OS** (e.g. from /etc/os-release): Oracle Linux Server 7.5
- **Kernel** (e.g. `uname -a`): 4.1.12-112.16.7.el7uek.x86_64

**What happened**:

I'm trying to create simple Kong configuration based on [custom types](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/custom-types.md) tutorial

But whenever i try to create a new consumer, the controller mess up resource creation/synchronization between Kubernetes and Kong.

I'm using the following configuration for the consumer creation:

```yml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-team-x
  namespace: kong
username: team-X
```

both entities get created:

- kubernetes: `kubectl describe kongconsumer consumer-team-x`
```yml
Name:         consumer-team-x
Namespace:    kong
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"configuration.konghq.com/v1","kind":"KongConsumer","metadata":{"annotations":{},"name":"consumer-team-x","namespace":"kong"},"username":...
API Version:  configuration.konghq.com/v1
Kind:         KongConsumer
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-07-20T18:00:31Z
  Generation:          1
  Resource Version:    11580589
  Self Link:           /apis/configuration.konghq.com/v1/namespaces/kong/kongconsumers/consumer-team-x
  UID:                 cb2a35d1-8c46-11e8-a4ba-90b11c1dd55e
Username:              team-X
Events:                <none>
```
- admin-api: `curl http://<host>:<port>/consumers`
```json
{
   "next":null,
   "data":[
      {
         "custom_id":null,
         "created_at":1532109545,
         "username":"team-X",
         "id":"8f81bc04-df4e-4afe-b165-3be99e67dcf6"
      }
   ]
}
```

although, both entities are there, `ingress-controller` keeps trying to recreate consumer object in kong using kubernetes UUID: `cb2a35d1-8c46-11e8-a4ba-90b11c1dd55e`, and do complete other configuration objects setup. Controller log:

```txt
W0720 18:27:32.851926       7 queue.go:113] requeuing simet/lmap-collector, err creating a Kong consumer: the server reported a conflict (post consumers.meta.k8s.io)
I0720 18:27:36.181051       7 controller.go:127] syncing Ingress configuration...
I0720 18:27:36.181075       7 kong.go:465] checking if Kong consumer consumer-team-x exists
I0720 18:27:36.182976       7 kong.go:469] Creating Kong consumer cb2a35d1-8c46-11e8-a4ba-90b11c1dd55e
E0720 18:27:36.185011       7 controller.go:130] unexpected failure updating Kong configuration: 
creating a Kong consumer: the server reported a conflict (post consumers.meta.k8s.io)
W0720 18:27:36.185035       7 queue.go:113] requeuing kong/kong-ingress-controller, err creating a Kong consumer: the server reported a conflict (post consumers.meta.k8s.io)
```
and looking at admin-api logs, we can see that the controller is trying to recreate the consumer with the wrong id:

```txt
::1 - - [20/Jul/2018:18:49:32 +0000] "POST /consumers HTTP/1.1" 409 144 "-" "Go-http-client/1.1"
::1 - - [20/Jul/2018:18:49:36 +0000] "GET /consumers/cb2a35d1-8c46-11e8-a4ba-90b11c1dd55e HTTP/1.1" 404 24 "-" "Go-http-client/1.1"
2018/07/20 18:49:36 [notice] 88#0: *245958 [lua] init.lua:391: insert(): ERROR: duplicate key value violates unique constraint "consumers_username_key"
Key (username)=(team-X) already exists., client: ::1, server: kong_admin, request: "POST /consumers HTTP/1.1", host: "localhost:8001"
::1 - - [20/Jul/2018:18:49:36 +0000] "POST /consumers HTTP/1.1" 409 144 "-" "Go-http-client/1.1"
```
**note**:  Kong consumer uuid is: `8f81bc04-df4e-4afe-b165-3be99e67dcf6`

I've tried to recreate all pods and configurations a couple a of times and with some modifications, but things always end up like that.

**What you expected to happen**:

I'd expect Kong object to be created with Kubernetes object UUID so controller can work properly

**How to reproduce it** (as minimally and precisely as possible):

i'm using a namespace similar to the one described by the [controller tutorial](https://konghq.com/blog/kubernetes-ingress-controller-for-kong/):
https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml

thx in advance
