### ISSUE TITLE
SanitizeKonnectConfigDumps breaking consumer group mapping in Konnect

### ISSUE THREAD

**Issue by jeffrey-arndt** [Kong/kubernetes-ingress-controller#7143]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

As of KIC 3.1.0, SanitizeKonnectConfigDumps feature flag is enabled by default

Applying the following yaml results in KIC performing 2 creations (1 consumer, and 1 consumer group). We never see the KIC performing a 3rd necessary request that ties the consumer to the group

```
apiVersion: configuration.konghq.com/v1beta1
kind: KongConsumerGroup
metadata:
  name: cg1
  annotations:
    kubernetes.io/ingress.class: kong
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: c1
  annotations:
    kubernetes.io/ingress.class: kong
username: c1
consumerGroups:
- cg1
---
```

We also see that the KIC is generating the correct config when pushing to the Gateway (KIC config dump):

    "consumers": [
      {
        "id": "4d5e7c0d-0a40-57eb-bebf-ffe8337d5e4b",
        "username": "c1",
        "tags": [
          "k8s-name:c1",
          "k8s-kind:KongConsumer",
          "k8s-uid:682b3396-d041-41c5-97c6-18d314012fa4",
          "k8s-group:configuration.konghq.com",
          "k8s-version:v1"
        ],
        "groups": [
          {
            "name": "cg1"
          }
        ]
      }
    ],
    "consumer_groups": [
      {
        "id": "e723d40d-03a0-558e-9b17-fbc82ff50127",
        "name": "cg1",
        "tags": [
          "k8s-name:cg1",
          "k8s-kind:KongConsumerGroup",
          "k8s-uid:4be7434e-a2ac-4cb5-8bdf-7cb149a59173",
          "k8s-group:configuration.konghq.com",
          "k8s-version:v1beta1"
        ]
      }
    ]

### Expected Behavior

Sanitize should not be interfering with the functionality

KIC should perform 3 requests to generate a consumer, consumer group, and tie them together:

```
"method": "PUT", "url": "https://us.kic.api.konghq.com/kic/api/control-planes/e4016da7-8f41-4e05-9272-6a09e25af10b/consumers/4d5e7c0d-0a40-57eb-bebf-ffe8337d5e4b"

"method": "POST", "url": "https://us.kic.api.konghq.com/kic/api/control-planes/e4016da7-8f41-4e05-9272-6a09e25af10b/v1/consumer-groups"

"method": "POST", "url": "https://us.kic.api.konghq.com/kic/api/control-planes/e4016da7-8f41-4e05-9272-6a09e25af10b/v1/consumers/4d5e7c0d-0a40-57eb-bebf-ffe8337d5e4b/groups/e723d40d-03a0-558e-9b17-fbc82ff50127/members"
```

### Steps To Reproduce

```markdown
1) Install KIC 3.4.1 in Konnect (or any version post 3.1.0)
2) kubectl apply -f the referenced yaml above
3) Navigate to your consumer group in Konnect, notice the consumer is not nested/tied in

If we explicitely disable the SanitizeKonnectConfigDumps feature flag, it works as expected:

controller:
  ingressController:
    image:
      tag: "3.4.1"
    env:
      feature_gates: "FillIDs=true,SanitizeKonnectConfigDumps=false"
```

### Kong Ingress Controller version

```shell
All version post 3.1.0
```

### Kubernetes version

```shell
Tested in 1.30
```
