### ISSUE TITLE
Gateway API HTTPRouteRule Resolution

### ISSUE THREAD

**Issue by ricfeatherstone** [Kong/kubernetes-ingress-controller#7178]
I'm trying to use the api-key plugin to provide course grained access at the HTTP method level, but the following configuration is not working. The [spec](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteRule) includes method match in the resolution criteria, so I expected this to work. 

When do a GET with the correct api key all is good, when I do a POST I get a 405.

Does KIC support this use case?

```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    konghq.com/plugins: simple-service-apikey,simple-service-apikey-readers-acl
  name: simple-service-apikey-readers
spec:
  hostnames:
  - simple-service-apikey.example.com
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: simple-service-apikey
      namespace: default
      port: 8080
    matches:
    - method: GET
      path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    konghq.com/plugins: simple-service-apikey,simple-service-apikey-writers-acl
  name: simple-service-apikey-writers
spec:
  hostnames:
  - simple-service-apikey.example.com
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: simple-service-apikey
      namespace: default
      port: 8080
    matches:
    - method: POST
      path:
        type: PathPrefix
        value: /
...
```

KIC v3.2
Gateway v3.7.1
