### ISSUE TITLE
Ingress controller crashes trying to create SSL Certificate

### ISSUE THREAD

**Issue by eduardoolimpio** [Kong/kubernetes-ingress-controller#72]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kong Ingress controller version**: 0.0.4 with Kong 0.14.0-centos

**Kubernetes version** (use `kubectl version`):
Client: v1.11.0
Server: v1.10.4-gke.2

**What happened**:
There is an issue with the ingress-controller tries to create a SNI after new certificate is added to the server. It tries to create the SNI returning the following error:
`Unexpected error creating Kong SNI: [400] {"fields":{"ssl_certificate_id":"unknown field","certificate":"required field missing"},"name":"schema violation","code":2,"message":"2 schema violations (certificate: required field missing; ssl_certificate_id: unknown field)"}`

After that it keeps trying to update the created certificate for the SNI, leading to the following error:
`Unexpected error creating Kong Certificate: [400] {"fields":{"snis":"example.com already associated with existing certificate 'abcd'"},"name":"schema violation","code":2,"message":"schema violation (snis: example.com already associated with existing certificate 'abcd')"}
`
Although it leads to this error, the HTTPS of `example.com` is working properly. However, because of this error, the controller does stops updating routes and services when Ingress are changed.

**What you expected to happen**:
After a certificate is created, HTTPS works fine and Ingress continues to update properly.

**How to reproduce it** (as minimally and precisely as possible):
Create a new certificate for a new SNI with valid secret. I use ingress-shim of cert-manager to issue certificates using Let's Encypt, here is the example of an Ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example.com
  annotations:
      kubernetes.io/ingress.class: "nginx"
      configuration.konghq.com: ingress-cert-manager
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/acme-http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    -  example.com
    secretName: example-crt
  rules:
  - host:  example.com
    http:
      paths:
      - path: /default
        backend:
          serviceName: default-http-backend
          servicePort: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ingress-cert-manager
route:
  preserve_host: true
  strip_path: false
```
**Anything else we need to know**:
I did not have this problem before using Kong 0.13.1-centos
