### ISSUE TITLE
Gateway API Traffic Splitting Not Working

### ISSUE THREAD

**Issue by ricfeatherstone-sky** [Kong/kubernetes-ingress-controller#7219]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I'm trying to do [traffic splitting ](https://gateway-api.sigs.k8s.io/guides/traffic-splitting/) using the following configuration 

What I am seeing is an undeterministic variation, sometimes 50/50, sometimes all green. 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-blue
  name: simple-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-blue
  template:
    metadata:
      labels:
        app: simple-blue
    spec:
      containers:
        - image: docker.io/ricfeatherstone/blue-green
          name: simple-blue
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-blue
  name: simple-blue
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: simple-blue
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-green
  name: simple-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-green
  template:
    metadata:
      labels:
        app: simple-green
    spec:
      containers:
        - image: docker.io/ricfeatherstone/blue-green
          name: simple-green
          env:
            - name: RESP
              value: green
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-green
  name: simple-green
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: simple-green
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: simple-weighted
  namespace: default
spec:
  hostnames:
    - simple-weighted.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: kong-external
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: simple-blue
          namespace: default
          port: 8080
          weight: 80
      matches:
        - path:
            type: PathPrefix
            value: /
    - backendRefs:
        - group: ""
          kind: Service
          name: simple-green
          namespace: default
          port: 8080
          weight: 20
      matches:
        - path:
            type: PathPrefix
            value: /
```

### Expected Behavior

I  expected ~80% of responses to be blue and ~20% of responses to be green.

### Steps To Reproduce

```markdown

```

### Kong Ingress Controller version

```shell
v3.4.3
```

### Kubernetes version

```shell
{
  "clientVersion": {
    "major": "1",
    "minor": "31",
    "gitVersion": "v1.31.3",
    "gitCommit": "c83cbee114ddb732cdc06d3d1b62c9eb9220726f",
    "gitTreeState": "clean",
    "buildDate": "2024-11-19T13:51:52Z",
    "goVersion": "go1.22.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.4.2",
  "serverVersion": {
    "major": "1",
    "minor": "31",
    "gitVersion": "v1.31.6-gke.1020000",
    "gitCommit": "84f41c2100b3d5f238e0dc12381df8fa8ad306bf",
    "gitTreeState": "clean",
    "buildDate": "2025-02-13T09:44:44Z",
    "goVersion": "go1.22.12 X:boringcrypto",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

### Anything else?

Gateway v3.8.0

**Comment by randmonkey** [comment]
@ricfeatherstone-sky You need to configure the two backends in one `backendRefs` in a single rule. Your manifests actually defined 2 rules two the two backends with the same match. 
The correct spec of `HTTPRoute` is like this:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: simple-weighted
  namespace: default
spec:
  hostnames:
    - simple-weighted.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kong
      namespace: kong-external
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: simple-blue
          namespace: default
          port: 8080
          weight: 80
     -  group: ""
          kind: Service
          name: simple-green
          namespace: default
          port: 8080
          weight: 20
      matches:
        - path:
            type: PathPrefix
            value: /
```

You can refer to `examples/gateway-httproute.yaml` to see how to configure traffic splitting correctly.

**Comment by ricfeatherstone** [comment]
@randmonkey thank you v.  much, I couldn't see the wood for the trees. I've also been doing header based routing like this and can now see where I've gone wrong.

```
rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: simple-stable
      namespace: default
      port: 8080
      weight: 1
    matches:
      - path:
        type: PathPrefix
        value: /
  - backendRefs:
    - group: ""
      kind: Service
      name: simple-canary
      namespace: default
      port: 8080
      weight: 1
    matches:
      - headers:
          - name: env
            type: Exact
            value: canary
        path:
          type: PathPrefix
          value: /
```

I'm also trying to route based on HTTP Method using the API Key plugin to restrict certain methods. There are two HTTP Routes with the same hostname using different ACLs to reference different groups. 

The following does not work, POSTs get a 405, is there a way to do this?

```
apiVersion: v1
kind: List
items:
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    annotations:
      konghq.com/plugins: apikey,readers-acl
    name: readers
    namespace: default
  spec:
    hostnames:
    - apikey.example.com
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: apikey
        namespace: default
        port: 8080
        weight: 1
      matches:
      - method: GET
        path:
          type: PathPrefix
          value: /
- apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    annotations:
      konghq.com/plugins: apikey,writers-acl
    name: writers
    namespace: default
  spec:
    hostnames:
    - apikey.example.sky.com
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: apikey
        namespace: default
        port: 8080
        weight: 1
      matches:
      - method: POST
        path:
          type: PathPrefix
          value: /
```
