### ISSUE TITLE
GKE ingress not creating upstream

### ISSUE THREAD

**Issue by EntonoX** [Kong/kubernetes-ingress-controller#73]
**Is this a request for help?**:
Yes
**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
ingress, upstream

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kong Ingress controller version**:
0.0.4

**Kubernetes version** (use `kubectl version`):
1.9.7

**Environment**:

- **Cloud provider or hardware configuration**: Googe Cloud
- **OS** (e.g. from /etc/os-release): unknown
- **Kernel** (e.g. `uname -a`): unknown
- **Install tools**: kubectl
- **Others**:

**What happened**:
I deployed the Kong ingress controller according to the YAML provided in the manifest. Further i'm using Konga as a GUI for Kong to see created upstreams ,services, etc. I use an auth-nginx deployment but i think any simple nginx sample application will provide enough to replicate the issue.

The ingress i created:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
   - http:
      paths:
      - path: /auth
        backend:
          serviceName: auth-nginx
          servicePort: 80
```

The 'auth-nginx' service is a NodePort type service and running. When i create the above ingress with 

`kubect create -f ingress.yaml` 

i see that the ingress is created in Google Cloud Kubernetes -> Services. By specifying the nginx ingress class, Kong should be notified and create an upstream. Is there anything that i'm missing why Kong Ingress doens't notice the creation of the ingress?

**What you expected to happen**:
Upstream created in Kong. And the upstream will be reachable with http://IP_OF_LB/auth

**How to reproduce it** (as minimally and precisely as possible):
Deploy above script in Google Cloud

**Anything else we need to know**:
Not that i can think of right now
