### ISSUE TITLE
Opentelemetry plugin's "config.resource_attributes" does not pass Webhook Validation because of the "." period in service.name key value

### ISSUE THREAD

**Issue by ctheisingfl** [Kong/kubernetes-ingress-controller#7336]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Is there an existing issue for this?

Kong 3.4.0

```
kind: KongClusterPlugin
metadata:
  name: myname
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  endpoint: myendpoint
  resource_attributes:
    service.name: kong-dev
plugin: opentelemetry
```

Failed to save resource: admission webhook "validations.kong.konghq.com" denied the request: plugin failed schema validation: schema violation (config.resource_attributes: expected a string)

Following the [Opentelemetry Documentation](https://docs.konghq.com/hub/kong-inc/opentelemetry/3.4.x/how-to/getting-started/#configure-the-opentelemetry-plugin) I have tried to set the service.name key pair, but run into the webhook validation issue.

This is tied to the https://github.com/Kong/kong/issues/10654, which stated was fixed in Kong 3.4, but we are still running into this issue.

### Expected Behavior

I expect the manifest to be created while using the service.name key pair.

### Steps To Reproduce

```markdown
Steps To Reproduce
(Optionally) Enable the OpenTelemetery plugin within Kong's configuration.
Within Kubernetes, enable Kong's validating admission Webhook via a ValidatingWebhookConfiguration.
Attempt to create a KongPlugin object by applying a manifest like the one shown earlier, via kubectl apply --filename --dry-run=server or kubectl apply --filename --server-side=true.
Observe that the validating Webhook rejects the manifest due to the "config.resource_attributes" mapping entry.
```

### Kong Ingress Controller version

```shell
2.12
```

### Kubernetes version

```shell

```

### Anything else?

Anything else?
This might be resolved for the Log-File plugin for [custom_fields_by_lua](https://github.com/Kong/kong/blob/master/CHANGELOG.md#admin-api-7),

But it is not fixed for OpenTelemetry.
