### ISSUE TITLE
How to use custom certificate with knative

### ISSUE THREAD

**Issue by StarpTech** [Kong/kubernetes-ingress-controller#740]
Hi, I use Knative with Kong ingress controller and it works great but I can't find out how to use a custom wildcard certificate with my Knative services. I'm looking for a way to configure the ingress with Kong CRD's.

Therefore I can't find any documentation on how TLS is configured at all.

**Comment by StarpTech** [comment]
I think this is related https://discuss.konghq.com/t/tcpingress-how-can-i-use-it/5908

**Comment by StarpTech** [comment]
I could fix it by using `TCPIngress`

```yaml
apiVersion: configuration.konghq.com/v1beta1
kind: TCPIngress
metadata:
  name: kong
spec:
  tls:
    - hosts:
      - "*.default.yourdomain.com"
      secretName: my-tls-domain
```
I'm still interested in how to display the complete ingress with kubectl.
