### ISSUE TITLE
kong ingress-controller URL rewrite not working 

### ISSUE THREAD

**Issue by ajaysourcedigital** [Kong/kubernetes-ingress-controller#741]
### Summary
I am using below documents and yaml files for services(*not ingresses as URL rewrite works on services*)
##### Document 
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-rewrites.md

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/host-header: '"internal.myapp.example.com"'
  name: api-unstable
  namespace: api-unstable
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: api-unstable
spec:
  clusterIP: 10.123.0.7
  ports:
  - name: 1337tcp01-api-unstable
    port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    workload.user.cattle.io/workloadselector: deployment-api-unstable-api-unstable
  sessionAffinity: None
  type: ClusterIP
```
Ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  
  labels:
    cattle.io/creator: norman
  name: api-unstable
  namespace: api-dev
  
spec:
  rules:
  - host: api-unstable.example.com
    http:
      paths:
      - backend:
          serviceName: api-unstable
          servicePort: 1337
```

**Kong Ingress controller version**
```
$ kong-ingress-controller --version
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.9.0
  Build:      0aad24a
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.14.1
-------------------------------------------------------------------------------
```

**Kong or Kong Enterprise version**
```
bash-5.0$ kong version
2.0.4
```

### Kubernetes version
`Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean"
, BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeStat
e:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}`
### Environment
- GKE

### What happened
Trying to use URL-rewrite pre-built plugin but its not working and giving the same results. Even if I do use `curl` command 
```
> HEAD / HTTP/2
> Host: api-unstable.example.com
> User-Agent: curl/7.54.0
```
### Expected behavior
Below host-header should be visible.

```
> HEAD / HTTP/2
> Host: internal.myapp.example.com
> User-Agent: curl/7.54.0
```

### Steps To Reproduce

1. Create deployment 
2. Create svc
3. Create Ingress
4. Patch svc with `{"annotations":{"konghq.com/host-header":"internal.myapp.example.com"}}`
