### ISSUE TITLE
Multiple SNIs on a TLS certificate are not reflected in Kong certificate object

### ISSUE THREAD

**Issue by dag24** [Kong/kubernetes-ingress-controller#75]
**Is this a request for help?**: No

**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.): sni, tls, certificate

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Kong Ingress controller version**: 0.13

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**: kubeadm cluster
- **OS** (e.g. from /etc/os-release): Linux
- **Others**: A TLS certificate from Let's Encrypt

Given the following ingress definition, and a valid TLS secret that contains a certificate for SNIs `foo.example.com` and `bar.example.com`, a Kong certificate will be created with only one of the SNIs shown in `spec.tls[0].hosts`, not all of them.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  tls:
  - secretName: tls-secret
    hosts:
    - foo.example.com
    - bar.example.com
  rules:
  - host: foo.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: foo
          servicePort: 80
  - host: bar.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: bar
          servicePort: 80
```

Kong admin API: `/certificates`: notice that the `snis` array contains only one of the above `tls[0].hosts` values, not both.

```
{
  "data": [
    {
      "created_at": 1533315433000,
      "cert": "<certificate>",
      "id": "4c997a38-973c-11e8-96dc-00155dea8698",
      "key": "<private key>",
      "snis": [
        "foo.example.com"
      ]
    }
  ],
  "total": 1
}
```

Kong admin API: `/snis`:

```
{
  "total": 1,
  "data": [
    {
      "created_at": 1533315433000,
      "name": "foo.example.com",
      "ssl_certificate_id": "4c997a38-973c-11e8-96dc-00155dea8698"
    }
  ]
}
```

This means that accessing `bar.example.com` via HTTPS throws a certificate error, when in fact that should work. Therefore it is not currently possible to share a valid TLS certificate across multiple Kong backends in the Kubernetes controller, but this is possible in "vanilla" Kong when you POST the full list of SNIs to `/snis` for a given certificate ID.
