### ISSUE TITLE
Validating webhook fails with "missing required field(s): secret" for KongConsumer credentials Secret with RS256 key

### ISSUE THREAD

**Issue by atikhono** [Kong/kubernetes-ingress-controller#750]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

KIC with validation webhook enabled and configured as described in official documentation. Validation fails for the following KongConsumer credential (pseudo-code for Secret):

```
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: prometheus
  namespace: default
username: prometheus
credentials:
  - prometheus-jwt
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-jwt
  namespace: default
type: Opaque
data:
  kongCredType: base64("jwt")
  key: base64(KEY)
  algorithm: base64("RS256")
  rsa_public_key: base64(PUB_KEY)
```

  msg: 'Failed to create object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \\"validations.kong.konghq.com\\" denied the request: missing required field(s): secret","code":400}'''
  reason: Bad Request
  status: 400

If I add `secret: base64("anything")` field to prometheus-jwt Secret definition -- validation passes.

**Kong Ingress controller version**
0.9.1

**Kong or Kong Enterprise version**
Kong 2.0.4

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

### Environment

Azure Kubernetes Service
Docker Desktop Kubernetes

### What happened
Secret validation failed for RS256 key without `secret` field.

### Expected behavior
"secret" field is optional for RS256 key as per JWT plugin doc: https://docs.konghq.com/hub/kong-inc/jwt/#create-a-jwt-credential. I expect validation to pass without that field.

### Steps To Reproduce

1. Deploy Kong with KIC and configure validation webhook
2. Create KongConsumer and Secret from the above description.
