### ISSUE TITLE
Multiple plugins are not working, rewrite URI

### ISSUE THREAD

**Issue by Liizus** [Kong/kubernetes-ingress-controller#7559]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Installed Kong via helmchart. 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kong
    releaseName: kong
    namespace: kong
    repo: https://charts.konghq.com/
    version: 2.49.0 # Replace with the latest stable version if needed
    valuesInline:
      ingressController:
        enabled: true
        installCRDs: true
        ingressClass: kong
        env: # Add this section
          controller_log_level: "debug" # Set KIC logging to debug
      proxy:
        type: ClusterIP
        env: # Add this section
          KONG_LOG_LEVEL: "debug"
          KONG_PLUGINS: "bundled,request-transformer-advanced"
```
I've specified the `request-transformer-advanced` plugin in an effort to utilize it in rewriting URI and adding additional headers. Here's my kubernetes file.

```
apiVersion: v1
kind: Secret
metadata:
  name: productA-rt-key
stringData:
  apiKeyHeader: '"ApiKey:<api-key>"'
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    konghq.com/credential: key-auth
  name: secret-of-kong-consumer-productA-subscription-key
stringData:
  key: <sub-key>
type: Opaque
---
apiVersion: configuration.konghq.com/v1
credentials:
- secret-of-kong-consumer-productA-subscription-key
custom_id: kong-consumer-productA-subscription-key
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: kong-consumer-productA-subscription-key
username: kong-consumer-productA-subscription-key
---
apiVersion: configuration.konghq.com/v1
config:
  add:
    headers:
    - AppName:ProductA
configPatches:
- path: /add/headers/-
  valueFrom:
    secretKeyRef:
      key: <sub-key>
      name: productA-rt-key
kind: KongPlugin
metadata:
  name: kong-plugin-header-transform-productA
plugin: request-transformer-advanced
---
apiVersion: configuration.konghq.com/v1
config:
  replace:
    uri: /def/$1
kind: KongPlugin
metadata:
  annotations:
    konghq.com/plugins-tags: uri-rewrite
    kubernetes.io/ingress.class: kong
  name: kong-plugin-uri-rewrite-productA
plugin: request-transformer-advanced
---
apiVersion: configuration.konghq.com/v1
config:
  hide_credentials: false
  key_in_header: true
  key_in_query: true
  key_names:
  - Subscription-Key
kind: KongPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: subscription-key-auth
plugin: key-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/methods: GET, POST
    konghq.com/plugin-order: |
      subscription-key-auth:10
      kong-plugin-uri-rewrite-productA:20
      kong-plugin-header-transform-productA:30
    konghq.com/plugins: |
      subscription-key-auth,
      kong-plugin-uri-rewrite-productA,
      kong-plugin-header-transform-productA
    konghq.com/strip-path: "false"
    kubernetes.io/ingress.class: kong
  name: ingress-kong-productA
spec:
  ingressClassName: kong
  rules:
  - host: dev-kong.mcdonalds.io
    http:
      paths:
      - backend:
          service:
            name: productA
            port:
              number: 80
        path: /abc/(.*)
        pathType: ImplementationSpecific
```

### Expected Behavior

Running curl:
1. `curl -v "https://dev-kong.mcdonalds.io/abc/accountinfo?RequestId=<api-key>" -H "Subscription-Key: <sub-key>"`
  a. the plugin should validate that it has the Subscription-Key and that the value matches the `<sub-key>` value.
  b. If it succeeds, then it should rewrite the url to:
         i. `https://dev-kong.mcdonalds.io/def/accountinfo?RequestId=<api-key>`
  c. it should also add additional headers:
         i. `ApiKeyHeader:<api-key>`

### Steps To Reproduce

```markdown

```

### Kong Ingress Controller version

```shell
2.49.0
```

### Kubernetes version

```shell
1.32.4
```

**Comment by randmonkey** [comment]
@Liizus What is the current behavior of using the configuration?
Also order of executing plugins is specified in the `Ordering` field in the `KongPlugin` resource but not the annotations. For example, if you want run `key-auth` before `url-rewrite`, you can specify like this
```yaml
apiVersion: configuration.konghq.com/v1
config:
  replace:
    uri: /def/$1
kind: KongPlugin
metadata:
  annotations:
    konghq.com/plugins-tags: uri-rewrite
    kubernetes.io/ingress.class: kong
  name: kong-plugin-uri-rewrite-productA
plugin: request-transformer-advanced
---
apiVersion: configuration.konghq.com/v1
config:
  hide_credentials: false
  key_in_header: true
  key_in_query: true
  key_names:
  - Subscription-Key
ordering:
  before:
    access:
    - uri-rewrite
kind: KongPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: subscription-key-auth
plugin: key-auth
```
