### ISSUE TITLE
[Monitoring] HTTPRoute metrics are aggregated when multiple rules reference the same backend service

### ISSUE THREAD

**Issue by parkjeongryul** [Kong/kubernetes-ingress-controller#7562]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When an HTTPRoute has multiple rules that reference the same backend service, the kong_http_requests_total metric with route labels are aggregated instead of being reported separately for each rule/path.

Only one route label appears in metrics, even though there are two different paths (/path-a and /path-b).

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: default
spec:
  parentRefs:
  - name: kong-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /path-a
    backendRefs:
    - name: shared-service
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /path-b
    backendRefs:
    - name: shared-service  # Same backend service
      port: 80
```

### Expected Behavior

Both rules should generate separate route labels:

- `kong_http_requests_total{route="httproute.default.test-route.0.0"}`
- `kong_http_requests_total{route="httproute.default.test-route.1.0"}`

### Steps To Reproduce

```markdown
1. Create the HTTPRoute above with two rules pointing to the same backend service
2. Send requests to both /path-a and /path-b
3. Query kong_http_requests_total metrics
4. Observe that metrics for both paths are merged under a single route label instead of being separated
```

### Kong Ingress Controller version

```shell
v3.3.1
```

### Kubernetes version

```shell
v1.23.15
```
