### ISSUE TITLE
Duplicated plugin breaking the proxy

### ISSUE THREAD

**Issue by ulyssescb** [Kong/kubernetes-ingress-controller#762]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary
In my use case it was necessary to have two  definitions of the `ip-restriction plugin` at the same ingress (it's probably not a good practice). It's possible to apply this config, but the `proxy` it's breaking. If this not allowed, how can I prevent the `kong-ingress` for accept such configurations? 

**Kong Ingress controller version**
0.9.1

**Kong or Kong Enterprise version**
2.0.2

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuilIf this not allowed, how can I prevent the `kong-ingress` for accept such configurations? dDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

### What happened
```
 [error] 24#0: *4842322 [kong] api_helpers.lua:260 Cannot serialise table: excessively sparse array, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
```

### Expected behavior
The `ingress-controller` should not accept this kind of configuration. 

### Steps To Reproduce

1.
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ip-plugin-1
plugin: ip-restriction
config:
  whitelist:
  - 127.0.0.0/8
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 100.64.0.0/10
  - 198.18.0.1/32
```
2.
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ip-plugin-2
plugin: ip-restriction
config:
  whitelist:
  - 192.30.252.0/22
  - 185.199.108.0/22
  - 140.82.112.0/20
```
3.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong    
    konghq.com/plugins: ip-plugin-1,ip-plugin-2
  labels:
  name: endpoint-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: 8080
        path: /mypath/
```
