### ISSUE TITLE
Rate Limiting by header doesn't supported ?

### ISSUE THREAD

**Issue by mholleville** [Kong/kubernetes-ingress-controller#779]
Hi ! 

I saw on the plugin hub which we can rate limiting by header_name : https://docs.konghq.com/hub/kong-inc/rate-limiting/

When I'm trying to deploy on Kubernetes I have the following message. 

```
400 Bad Request {"fields":{"plugins":[{"config":{"header_name":"unknown field","limit_by":"expected one of: consumer, credential, ip, service"}}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {plugins={{config={header_name=\"unknown field\",limit_by=\"expected one of: consumer, credential, ip, service\"}}}}"}
```

With the ingress controller we can only rate limit by `consumer`, `ip`, `service`

My Deployment file 

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: global-rate-limit
  labels:
    global: "true"
service: Test
config:
  minute: 2
  header_name: Custom-header
  policy: local
  limit_by: header
plugin: rate-limiting
```
Can you tell me if the rate limiting by header_name was possible which another way ?
