### ISSUE TITLE
Rewrite target is not working

### ISSUE THREAD

**Issue by meonthewire** [Kong/kubernetes-ingress-controller#78]
Hi there, the annotation **ingress.kubernetes.io/rewrite-target: /** doesn't works. I need that the path: `/sample` be removed before Kong calls the upstream service.
This is a bug?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my.host.local
    http:
      paths:
      - path: /sample
        backend:
          serviceName: my-svc
          servicePort: 80
```

kong-ingress-controller version: `kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.0.4`

Kong deployment was made with the yml file: `https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/single/all-in-one-postgres.yaml`

kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.4", GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf", GitTreeState:"clean", BuildDate:"2018-06-15T21:48:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lmorais** [comment]
Hi,

When I call this url `http://my.host.local/sample` the path `/sample` is sent to upstream service. This is a expected behavior for kong-ingress? I expected that the path will not sent to upstream service.

**Comment by lmorais** [comment]
Hi @hbagdi ,

When I call this url http://my.host.local/sample the path /sample is sent to upstream service. This is a expected behavior for kong-ingress? I expected that the path will not sent to upstream service.

**Comment by lmorais** [comment]
Hi @hbagdi 

When I call this url http://my.host.local/sample the path /sample is sent to upstream service. This is a expected behavior for kong-ingress? I expected that the path will not sent to upstream service.
```
curl --header "Host: my.host.local" http://200.x.x.x/sample -vvv
*   Trying 200.x.x.x...
* TCP_NODELAY set
* Connected to 200.x.x.x (200.x.x.x) port 80 (#0)
> GET /konga HTTP/1.1
> Host: my.host.local
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< X-Powered-By: Sails <sailsjs.org>
< Date: Fri, 10 Aug 2018 14:10:15 GMT
< X-Kong-Upstream-Latency: 2
< X-Kong-Proxy-Latency: 0
< Via: kong/0.13.1
< 
* Connection #0 to host 200.x.x.x left intact
```

**Comment by lmorais** [comment]
Hi @hbagdi 

When I call this url http://my.host.local/sample the path /sample is sent to upstream service. This is a expected behavior for kong-ingress? I expected that the path will not sent to upstream service.

```
curl --header "Host: my.host.local" http://200.x.x.x/sample -vvv
*   Trying 200.x.x.x...
* TCP_NODELAY set
* Connected to 200.x.x.x (200.x.x.x) port 80 (#0)
> GET /sample HTTP/1.1
> Host: my.host.local
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< X-Powered-By: Sails <sailsjs.org>
< Date: Fri, 10 Aug 2018 14:10:15 GMT
< X-Kong-Upstream-Latency: 2
< X-Kong-Proxy-Latency: 0
< Via: kong/0.13.1
< 
* Connection #0 to host 200.x.x.x left intact
```

**Comment by hbagdi** [comment]
I'm not sure if I see upstream being sent `/sample` in the cURL output you've posted above. It seems like Kong is proxying the request (`Via` header).

Do you see a log in your service which says that it received `/sample`?
Is there an echo endpoint in your upstream service which could be handy for your debugging?

**Comment by andrewtappert** [comment]
I'm having the same problem.  I do see in my upstream service logs that the path is not being stripped, and when I query the Kong Admin API for the route created for the ingress, I see that strip_path is false.

**Comment by andrewtappert** [comment]
@lmorais @hbagdi As mentioned above, I found that strip_path was not being set by default (v0.0.5).  I achieved a request path rewrite by creating a KongIngress, like so:
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: echo-ingress
route:
  strip_path: true
```

...corresponding to this ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /echo
        backend:
          serviceName: echo-service
          servicePort: 8080
```

That takes care of the rewrite, although I found that that if the ingress already exists, it must be deleted and re-created to pick up the config from the KongIngress, per https://github.com/Kong/kubernetes-ingress-controller/issues/56#issuecomment-412246411

Note, though, that I haven't got this extremely basic example working without specifying a host, which I don't actual want to do.  (https://github.com/Kong/kubernetes-ingress-controller/issues/84)

**Comment by hbagdi** [comment]
Hello @andrewtappert 

> That takes care of the rewrite, although I found that that if the ingress already exists, it must be deleted and re-created to pick up the config from the KongIngress, per #56 (comment)

This should not be required with Ingress controller 0.1.0. This bug was fixed in #92 


It seems like the ingress controller is creating routes with `strip_path` set to false by default, in which case, as you figured out, you will need to use `KongIngress` resource to set it to false.

**Comment by brysk** [comment]
Hi @hbagdi 
ingress controller version: 0.2.2
`strip_path` is set to false for any created rules, is that expected?

**Comment by zeusro** [comment]
```yaml

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    konghq.com/strip-path: "true"    
    kubernetes.io/ingress.class: kong    
spec:
  rules:
  - host: my.host.local
    http:
      paths:
      - path: /sample/
        backend:
          serviceName: my-svc
          servicePort: 80
```
