### ISSUE TITLE
x-forwarded-prefix header is not just the ingress route path

### ISSUE THREAD

**Issue by jerfer** [Kong/kubernetes-ingress-controller#784]
### Summary
The x-forwarded-prefix header sent to upstreams seems to be always equal to the full request path instead of just being the path specified as the ingress route.

**Kong Ingress controller version**
0.9.1

**Kong or Kong Enterprise version**
CE 2.0.4

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.6-eks-4e7f64", GitCommit:"4e7f642f9f4cbb3c39a4fc6ee84fe341a8ade94c", GitTreeState:"clean", BuildDate:"2020-06-11T13:55:35Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

### Environment
- **Cloud provider or hardware configuration**: AWS EKS with NLB (proxy protocol v2 enabled)
```
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: proxy
      port: 80
      protocol: TCP
      targetPort: 8000
    - name: proxy-ssl
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: ingress-kong
```

### What happened
The x-forwarded-path header being sent upstream seems to always be equal to the full request path. Upstream services that use this prefix to construct their redirect URLs, for example, end up repeating all or a portion of the path. For example, a GET to https://echo.somedomain.com/page1 results in the following:
```
Hostname: echoservice-566b945c6c-vbpdl

Pod Information:
	node name:	ip-10-10-1-68.ec2.internal
	pod name:	echoservice-566b945c6c-vbpdl
	pod namespace:	default
	pod IP:	10.10.1.199

Server values:
	server_version=nginx: 1.13.3 - lua: 10008

Request Information:
	client_address=10.10.1.20
	method=GET
	real path=/page1
	query=
	request_version=1.1
	request_uri=http://echo.somedomain.com:8080/page1

Request Headers:
	accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
	accept-encoding=gzip, deflate, br
	accept-language=en-US,en;q=0.9
	connection=keep-alive
	cookie=session=TEaV5GAdovCaFP-ZVV-fAA|1596073344|4HeG3GPrBlz69fDH9Y7DcdaxYaw
	dnt=1
	host=echo.somedomain.com
	sec-fetch-dest=document
	sec-fetch-mode=navigate
	sec-fetch-site=none
	sec-fetch-user=?1
	upgrade-insecure-requests=1
	user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
	x-forwarded-for=<obfuscated>
	x-forwarded-host=echo.somedomain.com
	x-forwarded-port=8443
	x-forwarded-prefix=/page1
	x-forwarded-proto=https
	x-real-ip=<obfuscated>

Request Body:
	-no body in request-
```

An upstream receiving such an x-forwarded-prefix header would normally prepend the provided prefix to any of its redirect URL paths, resulting in redirects to `http://echo.somedomain.com/page1/redirectTargetPage`. Setting `konghq.com/strip-path: "true"` has no effect on the value of x-forwarded-prefix and only serves to remove the route path from the path on the request to the upstream.

### Expected behavior
The x-forwarded-prefix should only contain the portion of the path that isn't being requested to the upstream. As far as I understand, this value should only contain the _stripped_ portion of the path of the original request.

### Steps To Reproduce

1. Deploy Kong Ingress Controller
2. Deploy an echo service
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoservice
  template:
    metadata:
      labels:
        app: echoservice
    spec:
      containers:
        - name: echoservice
          image: gcr.io/google_containers/echoserver:1.8
          ports:
            - containerPort: 8080
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  name: echoservice
  namespace: default
  labels:
    app: echoservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: echoservice

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echoservice
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "kong"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
    konghq.com/protocols: "https"
    konghq.com/strip-path: "false"
    konghq.com/https-redirect-status-code: "308"
spec:
  tls:
    - hosts:
        - echo.somedomain.com
      secretName: echoservice-tls
  rules:
    - host: echo.somedomain.com
      http:
        paths:
          - path: "/"
            backend:
              serviceName: echoservice
              servicePort: http
---
```
3. Issue a request to `https://echo.somedomain.com/somePath`
4. Note the x-forwarded-prefix is `/somePath` instead of `/`.
