### ISSUE TITLE
Custom paths with Kong Ingress Pass As-Is to Internal App

### ISSUE THREAD

**Issue by saifrahmed** [Kong/kubernetes-ingress-controller#794]
We're following the instructions on setting up ingress with paths using Kong.
On the ingress spec, using a path setting of `path: /` works fine, but any other path, for example `path: /whatever` does not work. 

In the default case, /, the flask application (in this case) works well and serves as expected. 
In the modified case, /whatever, the we get an error "The requested URL was not found on the server". This suggested that /whatever isnt being mapped to the base url of the internal app (Flask in this case) but rather the /whatever is being passed into the app. We verified this with the Flask logs. 

Our assumption was that the /whatever path would map to the base of the application -- how can we do this?

For your references, we set up the below (Kong + Deployment + Ingress + Service) on Azure AKS.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentname1
spec:
  selector:
    matchLabels:
      run: deploymentname1
  replicas: 1
  template:
    metadata:
      labels:
        run: deploymentname1
    spec:
      restartPolicy: Always
      containers:
        - name: deploymentname1
          image: xxx/throwaway-flask-test:r7.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5187
              protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: deploymentname1
spec:
  rules:
  - http:
      paths:
      - path: /whatever
        backend:
          serviceName: deploymentname1
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:  
  name: deploymentname1
spec:
  selector:    
    run: deploymentname1
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 5187
    protocol: TCP
```
