### ISSUE TITLE
How to config kong ingress controller for proxy websoket request

### ISSUE THREAD

**Issue by swift1911** [Kong/kubernetes-ingress-controller#802]
### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.9.1

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:05:01Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
**paste `kubectl version` output**

### What happened
I want to use kong to proxy websocket request to my backend service.But i don't find the solution from the document.The following is my config of Ingresss.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websocket-ingress
spec:
  rules:
  - host: xxx.xxx.org
    http:
      paths:
      - backend:
          serviceName: websocket
          servicePort: 8080
        path: /
```
But it's error for testing 'error: Unexpected server response: 101' , it seem that the header 'Connection: Upgrade' my not be applied to the proxy.
Is there any solution for websocket?

**Comment by hbagdi** [comment]
What is the version of Kong?

> error: Unexpected server response: 101

And where do you get this error from?

**Comment by swift1911** [comment]
> What is the version of Kong?
> Kong community 2.1.2
> > error: Unexpected server response: 101
>  I have used wscat tool https://www.npmjs.com/package/wscat  to make connection to the server 
> And where do you get this error from?

**Comment by hbagdi** [comment]
@gszr Any idea?

**Comment by phamquyhai** [comment]
Same me, 
I need add a config to support web socket, but not found :(
nginx.conf
```
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```

**Comment by hbagdi** [comment]
ping @bungle @gszr

**Comment by fuhrmannd** [comment]
Is there any update or solution here? I am struggling with the same problem :(
Help would be really appreciated! @hbagdi @phamquyhai @bungle @gszr 
Best regards,
Daniel

**Comment by w564791** [comment]
> Same me,
> I need add a config to support web socket, but not found :(
> nginx.conf
> 
> ```
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
> ```

me too

**Comment by myvodx** [comment]
It's related https://github.com/Kong/kubernetes-ingress-controller/issues/995

It works for me. Just need to update the ingress annotations as bellow.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # ... other properties
  annotations:
    konghq.com/headers.Connection: "Upgrade"
    konghq.com/headers.Upgrade: "WebSocket"
   ...
```

See more information:
- https://docs.konghq.com/gateway-oss/2.2.x/proxy/#proxy-websocket-traffic
- https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomheaders
