### ISSUE TITLE
Basic authentication doesn't work on KONG in kubernetes cluster

### ISSUE THREAD

**Issue by SiarheiBortnik** [Kong/kubernetes-ingress-controller#808]
### Summary
We use KONG in our kubernetes cluster and deploy it with help of helm.
We need to use basic authentication on our prometheus ingress resource.
Kong controller deployed in dev2 namespace, prometheus deployed in monitoring namespace.

**Kong Ingress controller version**
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.1

**Kong or Kong Enterprise version**
kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:2.1.0.0-beta1-alpine

### Kubernetes version
1.15.6
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-13T17:40:34Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-13T17:40:34Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
### Environment

- **Kubernetes cluster based on Azure AKS**:
- **OS** ("Ubuntu 18.04.4 LTS"):
- **Kernel** Linux k8s-master-13666935-0 5.3.0-1034-azure #35~18.04.1-Ubuntu SMP Mon Jul 13 12:54:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What happened
We have ingress resource:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    konghq.com/plugins: basic-auth
    kubernetes.io/ingress.class: kong-dev2
  generation: 1
  labels:
    app: prometheus-operator-prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-operator-7.4.0
    heritage: Helm
    release: prometheus-operator
  name: prometheus-operator-prometheus
  namespace: monitoring
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: prometheus-operator-prometheus
          servicePort: 9090
        path: /prometheus/
  tls:
  - hosts:
    - example.com
    secretName: letsencrypt-secret
status:
  loadBalancer:
    ingress:
    - ip: 0.0.0.0
```
And resources needed for basic authentication:
```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth
  namespace: monitoring
consumerRef: basic-auth
config:
  hide_credentials: true
plugin: basic-auth
" | kubectl create -f -

echo "
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: basic-auth
  namespace: monitoring
username: user
credentials:
- prometheus-secret
" | kubectl create -f -

echo '
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
  namespace: monitoring
stringData:
  kongCredType: basic-auth
  username: user
data:
  password: pass' | kubectl create -f -`
```
Also I tried to use old way without secret and without section "credentials:" in "KongConsumer", using:
```
echo "
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: basic-auth
  namespace: dev2
consumerRef: basic-auth
type: basic-auth
config:
  username: user
  password: pass
" | kubectl create -f -
```
but result was the same. I have an error after login, using username "user" and password "pass"  - **{"message":"Invalid authentication credentials"}**

### Expected behavior
Login using username "user" and password "pass"

**Comment by hbagdi** [comment]
Here are the commands I execute and things work fine:
```
$ kubectl apply -f https://bit.ly/k8s-httpbin                                                                                                          

$ echo '
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  annotations:
    konghq.com/strip-path: "true"
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: httpbin
          servicePort: 80
' | kubectl apply -f -

➜  kic git:(master) http :8000                                                                                                                                           <<<
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 48
Content-Type: application/json; charset=utf-8
Date: Wed, 26 Aug 2020 17:25:52 GMT
Server: kong/2.0.4
X-Kong-Response-Latency: 1

{
    "message": "no Route matched with those values"
}

➜  kic git:(master) export PROXY_IP=localhost:8000                                                                                                                       
➜  kic git:(master) curl -i $PROXY_IP/foo/status/200                                                                                                                     
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Server: gunicorn/19.9.0
Date: Wed, 26 Aug 2020 17:26:10 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Kong-Upstream-Latency: 5
X-Kong-Proxy-Latency: 26
Via: kong/2.0.4

➜  kic git:(master) echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: httpbin-auth
plugin: basic-auth
" | kubectl apply -f -

kongplugin.configuration.konghq.com/httpbin-auth created


➜  kic git:(master) echo '
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: httpbin-auth
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: httpbin
          servicePort: 80
' | kubectl apply -f -
ingress.extensions/demo configured
➜  kic git:(master) curl -i $PROXY_IP/foo/status/200
HTTP/1.1 401 Unauthorized
Date: Wed, 26 Aug 2020 17:26:42 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
WWW-Authenticate: Basic realm="kong"
Content-Length: 26
X-Kong-Response-Latency: 0
Server: kong/2.0.4

{"message":"Unauthorized"}%                                                                                                                                                  ➜  kic git:(master) echo "apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: harry
username: harry" | kubectl apply -f -

kongconsumer.configuration.konghq.com/harry created

➜  kic git:(master) kubectl create secret generic harry-basicauth  \                                                                                                  
  --from-literal=kongCredType=basic-auth  \
  --from-literal=username=harry \
  --from-literal=password=foo
secret/harry-basicauth created

➜  kic git:(master) echo "apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: harry
username: harry
credentials:
- harry-basicauth" | kubectl apply -f -

kongconsumer.configuration.konghq.com/harry configured

➜  kic git:(master) curl -i -u 'harry:foo' $PROXY_IP/foo/status/200
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Server: gunicorn/19.9.0
Date: Wed, 26 Aug 2020 17:28:36 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Kong-Upstream-Latency: 4
X-Kong-Proxy-Latency: 1
Via: kong/2.0.4  
```

**Comment by SiarheiBortnik** [comment]
We updated kong with new image. Currently we use: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:2.1.3.0-alpine
I tried to applied it on different resource in one namespace:
```
echo '
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: httpbin-auth
  namespace: kong
plugin: basic-auth
' | kubectl create -f -

```
Then add annotation to my ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    konghq.com/plugins: httpbin-auth
    kubernetes.io/ingress.class: kong-kong
    meta.helm.sh/release-name: vault-kong
    meta.helm.sh/release-namespace: kong
  labels:
....
```
```
echo '
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user
  namespace: kong
username: user
' | kubectl create -f -
```

`kubectl create secret generic user-basicauth -n kong --from-literal=kongCredType=basic-auth --from-literal=username=user --from-literal=password=foo`

```
echo '
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user
  namespace: kong
username: user
credentials:
- user-basicauth' | kubectl apply -f -
```

And after check:
```
curl -i -u 'user:foo' https://my-ingress-url-path/
HTTP/2 401
date: Thu, 27 Aug 2020 08:02:46 GMT
content-type: application/json; charset=utf-8
content-length: 48
vary: Origin
access-control-allow-origin: *
x-kong-response-latency: 1
server: kong/2.1.3.0-enterprise-edition

```
