### ISSUE TITLE
Cluster Local service is visibile from public on Knative

### ISSUE THREAD

**Issue by nak3** [Kong/kubernetes-ingress-controller#810]
### Summary

- Private service (`*.svc.cluster.local`) is visibile in public.

**Kong Ingress controller version**

- kong:2.0
- kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.1

### Kubernetes version

- 1.18

### Environment

- Knative (HEAD)

### What happened

- Access to cluster local service from external works fine.

```
$ curl  http://hello-example.default.example.com -H "Host: hello-example.default.svc.cluster.local"
Hello World!
```

### Expected behavior

- It should not be accssiable.
- Knative expects cluster local route does not allow to access from external - https://knative.dev/docs/serving/cluster-local-route/

#### 1. Deploy any knative service

e.g.
```
kn service create hello-example --image=gcr.io/knative-samples/helloworld-go
```

#### 2. Add cluster local label

```
KSVC_NAME=hello-example
kubectl label kservice ${KSVC_NAME} serving.knative.dev/visibility=cluster-local
```

- It becomes hello-example.default.svc.cluster.local

```
$ kubectl get ksvc
NAME            URL                                              LATESTCREATED           LATESTREADY             READY   REASON
hello-example   http://hello-example.default.svc.cluster.local   hello-example-htrgv-1   hello-example-htrgv-1   True    
```

### 3. access from external (and it still works)

```
$ curl  http://hello-example.default.example.com -H "Host: hello-example.default.svc.cluster.local"
Hello World!
```

**Comment by rainest** [comment]
@nak3 do you know of any reason our controller would expose these services at all? How should these labels/resulting KIngress fields be interpreted in practice?

When I configure such a Knative service, Knative creates a KIngress with a `visibility: ClusterLocal` rule:

```
spec:
  rules:
  - hosts:
    - smelloworld-go.example.svc.cluster.local
    http:
      paths:
      - retries:
          attempts: 3
          perTryTimeout: 10m0s
        splits:
        - appendHeaders:
            Knative-Serving-Namespace: example
            Knative-Serving-Revision: smelloworld-go-5dx44
          percent: 100
          serviceName: smelloworld-go-5dx44
          serviceNamespace: example
          servicePort: 80
        timeout: 10m0s
    visibility: ClusterLocal
  visibility: ExternalIP
```

That does complicate things, since we can't add a function to discard these entirely with an additional function at https://github.com/Kong/kubernetes-ingress-controller/blob/82b23323c590a176e490d2b5e26a3ecb1cd54262/internal/ingress/store/store.go#L213-L215, but I'm also not sure when we'd process these rules at all--the controller (and Ingress in general) exposes resources to external clients, and leaves internal traffic routing up to other K8S functionality.

The closest equivalent I can think of are internal load balancers, but those are still "external" (with respect to the K8S cluster, if not the network it resides in), but those are both outside the controller's domain and don't appear to be appropriate here.
