### ISSUE TITLE
Set Kong Service to use HTTPS via k8s Service yaml

### ISSUE THREAD

**Issue by cronventis** [Kong/kubernetes-ingress-controller#814]
How is it possible to set the Kong Service to use HTTPS via a k8s yaml where you specify the service?

```
apiVersion: v1
kind: Service
metadata:
  name: alpha-external
spec:
  ports:
  - protocol: TCP
    port: 443
  type: ExternalName
  externalName: alpha.myexternalapp.com
```
---
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alpha-external
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
spec:
  rules:
  - host: alpha.myinternalapp.com
    http:
      paths:
        - path: /
          backend:
            serviceName: alpha-external
            servicePort: 443
  tls:
  - hosts:
    - alpha.myinternalapp.com
    secretName: mysecret
```

And this results in

```
{
  "host": "alpha-external.default.443.svc",
  "created_at": 1598366276,
  "connect_timeout": 60000,
  "id": "4ae702c9-d7b5-4a01-xxxx-377a4a5d75ba",
  "protocol": "http",
  "name": "default.alpha-external.443",
  "read_timeout": 60000,
  "port": 80,
  "path": "/",
  "updated_at": 1598366276,
  "retries": 5,
  "write_timeout": 60000,
  "tags": [
    "managed-by-ingress-controller"
  ],
  "client_certificate": null,
  "extras": {}
}
```

The **"protocol":"http"** should be https.. Which can be done via Konga or curl. But I'm just blind and cant find a way to do it with k8s yaml...
