### ISSUE TITLE
Plugin annotations do not work with multiple hosts

### ISSUE THREAD

**Issue by jaygorrell** [Kong/kubernetes-ingress-controller#83]
**Kong Ingress controller version**:
kong:0.13.1-centos

**Kubernetes version** (use `kubectl version`):
v1.9.3

**What happened**:
I have an ingress with multiple `host` matches on it (which turns into `routes` in Kong) and have now added a handful of plugin annotations to it. This resulted in one of the routes receiving all but one of the plugins and the other route receiving the other.

**What you expected to happen**:
All host/routes would have the plugins applied.

**How to reproduce it** (as minimally and precisely as possible):
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-request-id
config:
  header_name: Request-ID

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test
  annotations:
    correlation-id.plugin.konghq.com: add-request-id
spec:
  rules:
  - host: test1.com
    http: &http_rules
      paths:
      - path: /mypath
        backend:
          serviceName: myservice
          servicePort: 80
  - host: test2.com
    http: *http_rules
  - host: test3.com
    http: *http_rules
```

Apply the above and see that `/routes` shows a unique id for each of the `host` above and that `/plugins` shows that each plugin appears only once and is bound to a single `route_id`.
