### ISSUE TITLE
The host attribute should not be required

### ISSUE THREAD

**Issue by jaygorrell** [Kong/kubernetes-ingress-controller#84]
Kong Ingress controller version:
kong:0.13.1-centos

Kubernetes version (use kubectl version):
v1.9.3

**What happened**:
I tried to create an ingress resource without a host specified. The ingress resource was created but the route was not created in Kong.

**What you expected to happen**:
I expected the route to exist in Kong since host is semi-optional in both Kong and Ingress.

**How to reproduce it** (as minimally and precisely as possible):
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: foo
          servicePort: 80
```
See that the above creates an `Ingress` resource but not a Kong route.

**Comment by andrewtappert** [comment]
@hbagdi I'm interested in trying to fix this.  Can you give a hint of what to look at?

**Comment by theissn** [comment]
Heya! 

Just tried the above example running the latest version of kong and nothing registers.

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: foo
          servicePort: 80
```

Any ideas?

**Comment by hbagdi** [comment]
@theissn This is not yet available in any release. The feature will be included in the upcoming 0.2.1 and 0.1.2 releases happening later this month.

**Comment by slkinnison** [comment]
I noticed that you released 0.1.2/0.2.1 this weekend (October 26, 2018). I'm using kong:0.13.1-centos, so I updated my kubernetes-ingress-controller from 0.1.0 to 0.1.2. However, much like @theissn, my Ingress controller didn't register with Kong unless I restored the host.

FWIW: I originally deployed Kong using https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/96b2f0b73bd19df9264ee212dae53b935c10e501/deploy/single/all-in-one-postgres.yaml

**Comment by slkinnison** [comment]
Thanks for getting back to me so fast! 

The diff of my update to all-in-one-postgres.yaml:
`
386c386
<         image: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.1.0
---
>         image: kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.1.2
416c416
<   type: NodePort
---
>   type: LoadBalancer
`

The new echoserver's Ingress specification:
`
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foo-bar
  namespace: bnb
spec:
  rules:
  - http:
      paths:
      - path: /bnb2
        backend:
          serviceName: http-svc
          servicePort: 80
`

**Comment by hbagdi** [comment]
@slkinnison,

Just to make sure, you did bump the version of your Ingress controller to 0.1.2, right? Cause that's not what I see in the diff.

**Comment by slkinnison** [comment]
In the diff above the change on line 386 was to change the version from 0.1.0 to 0.1.2. Did I miss a change somewhere else in all-in-one-postgres.yaml?

**Comment by hbagdi** [comment]
@slkinnison Apologies, I didn't read the diff output correctly.

I can replicate it.
It seems like you need one `host` based rule along with other empty host for this to work. There seems to be an error in the Ingress controller in how it is parsing the Ingress objects.

The following works:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test-1
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /mypath-2
        backend:
          serviceName: http-svc
          servicePort: 80
    host: foo.com
  - http:
      paths:
      - path: /mypath-2
        backend:
          serviceName: http-svc
          servicePort: 80
```

But, the following doesn't:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test-2
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /mypath-2
        backend:
          serviceName: http-svc
          servicePort: 80
```

**Comment by slkinnison** [comment]
Thanks for digging into this. I'll adjust my settings accordingly.

**Comment by fresh618** [comment]
@hbagdi Do you have any plan for making the following Ingress works?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-test-2
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /mypath-2
        backend:
          serviceName: http-svc
          servicePort: 80
```
