### ISSUE TITLE
Unable to expose the deployment on hostNetwork and hostPort

### ISSUE THREAD

**Issue by shantanubansal** [Kong/kubernetes-ingress-controller#857]
```  template:
    metadata:
      annotations:
        prometheus.io/port: "8100"
        prometheus.io/scrape: "true"
      labels:
        app: ingress-kong
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```

```
ports:
            - containerPort: 8000
              name: proxy
              protocol: TCP
              hostPort: 8000
            - containerPort: 8443
              name: proxy-ssl
              protocol: TCP
              hostPort: 8443
            - containerPort: 8100
              name: metrics
              protocol: TCP
              hostPort: 8100
            - containerPort: 4222
              name: nats
              protocol: TCP
              hostPort: 4222

```
I am trying to expose the kong - ingress using a hostNetwork. 
But the problem is that I am bound to create a service to be provided via --publish-service argument in ingress controller.

**Comment by mflendrich** [comment]
Hi @shantanubansal,

Have you tried leaving `---publish-service` empty but setting `--publish-status-address` to the host IP address?

You can use the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/) to get the IP address of the pod running with `hostNetwork: true` and pass it through the `CONTROLLER_PUBLISH_STATUS_ADDRESS` environment variable.

**Comment by shantanubansal** [comment]
But hostIp can change right?

**Comment by shantanubansal** [comment]
Yes I trien leaving publish service as empty

**Comment by shantanubansal** [comment]
It still does not work @mflendrich ,
I tried this
```
            - name: CONTROLLER_PUBLISH_STATUS_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```
