### ISSUE TITLE
kong use https. declarative config is invalid

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/kubernetes-ingress-controller#872]
```bash
2020-09-23T03:44:46.605052234Z posting new config to /config: 
400 Bad Request {"fields":{"services":{"test.stke-egress-svc.443":
["invalid reference 'client_certificate: cdd684a5-909c-4cdd-a57a-272b2dccc9a9' (no such entry in 'certificates')"]}},
"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: 
{services={[\"test.stke-egress-svc.443\"]={\"invalid reference 'client_certificate: 
cdd684a5-909c-4cdd-a57a-272b2dccc9a9' (no such entry in 'certificates')\"}}}"}
```

When I use helm to deploy my gateway config with https, It show me this.

My yaml file is:
```yaml
# Source: routes/templates/kong-egress-routes.yaml
kind: Secret
apiVersion: v1
metadata:
  name: stke-egress-secret
type: kubernetes.io/tls
data:
  tls.crt: xxxxxx
  tls.key: xxxxxx
---
# Source: routes/templates/kong-egress-routes.yaml
apiVersion: v1
kind: Service
metadata:
  name: stke-egress-svc
  annotations:
    konghq.com/client-cert: stke-egress-secret
    konghq.com/protocol: https
spec:
  type: ExternalName
  externalName: tke.kubernetes.oa.com
  ports: 
    - port: 443
      targetPort: 443
      protocol: TCP
---
# Source: routes/templates/kong-egress-routes.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stke-egress-ing
  annotations:
    kubernetes.io/ingress.class: "egress"
    konghq.com/strip-path: "true"
    konghq.com/override: stke-egress-ing
    konghq.com/protocols: "https"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /external/stke
        backend:
          serviceName: stke-egress-svc
          servicePort: 443
---
# Source: routes/templates/kong-egress-routes.yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: stke-egress-ing
  annotations:
    kubernetes.io/ingress.class: "egress"
proxy:
  protocols:
    - https
route:
  protocols:
    - https


```

I want to know where is wrong.

**Comment by NICK-DUAN** [comment]
**version**

kong: 2.0
kong-ingress-controller: 0.9.0
helm: v3.3.0-rc.1
kubectl: v1.18.5
GoVersion: go1.13.9
Compiler: gc
Platform: linux/amd64


**templates**

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: {{ .name }}-egress-secret
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $files.Get "pem/qci.pem" | b64enc | indent 2 }}
  tls.key: |-
    {{ $files.Get "pem/qci-key.pem" | b64enc | indent 2 }}
```
