### ISSUE TITLE
KongClusterPlugin is not being applied by the ingress-controller

### ISSUE THREAD

**Issue by hizeph** [Kong/kubernetes-ingress-controller#885]
### Summary

KongClusterPlugin is not being applied by the ingress-controller.
Using Postgres DB (RDS)

**Kong Ingress controller version**

0.10.0

**Kong or Kong Enterprise version**

2.1.4

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:52:43Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Alpine Linux
- **Kernel** (e.g. `uname -a`): Linux proxy-ingress-kong-5698d695fd-cphg6 4.9.0-9-ad=md64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 Linux
- **Install tools**: Applied with Helm version 1.10.0 - https://github.com/Kong/charts/tree/main/charts/kong)
- **Others**: Installed in Standalone mode (Proxy + Controller). KongClusterPlugin created with kubectl

### What happened

On applying KongClusterPlugin, as documented at https://docs.konghq.com/hub/kong-inc/ip-restriction, the global plugin is not applied to Kong, and the ingress-controller logs says "no configuration change, skipping sync to kong".

Resource is created as expected in the cluster:
```
$ kubectl describe kongclusterplugins kong-ip-restriction -n ingress-kong

Name:         kong-ip-restriction
Namespace:    
Labels:       global=true
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"configuration.konghq.com/v1","config":{"allow":["1.2.3.4","2.3.0.0/24"....
API Version:  configuration.konghq.com/v1
Config:
  Allow:
    1.2.3.4
    2.3.0.0/24
Kind:  KongClusterPlugin
```

ip-restriction.yaml (example, same behavior with other plugins too)
```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kong-ip-restriction
  labels:
    global: "true"
plugin: ip-restriction
config:
  allow:
  - 5.5.5.5/24
  - 1.2.3.4
```

### Expected behavior

KongClusterPlugin would be applied to Kong as a global plugin.

### Steps To Reproduce

1. Install Kong with Helm 1.10.0
Values Files:
shared.yaml
```
image:
  repository: kong
  tag: "2.1"

env:
  prefix: /usr/local/kong/
  database: postgres
  pg_host: 
    valueFrom:
      secretKeyRef:
        key: host
        name: kong-postgres
  pg_database:
    valueFrom:
      secretKeyRef:
        key: database
        name: kong-postgres
  pg_user:
    valueFrom:
      secretKeyRef:
        key: user
        name: kong-postgres
  pg_password:
    valueFrom:
      secretKeyRef:
        key: password
        name: kong-postgres
  real_ip_header: proxy_protocol
  real_ip_recursive: "on"
  trusted_ips: 0.0.0.0/0
  headers: "off"

# Hybrid Mode Only
cluster:
  enabled: false
  tls:
    enabled: false

# Kong Enterprise Only
manager:
  enabled: false
  ingress:
    enabled: false
  http:
    enabled: false
  tls:
    enabled: false

# Kong Enterprise Only
portal:
  enabled: false
  ingress:
    enabled: false
  http:
    enabled: false
  tls:
    enabled: false

# Kong Enterprise Only
portalapi:
  enabled: false
  ingress:
    enabled: false
  http:
    enabled: false
  tls:
    enabled: false

postgresql:
  enabled: false
```
proxy-ingress.yaml
```
migrations:
  postUpgrade: true
  preUpgrade: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
    type: Resource
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 150Mi

ingressController:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 75Mi
    limits:
      cpu: 100m
      memory: 120Mi
  env:
    kong_admin_tls_skip_verify: true
    kong_admin_url: https://admin-kong-admin.ingress-kong.svc:8444

proxy:
  enabled: true
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  ingress:
    enabled: false
  http:
    enabled: true
    parameters:
    - proxy_protocol
  tls:
    enabled: true
    parameters:
    - ssl
    - proxy_protocol

admin:
  enabled: false
  ingress:
    enabled: false
  http:
    enabled: false
  tls:
    enabled: false
```
admin.yaml
```
migrations:
  postUpgrade: false
  preUpgrade: true

admin:
  annotations: {}
  enabled: true
  http:
    containerPort: 8001
    enabled: true
    servicePort: 8001
  ingress:
    enabled: false
  tls:
    containerPort: 8444
    enabled: true
    parameters:
    - http2
    servicePort: 8444
  type: NodePort

proxy:
  enabled: false
  ingress:
    enabled: false
  http:
    enabled: false
  tls:
    enabled: false

ingressController:
  enabled: false
```
2. Apply KongClusterPlugin with kubectl
```
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kong-ip-restriction
  namespace: ingress-kong
  labels:
    global: "true"
plugin: ip-restriction
config:
  allow:
  - 1.2.3.4
  - 2.3.0.0/24
```
