### ISSUE TITLE
Update guide for Prometheus setup

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#897]
Guide in question: https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/prometheus-grafana.md

TODO:
- Update the revision of Grafana dashboard to the latest one
- Specifically call out the `podAnnotations` that are being set via a bitly link and explain why they are being used
- Call out that in case of a Hybrid deployment, the DP pods need to be scraped for metrics

**Comment by Sonlis** [comment]
Something else I would like to bring up, as I had a problem while setting up the Prometheus plugin: the scrape port on KIC as changed from 9542 to 8100, as I have been pointed out [here](https://discuss.konghq.com/t/prometheus-plugin-get-metrics-connection-refused/7859). However, on the current version of the doc, KIC is being installed with these values:
```yaml 
podAnnotations:
  prometheus.io/scrape: "true" # Ask Prometheus to scrape the
  prometheus.io/port: "9542"   # Kong pods for metrics
```
Making Prometheus unable to collect metrics.
