### ISSUE TITLE
https upstream configuration not working

### ISSUE THREAD

**Issue by SamuelTJackson** [Kong/kubernetes-ingress-controller#898]
### Summary

**Kong 2.1.4**

### Kubernetes version

**Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"a8b52209ee172232b6db7a6e0ce2adc77458829f", GitTreeState:"clean", BuildDate:"2019-10-15T12:12:15Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.6-r1-CCE2.0.30.B001", GitCommit:"3270aae40a24cd434ea48f594746f020c7473203", GitTreeState:"clean", BuildDate:"2020-01-08T10:05:41Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}**

### Environment

- **Open telecom cloud**:
- **euler OS** :

### What happened
`2020/10/08 07:28:56 [error] 30#0: *14535 upstream sent no valid HTTP/1.0 header while reading response header from upstream, client: 172.16.0.17, server: kong, request: "GET / HTTP/2.0", upstream: "http://172.16.0.57:9443/", host: "upstream.de"
`

### Expected behavior
upstream should be https://172.16.0.57:9443

### Steps To Reproduce
**KongIngress**
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: https-service-configuration
proxy:
  protocols:
    - https
route:
  protocols:
  - https
  preserve_host: true
```
**Ingress**
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: test-upstream
  namespace: default
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: upstream
    app.kubernetes.io/version: 1.16.0
  annotations:
    configuration.konghq.com: https-service-configuration
    konghq.com/plugins: add-proxy-headers
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - hosts:
        - upstream.de
      secretName:upstream-tls-cert
  rules:
    - host: upstream.de
      http:
        paths:
          - path: /
            backend:
              serviceName: upstream-node
              servicePort: 9443
```
**Plugin**
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-proxy-headers
config:
  add:
    headers:
    - 'X-ProxyHost: $(headers["host"])'
    - 'X-ProxyContextPath: /'
    - 'X-ProxyScheme: https'
    - 'X-ProxyPort: 443'
plugin: request-transformer
```
**Service**
```
kind: Service
apiVersion: v1
metadata:
  name: upstream-node
  namespace: default
  labels:
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: upstream
    app.kubernetes.io/version: 1.16.0
  annotations:
    configuration.konghq.com: https-service-configuration
    meta.helm.sh/release-name: test
    meta.helm.sh/release-namespace: default
spec:
  ports:
    - name: https
      protocol: TCP
      port: 9443
      targetPort: https
      nodePort: 30640
  selector:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: upstream
  type: NodePort

```
