### ISSUE TITLE
How to set connect_timeout?

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/kubernetes-ingress-controller#905]
Kong default connect_timeout, read_timeout, write_timeout are 6,000, but it's not long enough with use a websocket connection, so I want to set a custom value. follow these issue: #354 #472 , but the way they did it's not work for me, so can you point out my problem?
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  annotations:
  name: ci-console-kong-ing
  namespace: ci
proxy:
  connect_timeout: 3000000
  protocol: http
  read_timeout: 3000000
  retries: 10
  write_timeout: 3000000
route:
  protocols:
    - http
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/override: ci-console-kong-ing
  name: ci-webconsole-server
  namespace: ci
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/override: ci-console-kong-ing
    kubernetes.io/ingress.class: kong
  name: ci-webconsole-server-ing
  namespace: ci
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ci-webconsole-server
              servicePort: 8080
            path: /api/ci-ws/console
```

**Comment by NICK-DUAN** [comment]
@hbagdi

**Comment by NICK-DUAN** [comment]
and then i delete the annotations: `konghq.com/override: ci-console-kong-ing` from `Ingress`, but it not work, too.

**Comment by NICK-DUAN** [comment]
And I get service detail:
`curl https://127.0.0.1:8444/services -k`
```json
{
            "client_certificate": null,
            "connect_timeout": 3000000,
            "created_at": 1602484991,
            "host": "ci-webconsole-server.ci.8080.svc",
            "id": "be9e324b-0d96-519a-84bd-b559e17abc68",
            "name": "ci.ci-webconsole-server.8080",
            "path": "/",
            "port": 80,
            "protocol": "http",
            "read_timeout": 3000000,
            "retries": 5,
            "tags": null,
            "updated_at": 1602484991,
            "write_timeout": 3000000
        }
```

I didn't see `connect_timeout` attribute, and my websocket connection still make a 60s connection.

**Comment by lornatumuhairwe** [comment]
Hi @NICK-DUAN 

I ran into this issue while looking for a solution for something similar issue today - read_timeout and write_timeout. My colleague showed me I could set it on individual services definitions in kong. Check out [this link,](https://docs.konghq.com/0.13.x/admin-api/#update-service) you can make an api call to update the service. You should be able to update the `connection_timeout` as well.

I used konga to do that. But the api call should do the same thing. I'm not sure if that's something that can be set globally.

**Comment by hbagdi** [comment]
Hey @NICK-DUAN,
So it seems that the KongIngress configuration was correctly applied to Kong.
Do you mean to say that your websocket connection is still closed even after write and read timeouts in service have been changed to 3000000? If so, can you please describe the behavior you are seeing in more detail? Like, how do you measure time, and what happens after 60s? Do you see anything in logs of kong or the upstream service?

**Comment by NICK-DUAN** [comment]
I used websocket to make a web terminal, before I create `KongIngress` resource, the connection will close after 60s. 
Then I  did create `KongIngress` and set `connect_timeout`, `read_timeout`, `write_timeout` for 180,000. But now the connection closes at an unstable time. 

I don't know why and I am replacing the network environment to verify that the network environment is not the cause of the problem.

I will keep update.

**Comment by NICK-DUAN** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you and I have found the link and Proxy Reference.Because my plugins and kong are deploy on kubernetes, then I found this issue, and I follow the way which worked. But my api is still timeout. I will keep update this issue, if you want to know, please stay tuned.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                dlm291459214
                            
                    
                        
                            
                                    dlm291459214@outlook.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 10/12/2020 23:08，Lorna Tumuhairwe<notifications@github.com> wrote： 



Hi @NICK-DUAN
I ran into this issue while looking for a solution for something similar issue today - read_timeout and write_timeout. My colleague showed me I could set it on individual services definitions in kong. Check out this link, you can make an api call to update the service. You should be able to update the connection_timeout as well.
I used konga to do that. But the api call should do the same thing. I'm not sure if that's something that can be set globally.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by NICK-DUAN** [comment]
I changed my environment, and the result not changed, the websocket connection still close after 60s.

Sorry to forget to tell you the version:
kong-ingress-controller:0.9.0
kong:2.0

**Comment by marianopw** [comment]
Hi @NICK-DUAN , we had a similar issue today.

If your deployment is in AWS you should check your ELB idle timeout setting (By default is 60 seconds)
After changing this the issue was resolved.

Hope it helps

**Comment by NICK-DUAN** [comment]
> Hi @NICK-DUAN , we had a similar issue today.
> 
> If your deployment is in AWS you should check your ELB idle timeout setting (By default is 60 seconds)
> After changing this the issue was resolved.
> 
> Hope it helps

My Deployment was in TKE(Tencent Kubernetes Engine), So could you tell me what ELB idle exactly is? And I can find a same thing in TKE which can help me to resolve my problem?

**Comment by marianopw** [comment]
ELB stands for elastic load balancer.
You might have another load balancer, or something else in front of kong that is terminating your connection.

(Outside kubernetes).

**Comment by NICK-DUAN** [comment]
I konw what the problem is.

This code should add to a Service instead of a Ingress:
```yaml
annotations: 
  konghq.com/override: $YOUR_KONGINGRESS_NAME
```
And your kongIngress should set like this:
```yaml
kind: KongIngress
apiVersion: configuration.konghq.com/v1
metadata:
  annotations:
    kubernetes.io/ingress.class: "kong"
    name: timeout-kong-ingress
proxy:
  protocol: http
  connect_timeout: 360000       # ms
  read_timeout: 360000
  write_timeout: 360000
```

And you also need a Ingress to route your request. The whole file is:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket
        image: ksdn117/web-socket-test
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: websocket
  annotations:
    konghq.com/override: timeout-kong-ingress
spec:
  selector:
    app: websocket
  ports:
  - port: 80
    targetPort: 8010
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test2
  annotations:
    kubernetes.io/ingress.class: "kong"
    # konghq.com/strip_path: "true"
spec:
  rules:
    - http:
        paths:
        - path: /api/ws/test
          backend:
            serviceName: websocket
            servicePort: 80
---
kind: KongIngress
apiVersion: configuration.konghq.com/v1
metadata:
  annotations:
    kubernetes.io/ingress.class: "kong"
  name: timeout-kong-ingress
proxy:
  protocol: http
  connect_timeout: 360000
  read_timeout: 360000
  write_timeout: 360000
```
