### ISSUE TITLE
How to rewrite URL using Request Transformer plugin?

### ISSUE THREAD

**Issue by eufat** [Kong/kubernetes-ingress-controller#906]
How do I rewrite URL using Request Transformer plugin? 

In the docs, there is no example URL rewrite/replacement (https://docs.konghq.com/hub/kong-inc/request-transformer/#enabling-the-plugin-on-a-route). 

For example, I want to rewrite `/foo` using route, is this right?

```ingress.yaml
apiVersion: networking/v1beta1
kind: Ingress
metadata:
  name: <route>
  annotations:
    kubernetes.io/ingress.class: kong
    plugins.konghq.com: <request-transformer-example>
spec:
  rules:
  - host: rewrite.bar.com
    http:
      paths:
      - path: /foo(/|$)(.*)
        backend:
          serviceName: echo
          servicePort: 80
```

```replace-uri.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: <request-transformer-example>
config: 
  replace:
    uri:
    - /foo(/|$)(.*):/(/|$)(.*)
plugin: request-transformer
```

For example, above will result:

`rewrite.bar.com/foo` rewrites to `rewrite.bar.com/`
`rewrite.bar.com/foo/` rewrites to `rewrite.bar.com/`
`rewrite.bar.com/foo/bar` rewrites to `rewrite.bar.com/bar`

What I want to achieve is similar to what in NGINX controller docs (https://kubernetes.github.io/ingress-nginx/examples/rewrite/#rewrite-target).

**Comment by danieldides** [comment]
I just went through something similar (assuming that I'm understanding what you're asking correctly). I configured my ingress like this:

```yaml

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-httpbin
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: stripper
spec:
  rules:
  - host: host.example.com
    http:
      paths:
      - path: /foo/(.*)
        backend:
          serviceName: httpbin
          servicePort: 8000

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: stripper
config: 
  replace:
    uri: '/$(uri_captures[1])'
plugin: request-transformer
```
