### ISSUE TITLE
Updates to KongIngress are not reflected in Kong until the Ingress is recreated

### ISSUE THREAD

**Issue by jaygorrell** [Kong/kubernetes-ingress-controller#91]
### Summary

Creating a `KongIngress` and `Ingress` resource correctly configures Kong but subsequent edits ot the `KongIngress` are not immediately reflected in Kong. Deleting and recreating the `Ingress` will force Kong to be updated.

This _may_ apply to more than the `KongIngress` resource, but this is where I first noticed the problem.

**kong:0.13.1-centos**

### Kubernetes version

**1.9.3**

### What happened
Changes to the `KongIngress` resource (`strip_path`) were not reflected in the Kong configuration.

### Expected behvaior
Changes to `KongIngress` are picked up and applied by Kong.

### Steps To Reproduce

1. Create the following (assuming a service `myservice` exists)
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: mykongingress
route:
  strip_path: true

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    configuration.konghq.com: mykongingress
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - path: /foo
        backend:
          serviceName: myservice
          servicePort: 80
```

2. Verify settings in Kong `/routes`
3. Change `strip_path` to `false` and apply changes
4. Observe that settings in Kong have not changed
5. Delete/create `myingress` again
6. Observe that settings in Kong have been updated
