### ISSUE TITLE
Kong Ingress controller exposing only few prometheus metrics

### ISSUE THREAD

**Issue by sonujose** [Kong/kubernetes-ingress-controller#910]
### Summary

While setting up Prometheus monitoring for kong, observed only few metrics are exposed in the metrics: 9542/TCP port. 
```
kong_memory_lua_shared_dict_bytes
kong_datastore_reachable
kong_memory_lua_shared_dict_total_bytes
kong_memory_workers_lua_vms_bytes
kong_nginx_http_current_connections
kong_nginx_metric_errors_total
```
Find the full metrics here I have got- [metrics.log](https://github.com/Kong/kubernetes-ingress-controller/files/5382968/metrics.log)

Installed prometeus `KongClusterPlugin` to get metrics from all the requests to the endpoints 
```
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus-global-plugin
  annotations:
    kubernetes.io/ingress.class: kong-dev
  labels:
    global: "true"
config:
  enabled: true
plugin: prometheus
```
The kong proxy is working, am able to successfully setup the ingress rules and it is reachable, but the monitoring is not working

**Kong Ingress controller version**
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.0

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Environment
- **Azure Kubernetes Service**

### What happened

While setting up monitoring for Kong ingress controller, happened to see only few metrics. The metrics endpoint is only showing few. Prometheus server is designed to scrap metrics from `9542/metrics` endpoint.
What all metrics endpoints are there in the metrics endpoints, it is scrapping and am able to visualize in the prometheus and grafana dashboard

### Expected behavior

Should Able to see all metrics endpoints including request latencies, error rates and services in the prometheus metrics and same in the grafana dashboard

### Steps To Reproduce

1. Setup Kong Ingress controller
2. Install prometheus and grafana, used Kong grafana template (7424)
3. Enable scrapping in the pods by annotations
4. Install services and ingress and prometheus kong plugin
5. Now only few metrics are coming on.

followed the tutorial - https://konghq.com/blog/observability-kubernetes-kong/

**Comment by mayankshah1607** [comment]
Hey @sonujose 
Were you able to solve this issue? I seem to be stuck here too.
Thanks

**Comment by wi1dcard** [comment]
Having the same issue here

**Comment by dogaakcinar** [comment]
I've been trying to solve this for a few hours. In case somebody faces this issue, in Prometheus plugin configuration default values for additional metrics set to false. Setting them to true as shown below solved my issue.
(https://docs.konghq.com/hub/kong-inc/prometheus/configuration/)
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus
plugin: prometheus
config:
  per_consumer: true
  status_code_metrics: true
  latency_metrics: true
  bandwidth_metrics: true
  upstream_health_metrics: true
```
