### ISSUE TITLE
level=fatal msg="NegotiateIngressAPI failed: the server could not find the requested resource, tried: [networking.k8s.io/v1 networking.k8s.io/v1beta1 extensions/v1beta1]"

### ISSUE THREAD

**Issue by fing999** [Kong/kubernetes-ingress-controller#918]
This error does not occur when using 0.9.1, and an error is reported in 1.0.0

**Comment by uplogin** [comment]
the same issue

**Comment by yaobo-lab** [comment]
I have the same problem！！！

**Comment by yaobo-lab** [comment]
If you solved the problem.Also tell me。thx

**Comment by mflendrich** [comment]
@yaobo-lab and @fing999 could you please attach the result of `kubectl version` and `kubectl api-resources`?

**Comment by yaobo-lab** [comment]
> @yaobo-lab and @fing999 could you please attach the result of `kubectl version` and `kubectl api-resources`?

kubectl version is 1.12 .  I checked the official document.   it was kubernetes  version too low

**Comment by mflendrich** [comment]
I have managed to reproduce this error in Kubernetes 1.12.

The Ingress version negotiation algorithm walks through group-versions (GVs) of Ingress resources that KIC supports, in the order of KIC's preference. By default the list is `[networking.k8s.io/v1 networking.k8s.io/v1beta1 extensions/v1beta1]`.

For each GV in this list: if the apiserver doesn't support the Ingress kind in that GV, KIC tries the next one.

However, it turns out that if, in addition to Ingress being not present in a GV, that GV also doesn't exist in that apiserver at all, negotiation fails unrecoverably (where it should pass over that GV).

For 1.12, Ingress is present in the `extensions/v1beta1` GV, but not in `networking.k8s.io/v1beta1` nor `networking.k8s.io/v1`. Furthermore, `networking.k8s.io/v1beta1` and `networking.k8s.io/v1` don't exist in K8s 1.12 at all, but they do exist in 1.14.

KIC should work fine for >= 1.14 because all of these GVs are known to apiserver >= 1.14  (regardless of whether the Ingress kind is supported in them or not). <1.14 did not have the `networking.k8s.io/v1beta1` GV, though - which is the trigger for the issue.

While this bug surfaces only in versions of k8s [we don't support anymore](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/references/version-compatibility/#kubernetes), this is a logical bug that needs to be fixed.

## Workaround for k8s <1.14

**If running Kubernetes <1.14** (which we don't support anymore, btw) and you're getting an error like in the issue title, the workaround is to add the following `env` variables to the ingress controller container:

```yaml
         - name: CONTROLLER_DISABLE_INGRESS_NETWORKINGV1                                                                                                                                                                                                                       
           value: "true"                                                                                                                                                                                                                                                       
         - name: CONTROLLER_DISABLE_INGRESS_NETWORKINGV1BETA1                                                                                                                                                                                                                  
           value: "true"            
```
