### ISSUE TITLE
Kong Docker postgres migration job cannot login into Azure Postgres service

### ISSUE THREAD

**Issue by david-freistrom** [Kong/kubernetes-ingress-controller#919]
### Summary

Kong could not migrate Postgres Database placed in Azure as a service because of a invalid authentication format
The Problem here seems like the mandatory format of the username which includes a @ symbol which is maybe not parsed well from the scripts.

**Kong Ingress controller version**

2.1

**Kong or Kong Enterprise version**

---

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"73ec19bdfc6008cd3ce6de96c663f70a69e2b8fc", GitTreeState:"clean", BuildDate:"2020-09-17T04:17:08Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: Azure

- **OS** (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- **Kernel** (e.g. `uname -a`): Linux aks-akspoolmin-35064155-vmss000000 5.4.0-1031-azure #32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

### What happened

2020-10-24T04:05:16.080913975Z Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: FATAL: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.
2020-10-24T04:05:16.080959375Z 
2020-10-24T04:05:16.080963275Z   Run with --v (verbose) or --vv (debug) for more details

### Expected behavior

Migrating the Database - Login access

### Steps To Reproduce

1. Create Azure Postgresql Database
2. Run Kong Helm chart against it
3. Check out the migration job which produce the error

```yaml
env:
  database: postgres
  pg_username: "kong%40kong-db" # I tried to mask the '@' 
  pg_database: kong-db
  # pg_host: SET BY ANSIBLE AT RUNTIME
  pg_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35643832376630643032616566313165643039643238366639646234363836643533333031363531
    6466386566383537613930376438666337333037646435330a616339313233393064353831613838
    38383533386134356438353362663262623264643431653461376133396162623664303661636433
    3161303636623461330a323662333038353237633734623033393761313966306635386434333935
    66303264356330346338303730386263333566303963306535613134353231643138363036383036
    65666231643637373663373864363531386431343332663766313165623237363034623938336535
    373030343661343064376339373139303635
  nginx_worker_processes: "1"
  proxy_access_log: /dev/stdout
  admin_access_log: /dev/stdout
  admin_gui_access_log: /dev/stdout
  portal_api_access_log: /dev/stdout
  proxy_error_log: /dev/stderr
  admin_error_log: /dev/stderr
  admin_gui_error_log: /dev/stderr
  portal_api_error_log: /dev/stderr
  prefix: /kong_prefix/
```
