### ISSUE TITLE
Ingress with multiple paths does not use plugin

### ISSUE THREAD

**Issue by eamonnmcevoy** [Kong/kubernetes-ingress-controller#93]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version** 0.0.5

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: AKS

### What happened

Is it possible to configure multiple paths on a single ingress while using a plugin?

When I define separate KongPlugins and Ingresses, it works:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-A
  namespace: my-namespace
  annotations:
    jwt.plugin.konghq.com: my-plugin-jwt-A
spec:
  rules:  
    - host: localhost
      http:
        paths:
        - path: /routeA
          backend:
            serviceName: my-service-A
            servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-B
  namespace: my-namespace
  annotations:
    jwt.plugin.konghq.com: my-plugin-jwt-B
spec:
  rules:  
    - host: localhost
      http:
        paths:
        - path: /routeB
          backend:
            serviceName: my-service-B
            servicePort: 80
```

However, this is a bit cumbersome I would like to combine the ingresses and use one plugin CRD like so:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: my-namespace
  annotations:
    jwt.plugin.konghq.com: my-plugin-jwt
spec:
  rules:  
    - host: localhost
      http:
        paths:
        - path: /routeA
          backend:
            serviceName: my-service-A
            servicePort: 80
        - path: /routeB
          backend:
            serviceName: my-service-B
            servicePort: 80
```

This issue is related to [<Feature Request> KongPlugin CRDs should be reusable](https://github.com/Kong/kubernetes-ingress-controller/issues/6) , but I think this refers to using one plugin over multiple ingress definitions.

Is what I am attempting possible?
I still see all of the services and routes are created, just no plugins.

### Expected behvaior

Each route should get an instance of the plugin
