### ISSUE TITLE
Can't get JWT plugin working - Kubernetes secrete to kong consumer credentials keeps failing

### ISSUE THREAD

**Issue by viky293** [Kong/kubernetes-ingress-controller#935]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Can't get JWT plugin working - Kubernetes secrete to kong consumer credentials keeps failing - have been trying all the available solutions.

NOTE: KEY is equal to ISS in JWT 

apiVersion: v1
kind: Secret
metadata:
  name: fsjwt-key
  namespace: kong
type: Opaque
data:
  kongCredType: jwt
  key: KEY_TEXT
  algorithm: RS256
  rsa_public_key: |-
    -----BEGIN CERTIFICATE-----
   KEY_CONTENTS_S
    -----END CERTIFICATE-----

SUMMARY_GOES_HERE

**Kong Ingress controller version**

1.0.0

**Kong or Kong Enterprise version**

### Kubernetes version

**paste `kubectl version` output**
kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:33:34Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-gke.801", GitCommit:"3a26ac58e2a1ce0170c304c4134149ce3526eb8a", GitTreeState:"clean", BuildDate:"2020-09-28T17:32:58Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

time="2020-10-30T16:56:11Z" level=error msg="failed to sync: posting new config to /config: 400 Bad Request {\"fields\":{\"consumers\":[null,{\"jwt_secrets\":[{\"rsa_public_key\":\"invalid key\",\"@entity\":[\"failed conditional validation given value of field 'algorithm'\"]}]}]},\"name\":\"invalid declarative configuration\",\"code\":14,\"message\":\"declarative config is invalid: {consumers={[2]={jwt_secrets={{[\\\"@entity\\\"]={\\\"failed conditional validation given value of field 'algorithm'\\\"},rsa_public_key=\\\"invalid key\\\"}}}}}\"}" component=sync-queue

Goes in infinite loop and crashes, produces many evicted pods. 

### Expected behavior

credentials should sync 

### Steps To Reproduce
Followed 
https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/configure-acl-plugin.md

1. Create kubernetes secret to save JWT credentials to match against  
   kongCredType: jwt
  key: TEXT
  algorithm: RS256
  rsa_public_key: MULTI_LINE_TEXT

2. Create JWT plugin & Apply to ingress
3. Create customer & specify credentials from the secrete

**Comment by rainest** [comment]
Can you try creating a Secret file and creating that, using `stringData` fields similar to the example at https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret ? That will allow you to use a YAML multiline string with the literal (`|`) format for the RSA key: https://yaml-multiline.info/

https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-mtls-auth-plugin.md shows a more complete example of what that will look like--it's a different type of PEM, but the general concept is the same.

We should probably adjust the documentation to use those examples. Getting the newlines in the key using the CLI tool and `--from-literal` isn't impossible, but it is tricky.

**Comment by MushiTheMoshi** [comment]
@rainest  could you share an example of how it should look like? I'd appreciate a lot, been trying for days... thanks in advance!!!

**Comment by ben-dyer** [comment]
@MushiTheMoshi Not sure this answers the question, but here is a snippet which works in my environment -

Get base64 encoded values (if not using stringData)
```
$ echo -n "jwt" | base64
and0
$ echo -n "KEY_TEXT" | base64
S0VZX1RFWFQ=
$ echo -n "RS256" | base64
UlMyNTY=
$ ssh-keygen -N "" -f ~/garbage_key/key
$ ssh-keygen -f ~/garbage_key/key.pub -e -m pem | base64 -w0
LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXlmd002NG5XdzQwUGhmRFc2MFh2ak5aUW0vSzJLZGJPZDZ6MWd6ZXFqVHVkZFRRS1pHZloKYVRTM0xaZDh3MHNsUG55QnFFUnN3ZHNYVTdRQTY2ODRHUDBWcnIrZEg5YlQ1UFNKSnMzSXpsN1hQZVNPd3FLUAp2aFZWd29HeVllRG5CcjZnR3Q3UWh4Y3lFM0REaWpYSlZoNGZqZ1ZzMm1RVW1ZV3BRZXpvTlR4SXA0RUdmVEFECks0QmZaa1dteUlEZWtPUi9aZ0svaFl4dHlMdlRMR3dSZkhaa1NJVWRVZUJmWVVyOVVINWVSZVJTa1pPMnl6dFUKdG5PVGp4NDJ5d0tYNjQza0dxUmdQaEtoQUp1RThRT2l5eVBmMTJ3SGxBZzBYVFRiS2tKRjZGT2RQNW95N3dLSwpoREh6cHNkcEUxODFDWmkyaGdjaDlNUyt2a0NRTExybzV3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
```

Copy values into `secret.yml`
```yml
apiVersion: v1
kind: Secret
metadata:
  name: my-garbage-key
type: Opaque
data:
  kongCredType: and0
  key: S0VZX1RFWFQ=
  algorithm: UlMyNTY=
  rsa_public_key: |
    LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXlmd002NG5XdzQwUGhmRFc2MFh2ak5aUW0vSzJLZGJPZDZ6MWd6ZXFqVHVkZFRRS1pHZloKYVRTM0xaZDh3MHNsUG55QnFFUnN3ZHNYVTdRQTY2ODRHUDBWcnIrZEg5YlQ1UFNKSnMzSXpsN1hQZVNPd3FLUAp2aFZWd29HeVllRG5CcjZnR3Q3UWh4Y3lFM0REaWpYSlZoNGZqZ1ZzMm1RVW1ZV3BRZXpvTlR4SXA0RUdmVEFECks0QmZaa1dteUlEZWtPUi9aZ0svaFl4dHlMdlRMR3dSZkhaa1NJVWRVZUJmWVVyOVVINWVSZVJTa1pPMnl6dFUKdG5PVGp4NDJ5d0tYNjQza0dxUmdQaEtoQUp1RThRT2l5eVBmMTJ3SGxBZzBYVFRiS2tKRjZGT2RQNW95N3dLSwpoREh6cHNkcEUxODFDWmkyaGdjaDlNUyt2a0NRTExybzV3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
```

Create secret and check
```bash
$ kubectl apply -f path/to/secret.yml
secret/my-garbage-key created
$ kubectl get secret my-garbage-key -o jsonpath='{.data}'
map[algorithm:UlMyNTY= key:S0VZX1RFWFQ= kongCredType:and0 rsa_public_key:LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJDZ0tDQVFFQXlmd002NG5XdzQwUGhmRFc2MFh2ak5aUW0vSzJLZGJPZDZ6MWd6ZXFqVHVkZFRRS1pHZloKYVRTM0xaZDh3MHNsUG55QnFFUnN3ZHNYVTdRQTY2ODRHUDBWcnIrZEg5YlQ1UFNKSnMzSXpsN1hQZVNPd3FLUAp2aFZWd29HeVllRG5CcjZnR3Q3UWh4Y3lFM0REaWpYSlZoNGZqZ1ZzMm1RVW1ZV3BRZXpvTlR4SXA0RUdmVEFECks0QmZaa1dteUlEZWtPUi9aZ0svaFl4dHlMdlRMR3dSZkhaa1NJVWRVZUJmWVVyOVVINWVSZVJTa1pPMnl6dFUKdG5PVGp4NDJ5d0tYNjQza0dxUmdQaEtoQUp1RThRT2l5eVBmMTJ3SGxBZzBYVFRiS2tKRjZGT2RQNW95N3dLSwpoREh6cHNkcEUxODFDWmkyaGdjaDlNUyt2a0NRTExybzV3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K]
```

Then reference in a kongconsumer:
```yml
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test
username: "Test consumer"
custom_id: "test-consumer"
credentials:
  - my-garbage-key
```
