### ISSUE TITLE
Ensure dual-stack service readiness (aka IPv6 support)

### ISSUE THREAD

**Issue by yaoice** [Kong/kubernetes-ingress-controller#972]
### Summary
I use kong and kubernetes ingress controller in k8s ipv4/ipv6 dual stack environment,  kubernetes-ingress-controller failed to generate the correct target address when use the service ipFamily is IPv6.  

### Steps To Reproduce
1. Use [all-in-one-dbless.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless.yaml) to Install kubernetes kong ingress controller, update some config to deploy

update deloyment config, to let port 8000 and 8443 listen in ipv6 address 
```
apiVersion: apps/v1
kind: Deployment
    ......
    spec:
      containers:
      - env:
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl http2, [::]:8000, [::]:8443 ssl http2"
        - name: KONG_LOG_LEVEL
          value: debug
      ......
      - env:
        - name: CONTROLLER_LOG_LEVEL
          value: trace
```

update service config, to use NodePort to expose kong 80 and 443 for external access
```
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: kong
spec:
  ipFamily: IPv6
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 30080
  - name: proxy-ssl
    port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 30443
  selector:
    app: ingress-kong
  type: NodePort 
---
```

ingress-kong is running
```
# kubectl -n kong get pod
NAME                            READY   STATUS    RESTARTS   AGE
ingress-kong-7c66d9cc7c-2nm8z   2/2     Running   0          48m
konga-5f9fbd977b-d2rz9          1/1     Running   0          39h

# kubectl -n kong get svc
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kong-proxy                NodePort    fd00::8c85       <none>        80:30080/TCP,443:30443/TCP   24h
kong-validation-webhook   ClusterIP   10.109.213.100   <none>        443/TCP                      24h
```

2. Run an nginx deployment with service ipFamily is IPv6 and ingress in k8s
```
kubectl apply -f - << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-nginx
  labels:
    app: common-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: common-nginx
  template:
    metadata:
      name: common-nginx
      labels:
        app: common-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: common-nginx
spec:
  ipFamily: IPv6
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: common-nginx 
  sessionAffinity: None
  type: ClusterIP 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: common-nginx
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: common-nginx.test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: common-nginx
            port: 
              number: 80
EOF
```

```
# kubectl get pod
NAME                            READY   STATUS    RESTARTS   AGE
common-nginx-76457bb678-9kzcg   1/1     Running   0          3s
common-nginx-76457bb678-dk85v   1/1     Running   0          3s
common-nginx-76457bb678-lrwwn   1/1     Running   0          3s

# kubectl get svc
NAME           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
common-nginx   ClusterIP   fd00::8c1f   <none>        80/TCP    5s

# kubectl get endpoints
NAME           ENDPOINTS                                                                                               AGE
common-nginx   [fc00::26d1:ddab:d697:fe01:78cf]:80,[fc00::26d1:ddab:d697:fe01:78d5]:80,[fc00::26d1:ddab:d697:fe01:78d7]:80   7s

]# kubectl get ingresses.networking.k8s.io 
NAME           CLASS    HOSTS                   ADDRESS          PORTS   AGE
common-nginx   <none>   common-nginx.test.com   192.168.101.53   80      47s
```

3. Use curl to access common-nginx.test.com, failed to access
```
# curl -H "Host: common-nginx.test.com" -I -g -6 'http://[<host-ipv6-address>]:30080'
HTTP/1.1 502 Bad Gateway
Server: openresty
Date: Thu, 03 Dec 2020 02:35:04 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 75
X-Kong-Upstream-Latency: 1002
X-Kong-Proxy-Latency: 5010
Via: kong/2.2.0
```

found that the ipv6 address don't use [] to include in  the ingress-controller log
```
# kubectl  -n kong logs -f ingress-kong-7c66d9cc7c-2nm8z -c ingress-controller
time="2020-12-03T02:44:29Z" level=debug msg="fetching endpoints" component=store service_name=common-nginx service_namespace=default service_port="&ServicePort{Name:proxy,Protocol:TCP,Port:80,TargetPort:{0 80 },NodePort:0,AppProtocol:nil,}"
time="2020-12-03T02:44:29Z" level=debug msg="found endpoints: [{fc00::26d1:ddab:d697:fe01:78cf 80} {fc00::26d1:ddab:d697:fe01:78d5 80} {fc00::26d1:ddab:d697:fe01:78d7 80}]" component=store service_name=common-nginx service_namespace=default service_port="&ServicePort{Name:proxy,Protocol:TCP,Port:80,TargetPort:{0 80 },NodePort:0,AppProtocol:nil,}"
```
the correct ipv6 format is:  [{[fc00::26d1:ddab:d697:fe01:78cf] 80} 

4. enter the ingress-kong pod network namespace, call the kong admin api, found that target address is also not include `[]` to represent ipv6 address
```
# curl -k https://127.0.0.1:8444/config
{"config":"_transform: false\n_format_version: '2.1'\nservices:\n- host: common-nginx.default.80.svc\n  id: 3dd3cac0-1895-5419-9927-4c58759e2625\n  protocol: http\n  read_timeout: 60000\n  tls_verify_depth: ~\n  port: 80\n  updated_at: 1606962499\n  ca_certificates: ~\n  created_at: 1606962499\n  connect_timeout: 60000\n  write_timeout: 60000\n  name: default.common-nginx.80\n  retries: 5\n  path: \/\n  tls_verify: ~\n  client_certificate: ~\n  tags: ~\nroutes:\n- id: fa05ef59-e575-51f6-a7ec-aec710dbff1b\n  tags: ~\n  updated_at: 1606962499\n  destinations: ~\n  headers: ~\n  protocols:\n  - http\n  - https\n  strip_path: false\n  created_at: 1606962499\n  snis: ~\n  service: 3dd3cac0-1895-5419-9927-4c58759e2625\n  name: default.common-nginx.00\n  hosts:\n  - common-nginx.test.com\n  methods: ~\n  preserve_host: true\n  regex_priority: 200\n  paths:\n  - \/\n  sources: ~\n  response_buffering: true\n  https_redirect_status_code: 426\n  path_handling: v0\n  request_buffering: true\nupstreams:\n- client_certificate: ~\n  created_at: 1606962499\n  id: 984b3a78-5afc-5cab-9806-669216d1b8ad\n  algorithm: round-robin\n  name: common-nginx.default.80.svc\n  tags: ~\n  hash_fallback: none\n  hash_fallback_header: ~\n  healthchecks:\n    active:\n      https_verify_certificate: true\n      type: http\n      http_path: \/\n      timeout: 1\n      unhealthy:\n        http_statuses:\n        - 429\n        - 404\n        - 500\n        - 501\n        - 502\n        - 503\n        - 504\n        - 505\n        tcp_failures: 0\n        timeouts: 0\n        http_failures: 0\n        interval: 0\n      healthy:\n        http_statuses:\n        - 200\n        - 302\n        interval: 0\n        successes: 0\n      https_sni: ~\n      concurrency: 10\n    threshold: 0\n    passive:\n      unhealthy:\n        http_failures: 0\n        http_statuses:\n        - 429\n        - 500\n        - 503\n        tcp_failures: 0\n        timeouts: 0\n      healthy:\n        successes: 0\n        http_statuses:\n        - 200\n        - 201\n        - 202\n        - 203\n        - 204\n        - 205\n        - 206\n        - 207\n        - 208\n        - 226\n        - 300\n        - 301\n        - 302\n        - 303\n        - 304\n        - 305\n        - 306\n        - 307\n        - 308\n      type: http\n  hash_on_cookie: ~\n  hash_on: none\n  hash_on_cookie_path: \/\n  host_header: ~\n  hash_on_header: ~\n  slots: 10000\ntargets:\n- created_at: 1606962499.246\n  weight: 100\n  tags: ~\n  id: 63c74cc3-569f-5ff4-8360-4fcb78888775\n  target: fc00::26d1:ddab:d697:fe01:78d5:80\n  upstream: 984b3a78-5afc-5cab-9806-669216d1b8ad\n- created_at: 1606962499.246\n  weight: 100\n  tags: ~\n  id: e562bbf3-c940-5842-a104-eacfff4c258e\n  target: fc00::26d1:ddab:d697:fe01:78cf:80\n  upstream: 984b3a78-5afc-5cab-9806-669216d1b8ad\n- created_at: 1606962499.246\n  weight: 100\n  tags: ~\n  id: c62bea19-6dc4-5f2c-8d79-c7789c467667\n  target: fc00::26d1:ddab:d697:fe01:78d7:80\n  upstream: 984b3a78-5afc-5cab-9806-669216d1b8ad\n"}
```

### Additional Details
Kubernetes version: 1.19.3
Kong version: 2.2
Calico version: v3.17.0
kubernetes-ingress-controller version: master branch
K8s dual stack config: [IPv4/IPv6 dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/)
Calico deploy: [Calico install](https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremise)
Calico dual stack config: [Enable dual stack](https://docs.projectcalico.org/networking/ipv6#enable-dual-stack)
Operating system: CentOS Linux release 7.5.1804 (Core)
Arch: amd64
