### ISSUE TITLE
Lambda Function for config.replace.headers is not working, expecting string [plugin: request-transformer]

### ISSUE THREAD

**Issue by justmy2centx** [Kong/kubernetes-ingress-controller#989]
I tried to implement a lambda function template for replacing my header using the request transformer plugin. Getting validation errors

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
 kubectl describe deploy/api-gateway-kong -n kong | grep Image
    Image:      kong:2.1
    Image:      kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:1.0

### Kubernetes version

**paste `kubectl version` output**

k version --short
Client Version: v1.15.11-eks-065dce
Server Version: v1.16.15-eks-ad4801

### Environment

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release): 
```
  nodeInfo:
    architecture: amd64
    containerRuntimeVersion: docker://19.3.6
    kernelVersion: 4.14.198-152.320.amzn2.x86_64
    kubeProxyVersion: v1.16.13-eks-ec92d4
    kubeletVersion: v1.16.13-eks-ec92d4
    operatingSystem: linux
    osImage: Amazon Linux 2
```

### What happened

I tried creating this plugin:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-xformer
config:
  replace:
    headers:
    - 'Authorization': '$((function()
          local body, err, mimetype = kong.request.get_body()
          local value = headers.Authorization
          local default_basic_auth = "Basic " .. encode_base64("test:test") 
          if (body.grant_type == "password" or body.grant_type == "refresh_token") then
              return default_basic_auth
          end
          if body.grant_type == "client_credentials" then
              return "Basic " .. encode_base64(body.client_id .. ":" .. body.client_secret) 
          end
          return kong.response.exit(401, [[{"message":"Invalid Credentials"}]])
        end)())'
plugin: request-transformer
```
### Expected behavior

plugin to be successfully created
replace headers authorization

### Steps To Reproduce

1. When I applied the yaml im getting webhook validation errors
**k apply -f modified-plugin.yaml**
```
Error from server: error when creating "modified-plugin.yaml": admission webhook "validations.kong.konghq.com" denied the request: 400 Bad Request {"fields":{"config":{"replace":{"headers":["expected a string"]}}},"name":"schema violation","code":2,"message":"schema violation (config.replace: {\n  headers = {\n    \"expected a string\"\n  }\n})"}
```

I am trying to follow this from the documentation but for dbless kong ic in k8s
https://docs.konghq.com/hub/kong-inc/request-transformer/#advanced-templates

**Comment by john-stevenson-next** [comment]
ended up here for the same error for a similar-but-different use case. In mine, the root cause was that the header config does NOT want there to be a space afterwards. for those stumbling on this, encountered the same issue. In my case the issue was resolved by ensuring that there are no spaces between the header key and value. This was specifically causing problems as I was interpreting from a k8s secret (which is not a particularly well-documented use case):
```yaml
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: request-transformer-add-api-key-secret
  namespace: mynamespace
type: Opaque
stringData:
    HEADER_CONFIG: |
      add:
        headers:
        - api-key:no-space-before-me # note how there's not space after colon
```
and then the plugin
```yaml
# plugin.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-transformer-add-api-key-secret-plugin
  namespace: mynamespace
plugin: request-transformer
configFrom:
  secretKeyRef:
     name: request-transformer-add-api-key-secret
     key: HEADER_CONFIG
```
