### ISSUE TITLE
kong ingress pods failing liveness probe on EKS fargate profile after installing jwt plugin

### ISSUE THREAD

**Issue by neeraj-htp** [Kong/kubernetes-ingress-controller#990]
### Summary

Kong ingress pods keep failing Liveness and Readiness prob on EKS Fargate node after installing jwt plugin.

**Kong Ingress controller version**
kong 2.2

**Kong or Kong Enterprise version**
Kong

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
### Environment
- EKS with managed nodeGroup and fargate profiles. 
- **Cloud provider or hardware configuration**: EKS with fargate profile. kong is schedulded to run on fargate profile.
- **Install tools**: `eksctl` + `kubectl`

### What happened
- Installed kong ingress with  command `kubectl apply -f https://bit.ly/k4k8s`
- Kong components get installed on fargate node.
- Install JWT plugin with yaml
``` yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: firebase-jwt-auth
plugin: jwt
```
-  Observe kong ingress pods for a few minutes. They will start failing Readiness and Liveness prob with messages
``` log
Readiness probe failed: Get http://192.168.123.21:10254/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Liveness probe failed: Get http://192.168.123.21:8100/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
- Kubernetes will terminate and restart the pods every few minutes.

### Expected behavior
Kong pods should be stable.

### Steps To Reproduce

1. Create EKS cluster with `eksctl` with the following config and command `eksctl create cluster -f kong-test-cluster.yaml`
``` yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kong-test-cluster
  region: ap-south-1

managedNodeGroups:
  - name: ng-t3a-default
    instanceType: t3a.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
    
fargateProfiles:
  - name: fp-kong
    selectors:
      - namespace: kong
      - namespace: kuma-system

  - name: fp-default
    selectors:
      - namespace: default
```
2. It should create an EKS cluster with one managed `nodeGroup` and 2 `fargate` profiles. `kong` ingress and other resources are supposed to run on `fargate` nodes. 
3. Install kong with command `kubectl describe certificate -n cert-manager-test`
4. Observe kong pods for a few minutes. They are stable and running. Everything is working fine so far.
5. Enable jwt plugin with yaml
``` yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: firebase-jwt-auth
plugin: jwt
```
6. Create secret to hold jwt public key and other configurations with command
``` shell
kubectl create secret \
generic htp-firebase-jwt \
--from-literal=kongCredType=jwt \
--from-literal=key="test-issuer" \
--from-literal=algorithm=RS256 \
--from-literal=rsa_public_key="-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----"
```
7. Observe kong pods. They will start failing readiness and liveness prob with Timeout exceed error. These are the errors I can see.
``` log
Readiness probe failed: Get http://192.168.123.21:10254/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Liveness probe failed: Get http://192.168.123.21:8100/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
